Wipfuza iki?
Uragikunda?
We si umwana.
Uwuhagaze, yirinda kugwa.
Sindi ikijuju.
Ndagenda kuryama.
Ikimuga gisumba imva.
Wagize ubwoba?
Uba ngaha?
Vyibagire ivyo.
Uzosigara umwanya ungana iki?
Narumvise ko warongoye.
Amakuru maki?
Indimi zifise amajambo agoye.
Bite!
Iyo azakugira umwanya yari kugenda.
Ntiwibagire gutwara ikete.
Urayikunda?
Fata itagisi ikujana mw ihoteri.
Ryama neza, Timmy.
Iri darapo ni nziza cane.
Mariya arihe?
Nitwa Jack.
Nryama uko zandemye.
Ntiwibagire gutwara ibaruwa.
Ndashaka kugurana umuduga.
Vyiza kuruta vyobaye iyo utajaho.
Izina ryawe ni nde?
Izina ryawe ni nde?
Uwutwenga inkovu ntazi uruguma.
Iyo aguma imuhira, ntiyogize ingorane.
Biramuraba.
Ntiwoshobora kubisubira ico wavuze?
Namerewe nabi.
Tom arihe?
Ndi mu gikoni.
Raba iyi foto.
Watinye?
Igifurwe ntigifise amenyo.
Bite!
Ikibazo ciza.
Nyoko ari imuhira?
Utumvise, baza.
Bite, izina ryawe ni nde?
Magdalena na Ania ni abagenzi pfampfe.
Igitwazi kirasimba.
Ni akazi kiwe.
Urarikunda?
Umwansi aguye, muvyure.
Witwa nde?
Abana bagiye kw ishure?
Urarurumba.
Iki kintu kimaze iki?
Urukundo rurahuma.
Umuryango umerewe gute?
Nzogaruka.
Ntutwibagira!
Tuzosubira kubonana!
Umwansi w'umuntu n'umuntu.
Iyi nyabu ni yanje.
Bite!
Nariye amagi ejo.
Iyo udategereye, baza.
Nagasaga!
Afise imyaka ingahe?
Nashoboye kugira.
Ntutwibagira!
Ninde asoma?
Ntibaza uyu munsi.
Mugenda hehe?
Ibirato birihe?
Turashaka kuriha.
Sindashonje.
Korera iciza ababanka.
Ndarurumba.
Ahari ugushaka haba inzira.
Bite uyu munsi?
Sinshonje.
Ndagukunda.
Urashobora gutera ururirimbo.
Izana ryawe?
Ukora iki?
Indahiro ni ideni.
Bobo ni abana.
Muzinaniye hehe?
Niki?
Amakuru yawe?
Umunsi mwiza.
Agafuni kabagara ubucuti ni akarenge.
Musazawe arihe?
Nagasaga, Sayoko.
Ndagukunda.
Nataye impfunguzo zanje.
Icumba ni ciza.
Urawukunda?
Ndameneka umutwe.
Ndafise ikibazo.
Neza.
Iyo menya sinari kuza.
Iki kintu bimaze iki?
Nta kibazo.
Hagupfa wozanzama.
Ndi umwigisha.
Uyu munsi ni umunsi w'Imana.
Ni umunyeshuri mwiza.
Sinzi.
Iyo menya nari kugenda.
Ndashonje.
Uribuka?
Sinzi ico novuga...
Mukora iki?
Ufise imyaka ingahe?
Muri abana.
Kunda umwansi wawe.
Iyo udategereye, baza.
Umuhungu arasimba.
Ndabasavye, mumpe ifagitiri.
Ni angahe?
Uribuka uru rukino?
Ni igiciro giki?
Tuzobonana ejo!
Nta kamaro.
Nryama ubusa.
Imana iguhezagire!
Inzovu zirya ivyatsi.
Wewe uri umugenzi wanje.
Nta ngorane.
Ntiyasomaye iki gitabo.
Ntanumwe antegura.
Haguta isoni wotuma upfa.
Namaki?
Nayumvise ko warongowe.
Ntariye nopfa.
