I däd mir wenscha, dass mai Familie so glicklich wär wie daine.
Des geit a Gschrôe nô en ganz Ägypten, wia mr no koes ghört hôt ond au nemme hört.
Ässat dia Deitsche viel Schwainefloisch?
Friher hosch mid de Onderhosa no 's ganze Fahrrad butza kenna – heit langads grad no fir de Schboicha.
Tom hod sich scho wochålang brepariert.
I nemms Gleiche.
Dô war ä Flegg, jetzt isch r wegg.
Des war dr beschde Tee von dene, wo dr Tom bisher drongå hod.
Wenn driffschd du daine Konda?
Wenn dees d'Lösung isch, hedd i gern mei Problem zrugg.
Hend Se ihr neies Kloid gsäa?
Geld isch nix, abr viel Geld isch ebbes anders.
Bessr zom sei als die Schwoba ischd wia Wagglpudding an d' Wand nagla. Mr ko's vrsuacha, aber s' isch aussichtslos.
Ooo, s'rägnåt scho wiedr!
Wiå hauch du au fliågschd, nôchr wirschd du emmr auf d'Ärdå fallå.
Tom isch mid saim Plå gscheidrd, aus dem Schloss a Luxushotel fir Suprreiche zmachå.
I mjuess dir ebbes sagå: I han glogå, wenn i gsagt han, i woiß nix.
I muass nemme liab sai – i koa main Schogglad selber kaufa.
Was sagsch du als Obeteiligter eigentlich zom Thema Indelligenz?
I môg älles, was siå kochd.
Denglåd ned so!
Dees hett i ned dengd, dass dr Tom pünktlich dô wär.
Nix macht oin so alt, wie dr ewige Vrsuåch, jong zom bleibå.
Tom isch auf'm Feld dr Ähre gfallå.
S'Hirå deekt, s'Läbå lenkt.
S'ischd faschd siebå Uhr.
Mai eldeschde Schweschdr isch scho gschdorbä.
Ebbes isch älläweil.
Koi Frôg! Vo mir kriågd Tom nix mid.
I däd gärä läbä wia a armer Moa, mid am a Haufa Geld.
Er hôd äbbes am Härzä.
Melkt d'r Bauer mal sein Stier, trank der Seggl zu viel Bier.
Toms Hond hôd a blaschdiggugg gfresså.
I koå no ned guåd Franzesisch.
Schbreng mudig nai ens neie Jôhr, mit Gligg ond Fraid wirds wondrbar.
I han so Kopfweh – mai Hailigaschai druggd!
Han mir grad a Weld vorgschdelld, wo älle Seggl a Glöggle om dr Hals dragad. 'S war bruddal laut!
Em Hemml geits koi Bier, drom drenket dens mir hier.
Dr Fischfang war heit magr.
Dees will i aigentlich ned.
Wenns Weddr so bleibd, ischs morga wia heit!
Wenn du mir hilfschd, gåht älles guad.
Mir hend nix gsähå ond nix gherd.
Aigendlich sodd mr ned bloß Englisch, sondrn nô meeh Sprôchå kennå.
Tom isch etzad Arzt.
Dr Fisch schdenkt vom Kopf her.
Maria isch durch d'Zemmer gfäägt
Du kasch mir net helfa.
Dr Kondoauszug isch å bequems Middl, om rauszfendå, wie sähr mr ibr saine Vrheltnisse gläbt hôd.
Hôsch du ehm dankd?
Schnaufa isch wichdig, älles andre hod Zeit.
Du bischd mir oiner!
Älle Biächr kennet en zwoi Kategoriä aidoilt werda.
Hend se bidde nô å bissle Geduld!
Sisch ausm Nix aufdauchd.
Näemerd hôd Schweinkottlets bschdelld.
Onsre Vorfahrä hend em Aiklang mid dr Nadur gläbd.
Dees isch ä scheenä Fähnä.
Schatz, sag mr die drei magische Wörter: Mauldascha send fertig!
S'Essa schmegggd am beschda, wenn's ebber anderer zahld!
Der hod meh Dregg am Schdecka als Hoor uff 'm Grend.
Diå Sandfigurå vom Tom sähåd deischend ächt aus.
Fendåd Tom ond brengt en omm!
Neamrd hier hôd deen Nämä.
Tom kå koi Floisch und koine Oier ässå.
Dees Audo isch å Klabbrkischd.
Jede Schbrôch hôd ihre aigene Grammadig.
Kennschd du des Gfihl?
Thomas läbt em ma Raddaloch.
I môg dahoimgmachde Kardofflklöß mit Lebrwurschd drenn.
No 20 cm wachsa, ond i han mei Idealgwicht.
Ond lent nex üvrig bis an da Morga; aber wenn ebbas übrigbleibt, nä dent r s em Feuer vrbrennä.
I be verandwordlich fir dees, was i schwätz – ond ned fir dees, was du verschdohsch.
Heit ischs amôl Zeid, oifach „Danke“ zom sagå.
'S Läba isch koin Schlotzer – abr au koi Gosch voll Reißnegl.
Wie kommschd du denn drauf, dass i mid ebbr ausgangå bee?
Schwob sai isch es Schönschde, was oim bassiera koa!
I han geschdern daine Fraindin hier gsäå.
I will wissa, was du macha dädeschd.
I däd gärå nô amål mai alde Liebe wiedrsähå.
Guck aus'm Fenschdr, aber glei!
I benn an Idealischd. I woiß ned, wonô i gang, abr i gang main Weg.
Mr ko au ohne Alkohol luschdig sei – abr heit gang i liebr uff Nommer sicher.
Neamrd kennd da Tom so guåd wiån i.
Dend Sia mir ausm Wäg gangå?
I gang nô zu maim Fraind.
Schildkreta hent koi Zee.
Isĉ dees Ihrä Ziel?
Tom isst gärn å woichs Oi zom Friistigg.
Was isch a naggads Weib uff ma Kaschda Bier? – Em Weg!
I han neilich mol Liegeschditza brobierd. – Liega ko i, schditza no ned!
Heil bloos koine Krokodilsträna!
I mecht ebbrd lieb habå.
Beim Melka wird em Schdadtkend klar, dass dia Kuah an Bulle war.
Lenge hod nix mid Diefe zom do, Dauer nix mid Indensität.
Du hôsch då Helm falschrom auf.
I mechht net en ra großä Villa wohnä.
I han oruig gschlôfå.
Au Regiarä isch koi Reidä uffm Ponyhof.
Ned bloß en dr Wirdschaffd send Aufbliä ond Aufblää zwoierlai.
Was hod d' Muader ällawei gsait?: „Kommsch bald hoim, wenns donkel wird.“
Håsch du ihr neies Kloid gsäa?
Dees koå mr bloß aus Biåchr lärnå. Vorläsongå odr Vorträg zu dem Thema geits ibrhaubd etå.
Håsch du scho dai Teschtamend gschriebå?
Au Wassr wird zom edla Tropfa, mischd mr es mit Malz ond Hopfa.
Vor Gericht muass mr diå pure Woorheid sagå.
Tom hôd Maria nô niå ôgschmingd gsäå.
Tom hôd middå em Kisså aufgherd.
I benn ned bsondrs nervees.
Dr Schiedsrichdr zoigt ehm a Karte.
Wenn dir eber ebbes schenka will, no nemm's. Fortschmeissa kosch's ällaweil no.
„Wo guggsch du z'erschd no, wenn de a scheene Frau siehsch?“ – „Ha, ob mei Weib guggd!“
Oinrå Schdrôßabô ond oiner Aktie derf må niåmals nôchlaufå. Blôß Geduld. D*negschde kommd mid Sichrheid.
Machmol wär i gern dünner – aber no fällt mir wieder ai, wia granadamässig guat Spätzla mid Soss schmeggad.
Hät dees Tom absichtlich dô?
I fläh di ô, dass de dees ned duåsch!
'S Leba isch koin Schlotzer – aber au koi Gosch voll Reißnegl.
Dees gherd älles zu maim Plô.
Woischd du, wär des Brogramm endworfå hôd?
I han dees erschd viel schbädr vrschdandå.
Als d'r liebe Gott mi gschaffa hod, hod 'r gsait: „I woiss ned, wa bassierd, wird abr sicher luschdig!“
Er hôd Brod gschniddå.
Kurz vor äm Schlôfägangä sodd mr nix meeh ässä.
Wiilsch mid *m Chef schwätza – oder liaber mid oim, der sich auskennd?
Des isch mai Geld.
No ka ies schaffa bis om halber drui.
Mr muass koin Schwob sai, om mid mir befraindet zom sai, abr 's hilft ogmain.
Was moinschd? Kommt heit no Boschd?
I koa dees jetzt no net macha.
Gäld isch et so wichtig. Drom isch's mir ganz egal, ob i 70 odr 80 Millionä Dollar han.
Kender, bis jedzd hemm mr Glick ghett. Driggad Daumå, dass es so weidergohd.
I môg Kääs.
Wie viel Zukkr isch xond?
An die Person, die maine Schuah verschdeggd hod, während i uff dr Hipfburg war: „Werd erwachsa!“
En dera Nacht gang i durch s ganz Land Ägypten ond breng älle Erstgeburta om, von de Menscha ond vom Vieh. Ond i, dr Herrgott, halt s Sträfgericht ab über de Ägypter ihre Götter.
„Drengsch du dai Bierle aus'm Glas oder aus dr Flasch?“ „Aus'm Kaschda!“
Der Hond isch fortgloffå.
'S geit nur oine Dreiecksbeziehong, dia funktionierd; Lensa, Spätzla, Saitawurscht!
Em Läbä wähld ä Mô ondr zwoi Ibl meischd des hibschere.
Etz kommåd diå luschdige dääg.
Was gwä isch, koå må vrgesså, wenn koiner dô isch, wo drnå frogd.
Eigendlich han i heit viel vorghed! Jetzt han i hald morga viel vor!
I han grad mein Moa grad gfrogd, ob 'r woiß, wa heit fir an Daag isch. 'S isch so oifach, Männer Angschd zom macha.
Wie nennd mr bei de Badener an attraktiva ond intelligenta Menscha? – En Schwob!
En dr Weihnachdszeit drohsch de Kender drei Mol am Daag, dass de s'Chrischkendle oruafsch, wenn se ned schburad.
I will ihr Gäld et.
„Was hosch du zu Weihnachda griagt?“ – „An reachda Ranza!“
Zwoi Sacha, dia i ällaweil will: 1. Abnemma. 2. Essa!
I lieb da Sommer. 's isch oifach d' scheeschde Woch em Johr.
Wer koine Fääler macht, macht wahrscheinlich gar nix!
„Wia hoißt des Zaubrwörtle?“ – „Bidde!“
Wemmer gebbad, gebbad mr gern, aber mir gebbad nix.
Worom kommschd du ned mid mir aikaufå?
I han daine Ärdbeerå gesså.
Isch's woar?
Am beschda isch, wenn dai Meterschdab meh Bierla uffgmacht hod als Meter gmessa.
Wer uffrommd isch nur z' faul zom suacha.
Send Siå uff dem Foto?
Wer dr Moinong isch, dass mr mid Gäld elles machä kä, der macht sichr älles fir Gäld.
Moinschd du, dass Tom gscheit isch?
I han heit ogfähr drei Litr Wassr dronkå.
Mir Schwoba dädad onsere Fähler zuagäba – wenn mr oine häddat.
An Smoothie isch dr neie Weg, ma Seggl a Banane fir 2 Euro zom vrkaufa!
Wenn i oifach amol alloi sai will, schdell i mi em Baumarkt an da Infoschdand.
Ond was hend mir dômôls pro Dag zom ässä ĝedd? Drei Scheibä Brod, oine morgäds, oine middags, oine ôbeds, ond vieleichd ä halbä dôzwischä,
Mensch sai hoisst Utopia hann.
Iber dees schwätz i später mid Tom.
Mir send gegä Siä.
Er wird ghensld.
Geld alloi machd ned glügglich – ma muass sich scho Mauldascha davo kaufa.
I hoff, dass du mi vrstôschd.
Schbarå isch de richdige Midde zwischå Geiz ond Vrschwendong.
Mid Schbegg fengt mr Meis, mid Vrsprechongå Aktionär.
Heit koch i nix.
Wenn Rüabå gfrogd senn uff'm Markt, muåss ma se ned wäschå.
Sbrichhd nix drgegå.
Fir an arma Vadder kosch nix – Aber fir an arma Schwiegervadder.
Tom gååd mid saim hood Gassi.
Wär hôds dir's gäbå?
D*Henna lammer saua – abr d'Saua lammer henna.
Erschd kreized sich d'Wäg von zwoi Menschä ond nô lieged se heifig drnôch ibr Kreiz.
Seit zwoi Wocha mach i Diät ond *s oinzige, was i vrlora han, send zwoi Wocha!
A schees Gsichd brauchd Blatz.
Tom intressierd sich leidåschaftlich fir Musigg.
Haubdärbed war dômôls, äbbes zom ässa zom organisierä. „Hamschdrä“ hôd mr dees dômôls ghoißä.
Siå kô Portugiesisch schwätzå.
I kennd då Tom niå ersetzå.
's isch zwor heit Sonndich, aber i fühl mi vom Meedich scho beläschdigd.
Mir wissåd, was ihr geschdern ôbåd do hend.
I môg de, wie de bischd.
Tom isch å bissle nerwees.
Wenn i reich wär, hedd i meh Gäld.
Maria hod a Halskeddå tragå
I koa mrs ned laischdä, mai Zeit zu vrdommä, om Geld zu vrdienä.
Duscha zu zwoid schbard Wasser ond Zeit.
Mir send koine äfengr.
Meget ihr no ebbas Domatasupp?
Dr Wald isch voller Gfaar.
Maria isch vorbeikommå ond hat Tom gholfå.
Gell, do glodschd!
Wär zviel Kornschnaps drenkt, hôd am End bloß no Schdroh em Kopf.
Hosch du gsäa, wia se eich aguggt hot?
Wer ned will, hod ghed.
Noi, i schnarch ned. I draim no davo, a Mofa zom sai.
So wenig Luschd uff schaffa han i s' ledschde Mol geschdern ghed.
S' bleibd äbbes Bitters zrugg.
I han koi Angschs ghett.
Tom hôd lengres Hår wia n i.
Oiner håd ja endlich domid åfanga miasa.
Tom ståht mid oim Fuaß em Grab.
Dees han i en am Film gsäå.
Viel kennd oifachr sai, wenn es ned diå Kompromiss gäbå däd.
Er machd an ganz ährlichn Aidrugg.
I han main Rägaschirm ergendwo gedangälos en d Ecke gschdelld.
Isch die Unibibliothek jetzt offå?
I han ganz frgässå, fir Tom å Gschenk zom kaufå.
I han's mr ned rausgsuachd, an Schwob zom sai! I han oifach bruddal Gligg ghed!
Wär sich emmr normal aufierd, isch doch ned normal.
Schee isch anderschd.
„Drenkschd du dai Bierle aus 'm Glas odr aus dr Flasch?“ – „Aus 'm Kaschda!“
S'gôhd om Ihre Schwester.
Wenn no älle so wärad, wie i sai sodd.
Maria kôa wedr läsä no schreibä.
Tom wär ä guedr Vaddr.
I han geschdern ghehrt, dass Tom en Schwierigkeitå wär.
Egal wie ald i be! I will an Advendskalender!
Ziag dia Schraub å!
Isch dees xond, wenn mr kald duschd?
Kôsch du mir sagå, wo i benn?
I han nô nia an ächda Diamandä gsää.
Send Siå Zwilleng?
Worom hilfd eane koiner?
Dô drfir kriagschd du von mir an Bluspônkt.
Die Berse isch å Thermomedr dr effentlichå Moinong.
Heit hen mr gschaffd wia d' Bronnabutzer.
Wär heher schdeigd, als är sodde, fälld diåfr, als är gwelld hôd.
Liebe isch dr Wônsch äbbes zom gäbå.
Sähet Sia dees en äller Ruah å!
Wenn mr zu viel Zucker em Bluad hôd, hoißt mr dees Diabetes.
Vor andre Leid will a jeder å bissle guåd aussäå.
Der Film war et so intressant wia i denkt han.
Sisch Meedig, net woar?
Äll Dag hôd må koi Zeid, en de Feriå muåss må sich d'Zeid vrdreibå.
Mir älle sähåd dia gleiche Sonnå.
I kennt di vrknudscha.
Dahoim will wenigschdens d'Waschmaschee von mir o'gmacht werda.
's geit Seggl ond Schmedderleng – aber fliaga kosch du ned!
I will etzed aigendlich liåbr et mid dir schwätzå.
Wa fir å omeglichå gschuggåde!
Woischd du, wo dai Vaddr etzad isch?
Dees isch å harde Ärbed.
Tom isch beim Augåarzt gwä.
Koin Roschdbroada isch au koi Lösung!
Auf'm Hof isch viel Platz zom Schbielå.
Är isch von dr Bolizei vrhafded worda.
Schreib dain oigånå Namå auf dia punkdede Linie.
Wär Vrtrauå hôd, erläbt jeden Dag Wondr.
Doa hend au scho Scheenere Mischd glada.
Bidde mach ebbes dôgegå!
Wenn mr jedn Dag acht Stondä schlofd, vrschlôfd mä oi driddl von saim Läbä. Wenn mr also 75 Jôr ald wird, hod mä 25 Jôr bloß gschlôfä.
I ben ned perfekt – aber als Schwob verdammt nah dran!
Mir wohnäd seid drei Johr zsammä.
Es ko koi Zuafall sai, dass sich „Schwabe" uff „Gabe" reima duat.
Schwäbisch isch mai Muadrsproch.
I woiß nemme, was i geschdern Obend gesså han.
I be ned schichdern – I will oifach ned mid dir schwätza!
Mai Kopfwai haut langsam ab.
Isch des neie Johr vor dir ond des alde hendr dir, nô lass des alde liegå ond heb des neie uff.
Bscheidåheid isch å Zoichå ächdr Indelligenz.
I schlôf normalerweis ned so viel.
Frieher war älles leiĉder, i zom Beisĉbiel.
Wer schbäder kommd, hod frier Feierobend.
Er war aussr sich vor Fraid.
I will ned schderbå. No ned.
Mr kô ondr Fordschridd au des Weggangå vrschdandå-
Hend ihr äbbes gässå?
I glaub, å Schbio isch onder ons.
Ihrä isch s ned kald.
Dr Schiedsrichdr pfeifd die Partie ab.
Was hend Gold ond Hai gemeinsam? Dia onendliche Suacha noch dr Mehrzahl.
Erschd beim Abfassä dr Schdeiererklärong kommd mr dåhendr, wie viel Geld mr schbarå kennd, wenn mr kois hed.
Des send fempf weniger wia i zäld han.
Kurz mol gar nix denkd – zagg, gligglich!
Mir send gegä eich.
I han å andre Enformatiô.
Worom deant ihr ned saŭbermaĉa?
An Moa muass doa, was an Moa do muass! A Weib muass doa, was an Moa hed ned doa solla!
Du bisch a bißle bleed.
Chamäleô kennåd ihre Farb wexlå.
Stell di Kischd dô end Egg!
Des Bluat an dene Häuser, mô ihr dren wohnat, des isch a Schutzzoeche. Môn e des Bluat sieh, gang e an euch vrbei, dass euch koi Schlag trifft, solang e en Ägypten draeschlag.
Schwäbisch isch wie Boirisch. Bloß viel scheener!
„Wa duasch heit?“ – „Nix.“ – „Des hosch doch geschdern scho gmachd.“ – „Be hald ned ferddig worda.“
Der isch au liaber doa, wo ma scho gschaffd hod, aber no ned gveschbert.
Mir send gwarnd wordå.
Lasset mi durch, i ben Schwob!
Marie isch alloi.
Älle schlofad, oiner schbricht, so was nennd ma onderricht.
'S Guate uff'm Dorf: Jeder kennd jeden. 'S Schlechte uff'm Dorf: Jeder kennd jedden.
Was wird jetzt bassiera?
An Nochteil, wenn's wieder warm wird – d'Nochber kommad wiedr raus!
Tom hôd d'Maria om ä Autogramm bitäd.
Guåd isch, dass schbrachlichr Abfall ned au no endsorgd werrå muaß.
Wenn de Frischdügg am Bedd willsch, noa muasch en dr Kucha schlofa.
„Wa grieg i zom Geburtsdaag?“ – „Mid „E“ fängds oa! Ebbes schees.“
I hoff, dass es heit et regnåd.
Send dees daine Elträ?
'S Denka isch zwar ällna Leit erlaubt, aber 's bleibd viele Leit erschbard.
Macht oifach dees, was eier Muadr said.
Dees isch fai liab von dir, dass du mi vom Bôhof abholschd.
Ä ächdr Fraind isch ebber, wo dir Gäld leiht ond nô ens Gras beissd.
Em Frieleng kommad Zugvegl zrigg ond zwidschered vo earåm Liebesgligg.
Beim Tom dåhaim geits å gehaimå Kammr.
Der wird reich, der en Ondernehmongå inveschdierd, diå weniger koschded als se wärd send.
Heit isch dr Daag des Mitdenkens! No schad, dass 'n so wenig Leit mitfeira kennad.
Heit kommd mei Frau zrugg. I han a Woch ned uffgrommd, damit se sieht, dass i ned ohne se leba koa! Romandisch, gell?
I han maine Hausuffgabå scho en dr Schuål gmachd.
Dees kommd mir wia grufå.
Oser Fabrig hot a Aschlussglois.
I hans Fenschdr uffgmachd.
Wie hoissd des Password?
Dia Oich isch å Baum.
Sie vrzehlt seldå ebbes ibr sich selbr.
Kennsch du dô Nâmå vo dära Blomå?
Å gloine Tass Kaffee koschded zwoi Eiro.
I hets ahalda kenna.
Där Meteorit isch en dr Sahara gfondä wordä.
Ôsr Mannschhaft kô gwennä.
Wenn du duasch, was i sag, koasch macha, wa de willsch!
Wenn no älle wäred, wie i sai sodd!
S'Schenschde am Lerna isch, dass oim neamrd s'Glernde wegnemma koa.
Mir hend net gwissd, was mr do soddat.
Älle Fraua send guad! Aber die schwäbische send die beschda!
S'gibt Menschå, bei deene isch dr geischdige Horizont durch ihr Wischkäschdle definiert.
Dr Morgä isch d schenschde Zeid em Dag.
I benn en deärä Woch en Auschdraliä.
Mid Zrigghaldong kommsch ned weider.
I will hoim.
I wart scho seit'm Meedig uffs Wochaende.
Sie dräggd å bonts Kloid.
Tom isch vor em Kriagsausbruch nôch Kanada gfloå.
Als du heid morgå ned kommå bisch, han i mir Sorgå gmachd, dass äbbes bassierd isch.
En ra gscheida Floischbriah müssad meh Auga nausgugga wie nai.
No guat, dass ma mi ned denka höra koa.
I bleib nô a bissle, wenn'r nix dôgegå hennd.
Diå Regal mid dem Klobabier wared absolud lähr. So äbbes han i en maim ganzå Läbå nô ned gsähå.
Gäld hoißt mä heit Knet, weil mr dômit jeden woich kriagt.
Bei ons send Zärtlichkoitä en dr Öffentlichkeit net gärn gseä.
Scherba brengat Gligg, aber bloß fir d'Archäologa!
Liabr heimlich gscheid als oheimlich domm.
A schees Mädle heiroda, wo nix hat, isch wia aus ra Schissl fressa, wo nix denna isch.
Energie kô bloß durch Kontakte fließå.
An welchrå Haldestellå muåss i ausschdeigå?
Lend ons senga!
Der Reidr hôt an Sebl en dr Hand ghett.
Obacht gäba – lenger läba.
Mechdeschd du Ärdbeerå ässå?
Hosch du an Haischnupfa?
Forgess net emmer dia Gensefiaßla!
„Wa koaschdu figurtechnisch am beschda draga?“ – „An Kaschda Bier!“
Dr Tom will sich ned omziaga.
Ond den Dag machat r zo a ma Gedenkdag, den môn r nä ao feirat als a Fest für da Herrgott, bei älle eure Nächkomma, des gilt als Gesetz für älle Zeita.
Tom muass saine Fählr aigschdeå.
Maria muåss no ellerhand ärledigå.
Tom hôd äbbes gsää, was er ned hedd sää sollä.
Guad, wenn des Zemmr so schee uffgraimd isch, gell?
Wer hot dir so a wiaschds Auto vrkauft?
Nix isch so nix, dass es ned fir ebbes guat isch.
Des Weltall kennd koi Zeit ond koin Zeitbegriff.
Toms Nochbore hott enn oira Tuur gschwätzt ond gschwätzt ond oifach iar Schlabbrgosch et halda kenna.
Am Schwob sai Schätzle send Lensa med Spätzle.
Mee brauchet mir ned macha.
Mr wois niå, wenn mr oin brauchd.
Hör guad zuä, was i sag!
Isch dr Tom allergisch gegä äbbes?
Mir läbad en ra scheena Weld.
I mach heit was fir Bauch, Boiner ond Po, Mauldascha oder so.
Sag eånå, i komm wiedr.
Beim Dialegd fengd diå gschbrochånå Schbrôch erschd å.
Essa schmeggd am beschda, wenn's ebber anderer zahld!
Wär isch miad?
Wenn mr sai Ohr uff a hoißa Herdpladd druggd, koa ma riacha, wie bleed mr isch.
Dees han i fai sälbr kochd.
Älles Machå braucht Fantasie.
Älle Nussgnaggr von dr Wäld roichåd ned aus, älle harde Niss zom gnaggå.
Ald sai isch koi Broblem, abr es isch å Broblem, wemmer ald aussied.
Älles, was sie woiß. han i ihr beibrôchd.
Wenn i mir daine lachenda Aigla auf daine Bilder aschau, no woiß i, dass Frieda meglich isch uff dera Erda.
Mir wärdåd di ned vrgässå.
Wär uff an frischå Wend waardåd, derf et vrschnupfd sai, wenn er wirglich kommt.
Tom drengd gnauso gärå Bier wian i.
Was dr oine gwennd, muass dr andre vrlierå. Des Ganze nennd mr Nullsummåschbiel.
Ma sodd de Leit viel öfters ihre Rechde vorlesa. Viele wissad gar ned, dass se des „Rechd zom Schweiga“ habed.
Er isch vrgifded worrå.
Dees mecht i liåbr ned.
Vielleicht mecht i no äbbes bleibä.
Du wirschd a Schläfle macha.
Send mir heit bessr als geschdern ond morga bessr als heit?
Ruh de aus! Morgå isch au å Dag, ond dann machåd mir weidr.
Liebr a gsonde Liadrigkeit, wie a liadrige Gsondheit.
London isch oine von de gröschde Städt uff dr Weld.
Jetzt halt endlich amol dai saudomma gosch.
Wär Geld hôd, kauft ä Audo. Wär kois hôd, schdirbd anders.
I brauch koin Rägåschirm, s'nieselet jô bloß.
Koi Feschdung isch so stark, dass mr se net mid Gäld einnehmä kô.
Du bisch koin Seggl – aber so wie du sehad se aus!
Dees isch oine von de dreggigschde Städt en dr Weld.
Steer se ned, wenn se schlåfd.
I han då Wolf, då Fux ond då Haså gsäå.
Älle Wäg fangad mid ma Schritt oa.
Wo isch dia Braudjongfr?
Aber gega d'Israelita därf no et amôl a Hond mit dr Zong schlecka, weder gega en Menscha no gega a Stückle Vieh, dass r endlich kapierat, dr Herrgot macht en Onderschied zwischa Ägypten ond Israel.
I schnauf! Meh gohd heit ned.
Jedes Mol, wenn i ebbes kocha will, hör i mai Muader aus 250 Kilometer bruddla: „Ned mid am Messer en d' beschichdede Pfann!“
Mir wellåd meeh.
Er hôd a Katz ond a Karniggl.
Wochålang han i ibr dees Broblem nôchdengd, ond nô isch die Lesong so oifach! I kennd mr en då Hendrå beißå, dass i ed frier druff kommå bee.
Nigga, lächla – Seggl denka!
Bleed gschwätzt isch glei.
Kräht dr Gockel uff 'm Mischd, ändert sich 's Wedder odr 's bleibd, wies isch.
„Lass mi, i koa dees!“ – „Oh, jetzd ischs hee...“
Woischd du, was d'Ärdbeerå etzåd koschded?
Mir send so schnell gloffa, wia mr kend hend.
Er hod mir gsagd, dass er mi aŭ liaba dud.
Au kaufde Schpätzla hend a Recht druff, gessa zom werda!
Sisch net guad.
Isch des Gmies saubr?
Du hôsch jô Gäld, abr koi Hirn.
Dia Mondääg bassat mir net.
I ibrdreib manchmôl.
Kocha koa i net, abr essa!
I ben no et fertig, weil i vrstruubld ben.
I vrrais scho gärå, abr desmôl gugg i dir bloß nôch.
Kenderlacha duat der drauriga Sääle guad.
Tom macht sich emmer luschdig ibr mi.
Worom i so guad mid d'r Moinong von andre Leit klarkomm? – I hör oifach ned zua!
Au dr schdärgschde Rega fängd mid ma Dropfa oa.
I kô mai aigne Handchrift endziffrå.
I vrstand, dass du se kennschd.
Fir dô Fleißige hôd diå Woch siebå Heute, fir dô Faule siebå Morgå.
Willsch du dir da Dag versaua, musch du en da Spiegel schaua.
Tom hôd denkd, dass du dich dô dromm kemmerschd.
Wer hot mir des aodo?
Dr Wend hod då Staub vom Balkô fordblôså.
Duschå zu zwoid isch au å Fraid.
Diå Nudlå send aus Italiå
Danza lern i niå.
Di Jengschde isch dia schenschde gwä vo älle.
S'isch ledschde Woch' bassiert.
Bisch du scho amaal en Ola gwäh?
Dees isch å kenschdlichr Diamand.
I gleich maim Vadr ned.
Meine Eltra sagad ällaweil, i soll ned liaga! I sag no Weihnachtsmoa, Oschdrhaas,Zoahfee!
Bleed gschwätzd isch glei.
Wär koine Emotionå zeigd, hôd koin Werd.
I han då ganze Dag gschaffd ond bee sähr miad gwä.
Tom hôd von sainer Großmuadr å Gschenk griågd.
En onsr Stadt fahråd jedn Dag meeh als 150000 Leit mit dr Strôßåbô (Stand Merz 2019). Siå isch en onserm Läbå å ovrzichdbars Vrkehrsmiddl.
I sôrg ao drfür, dass des Volk en de Aoga von de Ägypter guat ågseha ischd, ond wann r nå gangat, dass r nå et mit leere Händ von sell fort müaßet. Jeda Frau kå von ihrer Nåchbere und von ihrer Hausfrau Silber- ond Goldschmuck ond Klôeder vrlanga. Des gebat r eure Söh ond Töchter, so dent r d Ägypter ausplündera.
A guade Sau frissd älles.
Singapur isch å Schdadschdaad.
Er isch Rechtsôwald gwää.
Tom hos sainen Roman uff ra aldå Schreibmaschinå dippd.
Geduld isch ebbes fir Ofänger! I dreh liebr glei am Rad.
Mir läbad an dr scheenå blauå Donau.
So domm send mir edä.
Liabr dr Maga verrenka, als dem Wirt ebbes schenka.
Wär schreibd no Briaf mid dr Hôôd?
Dublin isch en Irland.
Dees wenige, dass es gäbä hôd, hôd mä vrsuachd, meglichschd gleichmäßig zuä vrdoilä.
Diå beschde Gschäfdr send diå schlächte, diå mr erschd gar ed gmacht hôd.
Es gibt zwoi Arta von Menscha! Schwoba! Ond dia, dia gera Schwoba wäret!
Dr Bus isch genau om achde ôkommå.
Sie friert ned.
Du bisch a Schwob? Di mog i!
Neigier isch schdärger als Angschd.
Sogar ä henige Uhr zoigd zwoimäl am Dag diä richdige Zeid ä.
A ährliches Brodukt braucht an ählichn Vrkaifr.
Mir gäbed Hilfe zom Selberhelfå
Wenn i koin Schwob wär, würd i vorgäba, oiner zom sei.
Isch's vrbei?
Dem gåht dr Soifasiadr uff.
Du bisch so an Esel, Tom!
Sai Muddr isch dahoim gwä.
I hald dees nemmr lengr meh aus!
S’gibd koine Sorgå, dia mr sich ned machd.
I gang grad zu må Fraind.
Mir veschbrad om siebane.
Japanerinnå dragåd å Maske, wenn se koi Zeid hend, sich zu schmenkå.
Wieviel Aiwohnr hod Frankreich?
Alloi macht Bergschdeigå koin Spaß.
Tom håd aufm Kenn a Narb.
Noch vierzeeh Däg Urlaub woiss mr, was wirklich wichdig isch em Läba. Urlaub!
I werd an Dag blaumachå.
Wenn Se huåschdåd odr niåsåd, nô bedegged Se då Mond mid dr Ellåbogåbeige odr mit ama Daschaduåch.
Worom s'endrå?
Komm ond hilf!
'S geit scho bruddal viel Leit, dia fliessend Scheissdregg schwätzad!
Ned gschempfd isch gnuag globd.
I han die Aitriddskartä vorhär kaufd.
Turischdå send om den Geysir romgschdanda ond henn domm guggd.
Mr kô koi neies Läbå ôfangå, abr däglich ån neiå Dag.
Osr Kend kô no ned schwätzå.
Dua net so viel Pfeffr end Suppa!
Von Zeid zu Zeid sodd mr von sich sälbr zrickdretå wiå å Môlr von saim Bild.
Schwoba dirfed des!
I han nuibachns Brod kaufd.
Mr koas oifach ned ällna reachd macha.
Wenn Wirdaberg koiner mega däd, hätte mir's Bada ghoißa.
Kaum machd mr's richdig, scho gohds!
Au Dommheid ond Ignoranz kennåd wachså.
Du kôsch en därå Weld bloß läbå, wenn du se zu deinrå Liebschdå machsch.
So gnau welled mir dees gar ed wisså.
„Wie gôds Tom?“ – „Wies oim so gôhd, wemm mr scho 18 Monad lang dod isch.“
Am Schwoba sai Schätzla send Lensa mid Spätzla.
Maine Herrn, i han Siå fraindlicherweis härkommå lasså, om Eahne maine Endschaidongå berichdå.
Schbare en dr Zeid, nô hôsch äbbes en dr Nod.
Mam, muaß dr Nikolaus vom Nordpok omziagä, wenn dord s Eis schmilzd?
Worom hend Siå Tom gheirådet?
Der Ideåreichdomm isch am greschda, wenn oinr auf domme Gedangå kommd.
Hasch du gsäa, wia sie eich aguggd hot?
Kräht dr Goggl uff 'm Mischd, ändert sich's Wedder oder's bleibd, wies isch.
Bloß ned erwachsa werda. Des isch a Falle!
Mr muaß es ällaweil positiv säha: s'isch d'r ledschde Meedich vo dera Woch!
Dr Honger isch dr beschde Koch.
Dô dribr mechd i liäbr ned schwätzä.
Liebe isch s'Oinzige, was wexd, wem mr s'vrschwendåd.
'S Wichdigschde beim Eikauf isch, ned 's oigene Geld zom nemma.
Was är sagd, isch hoilig.
Å Elend isch des Bewachå vo må großå Vrmegå.
Tom guckt mr beim Schaffa zua.
Mir meget ons arg.
Bisch du an guådr Schachschbielor?
Menner werdad domm ohne Fraua und Fraua welkad ohne Menner.
„Wie schützschd du di am beschda vor dr Sonn?“ – „I gang schaffa!“
Mir brauchåd meeh Drengwassr.
Å gmeinsams Ziel erreichäd mir bloß mitanand, ned nebäeinand ond et hendreinand
Tom isch dômôls mai Partnr gwä.
Zom Gligg han i Bargäld bei mir ghedd.
Dui kommt aus Italien.
Wär frei isch, isch ôågreifbar.
Gohd a Frau en andre Omstend end 'Bäckerei ond sait: „I griag a Brod!“ – Sait d'r Becker: „Sacha geit's!“
Sie schaint die Zwanzger scho hender sich glassä han.
Du muschd net kapitulierä.
Gibts å Schdudendåwohnhaim mid Kantine?
Ällaweil dia neidische Bligge em Fiddness-Schdudio! Sollad se sich hald ihre oigene Mauldascha midbrenga!
Du hôsch di schwär vrändord, seid i di kennåglernd han.
Hoschd mr mol a Feierzeug?“ – „Noi- aber i kennd dir ins Aug langa, des brennd au.
Endweder du häldsch dai Wort oder dai Gosch .
Dia Aibrecher send middå am Dag kommå.
I glaub i spenn.
Dr Witz isch ä Dopingmiddl fir osre Erinnerong.
Gäld koschdet zviel.
I woiss, dass Tom å Diabedigr isch.
A Maa ohne Bauch isch a Kribbl.
Hoimet isch koin Ort – Hoimet isch a Gfühl.
Guck emmr durch die Brill vom Åglagdä ond du wirschd zweiflä.
Tom håd alloi läbå wellå.
Am beschda schlofd mr, wenn dr Traum neba oim leit.
Es gibd Menschä, diä dauchä ondr, om sich ibr Wassr zhaldä.
Se kenned dahommä wardä.
Komm, mir schbialed „I fiahl ebbes, wa du ned fialschd“!
Siesch du, dass*r gligglich isch?
Worom duåds dees ned?
I han Tom ibr da Fluss sĉwemma gsäa.
Mr muass sai Läbå aus dem Holz schnitzå, dees mr hôd, ond wenns kromm ond knorrig wär.
Dees muåss gfeierd werdå.
Due äbbes Salz dorzuå.
Ned jedå Red isch å Evangelium.
Hörrschd du gärn klassische Musik?
Lass ons äbbes ässå gangå!
S'ischd faschd siebåne.
Menedschment isch die Konschd, drei Leit dôdôzuå zom brenga, dass se d'Erbet vo drei Leit machad.
Hôsch du ehm beim Kochå gholfå?
Laut Forschung isch 12 die ideale Anzahl an Mauldascha am Dag.
Dees isch mir au scho amol bassierd.
Hold mi bidde om halbr drui vor am Haubddor ab.
Sischd scho hell!
I läs koine Zeidongå. Was wirkle wichdig isch, erfahr i an dr Börse.
Wella isch wiå kennå, bloß faulr.
Bedengå send ofd bedenklich statt bedengenswärd.
Was moinschd dä drzuå?
Was geits Bessres als a Mauldasch? Zwoi Mauldascha!
Isch dia Arbeidswoch vorbei, kommd au scho dr Sonnaschai.
Gibb mir môl då Schraubåschlissl romm.
Mir gfalled scheene Leit! Ihr Ausseha isch mir do grad egal.
Des isch abr amôle ä schees Haus.
Tom ziagt d'Hoandbrems.
I môg deen Ladä net.
Isch dees Lädr?
Kôsch du da Fernsäer ausmachå?
Schwär koas ned sai – sonschd kenndad's d' Weiber ned.
Om å Hoar hett dr Tom an Ofall baut.
Schwätz bidde langsam ond deitlich!
Gåschd du mir ausm Wäg?
I wandr gärå.
Mir missed ons xendr ernärå.
Solang d'Wurschd dicker isch wie *s Brod, isch's völlig wurschd, wie dick 's Brod isch.
I kô mai Gepäck net fendä.
A hausigs Weib isch d' beschd Schbarkass!
Mai ganz Läbå lang hend mir d'Leit gsaiht, dass i es ned schaffå werd.
Au Weiber kennad a Geheimnis fir sich bhalda, aber nur, wenn mr's dene ned verzähld.
Wia lang vrkaufad Sia scho Auto?
I will ned, dass mai Land å Mitglied von dr Eiropäischå Uniô wird.
Liabr z'viel essa als z'weng drenka.
Sain Opa hôdn bei älle saine Pleen ondrschditzt.
Was isch des Schlemschde, was bassierä kô?
Sei liåbr oimol en dr Sonnå als emmr henderm Mond.
Knapp isch emmr kuurz drvor, abr ned zu schbäd.
Doa gohd ma oimol leichdferddig en d' Wirtschafd, scho kommd ma leichd ferddig hoim.
Dees bedeidet doch ebbes.
„Was hosch du für Hobbies?“ – „Schlofa!“ – „Noi, i moin irgendebbes Aktives!“ – „Essa!“
Ned jeder, der a Lamp heba koa. isch a Leuchde.
Mir soddat dia Zukonft do lassa, wo se isch: en dr Zukonft.
Siå drenged Wodka? Abr dees isch doch des rainschde Gift fir d'Nervå!
Drennå wars so laud.
Du kôsch dahommä warda.
„Wo solle mr nohogga?“– „Uffs Fiedle!“
I han a furchtbare Erfahrong gmacht.
Der Hond isch hongrig.
„I ko Gedanka lesa!“ – „Glaub i ned!“ – „I woiss.“
I denk, Sia soddat ire Gosch halda.
I woiß, dass i manchmol bleed be – i be jo ned doof!
I war diregd hendr dir!
Dr Kiddl isch gfliggd.
Tom hôd a Waffleiså.
Tom hôd gwissd, dass i Maria liab.
Dia Fisch schdengat.
Schaffa, schaffa, Häusle baua, noa Hond vrkaufa, selber bella.
Gaffr hend diå Reddongsleid ghendrd.
Die Börse isch so schdill, dass mr diå Kurse fallå herd.
Fäälr kô må ned enddeckå, weil se fäälåd.
Bevor i mi uffreg, isch's mir liebr egal.
Zammå send mir ôschlagbar.
Wenn dai Weib sait: „Mach, wa de widd“, no mach uff koin Fall, wa de widd!
Är isch rod wiå Tomad.
Beim Klima kô mr d'Wôret et wegliågå.
Mach dees Beschde aus dir, ebbes Bessres kåsch du ned doå.
Wenn koiner woiß, was gschäa soll, saget älle, s'muass äbbes gschäå.
Zamma hend se acht Kender ghet.
I koå da Wagå ned selber ganz machå.
Hasch du gsäa, wia se di aguggd hot?
Mir gängad mid dr Wäld om, als hedded mir no ä zwoide em Koffrraum.
Maria will emmer d' erschde Geig spielå
„Kensch du die schwäbische Schorle?“ – „Obends a Fläschle Wein – morgens a Släschle Schbrudl.“
Tom isch en dä zwoite Stock nondr gängä.
I muaß des nemme so oft macha wia frier.
En dem Neschd isch oi ôe.
A Leba ohne Schbätzla isch meglich, abr sinnlos!
Kopf said Sport – Herz said Mauldäschla.
I benn d'Hitz gwehnd.
Wer billig vrkaufd ond deier kaufd, der hôd am Markd bals ausgschnaufd.
Dees war so onder oos aŭsgmaĉt.
Vorm Schwätza s' Denka ned vrgessa.
Frei isch bloß där, där nix brauchd ond dem nix fähld.
Ond nô isch dr Krieg losgångå.
I schbend älle drei Monat Blued.
'S gibd nix Bessers als äbbes Guats.
Koin Roschdbroada isch au koi Lösong.
I han å greßere Angschd vor Bärå als vor Schbennå.
Guadr Dienschd am Kondå fongzionierd bloß, wenn älle midmachad ond middenkåd.
Wenn a Schraub logger isch, hod's Läba wenigschdens a weng Schbiel.
I säh di gera schaffa.
Warom i so guat mit d'r Moinung von andra Leit klarkomm? I hör eane oifach ned zua!
Kia send de Hendus hoilig.
Dor Beddler isch zrlombd gwä.
Wo kennåd mir ässå?
Waas koa mr do no macha?
Mir isch an ährlichr Deifl liabr als an scheinhailiger Engl.
D'Midde dr Nacht isch scho dr Ofang vom neiå Dag.
I han koi Luscht zom fahra.
So dent r s essa: Da Gürtel ä, d Schah an de Füaß ond da Wanderstab en dr Hâd, so dent r s anandernôch essa, des ischd a Passa für da Herrgott.
I glaub et, dass se durchheld.
*s Oinzige, wa i guat em Griff han, isch mei Bierglas.
Des kô koi Zuäfall sai.
Isĉ dees dai Ziel?
Tom wäär schdolz.
Orôsch isch Toms Lieblingsfarb.
Wär en d'falschå Richdong laufd, muass omdreå.
Dr Tom will sich ned ändra.
Å Voråmeldog isch et needig.
Des Kend isch z'leichd åzogå.
Was hôsch du dô gfondå?
I môg eigendlich Geld ned, abr s beruhigt maine Nervå.
Wär en saim Läbå zguad läbd, wird em Alder dôdôfir bschdrôfd.
Dees isch ons au beinô bassiert.
Älle Wäg fangad mid mä Schridd oä.
Tom isch ned intressierd.
Sag amol des schwäbische Teschdword „ooagneem“.
Å Dame isch ä Frau, diä woiß, was se ned wissä derf, obwohl ses woiß.
Des Scheene an Aktiå isch, dass mr 1000 Prozend gwennå kô, abr hechschdends 100 Prozent vrlierå.
Älle sagad, des gohd ned. No isch oiner komma ond hat des ned gwissd ond hod's oifach gmachd!
Dahoim will wenigschdens d'Waschmaschee von mir o'gmanchd werda.
Mir missad å Endscheidong dreffå, aber glei!
Er hôd sai Dagebuåch em Birro liegå losså.
I denk, dass er bald zrickkommt.
Tom hôd an Rosägaardä.
„Klopf, klopf"“ – „Wer isch doa?“ – „Die Liebe deines Lebens.“ – „Liag mi ned oa, Sbätzla kennad ned schwätza.“
Des sdemmd et, egal, wär s secht.
Dr kranke Kerpr frait sich iber an xondå Geischd.
Guet esse un drenka isch ällewoil bessr wia domm rausschwätze.
Dädsch mi nemma, wenn i wedd?
Dia ganza Wies staht voller Bettsoicher.
Älles Luåg ond Truåg! Där Mensch liågd, liågd ond liågd!
Sei s'ganze Johr liab zu daim Weib – no musch ned an dr Valendinsdag denka!
Mir missed bloß abwardå.
Mai Dande hot a Doggasammlong aŭs Borzellan ghet.
Halt dai Gosch!
Do gohd ma oimol leichdferddig en d'Wirtschafd, scho kommd ma leichd ferddig hoim.
Gligg isch koi Froag des Zufalls, sondern ä Folge gscheiter Endschaidongä.
I mog di.
An aldr Må hôd em Park schinesisĉes Schaddaboxå gmachd.
Was hend diå vrbassd?
Wofiår send die Pedale vom Klavier?
En dr Weschkich hôd mr vor laudr Wassrdampf nemme d'Hååd vor de Augå gsähå.
I brauch koi Google – mei Weib woiß eh älles besser!
An verschiddats Wasser kosch nemme uffheba.
Tom hôd koi Audo ghedd.
Ihr därfets et roh oder mit Wasser gsottä essä, s’muaß mit Feuer bräta sae mit Kopf ond Schlegel ond mit de Ennereiä.
Gang schlofa, Tom!
Sieba Däg essat r ogsäuerts Brot. Glei am ersta Dag muaß dr Sauertôeg aus am Haus sae. Wer a gsäuerts Brot isst vom aersta Dag ä bis zom siebta, muaß ausgrottat wera aus Israel.
Ihr hends ächt guat, ihr hend mi.
Send ned so schdreng mid em!
Äll Dag gschäåd kloine Wonder. Mr muaß bloß gnau nôguggå.
Viele Menschä hend koin Weidbligg, doch die wnigschde wissed dees au.
Bei dem Weffer koa i mei Sofa omeeglich alloi lassa.
D Strôf muass zom Vrbrechä bassä.
Dr Obdimischt fendet emmer an Wäg. Dr Pessimischt emmer å Sackgass.
I benn als zwoide ôkommå.
Vom Ochsa soll ma ned meh vrlanga wie a baar Schdiggle Rendfloisch.
Ebbes, wo de zom Wai saga kosch, aber uff koin Fall zom Weib: Nix Bsonders, aber zom Kocha langds!
Se håd 'n vrärgerd åguggd.
Gugg erschd môl uffs Preisedikedd!
Was fir oin Senn älles hod, lernschd erschd hentrhär odr au niemols.
Dr Sommer kommd des Johr mindeschdens fünf Kilo z'früh.
Schwoba mached koi Pause – mir schonad bloß onsere Maschina.
I komm glei wiedr; i gang bloß fir gloine Mädlå.
Nia vrgessa: sechs Bier send a Essa!
I bee gärå an dainer Seit.
Dô send diå Augå greeßr wiå dr Maga.
Schwäbische Dorfmomente senn: Wenn du dai erschde Fahrstond mid daim Vadder uff*m Feldweg ghed hosch.
Wär vonamå englischå Satz bhaupdet, dass er ôgrammatisch wär, hôd faschd emmer ôrechd.
Mei Lieblingsgeräusch isch, wenn du dai Gosch häldsch.
Sisch net Gold.
Worom send ir suspendiert worrå?
Maria isch ibrarbeidet ond fix ond ferdig.
Sisch mai freier Dag.
Du bisch meeh als di somm vo daine Wörter.
Ihre Aŭgå hend gleichdåd.
Wär hôd des kochd?
Siå hädded ned so schnell uffgäbå sollå.
Å soddå Waffå duåd koiner meeh vrwendå.
Tom isch en ärztlichr Behandlong.
Tom hod sai teschtamend gschriebå.
Do ischs Klo.
Wär emmr uffraimd, isch bloß z'faul zom suåchå.
Tom isch ned arg glicklich gwä.
Diä Faldakrem ischd sähr deier.
Gdanga machåd Gwohnheidå.
Wenn*s oms Gäld gôd, hod jedr dia gleichå Religiô.
Wo håd er Esperanto glernd?
En Boirä isch Beschdechông koi Delikt, sondrn Brauchdomspflegä.
Drhoim isch do, wo du dain Ranza ned aizieha muasch.
Wenn de dir ganz sicher sai willsch, dass ebbes ned klappd, musch de no grad druff fraia.
I benn beim Tom guat ågsĉriebå.
Tom håd sai Wischkäschtle rausghold, om a Foto zom måchå.
Desmôl gang i dir ned aŭf då Laim!
Tom woiß, dass r dailweis Schuld hôd.
Moina derf ma – aber ned moina, ma derf.
I be glügglich, weil mir oifach egal isch, wa d'Leit ibr mi schwätzad!“
Wär sich zarg greå machd, den fressåd Goißå.
Mai Familje isch mai Lääba.
S'wär å kloineres Risiko gwä, å Eisåbôlinie quer durch Afrika zom bauå, als en å ôgsäanâ New Yorker Inveschdmendbank z'inveschdierå.
Tom hôd å guåde Handschrifd.
Emmer wenn frier „Tom und Maria“ kommå isch, send älle Schdrôsså läär gwä, weil älle drhoim vor am Fernsäer gsessâ send.
Menner hend au Gfühle – Honger zom Beisĉbiel.
Nes älles mid zwoi Bagga isch a Gsichd.
En mairä Tass ischh no a bissle warmr Tee.
Wenn Zeit Gäld isch, nô läbd jedr ibr saine Vrheltniss.
I hab geschdern drvo draimt, dass i Mauldascha ess – heit han i mir oine gmacht, läb daine Draim!
Tom isch veriggd nôch omgschdirzdå Ananaskuåchå.
Gang vordraus!
An kloiner Middagschlaf isch ogfähr so, als däd mr dr Daag mid Käs iberbagga!
I han deen Witz et vrschdandå.
I ward jetzt scho oi Stond uff då Bus.
Diå Flaschå isch nô faschd voll gwä.
Maria isch wedr mai Fraindin noch sonschd äbbes.
Menschä machäd falsches Gäld, und des Gäld macht falsch Menschä.
I will amôl am Fenschdr sitzå.
'S isch abheersicher dank em Schwäbischa Dialekt!
Wer durch d'Helle gangå isch, hod vie Feier en sich drenn.
Se werdåd daine Banônå ässå.
Tom isch auf'm Feld dr Ähre bliebå.
Mir Schwoba dädat onsre Fähler zuagebba – wenn mr welche häddat.
„Wia kommt mr am beschda zu de Berliner Philhamoniker?“ „Iaba! Iaba!
Hoimet isch då, wo die Sääle dahoim isch.
Beoruhigt di dees, Maria?
Dr Neischdard dr Wäldwirdschafd isch ä Riesschääs ond gleichteidig missad mir hellisch aufbassä.
„Send d'Kiah scho henna?“ – „Noi, se send no Kiah!“
Jetzåd soddåd gar selberbaschdelde Maskå helfå.
Moa mid Grill suchd Weib mid Kohle.
„Mir vrkaufad koine Zigareddä an Kendr“, hôd die Kassirere gsaid. „Die bleibed also hier.“ – „Abr die send fir main Vadder!“
Wo dr Reichtum regiert, isch d'Armet dôhoim.
Daine Auga send schee
Sie hôd iran Salad et gässå.
D'Zeit isch onendlich, s'Jetzd bloß ä Momend!
Ziag dir daine Stiefl å ond hol Brennholz ausm Waald.
Bevor du frogsch – koi Zeit.
Ihr Huad isch schee.
I ben vo dainer Erbet beeindruggd.
I hann nix ogwehnlichs gsäa.
Lobby hoißt där Ort, wo d'Wissaschaffd am beschda eren Schdammdisch hôd
Tom hôd vor am Spiegl giåbd.
Send Pinguin Veegl?
Tom ond Marie send hongrig.
Mir send hier ned bei „Deitschland suacht 's Middlmaß“.
Tom håd å Dengede wiå ån Goldfisch.
I will ned ihre Fählor nomål machå.
S'gibt å erfillds Läbå drotz vielr ohnerfillder Wensch.
Wär die Hilfe vo Andre braucht, sodd demidig sai.
Komm, schieg de å mi nô, swird Wendr.
Gäb i zviel fir Kloidr aus?
Was hend diå aigendlich vor?
Tom hod då Nåma dr Maria em Delefobuach gsuåchd.
I moin, du soddeschd å Weile ausruå.
Mir send scho seit 2013 dô.
Wer Spätzla mit Ketchup isst, hat d' Kontroll iber sai Läba vrlora.
Wär lachä kô, wo er hät keilä kennä, griegt wiedr Luschd am Läbä.
Fräg se doch oifach amäl, ob se mid dir ausgôhd!
Tom ond Maria hendt Klees gessä.
Isch's woar?
Uff saim Grab send Blômå glägå.
Holad Se mi bidde om halbr drui vor am Haubddor ab.
En wellem Jår isch diå Schuål baud wordå?
Du hôsch mir viel gäbå, abr nô mee weggnommå.
Was hend sia dônôch do?
Tom isch en dä zwoide Stock hoch gängä.
Dees isch zviel uff oimäl.
I kennt heila.
Wer mid am Deifl isst, muess an langå Leffl hau.
An dr Börse muåss mr sich vrhalda wiå beim Bada em kaldå Wassr: Neischbrengå ond schnell wiedr naŭs.
Frier warsch du bildschee! Heit isch nur no dai Bild schee!
D'Midde hengd vom Standponkt ab.
Send des älle ihre Dokumende?
S*gibt bloß oi sichre Prognos em Läbå: då Dod.
Tom hod å kriminälle Vrgangåhaid.
Ihr soddåd an Åwald nehmå.
Maria hôd oin Ohrreng vrlorå.
Des Känguru isch des Wappadier der Finanzminischdr; es macht au mit läärem Beidl grauße Schbreng.
Dr Gehald hier isch a Witz.
I môgs, wenne em Wald be.
Hôsch du ihr då Briåf ibrgäbå?
I will dr Beschde sai – emmer.
Är liagt wia druggd.
No guad, dass ma mi ned denka höra koa.
Wo isch dr Barmensch?
Mir hend wohl Pech.
Ko i ned beurteila! Müssd mi intressiera!
Äe hôd dia Zigarettkippe weggschmisså, bevoror en då Bus aigschdiegå isch.
Mir machad weider, bis oiner blärt.
I han zwoi jengere Briådr.
Was nitzt die beschde Bildong, wenn es am xondå Menschåvrschdand fähld?
Jedr Mensch draimd jede Nacht, au wenn'r sich am andrä Morgä nemme drô erinnräd.
Dr Zug fehrt ai!
Des send fir mi beemische Derfr.
A Leba ohne Spätzla isch meglich, aber sinnlos!
Tom hôd nô ned dia Zeeh butzd.
Bei mir laufad d' Däg ällaweil falschrom. I wach miad uff ond gang fit ens Bedd!
Sisch du main Hond?
Kôsch du des Kend badä?
Hend Se des Tom s*liab do?
An Boom hod Äschde, des isch das Beschde. Denn wär er kahl, noa wär's an Pfahl.
I han å Auto, aber i nutz 's ned oft.
„Babba, woisch des Deng zom Grombiera schäla?“ – „Dia isch ge aikaufa.“
Tom hôd koi Ahnong ghett, dass i komm.
Friher warsch bildschee! Heit isch nur no dai Bild schee!
Des mach i morga! Zack, scho wiedr a Woch rom!
Wenns Wedder so bleibd, ischs morga wia heit!
Dr Turå hôd sich leicht nôch Weschda gneigd.
S'ledschd Jôhr han i an Herzinfarkt ghedd.
Mai kloiner Zaia hilfd mir, em Donkla maine Mebel zom fenda!
Damid s' Essa richdig guat schmeggd, muass es endwedr saumäßig deier sai oder omasonschd!
Diå Dasch isch aus Lädr.
Ond Sia send ä Lehrere, gell?
Wa isch d'r Onderschied zwischa koschdalos ond omasonschd? Mei Schulbildong war koschdalos – daine omasonschd!
Dees isch mir no nia bassierd.
D' Marie isch ganz schee arogand.
I han bloß an mai Hoimet denkå kennå.
Älles isch noach Plan gloffa – bloss d'r Ploa war nix.
Gibsch du em Monad meeh als 20 US$ fir Kosmetik aus?
Mir hend ibr onsre Zukonftspläne gschwätzt.
Du soddeschd ehm soford hälfå.
Tom isch em dritta Stock.
Waarscheinlich hod Tom d'Wooret gsaid.
Mô koå då Dag am Obed lobå.
Dees Dåfir ond Dågegå abschädzå isch erschd då erschde Schridd.
I ben mit dr Not vo mainra Mathearbet zfrieda.
Wenn å Bedrieb guad laufd, wird d'Aktie schlussendlich folgå.
Deitsch ischd a Sproch, Schwäbisch ischd die Vollendung!
„I ernähr mi bewussd!“ – „Du isch grad a Kilo Roschdbroda.“ – „Jo, ond dees isch mir absolud bewussd!“
Ned jeder isch an Moa, wo a Weib hod.
Wie viele Menscha wissat, dass se läbat?
Send Grokodiele en dem Fluss?
Dusch du d'Epfl mid dr Schal ässa?
I mechd gärn an Bord kommä.
Ois vo de seldsamschde Sachå ibers Läbå isch, dass de Arme, dia wos Geld am moischdå brauchad, grad diå send, die niå ois hend.
Mir hend no ned oi Prozent von dem Schdernåsischdem erforschd.
Mir werdad Tom no Âbends treffa.
Ao daene Häuser ond daene Leut ihre Häuser send nô voler Haeschrecka. So ebbes hentt daene Väder ond Großväder bis haet no et gseha, so weit se zrickdenka könnat en dem Land dähannä. Nä hät sich dr Mose romdreht ond hät da Pharao standa lassa.
Die moischde Hemmonga werdad ons durch 'd Erzieong åzichdad.
Wenn Kender blärrad, bschdellad se no ebbes zom Essa!
Ja soll i biddå ond flähå?
Isch's woar?
Gfiale gherad ons ganz alloi, außer mir doiled se mid ebber.
Tom håd dr Maria s'Fristick ans Bett brochd.
Wie kå mr d'Stemm vo saim Gwisså ondrdriggå?
D'Schdimmung isch heit wie's Fondue-Set vo meinra Oma. Im Keller.
Mir gôd däär Gedankä ned ausm Kopf.
Sich domm stella koa sehr gscheid sai.
Des Problem isch, dass i ned amôl diå Frôg vrschdand.
I nemms dir et ibel.
D'Abweggslong fraid oin.
Glaubschd du, dass Gott onser Bätå hehrt?
A bissle isch emmer no besser wia gar nix.
So gnau han i des ned wisså wellå.
I ben en eire Dochdr vrliåbd.
Tom isch mit saim Auto en sai Birro en dr Stadt gfahrå.
Dia Fraua wissed, was se welled.
I koas ned leida, wenn außer mir nix Siaßes em Haus isch.
Wer bei Kardofflbrei ond Soß koin Schdaudamm baut em Deller, isch doch innerlich scho halba hee.
Heit nemme ond morga ned glei.
Risiko endstôd dann, wenn diå Ålegr ned wissed, was se deend.
Megåd Sia d'idalienische Kiche?
Em Zemmer wars kuånaachd.
I woiß jetzt, was Menschä vo Dierä onderschaided: Finanzielle Sorgä.
S'isch ned so gloffå, wiå i's blånd han.
Diå Kirch isch em fuffzehndä Jôrhondrd baud worrä.
D'Zugschbitz (2962 m) isch dr heggschde Pungd en Deitschland.
Mid mir isch heut ned guat Kirscha essa! Spätzla goht.
'S Läba isch wia a Schachdel Pralina. Z' deier.
Wia wird mr am beschda mid Debressiona fetig?
Mir isch boids egal.
Wenn dir äbbr vrzehld, dai Idee sei vrruggd, nô hehr ned auf den.
Wo kommt des bloß emmer her?
Dr Haupdgrond fir Schdress isch dr dägliche Omgang mid Lombaseggl!
Die Börse hôd an empfendlichån Magå, der vrdorbends Zeig soford ausspuggd.
Mr ko au ohne Alkohol luschdig sai – abr heit gang i liebr uff Nommer sicher.
Emmå oinzigå Augåbligg hôd sich maI Läbå vrendrd.
Ned älles mit zwoi Bagga isch a Gsichd.
Tom hôd sai Frau Maria vrmissd.
Sisch ned needig, di vorzschdellå.
Er hôd ned aufherä kennä zom heulä.
Moina derf ma – aber ned moina, ma derf.
I will main Sô åruåfå.
Dees mach i net noch amôl.
Wenn d'Weinachtsgloggå leidet, wird sogar dr Deifl mild.
I ben an dem Ende vo derä Schlang gschdandä.
Dui Frau isch å Nudd.
Ond se håt an saener Fuaßnat gschlåfa, bis an da Môrga. Nå isch se aufgschdanda no vôr am Dag, dass mr no neamerd richtig gseha håt. Ond r hôt denkt: Hoffentlich håt neamerd gseha, dass dui Frao auf d Tenne komma ischd.
A verschiddets Wasser kosch nemme uffheba.
Frier war älles leichder. I zom Beispiel.
Des „Macht nix“ macht doch ebbes.
So wi i Wurschd sag, fangat glei maine Gschmagsknoschba a zom blia.
'S geit nur oine Dreiecksbeziehong, dia funktionierd: Lensa, Spätzla, Saitewurscht!
Wenn älle Menschå sich emmr beischdandå dädåd, breicht neamrds des Gligg.
Tom isch viel älder wie sai Weib.
Mr sodd scho deshalb koi langs Gsichd machå, weil mr dann meh rasierå muass.
Er hôd sain Filler gsuåchd.
Mir send gegä di.
Kauf niå å Aktie, wenn du drnôch ned dômid läbå kôasch, wenn sich dr Kurs halbierd.
Wo schdôd er grad?
D'Pflichd rufd! – Sag 'r, i ruaf zrugg!
Bloß Ozfridähaid ruåfd Widrstand hervor
Mir hôd dr Film et gfallä.
I gang zu mainrä Muadr zrugg!
Schempfä isch leichd, dromm vrsuächad viele dees. Mid Vrschdand lobä isch schwär, dromm dean des so wenig.
Des kô må en Esperanto bessr ausdriggå.
Se hend schdondålang gschwätzt.
Bisch du bei dr Oma?
Bäte ond schaff' au.
I ben em Gras glägä
I han å Lischde gschriebå, was du em Lada kaufå soddeschd.
A hausigs Weib isch d' beschde Schbarkass'.
Bua, such dr a große Frau. A kloine frissd grad so viel, aber langed nirgends nuff.
Wiå hend ihr dees glärnd?
Se hend oi Jåår uff diå Raise gschbard.
Inveschdier nur en å Aktie, von der du vrschdôschd, was se schaffed.
I glaub dass Tom å haimlichå Vrährere hôd.
Wenn sich diå Knoschbå entfaldåd, kô m 8ihr Bliå ned aufhaldå.
Sisch scho kurios, dass d'Heanr beim Schlôfä ned von dr Stang fallad.
Då Schmugg hend diå Dieb ned ôgriehrd; se hends bloß auf dees Klobabier abgsähå.
Der Schbieler, der die heggschde Karte nôlegt, macht dä Schdich.
Digge Ärm ond fedde Wada – du bisch guat zom Mischd ufflada.
I han mi grad gwoga – bee z'kloi.
Kenntscht du aufhöra, elle 30 Sekonda dain Telefon rausziaga?
Wär ibrnemmd die Koschda?
Du solsch dees neåmrd sagå!
Frauå send gfährlich, wenn se d*Wuåd packd.
Wenn mr sai Ohr uff a hoisse Herdpladd druggt, koa mr riacha, wie bleed mr isch.
Nôch dr erschda Milliô fengt mr å, des Kloigäld zehlä.
I lern jedan Dag ä halbä Schdond Englisch.
Frôg mi gfälligschd, bevor du meine Kloidr ausleihschd.
Endlich isch's Freidag!
I schwätz, wie mir 's Maul gwachsa isch!
Då gotzige Platz isch nebam Tom gwä.
Tom fengd Fisch gärå mid Pfeil ond Bogå.
Endlich Freidig! Als reachder Schwob frait ma sich uff da Samschdig, weil ma endlich drhoim ebbas schaffa koa.
Was hend ihr dô gfondå?
Des ganze Joor hod vier Kender, sie hoißet Frieling, Sommr, Herbschd ond Wender.
I han me en deem ômeglichå Båhof vrirrd.
En dr Schual lernå mir läså ond schreibå
Ois isch gwiess, a Agger isch koi Wies.
Dr Idealismus wexd mid dr Endfernông vom Broblem.
Höretse guad zuä, was i sag!
Piede oni uzu la trotuaron.
„Wie viel Leit schaffad bei eich em Gschäfd?“ – „Faschd Hälfde!“
Mir hend viel zom ässå.
Fir di ischs koschdalos.
Mach ämôl a bissle mee Liachd! Mô kä ja gar nix sähä hier.
Grad bevor r zsammåbrochå isch, hod Tom gsagd, dass s em guad gôd.
Tom isch å Dirigend.
Hol mi bidde om halbr driu vor am Haubddor ab.
Wenn i s nô reachd woiß, nô hôd r femf Briädr.
A gromms Holz geit au a grads Feier!
I woiss nemme, wie der Sempl hoisst.
Tom hôd an Hai gsäå.
Willsch du ibrhaupt ned wisså, wiå s'isch?
Tom hôd då Preis zahld.
Mir hend so laud gsonga, wia mr kennå hend.
Eara Dogg isch vom a Auto ibrfahra worra.
Domm bleibt domm – då helfad koine Pillå. Au Aschpirin vrsaagt.
Å xondr Mensch ohne Gäld isch halber krank!
„Wo solla mr nohogga?“ – „Uffs Fiedle!“
„Was misst an Partner in die Bezieong aibrenga, dass er zu eahne basst?“ – „Spätzla!“
Dort hend se net viel zom essa.
Koi guads Buåch zoigd seine guade Seidå zerschd.
Friedrich dr Zwoide war ab 1740 Kenig en Breißå ond ab 1772 Kenig vô Breißå.
Wenn du daine Fählr kennschd, kenschhd du aŭ daine Schdärkä.
Wenn kloine Affa Äffle hoißad, wie hoißead no kloine Mada?
I han ondr am Baum Schutz gsuåchd.
Rache isch siaß.
Tom isch ôsälbschschdendig-
Dô isch jedan Morgå å Oichhernle kommå. Dees war so zuådraulich, dass es sich sogar von dr Maria hôd schdreichlå lasså.
Mô koå neamrd ibrholå, wem mr en saine Fuåßschpurå dabbd.
Wia lang welled Sia en Auschdraliå bleibå?
D'Manna hend zwar d'Hosa oa – aber d'Weiber saged ne, welche.
Sie hof ihr Audo vrkaufå miåså.
Arg vrdreggde Flüss kennat Feir fangä.
Wie viel Leit schaffad bei eich em Gschäft? Fasch'd Hälfde!
I hoff, dass du endlich äbbes gfondå håsch.
Jonggsellå send Menner, diå bloß halb uffs Ganze gangåd.
Gligg isch: wenn mr begreifd, wia älles zsamahengt.
En deem Wald läbåd viele Oichkätzlå.
Se ässåd kaum Floisch.
Was oi Word bedeided, kô å Satz ned sagå.
Z'fuaß got ma uffm Droddwar.
Mach Geld zu daim Godd ond es wird di blôgä wiä dr Deifl.
Tom hett des aloi gmacht.
Hoimet isch dô, wo mr sich et erklärä muess.
So isch des ällaweil gwä.
Des Bedd isch mir zwoich.
Er kommd heid.
Wär an dr Küschde bleibd, kô koine neie Ozeane enddeggå.
Kloine Goischdr intressierad sich firs Außrgwehliche, große Goischdr firs Gwehnliche.
Wilsch du å Bolizischdin wärrå?
I wolld des Johr zehn Kilo abnemma – fehlad no dreizehn!
Des gohd wies Katza macha.
Dees isch fatzaleichd zom erklärå.
I benn echt arm, abr i benn koi Dieb.
Wenn d'Weiber sagad: „Schee fir di“, isch's älles, no ned schee!
Heitzomdaag isch's schwer, bleed zom sai – weil d' Konkurrenz so bruddal gross isch!
Diå weiße Blôåmå brauched å Wasser.
I säh aus wie mai Vadder.
A neddes Kombliment isch ä glaubwirdigä Ibrdreibong.
Tom isch å Schlangåbschwörer.
'S isch no kois denna blieba.
Saine positive Denkede ond saine Åsichdä ibr d'Zukonft hend mi arg begeischdrd.
I han's mir ned rausgsuchd, an Schwob zom sai! I han oifach bruddal viel Gligg ghed!
Heirôte Se ned wegam Geld. Se kennet es ginschdigr leia.
No ned hudla.
S' isch schad, dass dr Tom kaum franzesisch vrstôht.
Die Zukonft hôd koi End!
„I moin, du sottescht a mol mid Tom ausganga.“ – Noi, den mog i ned.“
No ned huddla.
Wenn mir mol langweilig isch, widersprech i oifach maim Weib.
Du bischd ächt an Idi!
Dees isch mir net nei.
Hogged Sia sich nô, wo se wellåd!
Bidde weidrgångå!
I han Angschd bei Gwiddr.
I benn nebrå fremdå Frau uffgwachd.
Do bisch hee.
Dr Kittl isch gfliggd.
Wenn mr ebbes ondr dr Hoad kaufd, isch 'd Härkonfd obekannd.
S'isch emmer no guad ganga.
Mr sodd scho dia Reise åtreta, damid mr woiß, wo's nå gåd.
Wenn d' Leit iber di schwätzad, machsch wahrscheinlich älles richdig!
Där Dorn isĉ sähr dief aidrongå.
I koa heit ned fahra, i muass drenka!
Oifach mol d' Gosch halda.
Bisch du wiaschd!
Tom isch an Sauorschtoffmangl gschdorba.
I benn koi Seifr.
Was de ned biaga kosch, muasch au ned brecha wella.
Dees isch å Schbiel zu zwoit.
Wohnäd em schwäbischä Deppahausä wirkloch bloß Debbä?
Maria hôd sich ombrôchd.
Mr muass die Fildr dauschå.
Tom håd a Loch en d'Wååd bohrd ond å Wassrlaidong droffå.
Viele Kendr hend schwär erziehbare Eltrå.
Wemm mr sonschd koine Broblem hôd, nô kôs sai, dass mr sich oine åaigned.
Des Worom isch diå Muddr von ällrå Wissåschaftå, bloß ned von dr Bersåwissåschafd.
Erschd d*Erbad, nô s'Schbiel.
Hier ischs bassierd.
Tom kô guad sengå, Maria gar ned.
Bisch du vrkäldet?
I koå nix sagå.
No ned uffrega! Du kosch ned älle dod schlaga.
I benn wiklich froh, dass e hier benn.
I benn en Rente.
Irgend äbbes riåchd hier guåd.
Dr beschde Arzt isch dia Natur, weil sie ned bloß viele Leidä hoild, sondrn au niå schlächd von anamå andrå Kollegå schwätzt.
Mir roichts, wenn i woiß, dass i kennd, wenn i wedd.
Wenn mir fählerfrei wäräd, nô dädet mir et so viel Fraid han, Fählr bei andre zfendä.
Wenn mir mol langweilig isch, widersprech i oifach meim Weib.
I hann des Buåch emmer wiedr gläså.
Du muschd net sengä.
Tom isch å sähr talendierdr Mô.
„I benn glei zruck“ hôd må uff ma hangschriebänä Zäddl glesa, wo an dr Birrodiår gläbt war.
Wer beim Essa schwitzd ond beim Schaffa frierd, hod schdudiert!
I hoff, dass maine hochhackige Schuå dia Stapfa ausfillåd, diå se henterlassat5.
„Veronika, der Lenz ist da!“ – „Mir gebbad nix!
Tom hôd hardkochde Oier gässä
Mir werdad Tom no heit Nacht treffa.
Drigged se deen Knopf!
Ond d Noomi håt des Kend gnomma ond ra s an Brust glegt ond ischd sae Pflegere wôra.
Du bischd ned där, deen du glaubschd zo sai, sondern där, den andre sähåd en dir.
Worom solld i diå zwoidbeschde Aktie kaufå, wenn i die beschde habå kô?
I will dai drhoim säå
Schneggå ässå isch schwierig.
Wenn du rå Bank weniger als å Millio schuldeschd, hôsch du an Glaibigr. Wenn du mee als å Millio schuldeschd, hôsch du an Partnôr.
Gäbb älles, was du hôschd... mee kôsch du et dô!
I benn em å Bood.
Mir faret em Sommr nôch Siebåbirgå.
I hoiß David.
Send Siä an Reportr odr vielleicht von dr Bolizei?
Glicklichrweis hôd’s koine Vrletzde gäbä.
Worom hôd där so å grauß Haus?
Auf dui Art hätteschd mi grächd.
Du bisch stark ond gross wäga Spätzla mid Soss.
Gscheite Gockelor frisst dr Fux au.
Spätzla send bloß schädlich, wenn d'r an Zehn-Kilo-Sack uff dr Koopf fälld.
In ra Beziehong geits ällaweil oin, der reacht hod, ond oin Moa!
I bleib nô a bissle, wenn Se nix dôgegå henn.
Was woiß i?
Wenn i s nô reachd woiß, nô hôd se femf Briädr.
Viele Menscha werdåd woich, wenn's hard uff hard gåd.
Tom isch geischdig abwesend.
Was hôsch du drnôch do?
Endlich war i mid Tom alloi.
Hock na!
Mir hend heit koi Zeit fir ebbes andres.
„Wolldesch du ned uffschdanda?“ – „Schdemmd. I wolld ned uffschdanda!“
I mach, was e ka.
Her uff, dai Zeid em Internet zom verplembrä!
Also streck i mae Håd naus ond schlag dia Ägypter mit älle maene Wonder, môn i sell doa will, nå läßt r euch frei.
Tom hôd ä Schiefrdafl ghedd. Aŭf dr oinä Seide waräd Liniä, auf dr andarä Käschdlä.
Suach ned nôch Fählr, suach nôch Lesongå.
Tom dät gära weniger schaffa ond mee hoimbrenga.
Kenndeschd du miar äbbes zom drenka gäbå?
Noi, i schnarch ned. I träum no drvo, a Mofa zom sai.
Ond des isch a Schnook.
Dees schmeggd ôglaublich guad.
Tom spield Drompet.
Atmå gohd audomadisch. Ond wiå isch dees mid läbå?
Her auf, d'Leit guggad scho.
Ohne den oizelnå däds ned diå vkiele gäbå.
En maira Hos' isch es Stoßband los.
Mr koä diä Gwinne ned kapitalisierä ond d'Fählr sozialisierä.
Was fir Waffå hend se ghett?
Tom hot a baar dode Fisch aufm See schwemma gsäå.
Tom hod d'Morgåzeidong gläså.
„Send bei ons Gedangga nô frei?“ „Jô, wenn de ned dribr schwädschd!“
I mach's bloß, weil du's bisch.
Dr Gscheide isch laise.
Maine Kender ässåd am libschdå Schbätzlå mid Soos.
I han denkt, dass dr Maria dui Art von Musik gfelld.
I mog Nasherner, dia send wie Einherner, nur fedder.
Jedr Ålegr kô mid Aktiå reich werrå, wennr saine Hausaufgabå machd!
Älles dees brauch i ned.
En viele Fäll beschdôd kaum Aussichd auf Aisichd.
Se hôd koi Arbet ghett, koin Fraind, koi Gäld ond koi Wohnung.
Dees hoißt ma Fordschridd – kaum hådd ma sich dia Delefonnommra gmerkt, no werdad se omgschdelld.
Des Gsetz gilt en Japan net.
I koa scho kocha, aber 's schmeggd hald koim.
Gottes schönschde Gabe ischd und bleibt der Schwabe!
Dees hôd mir mai Schweschdr beibrôchd.
Wiå hend Siå des glärnd?
Zwischa Läbr ond Milz basst no emmer a Pils.
Saine Worde hend mir Muad gmachd.
Muschd du wirklich elles mid daine dreggige Hend âlanga?
Schwäbische Schorle: Obends a Fläschle Wai – Morgen's a Fläschle Schbrudl.
An Fuchs isch schlau ond schdelld sich domm – bei manchna isch des andersrom!
Onsr Haus isch en derå Gegend des oinzige mid am ma Schiefrdach.
Wissat daine Eltrå, dass du rauchschd?
Tom ischå Hailigr.
„En dr Schual henselät mi älle, weil i so dick ben“, hôd sich Maria beklagd ondr Tränä.
Wenn harde Ärbet so å wondrscheene Sach wär, nô dädåd dia Reiche se älle fir sich bhaldå.
Wenn mol ebbes zom Essa uff dr Boda gfalla isch – des fressad d' Vegl.
Dees Foto isch ibr hondrt Joar ald.
Håsch du koine zwoi Minuddå fir mi?
I han gnuag Geld fir da Reschd vo maim Läbä, außr wenn i mir ebbes kauf.
Tom hôd sich des Bild uff derå Schachdl ôguggd.
Schwoba send am Herrgodd sai Maischderschdiggle.
Meh wia an Schwob koa dr Mensch ned werda.
„Schätzle, sag mir die drei magische Werder: Mauldascha send fertig!“
I schnauf! Me gohd heit ned.
Tom schwätzt Franzesisch bloß drhoim.
Wie hoisch du, mai Siaße?
En deene aktuell schwäre Zeidå frogd mr sich, en welchrå Vrfassong osr Grondgsetz isch.
Leischdong isch s'Ergäbnis vo Motivatio.
I wiard nia noi saga.
I woiß, du kåsch meh! Mach meh aus dir!
Ois ond drei send ôgrade Zåhlå.
Dr Honger dreibds nai.
I beddl diå ned om Vrgäbong.
Die Menschheit! So å witzigs Marioneddåtheatr!
Mr sodd die Hoffnung niå aufgäbå.
Drei Sacha mach i mir ällaweil z' viel: Gedanka, Hoffnonga ond Spätzla.
Wenn Faulsai olimpisch wär. würd i gära Vierter werda, damit i ned uffs Podeschd muass.
Wenn du schwemma willsch, no schwemm doch!
Flädlesupp isch die beschde Medizin.
Was em oinzelnå et meglich isch, dees kennåd viele.
Er isch ibrgligglich gwä.
Wenn å Mô an vollå Maga hôd, isch's egal, ob r reich odr arm isch.
Morgå isch dr 20. Okdobr.
Tom isch auf ma großä Lädrstuhl gsessä.
Dr Tom hot dees gschafft.
Liebe isch, wenn de aussiehsch wia an Sagg Grombiera, aber oguggd wirsch wie hoisse Pommes.
Waas wird no älles bassiera?
Wär Schmeddrling sähå will, muaß Rauba akzepdierå.
Er isch no nia em Ausland gwä.
Älle hend uff da Dod von dem Aldå gwarded, der ned stärba hod wellå.
Liabr heimlich gscheit als oheimlich domm.
I han maine Notizå ôguggd.
Maine Auga dont weeh.
Mir hend Tom geschdern Obend gsäa.
Gibds andre Meglichkaitå?
Wermd eich am Feier.
Hôd eich koiner zoigt, was mr mid dem Blenger duåd?
Mai Bruådr issd koi Obschd.
I mecht n kennälernä.
Was machsch denn du doa?
Dr Februar isch dr käldeschde Monat em Johr.
I hann nix gegå grubbåsex, wenn di grubbe å Må ond å Frau isch.
D' schwerschde Schbroch isch ällaweil no „Klartekschd“.
Wenn de morgends uffwachsch ond's duad nix weh, bisch hee!
A Frau machd sich ällaweil Sorga om ihre Zukunfd, bis se an Moa hod. – A Moa machd sich koine Sorga om sei Zukunfd, bis er a Frau hod!
Dahoim isch fir mi do, wo's Spätzla geit!
Damid de ä guadr Môler bisch, brauchds vier Sachä : ä woichs Härz, ä fains Aug, ä leichde Hôd ond emmr frischgwäschene Bensl.
Ihr kennäd dahomma wardä.
Mennr ond Frauä dengäd fondamendal vrschiedä.
Wemr älles berechnåd, brengsch nix nô.
Geduld isch die oberschde Tugend von am ma Inveschdor.
Duar amol gschdäd.
Tom hôd et miad ausgsää, wenn Se mi frôgäd.
Mai Vorliabe em Bedd? – Schlofa!
Worom beschbrecht ihr dees ned oifach mit Tom.
Egal wie viel Spätzla du essa duaschd, d' Schua basset emmer.
Mr woiß scho lang, dass des Ibersetza von dr gsprochana Sproch sauschwer isch.
Mach endlich amol dai Wischkäschtle aus!
Denk dir ebbes aus.
Tom isch en dr erschdå Klasse vrreisd.
Du muschd dees dô.
Älle Schbrôchå hend å Kuldur.
Tom hôt sich vrschluggd.
'S Ländle vermissa fühld sich wia Liebeskummer a.
Silbr isch des neie Gold.
Ond Sia send ä Lehrer, gell?
Älles fangt mid dr Sehnsucht ä.
Mogsch du mi no?
Du kôsch mi ned bedriågå.
Sei vorsichdig, wenn de Sonnablomå Eel transbordierschd.
Om å Hoar hett dr Tom an Ofall baut.
„Schau mr a mol“, hod dr Blende gsait ond erschd nix gsea!
Wo send älle maine Fraind?
Manchmol wär i gern denner – aber no fälld mir wieder ei, wia granadamäßig guat Spätzla mis Soß schmeggad.
Weil i då ganze Dag gschaffd han, benn i sähr miåd gwä.
Tom isch em a katholischå Haus uffgwachså.
I woiß et, ob i Tom ibrzeigå kô.
I han mr denkt, neåmerd isch en dr Kuchå.
Tom isch am Soil naufgleddert.
Dees ischs ledschde Loch.
Pagg daine Sachä ond vrschwend aus maim Haus! I will di niå nômôl en maim Läbå wiedersäå.
I war nô nia so saumäßib bsoffa.
Mai Filler tut net.
Tom hôd en Tokio en å må Kapslhotel ibrnachdåt.
Da Burj Khalifa isch jetzat da hegschde Wolkagratzr vo dr Weld.
Der lachat bloß em Keller, wo's neamrd sieht.
I will ned mai ganz Läbä hier zuabrengä.
I han dees omsonschd gmacht.
Om wieviel Uhr macht des Museum zua?
Bisch du scho amaal en Ola gwäh?
I will mee wia ä Endschuldigung.
Der Hagel håt ällas zsemaghaoa, was aufm Feld draußa gwea ischd, Menscha, Vieh ond ällas Gwächs. Sogar Baem send zsemakracht.
Des machd mi ganz ferdig.
Ir misst dees dô.
Sisch net dai Geld, was i will.
Wo bekomm i an Schdadplô?
I hann an sauguadn Wai em Kellr.
Dai Nåchrichd isch fordgschiggd wordå.
So machäd mir Eisgreem.
I han drauf gwarded, dass des bassiert.
Hosch du des Tom s'liab do?
Anschainends glaubschd du mir eddå.
Manchmol will i oifach ned uffstanda – aber no fälld mir wieder ai, dass es heit Spätzle geit!
Ebbas Sauers därfat r überhaopt et essa, egal môn r wohnat, därfet r bloß ogsäuerts Fladabrot essa.
Mai girgele frai di, etzt kommt a Blatzrega.
Schwätz ned so domm dåhär!
Älle Mennr hend bloß zwoi Sachå em Senn, Gäld isch des andre.
„Bäddäd iohr drhoim vorm Essa?“ – „Noi - mai Muader ko kocha!“
I gang nô zu mainer Fraindin.
S'isch meglich, dass i mai ganzes Läbå em Gfengnis sai muass.
Muaddersproch: Schwäbisch!
Mai Schwschdr hôd mir beibrôchd, wiå mr d'Håår flächdåd.
Sai Grab isch et weit weg.
I han neilich drei Diäta gmachd – von oira alloi werd i ned satt!
Gäld vrdirbt bloß den Charakter, der scho vrdorba isch.
Sisch säär hoiß.
Die große Wäld stôhd bletzlich still, weil å kloiner Virus dees so will.
I han kaum schdandå kennå.
Kennded Se miar äbbes zom drenkä gäbå?
Dees han i ironisch gmoind.
Tom dreggd heit Schwarz.
Diå Schdrôß isch vom Vrkehr vrschdobfd.
Bei mir laufad d'Däg ällaweil falschrom. I wach miad uff ond gang fit ens Bedd!
Hend Sia gsäa, wia sui Sia aguggd hot?
I han scho gnuag dô.
Mir säåd ons am Sonndich en dr Kirch.
An Gscheider koa vom ma Domma lerna. Abr koin Dommer vom ma Gscheida.
Was em Läbå wichdig isch, han i älles en Tatoeba glernd.
Ond d'Nåchberna hent an Nåma ausgruafa ond gsaed: A Soh ischd gebora für d Noomi! Ond se hent saen Nåma gruafa: Obed. Des ischd dr Vadr vom Isai, am (König) David sae Vadr.
I komm ned, wenn s morgä rägnäd.
Onsre Gäul send miad.
Wer danzt, hod bloss koi Geld zom saufa.
Ess net so haschdig.
I hann sain ledschdå Romå kaufd.
Lenks isch wia rechts, bloß auf dr andara Seit'.
Siå hôd ned oi Sekond nôchdenkd.
Am scheenschda bisch, wenn de koim gfalla willsch.
I kenn ihrån Vaddr.
Wenn du denkgschd, å dods Pferd z’reidå. nô schdeig ab!
I benn ned perfekt – aber als Schwob vrdammt noah droa!
Mr koå an Menschå mid ra Wohnung genaŭ so ombrengå wiå mid ra Aggschd.
Dees isch mir au scho amol bassierd.
Du môgschd Mädlä, gell?
Diå Kendererziong isch fai schwieriger als i denk han.
„Kennsch des, wenn ma am Wochaende meh gmacht hod, wia ma sich vorgnomma hod?“ – „I au ned!“
Diå Leid dord send komisch.
I ka di net zoiga.
Idealmaße von ra Frau: Schwäbisch, luschdig, ährlich, schbarsam.
Kenndescht du et langsam schneller fahra?
Was i au en d'Hand nemm, dees glengd mir au.
Des muass i mainer Faulheid jo lassa – se hod a gherige Ausdauer.
Send ned so genau. Drnäbä isch s'Läbä.
Å jedr machd es äbbes andeschder.
I moin, sisch jetzetle z'schpät drzua.
Nur weil de en dr Zug kotzd hosch, bisch no lang ned bahnbrechend.
I lass mi ned so gärn ondrbrechå.
Denn se liäbr dees, was diä sagäd.
Von ra gwisså Somme å secht må zom Gäld Kabidal.
Drhoim isch's oifach am scheenschda.
Tom ond Marie hend Buachala gsammlat.
Menner hend au Gfühle – Honger zom Beischbiel.
Älles Große kommt vonam drotzdem.
Mir send Schwoba. Des rechtferdigt älles.
Tom hôd koi Fahrrad, Maria abr scho.
Mai Sofa ond i, mir vrschdandad ons blend.
Was welled ihr mir sagå?
Sie hot den Briaf emmer wiedr nochamaol gläsa.
Saine Witz dend weh.
Erfahrong isch die Summe von älle onsere Irrdömmr.
Beim Geld ischs wia mid em Meerwasser. Je meh ma drvo dronka hôd, je meh wird mä durschdigr.
Deen mr zsammapagga ond vrschwenda.
Mir ässat net.
mach oifach dees, was dai Muadr said.
Koi Mensch nemmd an guadä Rät ä, abr a jedr nemmd gärä Gäld, also isch Gäld bessr als ä guatr Rät.
Dees Bedd isch no warm.
Manche Menschå semd wiå Mangned. Oheimlich ôziend.
A männlichs, oejährigs Lamm ohne Fehler solls sae, von de Schäf oder Gôesä sollat er s nemma. Des hebat r bis zom vierzehnta Dag von dem Monat auf, dä solls nä de ganze Kultgemaende von Israel gega Åbad metzga.
Satt hoißt jo ned, dass koine Spätzle meh naibasset.
Sie dent nemme so narrat.
I môg dai Kochkonschd.
Ma koas oifach ned ällna reachd macha.
Hendr gsäa, wia se eich aguggt hot?
Koiner isch fählerlos.
Mir megåd eich.
Ondå schdôd ebbr, där di schbrechå will.
Ab ma gwissa Alder hoißd Gligg, en an Raum zom komma ond no wissa, wa ma wella hod.
S'geit no Menschä mid Vrschdand en onserm Land, Gottseidank.
Tom isch oifach emmr gegå älles Neie.
I han schdaubgsaugd ond uffgwischd.
I bleib nô a bissle, wenn de nix dôgegå hôsch.
I heer zuå, abr i heer nix.
S'fälld Schnee en de Berg.
Se schreibad.
Manchmol gugg i mir d'Leit en maim Alder oa ond denk mir: Haidanai, nommoal bruddal gligg ghed.
Dees kasch du so onemma.
Wer då ganzå Dag schaffd, hod koi Zeit, Gäld zom vrdienå.
Des greschde Broblem von dr kinschdlichå Entelligenz isch: Du kåschd ära koi Angschd machå!
Ganz nett! Aber hald ned Schwäbisch!
Er hoißt Tom.
Dees Buach hôd mir et gfallå.
I han denkd, so wärs leichdr.
Mr kå ned erkennå, wiå kuurz a Monat isch, bis mr Alimende zahlå muass.
Tom guggt gera alde Film â.
Deent em bloß des Buach gäbä.
Dui Sprôch isch fir mi ôausschbrechbar.
Zweifl fieråd zur Vrzweiflong.
I war nô niå em Zirkus.
I benn uff mi selber schdolz gwä.
Kommas send komblizierd.
Dr Näbl hôd se vrschluggd, bloß eäne Sdemmä hôd mä herä kennä.
Gäld kô mr ned atmä, drenkä odr ässä!
Tom hôd älle saine Fraind vrlorå ond hôd koine neie fendå kennå.
Gibds Goischdr?
Aigålob schdengd.
Layla hôd di Kreditkart von ihrå Muådr emmer gnommå.
I glaub, dass är Angschd hôd vor dera Schbenn.
Tom arbeided en ra Schäferei.
Du wirschd di au nô an diå Hitz gwehnå.
Wem mr ned auf kloine Gwenn vrzichdå koå, wird mr koine große Gwenn machå.
Oh liabs Herrgöttle vo Bibrach!
Tom hôd 14 kg abgnommå.
Wia lang bleibschd du en Auschdraliå?
I benn z'alt fir den Scheiß.
Du soddeschd nix gnaggå wellå, an dem du dir de Zehn ausbeischd.
A schwarza Kuah geit au a weissa Milch.
Uff dem Disch isch å digge Schdaubschicht gwä.
Wendschdill ond 23 Grad – ach noi, be no denna.
A bissle domm isch jedr – abr so domm wia manchr isch koiner.
I will jo ned ågäbå, abr es schdemmd!
I be ned erwachsa, i säh nur so aus.
Mir brauchäd Holz fiirs Feier.
Wär schwädzd, macht Bolidig! Wär was duåd, vrenderd d'Weld°
Tom drenkt gerå Milch gnauso wian i.
Maria môg sähr gern siass-saure Himbeertorte.
En dr Coronakrise missed mir zsammå alloi sai.
Heit gild jeder Autofahrer an Rassischd, wenn'r rechts abbiagt.
Mr muass des Omegliche vrsuåchå, om des Megliche zom kriågå.
Vorm Schwätza 's Denka ned vrgessa.
Woisch du, wia mr deen Roifa aufbomd?
So ebbes han i no nia gsäa.
Woisch du, wo i dai Kennkart gfondå han?
En ällem was läbt, steggd doch diå Fraid.
I mach Kucha saŭber.
Mir hend dô Zug grad nô griågd.
Ma hod nia z'viel Schuah. Mr hod no z'weng Schrank!
Sie hod emmer a Buåch dåbei.
Tom, diä Herrä send von dr Bolizei.
Schôf send wolllüschdige Diere.
Wenn's om Geld gôht, geits bloß oi Schlagwort: „Meeh!“
Du bisch au so gscheid wie an Meter Feldweg.
Tom hot scho ibr oin Monat koi Arbet mee.
Mir kennat emmer aŭfheera.
Tom hodd d'Rechnong ohne då Wird gmacht.
Worom hôsch du Tom oine rondrghaua?
Du hilfschd de Kender.
Wenn du mid dr Ärbed ferdig bisch, derfschd du hoimgångå.
Isĉ dees eier Ziel?
Scho schlemm, wenn mr emmer vrbesserd wird.
Liggd Schnee uff'm Glender, isch Wender. Liggd's Glender em Schnee, isch's hee. Liggd's Glender onderm Schnee, war's em Sommer scho hee.
I koå, weil i will, was i muass.
Ond se sollat von dem Bluat nemma ond boede Türpfosta ond da Türasturz von dene Häuser, mô se drenn essat, drmit ästreicha. Des Flôesch sollat se aber no en dr gleicha Nacht essa, am Feuer bräta sollat se s essa ond a ogsäuerts Brot mit bittere Kräuter drzua.
Maria hôd ä Åbedkloid dragä.
Die moischde sog. Sähenswirdigkeitå send scho vom vielå Nôguggå ganz ôgnuddzd.
Worom isch Marie alloi?
Kempfr aldred oifach bessr.
Wichdig isch, dass d' emmer ebber hosch, der em entscheidenden Moment noachschenggd!
Manchmol fühld sich mei Läba wie an Teschd oa, fir den i ned glernd han.
Außr mir sen älle en kloine Grubbå vo Fraind zammågschdandå.
I glaub, mir kenned d'Jurischdå en d'Kategorie dr Monschdr airoiå.
Manchmol fühld sich mei Läba wie an Teschd oa, fir den i ned glernt hab.
Mit dem Wischkäschtle als Spiegl hat sich Maria nachgschmingt.
Gäld ischd a herrlichä Ausschduier. Am beschdä ohne Frau.
Mir send sähr obtimistisch.
Er hôd mir vo sainrä neiä Erbet vrzehlt.
D’Wend hend Ohra.
Ihr Gäld isch ned vrlorå – es hôd etzat bloß å andrer.
I woiß zwar ned, was ihr vorhend, abr i wensch eich Gligg.
Wo fangäd mir ibrhaubd ä?
Au dees beschde Ondrnemå hod als kloinå Idee ågfangå.
Mr duåd, was mr koå.
Guade Ideå hådd ma oft en åguade Zeidå.
Willsch du an Bolizischd wärrå?
En maim Läbå geits Heå ond Diåfå.
Es pressierd net.
S'isch wiklich mai Haus.
Koin Roschbroada isch au koi Lösung!
Diefkihlkoschd isch lang haldbar.
Des isch mir älles zu kendisch dohanna – komm, Teddy, mir gangad.
Am liabschda mog i s'Zoichna.
Älle Draim kenned wôhr werdå, wenn mir då Muad uffbrenngåd, eahne zfolgå.
Tom siehd auf dem Bild guad aus.
S'bleibt net so, wia s'mol gwä isch.
Ärzte send Leit, diä ôläserliche Rezept schreibäd, wenn se sich mid ihrer Diagnose ned sichr send.
Was hend ihr dôrnôch do?
I seh es ond halt's Maul.
I bee jetzd em ma Alder, wo mir oi Wochaende en d'r Woch nemme langd.
Å Idee, wiå mr guad klaut, isch å Konschd fir sich.
Ben i där, wo ihr suåched?
Kenndet Sia des Kend badä?
Å Kua machd muh, viele Kiå machåd Ärbed.
I môg Obschd ond äss es äll dag.
Em Fasching maskierd mr sich, nô kô mr diå Maske au fallå lasså.
Tom machd emmr an saim Wischkäschdle rom.
Reich wird zukinftig ned där sai, der meeh hôd, sondrn där, der weniger brauchd.
Maria hôd å hellå Haud ond kuurze Lecklå.
'S Leba koa so schee sai! Musch's nur geniessa!
Kennsch den Moment, wenn de oifach mol koi Luschd uff Spätzla hosch? I au ned!
Tom isch an ons vorbeigsaut.
Leichdende Schmedderling send ibrall romgflogä.
A guade Soß ond an Bolla Floisch erweggad en mir Läbendsgeischdr.
