Der Ideåreichdomm isch am greschda, wenn oinr auf domme Gedangå kommd.
Håsch du ihm glaubd?
D'Sonnå isch schee.
Liebe isch s'Oinzige, was wexd, wem mr s'vrschwendåd.
Wie viel Menschå wissed, dass Siå läbad?
Oes, zwoe, droe, vier, fümf, sechs, siibe, acht, noen, zaen.
Die große Wäld stôhd bletzlich still, weil å kloiner Virus dees so will.
Hock na!
Gäbb älles, was du hôschd... mee kôsch du et dô!
D’Wend hend Ohra.
Tom isch an ons vorbeigsaut.
S'gôhd om Ihre Schwester.
Am 1. Januar 2019 flog die Raumsonde „Neue Horizonte“ (engl. New Horizons) an dem urzeitlichen Kuipergürtelobjekt Arrokoth vorbei.
Hock na!
Wär Schmeddrling sähå will, muaß Rauba akzepdierå.
Wir leben in einer komplizierten Welt.
I benn nebrå fremdå Frau uffgwachd.
Siesch du, dass*r gligglich isch?
Rache isch siaß.
Guada Morga!
Tom gelobte, eines Tages Rache zu nehmen.
Ois ond drei send ôgrade Zåhlå.
Schildkrotta hend koine Zee.
Isch's woar?
Siesch du, dass*r gligglich isch?
Hock na!
Isch's woar?
Wie viel Menschå wissed, dass Siå läbad?
Deidschland isch å grooß Land.
Da Burj Khalifa isch jetzat da hegschde Wolkagratzr vo dr Weld.
Isch dees so pressant?
Eschdr hôd a Nommr an ihrem Arm.
Schildkreta hent koi Zee.
