Denk dir ebbes aus.
Ois, zwoi, drei, vier, femf, sex, sibå, acht, nain, zeh.
Er isch no nia em Ausland gwä.
Worom beschbrecht ihr dees ned oifach mit Tom.
Wo fangäd mir ibrhaubd ä?
Wie kommschd du denn drauf, dass i mid ebbr ausgangå bee?
I benn wiklich froh, dass e hier benn.
Mir gôd däär Gedankä ned ausm Kopf.
Dees Bedd isch no warm.
Ihr kennäd dahomma wardä.
Denn se liäbr dees, was diä sagäd.
Mir send koine äfengr.
Eschdr hôd a Nommr an ihrem Arm.
Du muschd net kapitulierä.
Dr Morgä isch d schenschde Zeid em Dag.
Des sdemmd et, egal, wär s secht.
I koa net vrzeiä, was du dô hôsch.
I muass langsammr sĉwätzä.
Tom isch å Dirigend.
Dees mach i net noch amôl.
Môgsch du dees Land?
Dees isch mir no nia bassierd.
I han drauf gwarded, dass des bassiert.
Ihr kennäd dahomma wardä.
Er hôd ned aufherä kennä zom heulä.
I denk, dass er bald zrickkommt.
