Urabona iyi nzu? Ni rwanje.
Reka ndakugurire gishasha.
Mwahuye?
Nshaka kuganira nawe.
Ndakwumviriza.
Bite uyu munsi?
Sinzi ico nshaka.
Waciye ku kimenyetso c'itara ritukura.
Ndabasavye, mumpe ifagitiri.
Ntegerezwa gutaha.
Ntanumwe azi ibikenewe gukorwa.
Nzobiguha.
Kubera iki mumbaza?
Urarurumba.
Ntaco nywa.
Ufise bazoka mu kanwa, yicire.
Wifashe gute?
Ingo!
Urashaka ko nza?
We si umwana.
Uragenda canke?
Nagira ngo woba watashe.
Urashaka ko nza?
Igituma c'urugendo rwanyu ni nyabaki?
Nyene uyu muduga ni data wanje.
Harashushe cane, sivyo?
Sindagutegera.
Sinkunda kwiruka.
Ntundabe gutyo.
Biragushimishije?
Kubera iki mbwirizwa kugenda.
Kubera iki utari kw ishure?
Ndakwiyumvira.
Bite uyu munsi?
Sindi umuntu mwiza.
Urihe?
Naguze amagi n'amata make.
Ugurura idirisha.
Ntutegerejwe kuza.
Ndazi ingene umuntu ashikayo.
Turavukana.
Bagutwaraye hehe?
Ndakunda kuza ino.
Nahaye umuhungu igitabo.
Ndazi iyo mbwirizwa kuja.
Ni binini birenze?
Ntukomeye muri vyo.
Uyu muduga ni mwiza cane.
Iri jambo riva mu kigereki.
Urazi ko mbwirizwa kugenda.
Narinzi ko bigushimisha.
Uyu muvinyu ni uwande?
Ushaka kuja hehe?
Ntugende zirayoye.
Sinzi gute.
Ndazi ko wumviriza.
Iki ciyumviro cari icande?
Mbabarira ko nagutaye mu rudubi.
Nkeneye umwanya wo kwiyumvira.
Ndazi uvyirumvira.
Ndiko nduhuka.
Noshimishwa no kumenya izina ryawe.
Iyi hinguriro rikora ivyuma vy'imiduga.
Kubera iki bari aha?
Umuvyeyi wanje arankunda.
Ni rwacu.
Uranezereza.
Urambabarira ko ndabivuze.
Twugurure idirisha!
Ntimukeneye gunkengurukira.
Ndanezerewe ko uhari.
Murashaka kubitora?
Nje gusezera.
Uranhunga ko ndabivuze.
Ni umuduga wanje mushasha.
Ndanezerewe ko uhari.
Biranyuze.
Ico gisa n'ivu naco nyene ni rwanje.
Sinshaka gutunga.
Ntanumwe yarazi ibikenewe kurangurwa.
Uribuka?
Mpore ko ndabivuze.
Mpore ko ndabivuze.
Si neza.
Ukora iki ngaha?
Uramuzi.
Asa na nyina wiwe.
Nta wundi muntu yarahari kiretse jewe.
Biragushimisha?
Utaha ryari?
Ntimukeneye gunkengurukira.
Murazi aho mba?
Nta mahera tugifise.
Yamoye umutwe wiwe.
Uzi iki?
Nganirira umugambi wawe.
Ntusubire kubikora.
Sinzi aho muba.
Uvyuka ryari?
Ico gisa n'ivu naco nyene ni rwanje.
Uri ngaha kugira umbone?
Ndazi ibikenewe gukorwa.
Ndazi kubikora.
Umuduga wanje urihe?
Uramuzi?
Mbe nambare iki - ipantalo canke ijipo?
Ndazi ico wiyumvira.
Birampimbaza.
Kubera iki ujaho?
Uranezerewe?
Iyi nomero ya terefone ni iyande?
Igitabo kirihe?
Mpa isaha yawe.
Kubera iki umbaza?
Umuduga wanje wapfuye.
Sinzi ingene witwa.
Yamugomwe.
Abo ni abajapani?
Ndamukunda.
Ntitwumva igifaransa.
Ndamubonye.
Nagira ngo urabizi.
Ni umufaransa.
Mwebwe muri abana.
Mukunda gusoma ubwoko bw'ibitabo ibihe?
Mvyuka isaha imwe zo mugitondo.
Kubera iki utumviriza?
Usa n'umupolisi!
Twashitse.
Si vyiza.
Mvuga ico niyumvira.
Kubera iki tudataha imuhira?
Ndashobora kubibona kandi?
Wibaza ko ico ariki?
Amakuru maki?
Bambonye.
Umuryango wawe uri hehe?
Uri umuntu mwiza.
Arazi ko umukunda?
Ndi mu gikoni.
Urazi ico yavuze?
Ntibashaka ko tubimenya.
Ndazi ko ubifise.
Ibi bitabo ni rwacu.
Urakunda kwiga?
Sindakunda kwiga.
Sinshaka guteka.
Igitwazi kirasimba.
Uyu muhungu ni mwenebabo.
Nta numwe ahari!
Tuzongera ku wambere.
Ni vyiza uko biri.
Turi ngaha kubera wewe.
Araguzi?
Urabinyemereye?
Mvyuka isaha imwe zo mugitondo.
Uvyuka ryari?
Urazi ico ubwirizwa kugira?
Sinkora uko.
Reka nje kugura umukate.
Biranyuze.
Uri iwawe?
Ivyo ni vy'umugenzi wanje.
Kuki utaja imuhira?
Nariye amagi ejo.
Magdalena na Ania ni abagenzi pfampfe.
Ndazi ico wiyumvira.
Uranezerewe?
Sinshobora kuvuga ko bimbabaje.
Ni rwacu.
Ndazi neza ko hari aho maze kumubona.
Ntiwibagire gutwara ikete.
Nirukiye kwa mama.
Nanje.
Arakunda gusoma ibitabo.
Sinzi iryo jambo.
Umuduga wapfuye.
Mbwirizwa kwiyumvira.
Ndazi ingene bigirwa.
Raba hariya!
Ndazi ibikenewe gukorwa.
Turabizi.
Araguzi?
Ntaco ndabiziko.
Ishure riraheze.
Ntaco.
Ndazi ingene bikorwa.
Twama dukina ku munsi w'Imana.
Ntanumwe antega ugutwi.
Simbikeneye.
Murashaka kubitwara?
Yama ata mobile yiwe.
Waciye ku kimenyetso gitukura.
Ndashaka kubana na wewe.
Ntimubitegera?
Ushaka ko ndagusigira irangi ku nzara zawe?
Ndafise amahera.
Si ikintu co kwishima.
Uraba iki?
Tega amatwi!
Ndamubaza.
Urazi ico bashaka?
Ntanumwe antegura.
Iciyumviro nyabaki!
Ikiganza gifise intoki zitanu: urukumu, inkombarukoko, msumba zose, igihugunibenga, agahererezi.
Uko ni vyiza gusumba?
Ndazi ko utega ugutwi.
Amahera yarampereyeko.
Muri beza cane gwose.
Bigurwa angahe?
Ndakunda imishatsi migufi.
Ndazi igituma uri ngaha.
Udushakako iki?
Kubera iki ujaho?
Ja mu buriri!
Ndashobora kuronka iki gitabo?
Ndarurumba.
Turumva.
Sinteka.
Ntibiri nkuko uvyiyumvira.
Ndiko ndasoma igitabo.
Umuduga uraje.
Asa na nyina wiwe.
Reka tugure ivyo.
Kubera iki wiga igifaransa?
Sintegera igifaransa.
Kubera iki wiga igifaransa?
Ihinguriro rikora ibihumbi n'ibihumbi vy'amacupa kira kwezi.
Bitebe bitebuke vyose birahera.
Ico gisa n'ivu naco nyene ni rwanje.
Umubanyi wanje ni umubaji.
Wabonye amaso yabo?
Biranshimishije.
Nshaka ko mubibona.
Ntusa neza.
Ndakunda ibiharuro.
Iki gitabo ntigifise akamo.
Natanguye gukora muri ino societé kuva umwaka uheze.
Kera hari urusengero ngaha.
Ndibaza ku mfise umwanya w'ikindi gikombe c'ikawa.
Inzoka yamize igikere.
Vyibagire ivyo.
Kubera iki ubaza?
Iryo jambo ntaryonzi.
Iyi nzu ni iyande?
Kubera iki utari aha?
Turi imuhira.
Turahura nabo rimwe rimwe.
„Namaki?“ – „Nameza, murakoze!“
Ngiyo ifagitiri.
Ndazi nyoko.
Birera?
Ndashobora kwinjira?
Ejo naryamye umunsi wose, kuko wari umunsi w'Imana.
Nabonye hariya mushikanje.
Urazi ko mbwirizwa kugenda.
Turajana?
Twojana.
Urabikunda?
Uri umugore nkunda.
Iri kosa ni iryande?
Noshimishwa no kumenya izina ryawe.
Novuga gutyo.
Uri umuhinga.
Araza nawe?
Kubera iki mumbaza?
Nabarira vyose abavyeyi banje.
Urafise uwo muvukana?
Iri terefone ni iryande?
Ivyirabura ni vyanje.
Kubera iki udashaka kugenda?
Ngirango ntubikunda.
Ndi umunyeshuri mushaha muri kaminuza.
Nanje ndavyiyumvira uko.
Nitwa Jack.
Icumba cawe gifise amadirisha abiri?
Ndazi ingene bikoreshwa.
Ni umufaransa.
"Aya marori ni ayande?" – "Ni aya Data."
Ntanumwe azi izina ryiwe.
Ahari ugushaka haba inzira.
Iyo menya sinari kuza.
Bitebe bitebuke bizoshika.
Kera hari isengero ngaha.
Igihe ntikigize gukanya gusa, kiranajovye.
Ukora iki?
Ashaka gushika kuki?
Sinzi izina ryiwe.
Ntiwibagire gutwara ikete.
Ndazi uyo mwigeme.
Uranhunga ko ndabivuze.
Kubera iki tutabiraba?
Kubera iki jewe?
Ntiwibagire gutwara ibaruwa.
Sinshonje.
Nazanwe no kuramukanya.
Sinzi iyo ngana.
Uyu mukobwa yiyambika nk'umuhungu.
Reka kundaba!
Ur'uwacu.
Urambabarira ko ndabivuze.
Kubera iki muri imuhira?
Ntusubire kumbaza.
Uyu ni nyoko?
Ndi mu kiruhuko.
Uwu muduga ni mushasha?
Data wanje ntari imuhira.
Kubera iki wibaza ivyo?
Urabishaka canke?
Uhaguruka ryari?
Ndazi izina ryiwe gusa.
Ibintu vyawe birihe?
Urashobora gutora irangi iryariryo ryose rigushimisha.
Sinshaka kuba umutunzi.
Ndameneka umutwe.
Hari ijana y'abantu mu ngoro.
Nshaka gutaha.
Turiko dutakaza umwanya uzimvye.
Iyi kanzu nijewe nayikoreye.
Tuzobabwira iki?
Ndameneka umutwe.
Ni rwacu.
Urazi izina ryiwe?
Kera waranywa itabi, sivyo?
Ijoro ryiza!
Kubera iki utari kw ishure?
Ntabana nawe.
Sindashaka kurwara.
Turi ngaha kubwawe.
Dushaka ko ubitwara.
Ngaha nta numwe afise umuduga.
Ni umuntu mwiza.
Nimusohoke mu muduga.
Ndamuzi.
Urazi aho arihe?
Iki gitabo ntigifise akamo.
Tom arihe?
Urabona iyi nzu? Ni rwanje.
Twojana.
Namubonye yiruka.
Ni murabe neza iri foto.
Ndazi ko ubizi.
Namugomwe.
Uri umugenzi wanje.
Simfise mushikanje.
Ndashimishwa nivyo mbona.
Ku minsi y'Imana simba ndi imuhira.
Kera hari urusengero ngaha.
Turategera.
Urukundo rurahuma.
Ni bitoya birenze.
Urazi nyene uyu muduga?
Ndi umushinwakazi.
Urashaka ko nza?
Idirisha rirugaye.
Kubera iki utari mw'isomero?
Ndaguhwatira umucungwa.
Uragenda canke ntugenda?
Ibisi irahagaze ariko nta muntu yururutse.
Tuja hehe?
Naje kukurondera.
Rabira mw'idirisha.
Ndakunda kuba ngaha.
Kubera iki ataho tutajana?
Amahera yanje ari hehe?
Noshimishwa no kumubona.
Ndibaza ko ntegeye.
Ntanzi.
Nyene ibi bitabo ni mushikanje.
Urazi ico ubwirizwa gukora?
Urashobora gutera ururirimbo.
Ndakunda umuduga wanyu.
Ntanumwe ari i muhira.
Twoshobora kujana.
Bariko baturaba?
Ndi umwigisha.
Nyoko niho ari?
Simfise musazanje.
Ndakunda kwiga igifaransa.
Kera yari umwigisha.
Ndi umwotsi w'imikate.
Singushimye.
Uri mushasha?
Narasomye iki gitabo.
Uyu mwigeme yiyambika nk'umuhungu.
Muraturondera?
Kubera iki tugira ivyo?
Ndanezerewe ko uhari.
Ntidufise amahera.
Kubera iki utariyo?
Ubu buriri ni ubwande?
Ndabasavye, mumpe ifagitiri.
Uraza? Ego canke oya?
Yarabimpaye.
Turamuzi.
Nibiki bibaye ngaha?
Sinshaka kukubona.
Sindashaka kuba ngaha.
Sintegera ingene.
Nta mahera dufise.
Ururuka mu muduga.
Biragenda?
Wahuye nawe?
We si umwana.
Tujanayo twese hamwe.
Urakoze cane.
Murakoze!
Ni beza cane gwose.
Indahiro ni ideni.
Kubera iki batankunda?
Sindakwumva.
Ushaka kugenda ryari?
Ipantalo yawe iranduye.
Reka tugure ivyo.
Uramukunda?
Ngenda n'umuduga.
Urafise mwenewawe?
Ni bitoya birenze?
Naje kukurondera.
Kubera iki mutagerageza iyi goti? Ijanye neza n'ipantalo yanyu.
Asa na mwenewanyu.
Kubera iki mbwirizwa kubikora?
Mubwirizwa kugenda i muhira.
Mugenda hehe?
Sinibaza ko aza.
Ubironderera ngaha?
Urazi aho arihe?
Ndakubonye.
Urabona iyi nzu? Ni inzu yanje.
Sindabitegera.
Turajana.
Narakunze uyu muduga.
Birahimbaye gusubira kukubona.
Tubwirizwa gushira uburinganire hagati y'bisohoka n'ivyinjira.
Ndamanikwa impuzu.
Urafise umuduga?
Uyu munsi ni kuwagatatu.
Sinkunda aba bantu.
Urashaka kumenya ingene?
Ntibashaka kubikoresha.
Bitebe bitebuke vyose birahera.
Iki giti kirashaje.
Ndakunda ico nkora.
Mukora iki?
Uyu ni data wanje.
Bambonye.
Amapome vyose aguye hasi azoribwa n'ingurube.
Dusangiye indoto imwe.
Aramukunda.
Yavyaye umwana wa mbere afise imyaka mirongo ibiri.
Urashaka kumenya igituma?
Niga igifaransa mw'ishure.
Reka nje kugura umukate.
Ntaco ndabiziko.
Aya ni amadolari atanu.
Ushaka kuja hehe?
Kubera iki ndi ngaha?
Mpa icarico cose co kugira.
Turihe?
Ivyo ni ibiki?
Ico nico uriko urondera?
Urazi aho nzoba ndi.
Ntegerezwa kuja imuhira.
Oya, urakoze.
Ntubaze.
Ndakeneye umwanya wo kwiyumvira.
Turanezerewe.
Narinzi ko bigushimisha.
Yazunguje umutwe.
Sinzi aba bantu.
Ubwirizwa guheba inzoga.
Namerewe nabi.
Aba ngaha?
Urondera iki?
Ndi hehe?
Ibi biro ni ivyande?
Ntibimpa agateka.
Ni isaha icenda ibuze iminuta icumi n'itanu.
Ntusabe amahera.
Ihinguriro rizotangura gukora mu mwaka uza.
Urazi ico yavuze?
Ashaka gushika kuki?
Muzovyigaya cane.
Ubona iki?
Si umuduga wanje.
Ndategera ico uvuga.
Ni ku wagatandatu.
Ni naco gituma ndagukunda.
Ni umunsi!
Ndi imuhira.
Ntushavure!
Simfise amahera.
Kubera iki tubikora?
Nico nshaka kumenya.
Nico ndiko ndondera.
Nturi musazanje.
Muzinaniye hehe?
Sinzi ico nokora.
Ngirango ntanezerewe.
Ntiwibagire gutwara ibaruwa.
Sinzorabayo.
Nzero, Ruruhuma, Ntwarante, Ndamukiza, Rusama, Ruheshi, Mukakaro, Myandagaro, Nyakanga, Gitugutu, Munyonyo na Kigarama ni amezi icumi n'abiri y'umwaka.
Umuduga wacu urihe?
Umuryango wiwe urihe?
Mpore cane!
Kubera iki mbwirizwa kugenda.
Akira igitabo usome.
Ndabubaha.
Ntibimeze uko uvyiyumvira.
Urya mugambi wari uwande?
Hagati y'igisigara hadutse umuriro.
Uri umuhinga.
Ndazi ico nzokora.
Narinzi ko bikunezereza.
Sindashonje.
Reka gutegeka ngaha!
Umuhungu arasimba.
Namukunze.
Urabishobora.
Data ari imuhira.
Ikosa ni iryande?
Asa na musazawe.
Waciye ku kimenyetso gitukura.
Ndibaza ko ntegeye.
Urashaka ikintu co kunywa?
Afise ibitabo amajana n'amajana.
Nshobore gusubira kubibona?
Ndafise ibikorwa vy'ishure.
Urazi ico ubaza?
Bisa nkaho ata muntu ari mu nzu.
Ndi umutetsi.
Abo ni abavukanyi banje.
Ntibikenewe ko mwinyegeza.
Bandanya kurondera!
Ntiwoshobora kubisubira ico wavuze?
Ntanumwe amuzi neza kiretse abavyeyi biwe.
Sinumva igifaransa.
Mubaze izina ryiwe.
Ni vyiza, sivyo?
Nje gusezera.
Ndazi uyo mwigeme.
Kubera iki wibaza uko?
Uru ni urukundo?
Ihinguriro rikora ibihumbi n'ibihumbi vy'amacupa kira kwezi.
Ndarindirira hanze.
Hari imashini yo kumesura mu nzu?
Nimwambure ibirato vyanyu.
Ntanumwe antega ugutwi.
Narinzi ko wojayo.
Nasivye kw'ishuri.
Urazi ingene bisa?
Kubera iki mbwirizwa kugenda.
Ugara amadirisha yose.
Ni neza, siko?
Nataye impfunguzo zanje.
Ivyirabura ni vyanje.
Abashakashatsi bubutse ku magufa y'umuntu mw'isenga.
Ukuboko kwanje kw'ibubamfu kwagize ibinyanya.
Ikiganza gifise intoki zitanu: urukumu, inkombarukoko, msumba zose, igihugunibenga, agahererezi.
Urazi aho aba?
Ubwirizwa kuvyuka.
Uba he?
Mushikawe amerewe gute?
Ndazi uyo mukobwa.
Urandondera?
Aramutegera.
Ijipo ntiyari inkwiye nico gituma nabwirijwe guyihindura.
Iki ni igifaransa?
Uyu ni mama wawe?
Ntutegerejwe kuza.
Mfise mukuruwanje.
Sindamuzi.
Soma!
Ngiye guzana umuduga wanje.
Si ikintu co kwirata.
Urafise ikintu co gusoma?
Mugenda hehe?
Nta mahera yari agifise.
Ndazi aho uba.
Ntiyasomaye iki gitabo.
Ndazi so wawe.
Sinkugomwe.
Nikomerekeje n'igisu ku rutoki.
Uranhunga ko ndabivuze.
Bazomenya uko bagira.
Nje kugutwara i muhira.
Ntubwirizwa kuza.
Ntukomeye muri vyo.
Ntavuga icongereza.
Nari mborewe cane.
Sinshaka gutunga.
Urashaka kubibona?
Urafise musazawe?
Afise imyaka ingana iki?
Ubwirizwa kureka kunywa.
Ni twebwe murondera?
Ndafise umuduga.
Tuzobonana ejo!
Si umuduga wanje.
Muri abanyeshuri?
Nibajije ko ndakuzi.
Igiciro kiraduga.
Tuzotunga.
Ntimukeneye gunkengurukira.
Ico gisa n'ivu naco nyene kiranyegukira.
Bobo ni abana.
Urukundo ni iki?
Ndibaza ko azoza.
Sindi umunyeshuri.
Iki gitabo ni gishasha.
Ndazi ibikenewe kurangurwa.
Ico nico uriko urondera?
Urashaka kumenya igituma?
Ndakunda uyu muduga.
Ikibazo ciza.
Ntitubwirizwe kubivugana ubu nyene.
Ni bitoya birenze urugero.
Ntibimara umwanya mu nini.
Urashaka kwinjira?
Kubera iki utari mw'isomero?
Ndamuzi.
Urabibonye?
Sinzi izina ryawe.
Mbwirizwa kukubona.
Ntavuga icongereza gusa, avuga kandi n'ikidagi.
Mbirizwa kwiga gifaransa.
Nahaye umuhungu igitabo.
Nshaka ko utaha.
Narinzi ko biguhimbara.
Urazi ko ndagukunda.
Ivyo ni ibiki?
Narinzi ko wojayo.
Nshaka kwiga igifaransa.
Urazi aho aba?
Kubera iki wijiriwe?
Nzogenda ku munsi w'Imana.
Sintegera iri jambo.
Mpore ko ndabivuze.
Urigisha?
Uru ruhome rurakanye.
Uva hehe?
Ni umuhungu muremure.
Urakoze!
Narinzi ko biguhimbara.
O yawe isa na A yawe.
Birakwiye vyose ivy'urugendo?
Nazanwe no kwiga.
Ugenda ryari?
Ibirato birihe?
Ndafise ikibazo.
Hariko haba iki hariya epfo?
Nzogenda n'umuduga.
Turanezerewe cane.
Ntumwumvirize.
Ndafise bashikanje.
Ntusubire!
Biranshimishije.
Ndazi ico nkora.
Kubera iki udataha?
Sinzi neza igifaransa.
Urashaka ikintu co kunywa?
Ni naco gituma ndagukunda.
Ushaka kugenda ryari?
Ntanumwe arazi aho turi.
Ico gisa n'ivu naco nyene kiranyegukira.
Ni birebire birenze?
Ntuzi icarico?
Ngirango ntibigushimisha.
Iyo udategereye, baza.
Ku minsi y'Imana simba ndi imuhira.
Ni mushiki wawe?
Ntibaza uyu munsi.
Ndiga igifaransa imuhira.
Mu mwaka uheze navyaye imfura yanje.
Ndanezerewe ko ariho uri.
Nyogokuru avuga buhoro buhoro.
Uyu mwaka ntegekanya gusoma ibitabo vyinshi bishoboka.
Ukora iki, data?
Mubwirizwa kugenda i muhira.
Ndi mu karuhuko.
Iyi kanzu nijewe nayigiriye.
Ndakurondera.
Kubera iki udashaka kugenda?
Uranzi.
Simbizi.
Baranezerewe.
Ni igiki gituma abantu bagira uko ivyo?
Uyu muduga ni rwacu.
Turabitegera.
Nimumutware mu cumba co kubaga.
Ni bitoya birenze?
Urambabarira ko ndabivuze.
Wiyumvira iki?
Abo nabo mu bujapani?
Ndategera.
Ndababonye.
Nturi mwenewacu.
Nturabe hasi.
Urugendo rwacu ruva ku gihe.
Afise imyaka ingahe?
Ukora iki ngaha?
Urafise aya mahera?
Ndashaka kukubona pe.
Ivyo birashavuza!
Abo ni abajapani?
Nyoko ari imuhira?
Ninde akuri inyuma?
Iki cayi ni icande?
Sindashaka kuba ngaha.
Uba ngaha?
Urazi ico yavuze?
Kubera iki utaciga igifaransa?
Reka ndabe.
Oza ibirenge!
Nzoza kugutora.
Ndazi neza ko bari mu nzira.
Data ari imuhira.
Ngurisha impuzu ku murongo.
Niyumviye ko vyogutwenza.
Kubera iki udashaka kugenda?
Nta ngorane.
Nzoba ndi mu muduga wanje.
Ndi mu muduga.
Ni angahe?
Twamanutse twiruka agasozi.
Ntushaka kumenya ivyo!
Baba mu nzu duhangana.
Yataye urupfunguzo rw'umuduga wiwe.
Ijipo iranduta.
Ntuzi musazanje.
Narabiravye muri yu tubi.
Ndazi ko ubifise.
Ur'uwiwacu.
Ijwi ryanje rirasaraye kubera inkorora.
Ndashonje.
Umviriza nyoko!
Baratuzi.
Sinshaka kubisoma.
Ntiwibagire gutwara ikete.
Urakoza ko wajanye natwe.
Ntunzi.
Sinkugomwe.
Ntavyo bazi.
Umuduga wa data ni mushasha.
Sinzi aba bantu.
Ntimwugurure idirisha.
Ndi mu karuhuko.
Sindi ikijuju.
Duteka umuceri uku.
Akira ico ushaka.
Bitebe bitebuke bizoba.
Ndakuzi.
Sinzi aho bari.
Ndakurondera.
Muri Abadagi, sivyo?
Narinzi ko vyogushimisha.
Ndagukunda.
Ndazi ko wabivuze.
Nturyame idirisha ryuguruye.
Ndazi icarico urukundo.
Bavuga ko atunze cane.
Ntumuhagarike.
Turazi igituma waje ngaha.
Ndi umunyeshuri muri kaminuza.
Urafise ico gusoma?
Urambabarira ko ndabivuze.
Igituro ca bisi kiri iminota itanu uvuye ngaha.
Narasomye iki gitabo.
Ubwirizwa guheba inzoga.
Haraza gushuha.
Ndondera inzu mu gisagara, ata cizero.
Asa na Se wiwe.
Akinirahe?
Ndafise umuduga.
Yamugomwe.
Yamukunze.
Nawe turagukumbuye.
Nagasaga!
Nzoza kugutora.
Ni bitoya birenze?
Kora ibikorwa vyawe vy'ishure.
Urashaka ko nza?
Wibaza ko ivyo ari ibiki?
Umuduga wanje urihe?
Sinzi ingene.
Sinzi ico nshaka.
Wabonye amaso yabo?
Reka gutanga amategeko ngaha!
Iyi mbugita irapfushe.
Injira.
Ntubwirizwa kwandika ikete rirerire.
Ndakwiyumvira.
Ndazi umuryango wiwe.
Ntundabe gutyo.
Wanyoye ibikombe vy'ikawa bingahe?
Nagira ngo ni ikigorwa cawe.
Kubera iki utabikora?
Urazi icarico urukundo?
Uri imuhira?
Sinshaka kuba umutunzi.
Bitwarire nyoko.
Ndakunda umuryango wanje.
Ukora iki, data?
Abana bagiye kw ishure?
Baba iwawe?
Ndabubaha.
Ndazi ibikenewe kurangurwa.
Ndazi neza ko bari mu nzira.
Nuko rero nabigize.
Iri saho ni irya nde?
Narinzi ko bigushimisha.
Ntiyasomaye iki gitabo.
Kubera iki mbikora?
Nazanwe no kuramukanya.
Turaja ku burengero.
So wawe amerewe gute?
Ndazi igituma uri ngaha.
Narinzi ko bikunezereza.
Iyi nyabu ni yanje.
Urantegera.
Nshaka kubibona.
Ntibikenewe ko mwihisha.
Nimukure ibirato vyanyu.
Urazi aho nzoba ndi.
Narumvise ko warongoye.
Musazawe arihe?
Kubera iki abantu bavuga ivyo?
Ntanumwe amuzi neza kiretse abavyeyi biwe.
Ninde asoma?
Ndazi ico baravuze.
Amadirisha araguruye.
Urazi ko tugukunda.
Bikuvako.
Urukundo ni iki?
Kubera iki urwanko rwinshi?
Birakwiye vyose ivyerekeye vy'urugendo?
Ndakunda aho mba.
Nabo baraza?
Dushaka ko ubitwara.
Ndonka ico nshaka.
Aba ngaha?
Ushobora kuvga icongereza.
Sinzi guteka.
Ndazi aho turi.
Asa na nyina.
Sindi umunyeshuri muri kaminuza.
Mama wanje arihe?
Umunsi mwiza.
Ntasa n'uwunezerewe.
Mama wanje arankunda.
Kubera iki abantu batankunda?
Sindabikeneye.
Urazi icarico?
Nabigiriye wewe.
Iyi hinguriro rikora ivyuma vy'imiduga.
Ikanzu rikozwe mw'iharire.
Haraho uzogenda muri iri ci?
Uyu munsi ni umunsi w'Imana.
Ndabikorera wewe.
Urabizi?
Ndakunda gusoma.
Nguyo!
Kubera iki ubibaza?
Ntusubire kumbaza.
Ndafise ikibazo.
Ushaka kuba hehe?
Urazi nyene uyu muduga?
Ndabibonye.
Yitwa ngwiki kandi?
Kubera iki tutaja imuhira?
Ndibaza ko navyicayeko.
Urashobora gutora irangi iryariryo ryose ushimye.
Nshaka ko ubisoma.
Ndoza amadirisha.
Sinywa.
Ntanumwe yabonye ikintu.
Mpa igitabo.
Ndashaka nanje kugenda.
Sintegera gute.
Nta muduga mfise.
Raba iyi foto.
Nta muduga dufise.
Kubera iki bataza?
Ndazi neza ko namubonye ahantu ikindi gihe.
Wasomye iki gitabo?
Uzi izina ryanje hehe?
Ni naco gituma ndagukunda.
Uramuzi.
Nshaka kukubona.
Ndi mu kiruhuko.
Urashobora kurara iwacu.
Ntidushaka kubimenya.
Ndazi ko wabivuze.
Ndagenda kuryama.
Ndazi aba bagore.
Umuryango wiwe urihe?
Nazanwe no kwiga.
Ndazi ko unkunda.
Biragushimishije?
Ntiyasomaye iki gitabo.
Umuryango wanje ni muto.
Ndazi ico nogira.
Simfise mwenewacu.
Asa na nyina.
Umuntu ni co gikoko co nyene gishobora kuvuga.
Ku wambere musée yama yugaye.
Sinzi ico novyiyumvirako.
Wiga ryari?
Ndi umutetsi.
Tuzongera ku wambere.
Kora ibikorwa vyawe vy'ishure.
Uramuzi?
Nahaye umuhungu igitabo.
Ndanezerewe ko ariho uri.
Ntariye nopfa.
Ndashika isaha zine.
Ntimusubire kubigira.
Ni umugambi mwiza.
Ntubwirizwa kuza.
Ntegerezwa kugenda ubu.
Ni umuntu mwiza.
Namugwiriye.
Data ntari i muhira.
Sindi umunyeshuri.
Nimusohoke mu muduga.
Siko biri nkuko uvyiyumvira.
Ukuboko kwanje kw'ibubamfu kwagize ibinyanya.
Nari naborewe cane.
Mbwirizwa kuruhuka.
Kigurwa angahe?
Isaha yawe irihe?
Ntanumwe antegura.
Intumbero y'urugendo rwanyu ni iyihe?
Ntubwirizwa kuza.
Nabigiriye wewe.
Birakunyuze?
Turahura nabo rimwe rimwe.
Nahaye umuhungu igitabo.
Twiga ubuhinga bw'umuziki.
Kubera iki babikora?
Ndanezerewe ko uhari.
Sinshaka amahera yawe.
Woba ufise umunota?
Ndiga igifaransa imuhira.
Ibitoke bisa n'umuhondo.
Tom ni umubaji.
Sinashoboye kutarira.
Sinzi ico ushaka.
Iyo azakugira umwanya yari kugenda.
Waciye ku kimenyetso c'itara ritukura.
Ndazi ico bagira.
Ubugeni buzoba ku wagatandatu.
Haguye amama make y'imvura.
Ni mwenewacu.
Mbwira umugambi wawe.
Iri jambo ryamuka mu kigereki.
Urivuza?
Ntaco ndabiziko.
Ushaka kuzobibona.
Akira amahera.
Sinzi.
Ndakeneye abakozi b'abitanzi batatu.
Umwigisha wanyu ni nde?
Ni naco gituma ndagukunda.
Bakora iki ngaha?
Ufise imyaka ingana iki?
Ndabibonye nanje.
Nshaka kwiga igifaransa.
Umuryango umerewe gute?
Ntushaka kubimenya!
Vyiza kuruta vyobaye iyo utajaho.
Sibiraba amahera.
Mba ngaha.
Twoshobora kujana.
Usa naho unezerewe cane.
Ndi ngaha kubera wewe gusa.
Ntumpate kubikora.
Nivyo urondera?
Sinumva igifaransa.
Nari mbizi.
Nguyo araje!
Sinshaka amahera yawe.
Bavuga ko atunze cane.
Mubwirizwa gutaha.
Nta mazi akiri mw'icupa.
Indimi zifise amajambo agoye.
Kubera iki bavuga ivyo?
Bashaka ko tubigira.
Ndazi neza ko hari aho maze kumubona.
Ndazi Tom?
Urashobora gukoresha uwu muduga.
Narinzi ko wojayo.
Narinzi ko biguhimbara.
Ntadukunda.
Namerewe nabi.
Mpore ko ndabivuze.
Ntugende n'iminwe misa.
Sinshaka kubisoma.
Isaha yanje irihe?
Ni umunyamerika?
Ndagukunda.
Nandika kuri twebwe.
So arihe?
Turazi ico ukora.
Yamukunze.
Urazi aho biri?
Ngico igitabo cawe.
Reka gutanga amategeko ngaha!
Muri kino gisomwa ca umurongo munsi y'amavuga yose ya kazoza muri.
Ntanumwe yumviriza.
Sinkunda kwiruka.
Urabitegera?
Nshaka ko uja imuhira.
Ni igiki ntategera?
Ntiyasomaye iki gitabo.
Abana na we.
Urazi aho bari?
Izi ntambwe zirashobora kubuza ko ingwara isasagazwa.
Ntanumwe yakubajije.
Ico gisa n'ivu naco nyene kiranyegukira.
Kubera iki bataza?
Mara umwanya munini niga igitari.
Iyi hinguriro rikora ivyuma vy'imiduga.
Urabinyemereye?
Ndazi ico nokora.
Akora mw'ihinguriro.
Sinshonje.
Urakeneye umugambi.
Ubuzima niko bumeze.
Uhaguruka ryari?
Ikiganza gifise intoki zitanu: urukumu, inkombarukoko, msumba zose, igihugunibenga, agahererezi.
Kubera wewe ndi mu rudubi.
Kubera iki mwabeshe mu vyerekeye imyaka yanyu?
Asa na nyina.
Arumva igifaransa.
Ntiwitinye.
Tuja hehe?
Uza imuhira ryari?
Ndaribwa mu nda.
Ni murabe neza iri foto.
Ntanumwe azi izina ryiwe.
Ndanezerewe ko ariho uri.
Amatapi yo mukahise arafise agaciro kanini.
Sindi umubaji mwiza cane.
Abo nabo mu bujapani?
"Aya marori ni ayande?" – "Nyeneyo ni Data."
Ndabibonye.
Ndi umwigisha.
Sinkubona.
Nshaka kwiga igifaransa.
Uramukunda?
Musazanje siho ari.
Urashaka umuduga?
Wigahe?
Ndazi aho ari.
Ndabibonye nanje.
Simfise mwenewacu.
Umwigisha wanyu ni nde?
Uraza canke?
Subira gusoma.
Ndakunda ibiharuro.
Ipantaro ntinkwira. Ndashobora kuyiguza?
Uribuka uru rukino?
Sindi intore.
Uriga igifaransa?
Iki gitabo ni ciza cane.
Mukora iki?
Mariya arihe?
Urashobora kuruhuka.
Ndamubonye.
Ndazi aho turi.
Ntaco ndabiziko.
Iyo aguma imuhira uyo munsi, ntiyogize isanganya.
Ngibi ibisu, amakanya n'ibiyiko.
Kera waranywa itabi, sivyo?
Iyi nyabu ni yanje.
Sinzi izina ryiwe.
Murategera igifaransa?
Numa!
Turakuzi.
Ntaco babiziko.
Nzoba ndi mu muduga wanje.
Umuntu wese arashobora kubisoma.
Nyoko arihe?
Sinzi aho aba.
Ntiwibagire gutwara ibaruwa.
Ururuka mu muduga.
Ndazi uvyirumvira.
Si igifaransi.
Iki gitabo kiri ku meza ni icande?
Singushimye.
Uzi izina ryanje hehe?
Mushikanje asa na Mama.
Uranhunga ko ndabivuze.
Birampimbaza.
Iki gitabo ni ciza cane.
Murakoze cane.
Uba he?
Ipantalo yawe iranduye.
Twasezeye.
Ndi mushasha aha.
Uri umugenzi wanje.
Akora mw'ihinguriro.
Wiga kw ishure irihe?
Ndashonje.
Ndazi ko ubifise.
Ubwirizwa kuvyuka.
Ndazi aba bantu.
Nturi mwenewacu.
Ndashobora kwugururura irido?
Niki?
Tugende ku gituro c'igari ya moshi tugure amatike.
Nshaka ko umubona.
Nico gituma cakuzanye ngaha?
Birakunyuze?
Ndanezerewe gusubira kukubona.
Ni naco gituma ndagukunda.
Ndategera ico ushaka kuvuga.
Kira gitondo mva imuhira imbere y'isaha zibiri.
Muri abana.
Ndumva ico uvuga.
Usa gute?
Nataye impfunguzo zanje.
Bakora iki ngaha?
Ntibafise amahera.
Ntwumviriza.
Ndamukunda.
Raba neza ingene ndabikora!
Ntuzi icarico?
Nosubira kubikora.
Bitwarire nyoko.
Nikomerekeje n'imbugita ku rutoki.
Urazi izina ryiwe?
Musazanje ntari i muhira.
Niga igifaransa mw'ishure.
Urafise umuduga?
Narinzi ko bikunezereza.
Iki cayi ni icande?
Ntimubitegeye?
Mpembwa neza.
Sinshaka aya mahera.
Mvuga indimi zitatu.
Ni abanyamerika?
Mwahuye?
Nshaka ko ubimenya.
Simfise umuduga.
Rimwe rimwe tujana muri cenema.
Abo ni abavukanyi banje.
Kubera iki udatomora ico ufise ku muzirikanyi?
Urazi ko mbwirizwa kugenda.
Mfise benewacu.
Urazi ico bavuze?
Ndazi neza ko namubonye ahantu ikindi gihe.
Nanje ndururutse.
Nico cakuzanye ngaha?
Ufise imyaka ingahe?
Ninde agukurikirina?
Uradundega?
Iyo menya sinari kuza.
Turagukunda.
Ndakubonye.
Naganiriye vyose abavyeyi banje.
Hari umuntu ahagaze inyuma y'uruhome.
Harashushe birenze.
Naje kukurondera.
Birampimbaza.
Ipantalo yanje yajovye.
Turi hehe?
Ushobora gukoresha umuduga wanje.
Harashushe cane ngaha.
Urataha?
Nguyo!
Sindamubona.
Aramukunda.
Kubera iki utari kumwe na jewe?
Nico nshaka kumenya.
So wawe arihe?
Ntibintera iteka.
Yakarihije igisu.
Turavukana.
Sinzi aho muba.
Sinshaka kubimenya.
Bikozwe muki?
Uyu muduga usa na mushasha.
Ijipo irandenze.
Ndazi kubikora.
Iri darapo ni nziza cane.
Ushaka kubimenya iki?
Ni naco gituma ndagukunda.
Sindashonje.
Kuki utinjira?
Amasobe yanje ntarongorotse.
Reka gutegeka ngaha!
Ndazi uyo mukobwa.
Ni neza cane.
Narinzi ko uri ngaha.
Nabonye so wawe.
Ni umunyeshuri mwiza.
Sindi ikijuju.
Ubishatse, ushobora gukoresha umuduga wanje.
Umuduga wawe urihe?
Nshaka kuganira nawe.
Reka ndakugurire gishasha.
Munywa iki?
Nimukure ibirato vyanyu.
Woba ufise akanya ko kumfasha ikintu?
Ejo hari kuwagatanu.
Ndazi ico mvuga.
Ndanezerewe ko ariho uri.
Nyoko ari imuhira?
Wari umugambi wande?
Iyi koti ni iyande?
Reka ndakugurire gishasha.
Ukora iki ngaha?
Nturabe munsi.
Kubera iki wijiriwe?
Arakunda gusoma ibitabo.
Bashaka ko tubikora.
Ntitubizi.
Turamuzi.
Ndi umunyeshuri mushaha muri kaminuza.
Kubera wewe ndi mu ngorane.
Nzokora ico unsaba.
Uri umuvyeyi mwiza.
Mva muri Bresil.
Mubwirizwa gutaha.
Nzero ni ukwezi kwambere mu mwaka.
Urugendo rwacu ruvana n'igihe.
Nta gishasha.
Turakuzi.
Ntanumwe yavuze ijambo.
Aramwumva.
Umuduga wanyu uranshimisha.
Uribaza ko nezerewe?
Ntanumwe arazi aho turi.
Ndi umushinwakazi.
Murafise umuceri?
Amahera narayakiriye.
Ndashaka kuruhuka gato.
Neza, nawe?
Bishire nyoko.
Ndakujana.
Sinzi ico novuga...
Nshaka ko mubibona.
Ntitumuzi.
Mpamagara hagati y'isaha imwe n'isaha zibiri.
Urihe?
Tuzosubira kubonana!
Kubera iki babikora?
Ndazi ibikenewe gukorwa.
Uri umunyeshuri mushasha?
