Beim Geld ischs wia mid em Meerwasser. Je meh ma drvo dronka hôd, je meh wird mä durschdigr.
I benn nebrå fremdå Frau uffgwachd.
Die große Wäld stôhd bletzlich still, weil å kloiner Virus dees so will.
I glaub, dass ihr älle mi kennåd.
Marie hôd å Dochdr.
Geduld isch ebbes für d Ofenger! I dreh liebr glei am Rad.
I be glügglich, weil mir oifach egal isch, wa d'Leit ibr mi schwätzad!“
Tom hôd gsait, er will ned mid dir schwätzå.
Du muschd net sengä.
I han geschdern dai Fraindin hier gsähå.
Mir älle sähåd dia gleiche Sonnå.
Dô drauf bene sähr schdolz.
Eschdr hôd a Nommr an ihrem Arm.
Tom isch etzad Arzt.
Tom isch em Wenter uff d'Weld kommä.
I koa net vrzeiä, was du dô hôsch.
Dees bassierd bloß oimôl em Läbä.
Wenn d'Weinachtsgloggå leidet, wird sogar dr Deifl mild.
Der Ideåreichdomm isch am greschda, wenn oinr auf domme Gedangå kommd.
I woiß, dass Tom dees môg.
Maria hôd sich ombrôchd.
I han å Auto, aber i nutz 's ned oft.
I hoiß David.
Sami hôt sai Briefdasch uffgmachd.
Där Dieb isch fortgloffä, wiå n'r Bolizei gsäå hôd.
Maria hôd å Keed.
I glaub eane nemme.
Wieviel Kaffee isch nô ibrig?
I muass langsammr sĉwätzä.
Wenn älle Menschå sich emmr beischdandå dädåd, breicht neamrds des Gligg.
Er hôd koine scheene Hend.
Gäbb älles, was du hôschd... mee kôsch du et dô!
Er duåd ned arbeidå.
Du muschd net kapitulierä.
Älle derfå jetzetle mi Tom hoißå.
Tom ischå Hailigr.
Mir soddet mid leichde Frôgå åfangå.
Au Dommheid ond Ignoranz kennåd wachså.
I han scho gnuag dô.
Dees han i ned sagä miässä.
Môgsch du dees Land?
Die große Wäld stôhd bletzlich still, weil å kloiner Virus dees so will.
Er lauft romm wia å kopfloser Gockel.
Älle Wäg fangad mid mä Schridd oä.
Sai Bruadr isch Imam worrå.
Wär schwädzd, macht Bolidig! Wär was duåd, vrenderd d'Weld°
Du brauchsch nemme kommä.
Å gloine Tass Kaffee koschded zwoi Eiro.
I will ihr Gäld et.
Sai Bruadr isch Imam worrå.
Wenn du en Rom bischd, nô benimm de wia an Remer.
Her uff, dai Zeid em Internet zom verplembrä!
Im han ôgnommä, dass es omsonschd isch.
Maria hôd gsaid, dass es ihr schlächt gôd.
Als i s'letschde Môl Tom gsähä han, war er total bsoffä.
Tom ond Maria hend dees en ihre Tagbiachr gschriebä-
Di Jengschde isch dia schenschde gwä vo älle.
Mir läbåd.
Är isch rod wiå Tomad.
Nôch dem Ärdbebå hend viele Leit bschlosså, draußa en Zelt z'schlôfå.
I hann et gwissd, dass Tom mi ned môg.
Er kô bald schwemmå.
Wär Schmeddrling sähå will, muaß Rauba akzepdierå.
I hann sain ledschdå Romå kaufd.
I han neåmrd uff dr Strôß gsäå.
Menner vrlassad ihre Fraindenna erschd, wenn se was Bessers hend.
Siesch du, dass*r gligglich isch?
I heul nie.
Tom ond Marie send hongrig.
Liebe isch s'Oinzige, was wexd, wem mr s'vrschwendåd.
Megåd Sia d'idalienische Kiche?
