Mbabarira!
Tom nihari nawe?
Nyene uyu muduga ni data wanje.
Uhaguruka ryari?
Ndi mu muduga.
Uri umutetsi mwiza.
Urafise umuduga?
Mpa igitabo.
Nta ngorane.
Akira igitabo usome.
Igitabo kirihe?
Nyumviriza.
Nshaka gutaha.
Kubera iki ubaza?
Urupapuru rumwe rurabuze.
Urantegera.
Ntanumwe antegura.
Turihe?
Ufise imyaka ingana iki?
So wawe arihe?
Ndazi uyo mwigeme.
Afise imyaka ingahe?
Uvyuka ryari?
Murakoze cane.
Ibintu vyawe birihe?
Ni rwacu.
Ufise imyaka ingahe?
Uraza? Ego canke oya?
Ijoro ryiza!
Akira ico ushaka.
Urashaka ko nza?
Ukora iki?
Ibirato birihe?
Ni umuntu mwiza.
Ntitumuzi.
Ndamuzi.
Mu ruguma hari amashira.
Urashobora kugendayo.
Urakoze cane.
Uragikunda?
Uyu munsi ni umunsi w'Imana.
Ntadukunda.
Ndi umwe mu banyeshuri bawe.
We si umwana.
Nzovyiyumvira.
Ndi hehe?
Urugendo rwiza!
Urafise umuduga?
Mfise benewacu.
Mbe nambare iki - ipantalo canke ijipo?
Niki?
Simfise amahera.
Tuja hehe?
Ndafise ikibazo.
Uba ngaha?
Ndi umushinwakazi.
Nanje.
Sindi umunyeshuri.
Uri umugenzi wanje.
Ni mushiki wawe?
Murakoze cane.
Musazawe arihe?
Ndibaza ko ntegeye.
Ndafise umuduga.
Urashobora kujayo.
Urakoze!
Ibiciro vyaraduze.
Uru ni urukundo?
Ndakwiyumvira.
Afise imyaka ingana iki?
Bite uyu munsi?
Ndi imuhira.
Ndi umwotsi w'imikate.
Ni ordinateri yanje.
Ntiwibagire gutwara ibaruwa.
Mba ngaha.
Ndashonje.
Ibitoke bisa n'umuhondo.
Sohoka mu cumba canje!
Iki gitabo ni gishasha.
Ndamukunda.
Murafise umuceri?
Singifise umushikiwanje n'umwe.
Urukundo rurahuma.
Umuduga wapfuye.
We si umwana.
Biranshimishije.
Ndafise bashikanje.
Urihe?
Nabonye so wawe.
Ntanumwe antegura.
Si igifaransi.
Turi hehe?
Uyu muduga usa na mushasha.
Ndamuzi.
Tom arihe?
Sindabikeneye.
Ndamukunda.
Nzero ni ukwezi kwambere mu mwaka.
Ni neza cane.
Ushaka kuba hehe?
Kubera iki jewe?
Ndi umutetsi.
Ivyirabura ni vyanje.
Afise umuduga.
Ndi mushasha aha.
Mbabarire cane!
Ntegerezwa kugenda ubu.
Sindamuzi.
Ndi imuhira.
Isaha yanje irihe?
Ntumuhagarike.
Umuduga wanje urihe?
Simbikeneye.
Aranezerewe.
Urafise mwenewawe?
Ni ku wambere.
Ndagukunda.
Aranezerewe.
Murabe.
Uyu munsi ni kuwagatatu.
Uri umunyeshuri mwiza.
Nshaka ko ubisoma.
Niibagiye kugura umukate.
Ndashaka gusoma iki gitabo.
Soma!
Oya, urakoze.
Ndi iwanje.
Ndafise ikibazo.
Ushaka kugenda ryari?
Ndazi nyoko.
Nshaka gutaha.
Uramukunda?
Reka kundaba!
Ni naco gituma ndagukunda.
Urafise musazawe?
Ntiwibagire gutwara ikete.
Kubera iki tutaja imuhira?
Ndazi uyo mukobwa.
