Imbere yo gukatira iburyo mu masanganzira, gensura ko ata munyekinga aje.
Ikintu cose gifise amaherezo.
Vyose bifise urubibe.
Vyose birashoboka.
Bose bavuga ngo nabaye intwari, ariko naranguye igikorwa canje gusa.
Umusumakazi abonye umuporisi yaciye yiruka.
Umusumakazi amaze kubona umuporisi yaciye atungwa n'ayo yameze.
Reka ndagitumeko.
Reka ndakigure.
Rero, dushobora kuganira mu minsi iza, ariko ubu ndiko ndiruka ku kazi.
Ntushavure!
Uherereye hehe?
Uri mu ruhande uruhe?
Wiga kw ishure irihe?
Nagasaga, Sayoko.
Nta wundi muntu yarahari kiretse jewe.
Ntanumwe amuzi neza kiretse abavyeyi biwe.
Ibitoke bisa n'umuhondo.
Tebuka!
Nimwihute.
Abonye amaraso umurwayi yaciye araba.
Ineza ihimbara abantu gusumba ubwiza?
Mbe nagomwe?
Birakunyuze?
Nico cakuzanye ngaha?
Nico gituma cakuzanye ngaha?
Uri umunyeshuri mushasha?
Uranezerewe?
Ntunezerewe?
Nturoraniwe?
Uri imuhira?
Uri iwacu?
Uri iwawe?
Ntusabe amahera.
Ndagusavye ubimbwire.
Nimugende kandi.
Bishire nyoko.
Nimuzanire abandi.
Nimuzanire ibindi.
Bitware hirya.
Njana i muhira.
Ntwara i muhira.
Ntumpate kubikora.
Reka kunsomboroza kubivuga.
Tanga akaryobwa.
Nguyo arashitse!
Ntimushobora gufatira kuri ivyo.
Urakoze kuza.
Urakoza ko wajanye natwe.
Urakoze guhita.
Urakoze kuza iwanje.
Urakoze kwicisha iwacu.
Urakoze kuza iwanje.
Murakoze kuza.
Urakoze kuza.
Murakoze kwumviriza.
Urakoze cane!
Urakoze cane.
Urakoze!
Tuzobanza kubikorako.
Ndashobora kubibona kandi?
Nshobore gusubira kubibona?
Ndashobora kuronka iki gitabo?
Nashaka kubaza, mbe mugenzwa n'amaki?
Nashaka kubaza, mbe muhakura inyungu nki?
Ndashobora kubaza ico vyerekeye?
Ndashobora kubaza iyo bishira?
Ndashobora kwinjira?
Ngaruke?
Nsubire kugaruka?
Ntaco ndabiziko.
Umuduga wapfuye.
Umuduga wa data ni mushasha.
Nta nsiguro bikeneye.
Iki gitanda kiranonotse cane.
Iki gitabo ntaco kimaze.
Iki gitabo ntigifise akamo.
Idirisha riraba mu rugo.
Iyi nzu iri ku gasozi ni ishure ryacu.
Amahera yaheze.
Bivana n'igihe.
Bikuvako.
Nguyo araje!
Ni vyose bisigaye.
Ico gitabo ndagifise nanje.
Niwe umugabo mvuga.
Niwe umugabo ndiko mvuga.
Ni ibintu bikunda.
Ni ibintu bishoboka.
Iki kibazo ni ciza.
Ni rwacu.
Ni igitabo c'agatangaza.
Ni igitabo ciza cane.
Niko abantu bavuga.
Nico nshaka kumenya.
Ni vyiza, sivyo?
Capfuye.
Si isango y'ikiyago. Tuja gusa muri cenema.
Birumvikana.
Iyi nyabu ni yanje.
Ni rwanje. Nsubiza.
Ntibindaba mugihe ahimbawe.
Sico kimwe.
Ico sico gituma.
Siyo mvo.
Si neza.
Si vyiza.
Si umuduga wanje.
Nta bishasha.
Si ikintu co kwirata.
Si ikintu co kwishima.
Nta gishasha.
Nta kamaro.
Ni umuduga wiwe.
Ni igice c'umugambi.
Ni rwacu.
Ku bwanje harakanye birengeye.
Ni birebire birenze.
Ni birebire birenze urugero.
Ntibishobora ko ari ivyo mushaka.
Ntibishobora kuba ivyo mwipfuza.
Umwana ari ku ruhande rw'ibubamfu rw'inzu.
Ikanzu rikozwe mw'iharire.
Vyumvikana ukuntu.
Nta gorane.
Igisu kirakarishe cane.
Ku wambere musée yama yugaye.
Turakira ibikurikira.
Igitwazi kirasimba.
Birakwiye.
Mwama kubivuga.
Bisa neza.
Ni abavukanyi.
Bingwa neza.
Mpore.
Muzovyigaya cane.
Igihe ntikigize gukanya gusa, kiranajovye.
Bizoba neza cane.
Ivyo turabizi.
Turabizi.
Icumba ni ciza.
Ntimushobora gufatira kuri ivyo.
Ngico igitabo cawe.
Ipantalo yawe iranduye.
Uruhanga rwawe rurashushe cane. Ndakeeka ko ufise inyonko.
Uri inda nsa.
Namwe muravyiyumvira gutyo?
Ico gisa n'ivu ni rwanje.
Umudandaza yaduhaye inshumbushanyo nini.
Umudandaza yaratugabanirije cane igiciro.
Ijuru riracika ryiza mu kanya.
Umuhungu arasimba.
Umuhungu arabaza ikibazo.
Kuwagatatu haza birakunda.
Kuwagatatu haza ni vyiza.
Igiciro ni amajana atatu, si abiri.
Igiciro kiraduga.
Ijipo irandenze.
Ijipo iranduta.
Ijipo ntiyari inkwiye nico gituma nabwirijwe guyihindura.
Umubaji arapima isi.
Akazi kagenda buhoro buhoro kubera ko abakozi babuze.
Umubaji arapima ikibanza.
Umubaji arapima ikirere.
Ishure riraheze.
Ntanumwe yakubajije.
Ntanumwe yakubajije.
Akabare karabasorereye.
Igituro ca bisi kiri iminota itanu uvuye ngaha.
Ihinguriro rikora ibihumbi n'ibihumbi vy'amacupa kira kwezi.
Ihinguriro rizotangura gukora mu mwaka uza.
Amadirisha araguruye.
Ikiganza gifise intoki zitanu: urukumu, inkombarukoko, msumba zose, igihugunibenga, agahererezi.
Ikiganza gifise intoki zitanu: urukumu, inkombarukoko, msumba zose, igihugunibenga, agahererezi.
Ubugeni buzoba ku wagatandatu.
Ipantaro ntinkwira. Ndashobora kuyiguza?
Abana bari ibubamfu iruhande y'inzu.
Turashaka kuriha.
Intwaro iritwararika cane iki gikorwa.
Igifurwe ntigifise amenyo.
Inzoka yamize igikere.
Iki gikorwa kimugora birenze.
Iki gikorwa kiramurengeye.
Iki gikorwa kiramuvuna.
Ayo mashurwe ubona ni amarosi.
Nyene ibi bitabo ni mushikanje.
Iyi hinguriro rikora ivyuma vy'imiduga.
Iri darapo ni nziza cane.
Aya madirisha aherereye mu bumanuko.
Ayo madirisha yerekeye mu bumanuko.
Amadirisha aranduye.
Amadirisha ari umwanda.
Igishika co kukubona kigiye kunyica.
Iki giti kirashaje.
Muri ino gant hari intoboro ku rukumu.
Nyene uyu muduga ni data wanje.
Uyu muduga usa na mushasha.
Iki gitabo ni gitoya.
Iki gitabo ni gishasha.
Iki gitabo ni ciza cane.
Iki gitabo ntigifise akamo.
Ibi vyicaro bigenewe abantu bashaje n'abarwaye.
Izi ntebe bigenewe abantu bashaje n'abarwaye.
Iki gihugu gikesha itunga ibitoro.
Uyu mwigeme yiyambika nk'umuhungu.
Uyu mwigeme asa neza.
Iki gisu kirapfushe.
Iri jambo riva mu kigereki.
Uyu muduga ni rwanje.
Kuri ino ncuro sinshobora gushika.
Kuri ino ncuro sinshobora kubikora.
Izuba rirasira mu buseruko.
Izuba riserukira mu buseruko.
Izuba rindasira mu maso.
Ibarabara riri urwamo rwinshi.
Ibara ry'ikirava rihuje n'uruhome.
Igihe girarenze.
Waciye ku kimenyetso c'itara ritukura.
Waciye ku kimenyetso gitukura.
Uri umuhinga.
Uramukiwe.
Uri umuhinga.
Uri umugore nkunda.
Igihe cawe cashitse.
Niwe uramukiwe.
Uramukiwe.
Ur'uwiwacu.
Ur'uwiwacu.
Uri umutetsi mwiza.
Uri inda nsa.
Uri umuntu mwiza.
Uri umunyeshuri mwiza.
Urarwaye, ubwirizwa kuruhuka.
Uri umugenzi wanje.
Uri umubanyi wanje.
Nturi musazanje.
Nturi mwenewacu.
Urazi kubigira neza cane.
Wagomwe.
Uranyitwararika.
Ntubwirizwa kwandika ikete rirerire.
Ntutegerejwe kuza.
Nturekuriwe kwinjira.
Ndagukumbuye cane.
Ntiwakomye kw'isahani yawe na gato. Hari akakubakiye?
Hari akakubakiye.
Urafise isaha imwe.
Wabishoboye.
Urarurumba.
Wari kungirira cokimwe.
Ntwumviriza.
Ntushobora kubuza ko abantu bavuga.
Urashobora gutora irangi iryariryo ryose rigushimisha.
Ntushobora kwama uronka ico wipfuza.
Urazi bano bantu.
Uramuzi.
Ntuzi musazanje.
Uranzi.
Ntuza, sivyo?
Ntuzoza, sivyo?
Uba ngaha, sivyo?
Urampimbaza.
Uranezereza.
Ubwirizwa guheba inzoga.
Ubwirizwa kureka kunywa.
Ubwirizwa kuvyuka.
Ubwirizwa kuvyakira.
Ubwirizwa kujayo kubizana.
Ubwirizwa kureka kunywa.
Ntubwirizwa kuza.
Ubwirizwa kwumviriza.
Usa n'uwuhiriwe.
Usa n'uwunezerewe.
Usa na data wawe.
Usa na so.
Usa n'umupolisi!
Ubigerageze.
Urantegera.
Urazi ko ndagukunda.
Urazi ko mbwirizwa kugenda.
Urazi ko tugukunda.
Urazi aho nzoba ndi.
Uzosubira vuba gukomera.
Ushaka kuzobiraba.
Uzobitegera vuba.
Uzobikunda.
Uzomukunda.
Uzomukunda.
Uba ngaha, sivyo?
Urupapuru rumwe rurabuze.
Bamwe muri abo bakozi ntibamenyeye gukora ako kazi.
Rimwe, gatatu no gatanu ni ibiharuro bitagaburwa na kabiri.
Inzovu zirya ivyatsi.
Tuhavuye tuba twenyene.
Mbabarira!
Ntunga!
Mbabarira, izina ryawe ni nde?
Ntunga, mbega witwa nde?
Asa na Se wiwe.
Yakoze yivuye inyuma.
Akora mw'ihinguriro.
Yabanze izuru kw'idirisha.
Yabanze izuru ryiwe kw'idirisha.
Iminsi yose aja ku kazi ku maguru, kiretse iyo imvura igwa.
Agiye buhoro buhoro kugira umwana ashobore gukurikira.
Ntiyasomaye iki gitabo.
Afise umuduga.
Yandungitse.
Yacishije igisu ciwe ishami ry'igiti.
Yahemutse kw'ijambo!
Yatezuye!
Yafashe umunsi umwe w'uburuhuko.
Nta mahera yari agifise.
Muribuka ihimbaza ry'amavuko ya data?
Wibuke ubuntu bwawe wiyobagize ibindi.
Uribuka?
Ni umuntu mwiza.
Ni umunyeshuri mwiza.
Aranezerewe.
Yavyutse nabi.
Ni nk'umuvandimwe.
Arenza imyaka mirongo itatu.
Yamukunze.
Yaje wenyene.
Yagarutse ino.
Yagarutse ngaha.
Ngirango araza.
Aramukunda.
Ntadukunda.
Ntadukunda.
Yafashe ikinyugunyugu n'urukumu hamwe n'inkombarukoko.
Yakarihije igisu.
Yazunguje umutwe.
Asa na mwenewanyu.
Asa na data.
Ntasa n'uwunezerewe.
Asa na nyina wiwe.
Ntavuga icongereza.
Aranywa.
Arumva igifaransa.
Iyo aguma imuhira uyo munsi, ntiyogize isanganya.
Arihanaguye icuya mu maso.
Ntiyashatse gusaba imfashanyo naho yari ashonje cane.
Yatwawe ku bitaro.
Mbwira umugambi wawe.
Tubarire ivyo mukora muri kino gihe.
Tubwire ivyo mugira ubu.
Nganirira umugambi wawe.
Antera kuzirikana.
Antera kwiyumvira.
Urupapuru rumwe rurabuze.
Ntibikora.
Nyene ikintu ni musazanje.
Sibiraba amahera.
Bizoja imbere.
Mu buseruko bw'ikigwati hari ikiyaga.
Nta gituma kihari co kugira ubwoba.
Nta mvo ihari yo gutinya.
Nta gituma co guhagarika umutima.
Nta gituma co kugira umutima uhagaze.
Nta mvo yo kugira impungenge.
Nta mvo yo kugira ubwoba.
Nta ngorane.
Nta ngorane.
Hari amategeko.
Nta kamaro!
Ni isaha icenda ibuze iminuta icumi n'itanu.
Ntihahita.
Biramuraba.
Ni akazi kiwe.
Tubiravye neza, ni bimwe!
Aho ufungura ku mugoroba sindabinzwe.
Biranteye isoni.
Ndamaramaye.
Ni ku wambere.
Ntibiri nkuko uvyiyumvira.
Si vyiza.
Ntivyapfuye.
Ntibigoye cane.
Ntibimeze uko uvyiyumvira.
Ntanumwe ari i muhira.
Biratunganye.
Ni ku wagatandatu.
Ni binini cane.
Ni birebire cane.
Harashushe cane, canke?
Biramuraba.
Harakanye cane.
Ni munsi.
Ni isaha icenda ibuze iminuta icumi n'itanu.
Harashushe.
Ni igihe co kuruhuka gatoya.
Harashushe birenze.
Ni bitoya birenze.
Ni bitoya birenze urugero.
Ni birebire birenze.
Birashobora gupfa.
Bishoboka ko bipfa.
Ntibisa neza.
Bisa naho muri mu kuri.
Haguye amama make y'imvura.
Bingwa neza kubona tuvugana.
Mpore ko ndabivuze.
Uranhunga ko ndabivuze.
Mbabarira kugukankamira.
Mbabarira ko nagutaye mu rudubi.
Urambabaje.
Mbabarira, sinshobora kugenda.
Mbabarire cane!
Mpore cane!
Uzosubira vuba gukomera.
Bizogushimisha.
Bizokugwa neza.
Uzobikunda.
Haraza gushuha.
Erekana itike!
Haraho uzogenda muri iri ci?
Umwansi aguye, muvyure.
Ntimushakisha igituma!
Mubaze izina ryiwe.
Ntusubire kumbaza.
Ntubaze.
Reka kubaza!
Agafuni kabagara ubucuti ni akarenge.
Kera hari isengero ngaha.
Kera waranywa itabi, sivyo?
Bitebe bitebuke vyose birahera.
Bitebe bitebuke bizoba.
Urira aha canke uratekera?
Ukora kwa nde?
Ukorera nde?
Wibaza ko ndi nde?
Ndamusavye umpe urupapuro rwo kwandika.
Uragikunda?
Jayo ubu nyene.
Ja hirya.
Abana bagiye kw ishure?
Tujane twese hamwe gufungura ku mutaga.
Ntugende zirayoye.
Genda kwoga!
Uzofata urugendo wenyene?
Uragiye nawe?
Uragenda canke?
Uragenda canke ntugenda?
Urakomeye vyo?
Urakomeye vy'ukuri?
Je hanze!
Jabuka ibarabara.
Ja hiyo!
Ejo hari kuwagatanu.
Raba neza ingene ndabikora!
Heba!
Heba!
Bimuha.
Bimuhe.
Bimuha.
Ntumpebe.
Mpa isaha yawe.
Mpa amahera make.
Mpa akanya.
Mpa ikintu co kunywa.
Ntabaza ico kunywa.
Ntiwosubira kumpa ikindi gikombe c'icayi?
Ntuhebe!
Hari imashini yo kumesura mu nzu?
Uremera ko ataco bintwaye?
Uribaza ko nezerewe?
Imana iguhezagire!
Fata ico wipfuza.
Urugendo rwiza!
Ikibazo ciza.
Ijoro ryiza!
Bwakeye!
Umunsi mwiza.
Sawa, nzogikura.
Neza, nawe?
Bashizeko umukono?
Basinye?
Bite!
Hagarika uyo muduga.
Kanyemwo!
Kazibe!
Ntumuhagarike.
Wagize ubwoba?
Watinye?
Wavyibajije?
Warasomye ico gitabo mperuka kukugurana vuba.
Wasize idirisha ryuguruye?
Urafise aya mahera?
Watinye?
Wasomye iki gitabo?
Urafise musazawe?
Urafise mwenewawe?
Urafise uwo muvukana?
Urafise isahani ipfukuye y'isupu?
Urafise ikintu mu gutima, ushaka kwikura? Urashobora binganirira.
Wamenyesheje ivyabaye?
Waravye itelevisiyo uyu mugoroba?
Wabonye amaso yabo?
Uracambara ikareso imwe?
Urameneka umutwe?
Urafise amahera yanje?
Uramfitiye amahera?
Urashaka kugendaho?
Urafise ico gusoma?
Icumba cawe gifise amadirisha abiri?
Iyo menya sinari kuza.
Woba ufise akanya?
Woba ufise akanya?
Woba ufise umunota?
Woba ufise akanya ko kumfasha ikintu?
Kazae!
Uyu munsi hari ibicu vyinshi.
Uyu munsi ni kuwagatatu.
Mfise umukoshi uyu munsi.
Si umunsi wanje.
Eh, ushaka kuja hehe?
Emwe ga, uyu mushatsi ni uwande?
Ewe ga, urya mushatsi ni uwande?
Niho ndi!
Sabwe!
Ngaha nta numwe afise umuduga.
Ngico igitabo cawe.
Ngiyo ifagitiri.
Ngico ico mwasavye.
Nguyo!
Nguyu!
Ntimushobora guhagarika umuduga wanyu ngaha.
Pima.
Ngibi ibisu, amakanya n'ibiyiko.
Aya ni amadolari atanu.
Ngizo impapuro zanje.
Ngizo impapuro zanje.
Ngaha ntibaba abatunzi.
Nta batunzi baba ngaha.
Tora ibintu vyawe.
Nkura ngaha.
Bireke.
Reka.
Reka gutanga amategeko ngaha!
Reka gutegeka ngaha!
Reka kundaba.
Reka kwishima ata soni!
Reka kuvuga uko.
Reka kubaza!
Reka gusoma.
Nyumviriza.
Ntumwumvirize.
Tega amatwi!
Umviriza!
Imbwa zihamba kenshi amagufa.
Ndabubaha.
Ndakunda gukora ngaha.
Simbakorera.
Nanje.
Natanguye gukora muri ino societé kuva umwaka uheze.
Nahisemwo kurwana urwo rugamba.
Ndi jenyene.
Ndi mu nzira yaho.
Ndasemagurika.
Ndi umwotsi w'imikate.
Ndi iwanje.
Ndi umushinwakazi.
Aho biri ndanezerewe.
Biranshimishije.
Biranyuze.
Naje kubera wewe.
Ndi uwanyuma.
Ndi uw'impera.
Ndi uwo ku murizo.
Ndi umunyeshuri mushaha muri kaminuza.
Ndi umwe mu banyeshuri bawe.
Ndi umunyeshuri muri kaminuza.
Ndarwaye gahoro.
Ndanezerewe ku uhimbawe.
Ndanezerewe ko ariho uri.
Ndi ngaha ijoro rimwe.
Nje kugutwara i muhira.
Naje kukurondera.
Nje gusezera.
Ndashika mu kanya.
Ndanezerewe.
Ndi mu muduga.
Ndi mu gikoni.
Ndi mu karuhuko.
Ndi mu kiruhuko.
Ndagukunze.
Sindi intore.
Sindi umuntu mwiza.
Sindi ikijuju.
Sindi umutunzi.
Sindi umunyeshuri.
Sindi umunyeshuri muri kaminuza.
Ndi umutetsi.
Nahomvye.
Ndi umwigisha.
Ndarenga umugenzi.
Ndaruta umugenzi.
Ndazi neza ko hari aho maze kumubona.
Ndazi neza ko namubonye ahantu ikindi gihe.
Sinkomeye muri vyo.
Sinzi neza igifaransa.
Sinzi gufata amazina.
Singushimye.
Sinkugomwe.
Sindi umutunzi.
Sintunze.
Ntibimpa agateka.
Ntibintera iteka.
Ntibinshimishije.
Amahera yampereyeko.
Meze nabi.
Ndi umunyeshuri muri kaminuza.
Ndi umunyeshuri muri kaminuza.
Ndera.
Nta mahera mfise.
Namugomwe.
Ndasaze.
Ndi imuhira.
Ndakeneye umwanya wo kwiyumvira.
Simbikeneye.
Ndakeneye abakozi b'abitanzi batatu.
Simbikeneye.
Sindabikeneye.
Ndagutwara kw'ishure.
Nagira ngo ni ikigorwa cawe.
Nagira ngo woba watashe.
Nagira ngo urashobora kubitegera.
Nagira ngo urabizi.
Niyumviye ko vyogutwenza.
Nibajije ko ndakuzi.
Nagira ngo niwe ncuti idasumbwa.
Nagiro ngo niwe ncuti itarutwa.
Ndakwiyumvira.
Ndakwiyumviye.
Ndibaza ko azoza.
Ndibaza, icamubayeko.
Ndanezerewe kukubona.
Siniyumva neza ngaha.
Namerewe nabi.
Sindaheba.
Na jewe ngenda kw'ishure ngaha.
Ndatembera gato.
Ndakunda gutemberera ku ruzi.
Kira gitondo mva imuhira imbere y'isaha zibiri.
Ngiye guzana umuduga wanje.
Ndagenda kuryama.
Ndakwemera.
Ndibaza ko ntegeye.
Ndagukeje!
Ndabakeje!
Nasuzumye vyose.
Nakwiyumyiye.
Ndatinya inyoni.
Ndaribwa mu nda.
Navyiyumviye.
Nabizirikanye.
Navyiyumviye.
Nabigiriye wewe.
Naguhevye.
Naragukunda.
Natekeye neza ibirahuri kugira ntibimeneke.
Natekeye neza ibiyo kugira ntibimeneke.
Nasivye kw'ishuri.
Narasomye iki gitabo.
Iyi kanzu nijewe nayigiriye.
Narabikubwiye mu ndwi iheze.
Nahasanze umugenzi.
Mfise abakobwa batatu.
Mfise mukuruwanje.
Ndafise ikibazo.
Mfise mukuruwanje.
Nagize igitondo c'imirimo myinshi.
Mfise mukuruwanje.
Mfise umuhora.
Naguze amagi n'amata make.
Nashoboye kugira.
Nabigiriye wewe.
Nabiketse.
Nashoboye kugira.
Ndabibonye.
Nari mbizi.
Nababonye.
Ndababonye.
Ndarurumba.
Ndafise amahera yawe.
Ndagufitiye amahera.
Ejo naryamye umunsi wose, kuko wari umunsi w'Imana.
Nariye amagi ejo.
Ndashonje.
Naramuhaye igitabo.
Ndamubonye.
Namubonye yiruka.
Nasubiye kumubona.
Mu mwaka uheze navyaye imfura yanje.
Simfise umuduga.
Nta bitabo mfise vyo gusoma.
Simfise musazanje.
Sindashonje.
Sinshonje.
Singifise umushikiwanje n'umwe.
Simfise amahera.
Simfise imuhira.
Ndameneka umutwe.
Nabarira vyose abavyeyi banje.
Naratakaje ikaramu ryanje.
Nariyumviye kuguma iminsi mike iwawe.
Nikomerekeje n'igisu ku rutoki.
Ntaco ndabirabamwo.
Ntaco ntibindaba.
Ntaco ntibindora.
Ntaho dusa dusaniye n'ivyo bintu.
Mfise benewacu.
Ndafise bashikanje.
Ndamanikwa impuzu.
Ndahatswe gutura amasahani hasi.
Ndahatswe kumena amasahani.
Nitwa Jack.
Ndakwumviriza.
Sindavyumva.
Nazanwe no kwiga.
Naje kukurondera.
Ndashobora kugutegera.
Ndashobora kukwumva.
Sinshobora kwoza amasahani. Harabuze amazi.
Sinshobora kwoza amasahani. Harakenye amazi.
Sinzi kugumya amazina.
Sinshobora guhinduka uwo ndi.
Sinzi guteka.
Ndazi uyo mukobwa.
Ndazi uyo mwigeme.
Iryo jambo ntaryonzi.
Ndakuzi.
Ndakuzi kuva kera.
Ndazi aba bagore.
Sinzi aba bantu.
Ndazi uyo mukobwa.
Sinzi iryo jambo.
Ndazi izina ryiwe gusa.
Sindamuzi.
Sinzi izina ryiwe.
Sinzi izina ryiwe.
Ndamuzi.
Sinteka.
Mva muri Bresil.
Ndiko ndashinguka.
Ndiko ndasohotse.
Turazananye.
Ntitujana.
Ndashika isaha zine.
Ndaje kuguhitana.
Ndashika isaha zine.
Sinashoboye kutarira.
Ndonka ico nshaka.
Narasomye itama ryiwe.
Sinkunda kwiruka.
Mba ngaha.
Mba muri Noroveje ubu.
Niga igifaransa mw'ishure.
Niga igifaransa mw'ishure.
Sindakunda kwiga.
Ndiga igifaransa imuhira.
Ndiko ndasoma igitabo.
Ndagukunda.
Ndakunda iki gitabo.
Ndakunda kubikora.
Ndakunda kuraba ingene uteka.
Ndakunda ibiharuro.
Ndakunda akazi kanje pe.
Ndakunda akazi kanje vy'ukuri.
Ndakunda umuryango wanje.
Ndakunda data.
Ndamukunda.
Narakunze uyu muduga.
Simbesha na rimwe.
Ndabikorera wewe.
Simbikora neza.
Ndi mu karuhuko.
Ndi mu kiruhuko.
Ndiko nduhuka.
Ndi mu karuhuko.
Sinkunda inzoga.
Ndagukunda nanje.
Sinkunda aba bantu.
Ndakunda imishatsi migufi.
Ndakunda ibiharuro.
Ndakunda ibiharuro.
Sinshaka kugumya rwaye.
Ndabakunda bose.
Ndabikunda vyose.
Nshaka kwicara hafi y'idirisha.
Nshaka kwicara kw'idirisha.
Ndashaka kubihindura.
Nshaka ko ubimenya.
Ndashaka ko usoma iki gitabo.
Nshaka ko ubisoma.
Nshaka ko uja imuhira.
Nshaka ko umubona.
Ndashaka kuguherekeza.
Sindabishaka ubu nyene.
Sindavyipfuza ubu nyene.
Nshaka kugutekera.
Nshaka kugenda mu mahanga, akarorero: mu butaliano, muri espanye.
Nshaka gutaha.
Sindashaka kuba ngaha.
Mbwirizwa kureka.
Mbwirizwa kukubona.
Mbwirizwa kubifata uko biri.
Mbirizwa kwiga gifaransa.
Mbwirizwa kwiga.
Mbwirizwa gutunganya imishatsi yanje.
Mbwirizwa kwiyumvira.
Ntegerezwa gutaha.
Ntegerezwa kuja imuhira.
Mbwirizwa kuzirikana.
Mbwirizwa kwiyumvira.
Amahera narayakiriye.
Mfashe ibi aha.
Ndakujana.
Ndakira ibi.
Ndabitwara.
Ndavyakira.
Nzofata umunsi w'akaruhuko.
Ndatunganya amadirisha.
Nirukiye kwa mama.
Mvuga ico mfise ku mutima.
Mvuga ico mfise ku muzirikanyi.
Mvuga ico niyumvira.
Navuze ko bimbabaje.
Nahabonye mwenewacu.
Ndaguhwatira umucungwa.
Nryama ubusa.
Nryama uko zandemye.
Nandika kuri twebwe.
Ndarahiye.
Ndabiraba.
Sindamubona.
Sinsa uko.
Ndemanze ikosa ryanje.
Mvyuka isaha imwe zo mugitondo.
Nururukira ngaha.
Niga icongereza muri kaminuza.
Ndakurondera.
Ndondera inzu mu gisagara, ata cizero.
Sinywa.
Ntaco nywa.
Ndabigirira kubera wewe.
Ndabikorera wewe.
Nkora ivyo umuntu ambwira.
Ngurisha impuzu ku murongo.
Ngurisha impuzu ku murongo.
Ndagukumbuye cane.
Sindagutegera.
Sintegera iri jambo.
Ndabitegera.
Sindabitegera.
Sintegera igifaransa.
Sinumva igifaransa.
Ndategera.
Ndavyumva
Sintegera gute.
Ndategera ico ushaka kuvuga.
Ndategera ico ushaka kuvuga.
Ndategera ico uvuga.
Ndipfuza kuba umugenzi wawe.
Ndarindirira hanze.
Ndarorerera hanze.
Mpora mesura isutiye yanje n'amaboko.
Ndazi ko ubifise.
Ndazi ko unkunda.
Ndazi ko ubanga ugutwi.
Ndabizi neza.
Simbizi.
Sindakizi.
Ndabizi.
Sinzi.
Sinzi icarico.
Sinzi ico ushaka.
Sinzi ico novyiyumvirako.
Sinzi ico novuga...
Sinzi ico novuga...
Sinzi ico nshaka.
Sinzi ingene witwa.
Sinzi izina ryiwe.
Sinzi igihe uko kingana.
Sinzi gute.
Sinzi ingene.
Sinzi iyo ngana.
Sinzi iyo ndibuje.
Sinzi iyo ngana.
Sinzi aho muba.
Ndazi ibitari bike kuri wewe.
Ndazi igituma ubishaka.
Ndazi igituma uri ngaha.
Ndazi uvyirumvira.
Ndazi ico nzokora.
Ndazi ico nkora.
Ndazi ico nokora.
Ndazi ikiriko kiba.
Ndazi ibikenewe kurangurwa.
Ndazi ingene bigenda.
Ndazi kubikora.
Ndazi ingene umuntu ashikayo.
Ndazi ingene bikoreshwa.
Ndazi ingene bigirwa.
Ndazi ingene bameze.
Ndazi ingene bateye.
Ndazi aho biri.
Ndazi iyo mbwirizwa kuja.
Ndazi iyo baja.
Ndazi aho muri.
Ndazi aho mbwirizwa kugaba.
Ndazi aho ari.
Ndazi aho turi.
Nzomoka.
Nzota nomoke.
Nzogerageza vyose uko nshoboye.
Nije nzobanza kwinjira.
Nije nzotangura kwinjira.
Nije nzobanza kwinjira.
Nije nzotangura kwinjira.
Nzokugarukako.
Nzovyishoboza.
Ndabitora.
Ndabitwara.
Nzokuraba.
Nzokurora.
Nzokunezereza.
Sinzobikubuza.
Ndarindirira hanze.
Ndarorerera hanze.
Nzobiguha.
Nzobitora.
Ndabirora.
Nzobiraba.
Nzobishobora.
Nzogerageza.
Nzikosora.
Mpembwa neza.
Nururukira ngaha.
Nzoza kugutora.
Ndiko mpumura.
Ndiko nsaza.
Nzobijamwo.
Nzovyitaho.
Nzigora.
Ngenda n'umuduga.
Ndabiraba.
Nzobiraba.
Nzofata ivyo nshobora kwakira.
Sinzoreka.
Sinzorabayo.
Nzogaruka mu gihe.
Ndaje munsi.
Ndamanutse.
Ndururutse.
Nzomuhamagaza aha.
Nzokora ico unsaba.
Nshika iwawe isaha zibiri.
Ndashaka bimwe nanje.
Ndipfuza bimwe nanje.
Nshaka ko mubibona.
Ndashaka gusubira kukubona.
Sinshaka kubisoma.
Sinshaka kubimenya.
Nshaka kubibona.
Nshaka kwiga igifaransa.
Ndashaka kubana na wewe.
Sinshaka guheba.
Sinshaka kurora.
Sindashaka kurwara.
Sinshaka.
Sinshaka kurira.
Nta wundi nipfuza atari wewe.
Sinshaka kubabaza umuntu.
Sinshaka kugira uwo mbabaza.
Sinshaka kugira uwo nkomeretsa.
Mba ngaha.
Nokora gutyo.
Novuga gutyo.
Nokwongera.
Nosubira kubikora.
Noshimishwa no kumenya izina ryawe.
Ndipfuza gutambana nawe.
Ndipfuza ikindi gikombe c'ikawa.
Noshimishwa no kumubona.
Nari nzi ko wogaruka.
Narinzi ko vyogushimisha.
Narinzi ko bigushimisha.
Narinzi ko bikunezereza.
Narinzi ko wojayo.
Nari mbizi.
Sinarinzi ko muri buhabe uyu munsi.
Sinarinzi ko muri buhabe uyu munsi.
Mwebwe babiri ni muzanane nanje.
Ntibikenewe ko mwinyegeza.
Igikorwa cawe kizoba ico kwigisha abakozi ubuhinga bwa ordinateri.
Ntimuzi namba ivyashitse, canke?
Mubwirizwa gutaha.
Mubwirizwa gutaha.
Mubwirizwa kugenda i muhira.
Mubwirizwa kugenda i muhira.
Mwebwe muri abana.
Muri iri kostim ryirabura n'amarori y'izuba usa na umusahuzi.
Uyu mwaka ntegekanya gusoma ibitabo vyinshi bishoboka.
Muri ico gihe nararavye ya cenema wamye urata.
Uyu ni mama wawe?
Uyu ni nyoko?
Uwu muduga ni mushasha?
Ni ingorane?
Iki ni igifaransa?
Raba ingene biteye igomwe.
Birakwiye?
Ni bitoya birenze?
Nyoko niho ari?
Nyoko ari imuhira?
Ikiyaga gifise ibenga rinini?
Ni umunyamerika?
Ico nico uriko urondera?
Ubironderera ngaha?
Urondera ibi aha?
Nuko vyamwe?
Capfuye?
Uko ni vyiza gusumba?
Birera?
Ni binini birenze?
Ni birebire birenze?
Ni bitoya birenze?
Birakwiye vyose ivyerekeye vy'urugendo?
Tom nihari nawe?
Ego, ndazi.
Nzero, Ruruhuma, Ntwarante, Ndamukiza, Rusama, Ruheshi, Mukakaro, Myandagaro, Nyakanga, Gitugutu, Munyonyo na Kigarama ni amezi icumi n'abiri y'umwaka.
Nzero ni ukwezi kwambere mu mwaka.
Umudandaza wese arata ibidandazwa vyiwe.
Umuntu wese arashobora kubisoma.
Umuntu wese arashobora kubisoma.
Umuntu kanaka azugara idirisha.
Ni isaha icenda ibuze iminuta icumi n'itanu.
Nshobora kutumako kimwe?
Ndashobora kumenya ibintu nokuzanira.
Nshobora kwicara hirya?
Ndashobora kubaza ikindi kibazo?
Ndashobora kwinjira?
Ntiwoshobora kubisubira ico wavuze?
Urazi gutandukanya intama n'impene?
Urashobora kurungika umuntu ngo abikiranure mu maguru masha?
Ibitungwa ntibirekuriwe.
Ntanumwe yakubajije.
Ntanumwe yarazi ibikenewe kurangurwa.
Nta ngorane.
Ndamuzi?
Ndazi Tom?
Murazi aba bantu?
Urazi izina ryiwe?
Urazi izina ryiwe?
Araguzi?
Murazi aba bantu?
Duga hejuru!
Urira hejuru!
Ntimugaruke.
Ntimusubire kugaruka.
Ntimwongere kugaruka.
Injira.
Shika!
Ingo!
Manuka!
Ururuka!
Ingo!
Fata iyi nzira.
Ingo tujane.
Ingo kunsura.
Za kunsura.
Zanana!
Turajana?
Uraza canke?
Uraza? Ego canke oya?
Nimushike.
Azoza nawe?
Ingo wirorere.
Murashobora kuntegera?
Murashobora kunyuganga?
Murashobora kwinyuganza?
Inyoni zirashobora kwimotereza?
Dushobora kuganirira ngaha?
Ntidushobora kubiganirira ngaha?
Dushobora guhurira hehe?
Turashobora kugira aho tuganirira?
Urashobora gusubiramwo?
Murashobora kwugurura idirisha?
Honja!
Kubika ahakanye kandi humutse.
Ndakunda imishatsi migufi.
Bireke.
Reka ndaguhobere.
Reka ndakugwe mu nda.
Reka ndabe.
Reka ndabirabe.
Reka nje kugura umukate.
Reka ndabirabe.
Reka tugure ivyo.
Tugende ku gituro c'igari ya moshi tugure amatike.
Abavyeyi banyu baracariho?
Uba ngaha?
Aba ngaha?
Urigisha?
Uriga igifaransa?
Kunda umwansi wawe.
Urukundo rurahuma.
Urukundo rurahuma.
Hagupfa wozanzama.
Ikimuga gisumba imva.
Haguta isoni wotuma upfa.
Subira gusoma.
Soma!
Hogi, hoji!
Hogi!
Ugurura idirisha.
Ugara idirisha!
Ugara idirisha.
Kora ibikorwa vyawe vy'ishure.
Ruhuka!
Subira kandi.
Gira ico bakubwiye.
Gira ico ubwiwe.
Gira ico umuntu akubwiye.
Bandanya!
Komeza!
Shishikara!
Magdalena na Ania ni abagenzi pfampfe.
Urarikunda?
Urayikunda?
Ntibamuriha ku kwezi ahubwo ku munsi.
Bavuga ko atunze cane.
Mariya ahitana Tom ku gituro c'igari ya moshi.
Mariya atora Tom ku gituro c'igari ya moshi.
Sinshobora kugira vyinshi gusumba ivyo.
Sindashira akayabagu.
Musazanje ntari i muhira.
Musazanje siho ari.
Mpora mesura isutiye yanje n'amaboko.
Abavyeyi banje bampamagara kira munsi.
Mushiki wanje yoga ningoga.
Nyogokuru avuga buhoro buhoro.
Ipantalo yanje yajovye.
Inzu yanje iri hafi y'inyubakwa yo gusengeramwo.
Inzu yanje iri hafi y'urusengero.
Uwo tukorana yaciye ansubirira mugihe nari ngwaye.
Ukuboko kwanje kw'ibubamfu kwagize ibinyanya.
Izina ryanje ni John.
Umuhungu wanje yagiye uyu munsi.
Amasobe yanje ntarongorotse.
Data afise imirimo myinshi.
Data ari imuhira.
Data wanje ntari imuhira.
Data wanje ntari imuhira.
Data wanje ntari imuhira.
Data ari imuhira.
Kenshi twagarutse zirayoye.
Ndakunda umuduga wawe.
Ndakunda umuduga wanyu.
Amahera yarampereyeko.
Mize ndababara mu muhogo.
Ndacababara ivi gatoya.
Hagati y'igisigara hadutse umuriro.
Ushaka ko ndagusigira irangi ku nzara zawe?
Urashaka ko nza?
Urashaka ko tujana?
Urashaka ikintu co kunywa?
Urashaka ikintu co kunywa?
Urashaka kwinjira?
Mbwirizwa kwugurura idirisha?
Maze kuduga aka gasozi niruka, ugusemagurika ni kwose.
Banze imbere, ndakurikira.
Rengane, ndakurikira.
Oya, urakoze.
Ntanumwe yavuze ijambo.
Ntanumwe yumviriza.
Nta numwe ahari!
Ntanumwe azi izina ryiwe.
Ntanumwe arazi igituma.
Ntanumwe arazi imvo.
Ntanumwe arazi aho turi.
Itonde.
Akira amahera.
Akira kimwe.
Njana.
Akira ico ushaka.
Fata ico wipfuza.
Murakoze cane kandi.
Yagiye kw'ishure naho yararwaye.
Ntimwugurure idirisha.
Ntimwugurure idirisha.
Twugurure idirisha!
Utahari sico kimwe.
Oh, mpore.
Mu buseruko bw'ikigwati hari ikiyaga.
Itonde!
Raba neza iyo uja.
Muragaba k'umutwe wanyu.
Muritwararikire umutwe wanyu.
Urateganya kugenda mu nama?
Va mu buriri bwanje!
Sohoka mu cumba canje!
Va mu cumba canje!
Mpamagara hagati y'isaha imwe n'isaha zibiri.
Mubwire ko narwaye.
Bivuge mu gifaransa.
Babarire ivyashitse.
Babwire ivyashitse.
Murabe.
Nturabeyo.
Nturoreyo.
Nturabe munsi.
Ni murabe neza iri foto.
Ntundungike.
Ugara amadirisha yose.
Ugara idirisha.
Ku bwawe ni vyiza.
Kuri wewe ni vyiza.
Murabona iyi mitumba?
Murabona iyi nzu? Ni inzu yanje.
Ni murabe neza iri foto.
Murabona iyi nzu? Ni inzu yanje.
Korera iciza ababanka.
Ntushavure!
Numa!
Raba neza!
Ntimukeneye gunkengurukira.
Arakeneye amazi.
Bafungura ifi.
Aragenda ku maguru.
Bashize amazi y'icayi ku ziko.
Ntimuzi namba ivyashitse, canke?
Ntibafise amahera.
Bankana urunuka.
Ntiyasomaye iki gitabo.
Afise ibitabo amajana n'amajana.
Yataye urupfunguzo rw'umuduga wiwe.
Yamoye umutwe wiwe.
Raba neza!
Raba ico neza.
Raba iyi foto.
Raba hariya!
Arafasha nyina wiwe rimwe rimwe.
Aratabara nyina wiwe rimwe rimwe.
Nturabe hasi.
Nturabe munsi.
Urabona iyi mitumba?
Urabona iyi nzu? Ni inzu yanje.
Urabona iyi nzu? Ni rwanje.
Urabibonye?
Afise imyaka yiwe incuro zibiri.
Ni umunyeshuri mwiza.
Ni intore.
Ni umufaransa.
Yamugomwe.
Siho ari.
Nta nda afise.
Ntiyibungenze.
Afise inda.
Aribungenze.
Ntashobora kubika ibanga.
Ntashobora kugumya ibanga.
Baranzi.
Baratuzi.
Ntanzi.
Ariko arateka amagi mu gikoni.
Ntibaza uyu munsi.
Ntibaza uyu munsi.
Ngirango azoza ejo.
Ngirango araza.
Ntibishoboka ko vyose biba bibi.
Ntibabana.
Arakunda gusoma ibitabo.
Ntibakunezereza.
Aramukunda.
Mubwizwa gumperekeza.
Asa na nyina.
Asa na nyina wiwe.
Ni abavukanyi.
Baravukana.
Muri beza cane gwose.
Ni beza cane gwose.
Yigira nk'uwurwaye.
Yatetse umutaga wose.
Yama ata mobile yiwe.
Ntibavyumva.
Aramutegera.
Aramwumva.
Kera yari umwigisha.
Bazomenya uko bagira.
Barabizi.
Ndibaza ko babizi.
Ntaco babiziko.
Ntavyo bazi.
Abana na we.
Abana na we.
Ntibabana.
Bashaka ko tubigira.
Bashaka ko tubikora.
Ntibashaka ko tubimenya.
Yakuriye kwa nyirakuru.
Yarerewe kwa nyirakuru.
Yarukiye kwa nyirakuru.
Ni abanyamerika?
Birakwiye vyose ivyerekeye vy'urugendo?
Birakwiye vyose ivy'urugendo?
Bose bameze kumwe?
Bose bateye kumwe?
Vyose ni bimwe?
Abo nabo mu bujapani?
Abo ni abajapani?
Ni inyoni nziza cane.
Nuko rero nabigize.
Niko bimeze.
Siko bimeze.
Duteka umuceri uku.
Tujane?
Nimusohoke mu muduga.
Urira mu muduga.
Egeka imeza ku ruhome.
Shira imeza yo gukora ku ruhome.
Egeka ingazi ku ruhome.
Urakunda kwiga?
Muraturondera?
Nivyo urondera?
Ubironderera aha?
Ubironderera ngaha?
Urondera ibi aha?
Ubironderera ngaha?
Urandondera?
Ni twebwe murondera?
Tom ni umubaji.
Ntubinywe!
Kore igikenewe.
Uracababara ku kuguru kwawe kw'ibubamfu?
Ibitwazi vyacu birarushe.
Urugendo rwacu ruvana n'igihe.
Urigisha?
Muri kino gisomwa ca umurongo munsi y'amavuga yose ya kazoza muri.
Vyibagire!
Vyibagire ivyo.
Ntiwibagire gutwara ibaruwa.
Ntiwibagire gutwara ikete.
Ntiwibagire gutwara ibaruwa.
Ntutwibagira!
Ntumpebe.
Urabinyemereye?
Indahiro ni ideni.
Ntimubitegera?
Ntimubitegeye?
Murategera igifaransa?
Urabitegera?
Ntimubitegera?
Ntimubitegeye?
Murategera igifaransa?
Gerageza kuryama ubu!
Ibiti vyinshi vyararandutse.
Abantu benshi bagiye.
Urakenuye cane!
Urakoze cane!
Urakoze cane.
Ngirango ntanezerewe.
Ngirango araza uyu munsi.
Ngirango araza.
Ngirango ntaza.
Ngirango dushobora kujana mu nkengera y'ikiyaga iyi mpera y'indwi.
Ngirango ntubikunda.
Ngirango Laura yari arwaye.
Kuva ejo dushobora kujana ku kazi.
Sintegera ibintu nk'ivyo.
Iyi nomero ya terefone ni iyande?
Itonde!
Nimuduhitemwo!
Nimudutore!
Ugenda ryari?
Ni ryari uheruka gutamba ubwanyuma?
Uheruka gutamba ubwanyuma ryari?
Uza imuhira ryari?
Uzoza iwawe ryari?
Utaha ryari?
Uza imuhira ryari?
Wiga ryari?
Ushaka kugenda ryari?
Uhaguruka ryari?
Uvyuka ryari?
Rindira musazawe.
Rindira mwenewanyu.
Rindira mushikawe.
Rindira hariya.
Kubera iki ataco uronka?
Kubera iki uburiramwo?
Kubera iki utaha zirayoye?
Kubera iki ndi ngaha?
Kubera iki utari kumwe na jewe?
Kubera iki utariyo?
Kubera iki ufise agahinda?
Kubera iki wijiriwe?
Kubera iki wibaza ivyo?
Kubera iki wibaza uko?
Kubera iki ubimbwira ubu?
Kubera iki mumbaza?
Kubera iki ubaza?
Kubera iki mumbaza?
Kubera iki tudataha imuhira?
Kubera iki tutaja imuhira?
Kubera iki ataho tutajana?
Kubera iki ujaho?
Kubera iki udataha?
Kuki utaja imuhira?
Kubera iki mwabeshe mu vyerekeye imyaka yanyu?
Kubera iki ufise ico?
Kubera iki ufise ivyo?
Kubera iki uretse?
Kubera iki utumviriza?
Kubera iki ijuru risa n'ubururu?
Kubera iki aha?
Kubera iki harashushe?
Kubera iki udashobora kuronka na kimwe?
Kubera iki bataza?
Kubera iki unkunda?
Kubera iki babikora?
Kubera iki tugira ivyo?
Kubera iki ubikora?
Kubera iki utabikora?
Kubera iki abantu batankunda?
Kubera iki mbwirizwa kubikora?
Kubera iki mbwirizwa kubikora?
Kubera iki mbwirizwa kugenda.
Kubera iki abantu bavuga ivyo?
Kubera iki bavuga ivyo?
Kubera iki ubivuga?
Kubera iki uvuga ivyo?
Kubera iki tutabiraba?
Kubera iki muri imuhira?
Kubera iki tuticara?
Kubera iki bari aha?
Kubera iki nobesha?
Kubera iki wiga muri kaminuza?
Kubera iki utaciga igifaransa?
Kubera iki mbikora?
Kubera iki tugira ivyo?
Kubera iki utabikora?
Ubibwiwe n'iki?
Ni igiki gituma abantu bagira uko ivyo?
Ni igiki gituma abantu bagira uko ivyo?
Wiyumvira iki?
Iciyumviro nyabaki!
Ni umunsi!
Wari umunsi!
Hariko haba iki hariya epfo?
Wibaza ko ico ariki?
Ubifata gute?
Wiyumviye iki?
Ubibona gute?
Itandukaniro ni irihe?
Igituma c'urugendo rwanyu ni nyabaki?
Intumbero y'urugendo rwanyu ni iyihe?
Nibiki bibaye ngaha?
Mwashikiwe niki ejo ku mugoroba?
Urukundo ni iki?
Umuduga wanyu wabaye iki?
Umuduga wanyu wabaye iki?
Ushoboye iki?
Bigurwa angahe?
Kigurwa angahe?
Ni igiciro giki?
Uriko usoma iki?
Bakora iki ngaha?
Mukora iki?
Ukora iki ngaha?
Ashaka kuvuga iki?
Munywa iki?
Wipfuza iki?
Ushaka kubimenya iki?
Uteganya iki ku mpera z'indwi?
Ubona iki hanze?
Uraba iki?
Ubona iki?
Mbe nambare iki - ipantalo canke ijipo?
Ukora iki ngaha?
Ukora iki, data?
Ni igiki ntategera?
Tuzobabwira iki?
Urashaka kuraba iki?
Udushakako iki?
Ni igiki kizohinduka?
Muzi iki ku vyashitse?
Muzi iki ku vyabaye?
Ntashobora kuza kubera ko ararwaye.
Arazi ko umukunda?
Arazi ko umukunda?
Urabizi?
Hari ico ubizi ko?
Ntuzi icarico?
Urategera ivyanditse ngaha?
Urazi ico ubaza?
Urazi ico ubwirizwa gukora?
Urazi ico ubwirizwa kugira?
Urazi ico yavuze?
Urazi ico bavuze?
Uyu munsi ni ku wa kangahe?
Urazi nyene uyu muduga?
Urazi nyene uyu muduga?
Urazi nyene uyu muduga?
Urazi ingene bisa?
Urazi aho arihe?
Urazi aho aba?
Urazi aho arihe?
Urazi aho bari?
Urazi aho aba?
Tom arazi igituma?
Mukunda gusoma ubwoko bw'ibitabo ibihe?
Mukeneye imfashanyo nyabaki?
Ni ibiki bifatanye n'akazi kawe?
Ni ibiki bijanye n'akazi kawe?
Vyerekeye akazi kawe.
Dufise umunsi uyuhe?
Uyu munsi ni ku wa kangahe?
Ibishasha ni ibihe?
Igishasha ni ikihe?
Iki kinyamakuru ni icande?
Ni vyaba atarivyo, ni umubeshi.
Ufise bazoka mu kanwa, yicire.
Utagavye uzovuna amagufa.
Utumvise, baza.
Iyo azakugira umwanya yari kugenda.
Nzogira amagara meza vuba?
Nzokira bidatevye?
Wibaza ko ndi nde?
Uwutwenga inkovu ntazi uruguma.
Ninde yabirekuye?
Ninde yabirekuye?
Ninde yabitangiye uruhusha?
Ninde yabirekuye?
Umwigisha wanyu ni nde?
Umwigisha wanyu ni nde?
Ninde ataza?
Ninde asoma?
Abo bandi ni bande?
Muri bande kandi?
Ninde ashaka kugenda ubwambere?
Ninde yari abizi?
Iyi nzoga ni iyande?
"Aya marori ni ayande?" – "Nyeneyo ni Data."
Iki gitabo kiri ku meza ni icande?
Ibi biro ni ivyande?
Ikosa ni iryande?
Iri kosa ni iryande?
Iri saho ni irya nde?
Iri terefone ni iryande?
Iki ciyumviro cari icande?
Iyi koti ni iyande?
Iyi pizza ni iyande?
Uyu mupira ni uwande?
Ikosa ni iryande?
Iki cayi ni icande?
Iri terefone ni iryande?
Uyu muvinyu ni uwande?
Iki kinyamakuru ni icande?
Ufise imyaka ingahe?
Afise imyaka ingahe?
Afise imyaka ingana iki?
Ivyo bitera ishavu!
Biraca intege.
Biravuna intege.
Vyabaye akavunamutima.
So wawe amerewe gute?
Umuryango umerewe gute?
Bite uyu munsi?
Biragenda?
Imuhira bite?
Witwa nde?
Witwa ngwiki?
Yitwa nde?
Yitwa ngwiki?
Yitwa ngwiki kandi?
Ifagitiri ringana gute?
Uza imuhira gute?
Ugenda kw'ishure gute?
Bimara igihe kingana gute?
Bimara umwanya ungana gute?
Tumara uwanya ungana iki aha?
Amaze igihe kingana iki arwaye?
Ushaka kukigumya igihe kingana iki?
Akajambo murekarengane ni akahe?
Ni bibi gute?
Usa gute?
Kubera iki tutaja imuhira?
Kubera iki ijuru risa n'ubururu?
Kubera iki harashushe?
Kubera iki utazanana na twe?
Kubera iki utazanana na twebwe?
Kubera iki bari aha?
Kubera iki nobesha?
Kigurwa angahe?
Ni angahe?
Dufise igihe kingana iki?
Dufise umwanya ungana iki?
Igikombe c'icayi cokugwa neza?
Ubibona gute ku wagatanu?
Bite, ico kunywa?
Kaze iwacu!
Urashaka kureka?
Urabishaka canke?
Urashaka ko nza?
Urashaka kubibona?
Urabishaka canke?
Urashaka kumenya igituma?
Twese dufise imiryango.
Turagumanye.
Turi kumwe.
Tuzova ngaha ejo.
Turabasororeye.
Tujana twese hamwe.
Twiga mw'isomero rimwe.
Turaja ku burengero.
Turajana.
Twagenze inzira ndende.
Inyuma yacu hari urugendo runini.
Turafise ibintu vyinshi tuvugana.
Nta mahera tugifise.
Ntidufise amahera.
Twatandukanye.
Twavanye.
Twabirahiye.
Twasezeye.
Turazi igituma.
Turakuzi.
Turamuzi.
Ntiducana uwaka.
Durashobora guhurira.
Durashobora kubonana.
Twojana.
Twoshobora kujana.
Turiga igifaransa.
Turagukunda.
Tuzongera mu ndwi iza.
Ntidukunda iyi nzu.
Tubwirizwa kureka guhura uko.
Tubwirizwa kubitunganya ningoga.
Tubwirizwa gushira uburinganire hagati y'bisohoka n'ivyinjira.
Ntaco tugiheraniye.
Turabonanirayo.
Turahurirayo.
Tuzobonana mu kwezi kw'icumi.
Tuzongera mu ndwi iza.
Turabonana.
Twashitse.
Ni mwenewacu.
Turavukana.
Twaje kugusura.
Twaje kukubona.
Twaje kukuraba.
Twiga mw'isomero rimwe.
Ntituri twenyene.
Turanezerewe cane.
Turi abanyeshuri ba kaminuza.
Turagarutse.
Turi imuhira.
Turagarutse.
Twarukiye hamwe.
Turi magara make.
Turabwirizwe gufungura ku mutaga hamwe.
Turakwiye gufungura ku mutaga hamwe.
Twama dukina ku munsi w'Imana.
Tubivugana igihe cose.
Uzogaruka ku wa kabiri?
Turageramiwe.
Nawe turagukumbuye.
Turumvikana.
Ntitwumva igifaransa.
Turategera.
Turumva.
Turumvikana.
Tuzobishobora.
Tuzotunga.
Tubiteze amaso.
Turabizi.
Ntitubizi.
Turazi igituma.
Turazi imvo.
Tuba hariya.
Dushaka ko ubitwara.
Dushaka agahembo gasumvye.
Dushaka agahembo karusha.
Dushaka akarusho.
Dushaka wewe gusa.
Niwewe dushaka gusa.
Murazi aho mba?
Bagutwaraye hehe?
Mudutwaye hehe?
Mudutwaye hehe?
Mugenda hehe?
Mugenda hehe?
Mumuzi hehe?
Uzi izina ryanje hehe?
Ubikuye hehe?
Mugenda hehe?
Tuja hehe?
Urora hehe?
Mugenda hehe?
Ushaka kuja hehe?
Baba iwawe?
Uba ngaha?
Aba ngaha?
Igitabo kirihe?
Amahera arihe?
Umuduga wawe urihe?
Nyoko arihe?
Ishure ryawe ririhe?
Uba he?
Umuryango wiwe urihe?
Umuduga wanje urihe?
Mama arihe?
Amahera yanje ari hehe?
Tom arihe?
Muvahe?
Uva hehe?
Nsubiza iki gitabo hehe?
Baba hehe?
Murashaka kubitwara?
Ntimushaka kumenya igituma?
Turashaka kujana hamwe ku gituro c'igari ya moshi?
Murashaka kubitora?
Murashaka kubitwara?
Ntimushaka kumenya ivyabaye?
Ntimushaka kumenya ivyashitse?
Ushaka kuba hehe?
Wahagaritse umuduga hehe?
Wiyumvira iki?
Ashaka gushika kuki?
Ashaka kuvuga iki?
Ibintu vyawe birihe?
Abantu bose bagiye hehe?
Ibirato birihe?
Muri hehe uyu munsi?
Turi hehe?
Akinirahe?
Wigahe?
Uba he?
Sekuru wabo aba hehe?
Sekuru wabo aba hehe?
Iki kintu kimaze iki?
Ntiwari ubizi?
Hitamwo inomero.
Ntimutore inomero.
Nimukure ibirato vyanyu.
Nimwambure ibirato vyanyu.
Nabanje kwandika vyose mu gatabo kanje.
Ntumbwirize kubikora.
Ntumpate kubikora.
