Urazi aho arihe?
Izuba rirasira mu buseruko.
Sinshaka kurora.
Gira ico bakubwiye.
Ndi umwigisha.
Ndacababara ivi gatoya.
Siyo mvo.
Ntihahita.
Ndashobora kugutegera.
Ndamanikwa impuzu.
Tumara uwanya ungana iki aha?
Ndabitwara.
Yagiye kw'ishure naho yararwaye.
Kubera iki mumbaza?
Urazi aho bari?
Nguyo araje!
Ntimuzi namba ivyashitse, canke?
Wibaza ko ndi nde?
Nyene uyu muduga ni data wanje.
Mbwirizwa kubifata uko biri.
Ubwirizwa kuvyakira.
Ntidufise amahera.
Uyu mupira ni uwande?
Ndibaza, icamubayeko.
Bagutwaraye hehe?
Turazi igituma.
Sinshonje.
Yarerewe kwa nyirakuru.
Ipantaro ntinkwira. Ndashobora kuyiguza?
Waciye ku kimenyetso gitukura.
Biravuna intege.
Shira imeza yo gukora ku ruhome.
Bakora iki ngaha?
Turi imuhira.
Bankana urunuka.
Ntaco ndabirabamwo.
Pima.
Woba ufise akanya ko kumfasha ikintu?
Naje kukurondera.
Erekana itike!
Aho ufungura ku mugoroba sindabinzwe.
Kubera iki bavuga ivyo?
Yabanze izuru ryiwe kw'idirisha.
Sinteka.
Umuhungu wanje yagiye uyu munsi.
Uhaguruka ryari?
Uba ngaha, sivyo?
Ashaka gushika kuki?
Ndazi uvyirumvira.
Ni igihe co kuruhuka gatoya.
Arazi ko umukunda?
Turabonana.
Sinzi ico novyiyumvirako.
Imana iguhezagire!
Vyumvikana ukuntu.
Yitwa nde?
Ndazi ico nkora.
Nturabe munsi.
Uteganya iki ku mpera z'indwi?
Ngirango ntanezerewe.
Ntanumwe yakubajije.
Sinshaka kubisoma.
Murashaka kubitora?
Nshika iwawe isaha zibiri.
Uramukiwe.
Naragukunda.
Ntimushaka kumenya ivyabaye?
Narinzi ko bigushimisha.
Ntimubitegeye?
Umuryango umerewe gute?
Sindashaka kurwara.
Ushaka kuja hehe?
Ico sico gituma.
Umubaji arapima ikirere.
Biramuraba.
Urazi ico yavuze?
Tubwire ivyo mugira ubu.
Murabona iyi nzu? Ni inzu yanje.
Ndazi iyo mbwirizwa kuja.
Reka kunsomboroza kubivuga.
Ndakunda imishatsi migufi.
Reka ndagitumeko.
Ntashobora kugumya ibanga.
Tubivugana igihe cose.
Ku bwawe ni vyiza.
Hogi!
Ibitwazi vyacu birarushe.
Nazanwe no kwiga.
Sohoka mu cumba canje!
Nariye amagi ejo.
Mwebwe babiri ni muzanane nanje.
Umusumakazi amaze kubona umuporisi yaciye atungwa n'ayo yameze.
Ni birebire birenze?
Asa na nyina.
Ntimubitegeye?
Bite!
Simbizi.
Ntanzi.
Ndakuzi kuva kera.
Raba neza iyo uja.
Umudandaza wese arata ibidandazwa vyiwe.
Ndashika mu kanya.
Igishasha ni ikihe?
Shika!
Nyoko niho ari?
Ushaka kubimenya iki?
Ngirango araza.
Harashushe.
Uracambara ikareso imwe?
Reka ndakigure.
Uraza? Ego canke oya?
Ndakunda kuraba ingene uteka.
Ndategera ico ushaka kuvuga.
Kera hari isengero ngaha.
Ntanumwe yarazi ibikenewe kurangurwa.
Uzofata urugendo wenyene?
Dushobora kuganirira ngaha?
Tora ibintu vyawe.
Gerageza kuryama ubu!
Arumva igifaransa.
Ndazi uyo mukobwa.
Bizogushimisha.
Ndashika isaha zine.
Jabuka ibarabara.
Ndarahiye.
Si umuduga wanje.
Ibitungwa ntibirekuriwe.
Ntanumwe arazi igituma.
Nzomoka.
Mbe nagomwe?
Ndi mu gikoni.
Sindashira akayabagu.
Nzero ni ukwezi kwambere mu mwaka.
Baranzi.
Nturabe munsi.
Ukora iki, data?
Bimara umwanya ungana gute?
Njana.
Ndiga igifaransa imuhira.
Raba ico neza.
Biragenda?
Uzoza iwawe ryari?
Nta kamaro!
Iyi pizza ni iyande?
Mbabarira, izina ryawe ni nde?
Ingo!
Baratuzi.
Urashobora gutora irangi iryariryo ryose rigushimisha.
Ineza ihimbara abantu gusumba ubwiza?
Kubera iki tutabiraba?
Ndaje munsi.
Ingo!
Nzigora.
Naramuhaye igitabo.
Ico gisa n'ivu ni rwanje.
Iri terefone ni iryande?
Nta nsiguro bikeneye.
Fata iyi nzira.
Ndafise amahera yawe.
Amahera yaheze.
Sinzi iyo ndibuje.
Ntibaza uyu munsi.
Iri saho ni irya nde?
Kubera iki wibaza uko?
Mfise mukuruwanje.
Ubifata gute?
Nshobora kutumako kimwe?
Ubigerageze.
Ndasaze.
Nimushike.
Haraho uzogenda muri iri ci?
Ntutegerejwe kuza.
Inzoka yamize igikere.
Ninde ashaka kugenda ubwambere?
Warasomye ico gitabo mperuka kukugurana vuba.
Nzovyitaho.
Ntuzoza, sivyo?
Nta nda afise.
Iciyumviro nyabaki!
Amahera narayakiriye.
Ushaka ko ndagusigira irangi ku nzara zawe?
Ntadukunda.
Eh, ushaka kuja hehe?
Urakoze cane.
Urabona iyi nzu? Ni inzu yanje.
Kigurwa angahe?
Tubwirizwa gushira uburinganire hagati y'bisohoka n'ivyinjira.
Urazi kubigira neza cane.
Ntitwumva igifaransa.
Ntivyapfuye.
Ndamukunda.
Abana bagiye kw ishure?
Ingo kunsura.
Oya, urakoze.
Igikorwa cawe kizoba ico kwigisha abakozi ubuhinga bwa ordinateri.
Utahari sico kimwe.
Ndamubonye.
Yitwa ngwiki?
Ndarurumba.
Sindamubona.
Ni abavukanyi.
Raba neza ingene ndabikora!
Yabanze izuru kw'idirisha.
Simfise amahera.
Harashushe birenze.
Ntaco nywa.
Navyiyumviye.
Urigisha?
Ntumpebe.
Nkura ngaha.
Yagarutse ino.
Wabishoboye.
Nturabeyo.
Gira ico umuntu akubwiye.
Turazananye.
Niko bimeze.
Nzogerageza.
Nzofata umunsi w'akaruhuko.
Kubera iki utaha zirayoye?
Urazi nyene uyu muduga?
Murategera igifaransa?
Nshaka ko mubibona.
Birakwiye.
Ntiwakomye kw'isahani yawe na gato. Hari akakubakiye?
Ni binini birenze?
Mu mwaka uheze navyaye imfura yanje.
Reka kwishima ata soni!
Urazi ico ubaza?
Turagumanye.
Ufise imyaka ingahe?
Mu buseruko bw'ikigwati hari ikiyaga.
Ntimushobora gufatira kuri ivyo.
Muvahe?
Ni rwacu.
Ndagufitiye amahera.
Sinzi neza igifaransa.
Dushaka agahembo gasumvye.
Umwigisha wanyu ni nde?
Turagarutse.
Urashobora kurungika umuntu ngo abikiranure mu maguru masha?
Ngiye guzana umuduga wanje.
Ndiko ndasohotse.
Ico gitabo ndagifise nanje.
Ntumbwirize kubikora.
Sintegera gute.
Dushaka wewe gusa.
Akazi kagenda buhoro buhoro kubera ko abakozi babuze.
Kubera iki nobesha?
Naratakaje ikaramu ryanje.
Tuzotunga.
Igituro ca bisi kiri iminota itanu uvuye ngaha.
Sinzi iyo ngana.
Ntibakunezereza.
Kubera iki ubikora?
Biraca intege.
Mfise abakobwa batatu.
Ivyo bitera ishavu!
Mubwire ko narwaye.
Nimwihute.
Urabinyemereye?
Ndi umunyeshuri mushaha muri kaminuza.
Kubera iki babikora?
Sindi ikijuju.
Ngiyo ifagitiri.
Ushaka kuzobiraba.
Ndi mu karuhuko.
Ni birebire birenze.
Turabonanirayo.
Uzomukunda.
Vyose bifise urubibe.
Ndamuzi?
Ndazi aho ari.
Tuzongera mu ndwi iza.
Nshaka ko ubimenya.
Twashitse.
Raba neza!
Sindashaka kuba ngaha.
Uyu munsi hari ibicu vyinshi.
Kubera iki utazanana na twebwe?
Turategera.
Ni igiciro giki?
Ngirango Laura yari arwaye.
Ikiganza gifise intoki zitanu: urukumu, inkombarukoko, msumba zose, igihugunibenga, agahererezi.
Singifise umushikiwanje n'umwe.
Ni akazi kiwe.
Ndaruta umugenzi.
Asa na nyina wiwe.
Ndi mu nzira yaho.
Sinshobora kwoza amasahani. Harakenye amazi.
Mbwirizwa kwugurura idirisha?
Hari ico ubizi ko?
Ndiko mpumura.
Nshaka kwiga igifaransa.
Akira kimwe.
Muzovyigaya cane.
Nta gituma co kugira umutima uhagaze.
Sinsa uko.
Ndabiraba.
Uranhunga ko ndabivuze.
Hari imashini yo kumesura mu nzu?
Ndazi aba bagore.
Ngirango dushobora kujana mu nkengera y'ikiyaga iyi mpera y'indwi.
Ewe ga, urya mushatsi ni uwande?
Wari umunsi!
Nirukiye kwa mama.
Ntidukunda iyi nzu.
Urashaka kugendaho?
Nyene ikintu ni musazanje.
Ariko arateka amagi mu gikoni.
Asa na nyina wiwe.
Umuntu wese arashobora kubisoma.
Ndazi neza ko namubonye ahantu ikindi gihe.
Mugenda hehe?
Ndazi aho mbwirizwa kugaba.
Ndibaza ko ntegeye.
Aramutegera.
Mpore cane!
Sinzi gute.
Fata ico wipfuza.
Ndazi ico nokora.
Bandanya!
Sindavyumva.
Uri inda nsa.
Aya ni amadolari atanu.
Hari akakubakiye.
Igiciro ni amajana atatu, si abiri.
Ndakunda umuryango wanje.
Uyu munsi ni ku wa kangahe?
Ubona iki hanze?
Urakunda kwiga?
Reka nje kugura umukate.
Ntibaza uyu munsi.
Ngico igitabo cawe.
Arakunda gusoma ibitabo.
Nimukure ibirato vyanyu.
Twaje kugusura.
Sindi umunyeshuri muri kaminuza.
Honja!
Mbwirizwa kureka.
Amadirisha araguruye.
Komeza!
Banze imbere, ndakurikira.
Ndi umutetsi.
Uri umugore nkunda.
Akajambo murekarengane ni akahe?
Data wanje ntari imuhira.
Reka ndakugwe mu nda.
Ntumpebe.
Ntubwirizwa kwandika ikete rirerire.
Ntanumwe azi izina ryiwe.
Nzokuraba.
Tuba hariya.
Wasomye iki gitabo?
Urabishaka canke?
Ndakunda imishatsi migufi.
Murakoze kwumviriza.
Mbwirizwa kwiyumvira.
Rengane, ndakurikira.
Ninde yabirekuye?
Urakomeye vy'ukuri?
Akabare karabasorereye.
Niwewe dushaka gusa.
Umwigisha wanyu ni nde?
Itonde.
Ndashobora kubaza ico vyerekeye?
Reka tugure ivyo.
Kubera iki utabikora?
Ntibikora.
Urategera ivyanditse ngaha?
Urashaka ikintu co kunywa?
Sinzi aho muba.
Iki cayi ni icande?
Tuzongera mu ndwi iza.
Ndakunda gukora ngaha.
Kubera iki aha?
Umuryango wiwe urihe?
Mubwirizwa gutaha.
Aya madirisha aherereye mu bumanuko.
Hogi, hoji!
Maze kuduga aka gasozi niruka, ugusemagurika ni kwose.
Ubwirizwa guheba inzoga.
Ndi umunyeshuri muri kaminuza.
Ndi jenyene.
Nico gituma cakuzanye ngaha?
Inzovu zirya ivyatsi.
Uzosubira vuba gukomera.
Ihinguriro rikora ibihumbi n'ibihumbi vy'amacupa kira kwezi.
Nta gituma kihari co kugira ubwoba.
Ubwirizwa kwumviriza.
Ntimukeneye gunkengurukira.
Urazi aho nzoba ndi.
Ni murabe neza iri foto.
Ntaho dusa dusaniye n'ivyo bintu.
Yaje wenyene.
Wagomwe.
Reka kubaza!
Rindira mwenewanyu.
Ndipfuza kuba umugenzi wawe.
Va mu cumba canje!
Ntibimeze uko uvyiyumvira.
Nzoza kugutora.
Mfise mukuruwanje.
Ugara idirisha.
Si umunsi wanje.
Ntiwibagire gutwara ikete.
Tuzobishobora.
Ngurisha impuzu ku murongo.
Urashaka ko nza?
Amadirisha ari umwanda.
Mfise umuhora.
Nzobiguha.
Ni birebire birenze urugero.
Sinzi iyo ngana.
Nzero, Ruruhuma, Ntwarante, Ndamukiza, Rusama, Ruheshi, Mukakaro, Myandagaro, Nyakanga, Gitugutu, Munyonyo na Kigarama ni amezi icumi n'abiri y'umwaka.
Mba muri Noroveje ubu.
Sico kimwe.
Ni igiki kizohinduka?
Iyi nyabu ni yanje.
Urazi bano bantu.
Bose bavuga ngo nabaye intwari, ariko naranguye igikorwa canje gusa.
Reka ndabe.
Nashoboye kugira.
Ndabiraba.
Simbikeneye.
Ni inyoni nziza cane.
Reka.
Ni bibi gute?
Ntibisa neza.
Nta gituma co guhagarika umutima.
Kubera iki utumviriza?
Ninde yari abizi?
Ntunga!
Ntaco babiziko.
Kubera iki tutaja imuhira?
Wavyibajije?
Ndategera ico uvuga.
Iri jambo riva mu kigereki.
Sinywa.
Urazi ko mbwirizwa kugenda.
Uba ngaha, sivyo?
Iki kinyamakuru ni icande?
Nagira ngo niwe ncuti idasumbwa.
Ni igiki gituma abantu bagira uko ivyo?
Sinkomeye muri vyo.
Naje kubera wewe.
Arenza imyaka mirongo itatu.
Za kunsura.
Uri imuhira?
Ntimushaka kumenya ivyashitse?
Uzosubira vuba gukomera.
Ntiwibagire gutwara ibaruwa.
Itandukaniro ni irihe?
Ngaha ntibaba abatunzi.
Ntitubizi.
Ngizo impapuro zanje.
Wipfuza iki?
Reka ndabirabe.
Afise umuduga.
Sinzi guteka.
Vyerekeye akazi kawe.
Nzokira bidatevye?
Turajana.
Iki gisu kirapfushe.
Ntavyo bazi.
Ntanumwe arazi imvo.
Yandungitse.
Rimwe, gatatu no gatanu ni ibiharuro bitagaburwa na kabiri.
Urakoze!
Dufise umunsi uyuhe?
Tanga akaryobwa.
Aramwumva.
Narinzi ko vyogushimisha.
Niwe umugabo mvuga.
Urashobora gusubiramwo?
Kanyemwo!
Kubera iki ijuru risa n'ubururu?
Mbabarire cane!
Sinkunda inzoga.
Kubera iki mbikora?
Haguye amama make y'imvura.
Ayo madirisha yerekeye mu bumanuko.
Aho biri ndanezerewe.
Nabizirikanye.
Ni isaha icenda ibuze iminuta icumi n'itanu.
Kora ibikorwa vyawe vy'ishure.
Turahurirayo.
Abantu bose bagiye hehe?
Mugenda hehe?
Ndakwiyumviye.
Sindabishaka ubu nyene.
Kubera iki wijiriwe?
Yafashe ikinyugunyugu n'urukumu hamwe n'inkombarukoko.
Ndagusavye ubimbwire.
Ikosa ni iryande?
Aba ngaha?
Sinzobikubuza.
Ndavyakira.
Inyoni zirashobora kwimotereza?
Urayikunda?
Uri umunyeshuri mwiza.
Nuko rero nabigize.
Intumbero y'urugendo rwanyu ni iyihe?
Ni birebire birenze.
Bimara igihe kingana gute?
Ntushobora kwama uronka ico wipfuza.
Waravye itelevisiyo uyu mugoroba?
Urakoze cane!
Ntimwugurure idirisha.
Ni ibintu bikunda.
Kubera iki ujaho?
Urafise uwo muvukana?
Narasomye itama ryiwe.
Igihe cawe cashitse.
Ndi imuhira.
Urantegera.
Turashaka kuriha.
Urakoza ko wajanye natwe.
Usa gute?
Kore igikenewe.
Ntuza, sivyo?
Ni umufaransa.
Yama ata mobile yiwe.
Akora mw'ihinguriro.
Navyiyumviye.
Igihe girarenze.
Ngaruke?
Numa!
Umuduga wanyu wabaye iki?
Murabe.
Iyi koti ni iyande?
Iki gikorwa kiramurengeye.
Ntibavyumva.
Izina ryanje ni John.
Ni umunsi!
Bivana n'igihe.
Ndanezerewe ku uhimbawe.
Kira gitondo mva imuhira imbere y'isaha zibiri.
Uyu munsi ni kuwagatatu.
Urambabaje.
Abana bari ibubamfu iruhande y'inzu.
Raba iyi foto.
Rero, dushobora kuganira mu minsi iza, ariko ubu ndiko ndiruka ku kazi.
Ubironderera ngaha?
Umusumakazi abonye umuporisi yaciye yiruka.
Ntiwibagire gutwara ibaruwa.
Igishika co kukubona kigiye kunyica.
Ntusabe amahera.
Kuva ejo dushobora kujana ku kazi.
Kubera iki uvuga ivyo?
Mfise mukuruwanje.
Sindi umunyeshuri.
Biratunganye.
Bimuha.
Tuzova ngaha ejo.
Uyu mwigeme yiyambika nk'umuhungu.
Mubwizwa gumperekeza.
Siko bimeze.
Turamuzi.
Kubera iki mumbaza?
Magdalena na Ania ni abagenzi pfampfe.
Bavuga ko atunze cane.
Ndemanze ikosa ryanje.
Ndazi ko ubifise.
Yafashe umunsi umwe w'uburuhuko.
Nzogaruka mu gihe.
Ndazi Tom?
Ninde yabirekuye?
Nshobora kwicara hirya?
Wiyumvira iki?
Si vyiza.
Woba ufise akanya?
Ku bwanje harakanye birengeye.
Icumba ni ciza.
Birumvikana.
Turabwirizwe gufungura ku mutaga hamwe.
Arakeneye amazi.
Ntuzi icarico?
Izuba rindasira mu maso.
Ndakuzi.
Abana na we.
Iri terefone ni iryande?
Ni nk'umuvandimwe.
Ndakwumviriza.
Ndiko ndashinguka.
Urora hehe?
Wagize ubwoba?
Umuduga wanje urihe?
Ngirango ntaza.
Mukora iki?
Hariko haba iki hariya epfo?
Umubaji arapima isi.
Igikombe c'icayi cokugwa neza?
Sinzi igihe uko kingana.
Watinye?
Ayo mashurwe ubona ni amarosi.
Nimudutore!
Muritwararikire umutwe wanyu.
Uranzi.
Ni igitabo c'agatangaza.
Ndakunda kubikora.
Ni umunyeshuri mwiza.
Nzokunezereza.
Nshaka kubibona.
Sinumva igifaransa.
Ndafise ikibazo.
Nta ngorane.
Ntituri twenyene.
Umviriza!
Ni bitoya birenze urugero.
Ntumpate kubikora.
Nta kamaro.
Nimugende kandi.
Ejo hari kuwagatanu.
Aratabara nyina wiwe rimwe rimwe.
Ndanezerewe kukubona.
Urugendo rwacu ruvana n'igihe.
Mbabarira ko nagutaye mu rudubi.
Kuri wewe ni vyiza.
Turakwiye gufungura ku mutaga hamwe.
Ico nico uriko urondera?
Natanguye gukora muri ino societé kuva umwaka uheze.
Nabanje kwandika vyose mu gatabo kanje.
Murashobora kwugurura idirisha?
Mpa ikintu co kunywa.
Ururuka!
Uyu mwigeme asa neza.
Sinzoreka.
Ntumwumvirize.
Kubera iki utariyo?
Ndi umunyeshuri muri kaminuza.
Abana na we.
Twojana.
Urukundo ni iki?
Urazi gutandukanya intama n'impene?
Murategera igifaransa?
Bivuge mu gifaransa.
Murashaka kubitwara?
Igiciro kiraduga.
Ndagukumbuye cane.
Sinashoboye kutarira.
Iri kosa ni iryande?
Kubera iki tugira ivyo?
Nshaka kwicara kw'idirisha.
Kubera iki ataho tutajana?
Birakwiye vyose ivy'urugendo?
Wiyumvira iki?
Mukeneye imfashanyo nyabaki?
Twiga mw'isomero rimwe.
Ubironderera ngaha?
Baba iwawe?
Ntimushobora guhagarika umuduga wanyu ngaha.
Ufise bazoka mu kanwa, yicire.
Tuhavuye tuba twenyene.
Musazanje siho ari.
Ntabaza ico kunywa.
Uyu muduga ni rwanje.
Bingwa neza.
Sabwe!
Emwe ga, uyu mushatsi ni uwande?
Ndarindirira hanze.
Ni angahe?
Ndi mu kiruhuko.
Ni umuntu mwiza.
Hagati y'igisigara hadutse umuriro.
Nzogerageza vyose uko nshoboye.
Nshaka kugenda mu mahanga, akarorero: mu butaliano, muri espanye.
Reka gutanga amategeko ngaha!
Nagira ngo ni ikigorwa cawe.
Uragikunda?
Imuhira bite?
Ushaka kukigumya igihe kingana iki?
Mpore.
Musazanje ntari i muhira.
Ntibafise amahera.
Ntumuhagarike.
Nibiki bibaye ngaha?
Ngico ico mwasavye.
Raba neza!
Mama arihe?
Ndipfuza ikindi gikombe c'ikawa.
Urakoze kuza.
Urarwaye, ubwirizwa kuruhuka.
Ndarorerera hanze.
Bimuha.
Arihanaguye icuya mu maso.
Ibirato birihe?
Sinzorabayo.
Turanezerewe cane.
Simfise imuhira.
Mwebwe muri abana.
Urukundo rurahuma.
Ntibikenewe ko mwinyegeza.
Ntanumwe yakubajije.
Igituma c'urugendo rwanyu ni nyabaki?
Ndashaka kuguherekeza.
Ndazi ibikenewe kurangurwa.
Vyibagire!
Ndakunda ibiharuro.
Turashobora kugira aho tuganirira?
Uba he?
Nguyo arashitse!
Ndashobora kukwumva.
Uriko usoma iki?
Ntunga, mbega witwa nde?
Mudutwaye hehe?
Urafise isahani ipfukuye y'isupu?
Ntimwongere kugaruka.
Sintunze.
Afise imyaka yiwe incuro zibiri.
Ninde yabitangiye uruhusha?
Uzomukunda.
Urupapuru rumwe rurabuze.
Nta mahera mfise.
Ndabitora.
Ndururutse.
Nshobore gusubira kubibona?
Ubwirizwa kureka kunywa.
Urigisha?
Nta gishasha.
Dufise igihe kingana iki?
Asa na mwenewanyu.
Ninde ataza?
Ntimusubire kugaruka.
Ntunezerewe?
Itonde!
Mbirizwa kwiga gifaransa.
Umuntu wese arashobora kubisoma.
Abonye amaraso umurwayi yaciye araba.
Uracababara ku kuguru kwawe kw'ibubamfu?
Aranywa.
Yarukiye kwa nyirakuru.
Bingwa neza kubona tuvugana.
Nabigiriye wewe.
Urashaka ko tujana?
Kubera iki tugira ivyo?
Nguyu!
Nahasanze umugenzi.
Usa na data wawe.
Urabizi?
Urashaka kwinjira?
Ngenda n'umuduga.
Wasize idirisha ryuguruye?
Ngirango azoza ejo.
Meze nabi.
Urakomeye vyo?
Kubera iki mbwirizwa kugenda.
Ntiducana uwaka.
Niwe uramukiwe.
Reka ndaguhobere.
Igihe ntikigize gukanya gusa, kiranajovye.
Ndabigirira kubera wewe.
Urakoze cane!
Ndakunda data.
Subira gusoma.
Bizokugwa neza.
Itonde!
Urabitegera?
Murabona iyi nzu? Ni inzu yanje.
Ndategera ico ushaka kuvuga.
Urashaka ko nza?
Ndatunganya amadirisha.
Intwaro iritwararika cane iki gikorwa.
Ipantalo yanje yajovye.
Urakoze guhita.
Sekuru wabo aba hehe?
Uranezerewe?
Ndiko ndasoma igitabo.
Wiyumviye iki?
Afise ibitabo amajana n'amajana.
Urashaka ikintu co kunywa?
Muri kino gisomwa ca umurongo munsi y'amavuga yose ya kazoza muri.
Kuwagatatu haza birakunda.
Ubibona gute ku wagatanu?
Ubibwiwe n'iki?
Ni umuduga wiwe.
Bigurwa angahe?
Ntubinywe!
Ndategera.
Sinzi icarico.
Uko ni vyiza gusumba?
Ubwirizwa kureka kunywa.
Ndipfuza gutambana nawe.
Ntushobora kubuza ko abantu bavuga.
Nzobijamwo.
Sintegera iri jambo.
Ntegerezwa gutaha.
Ubironderera aha?
Nta batunzi baba ngaha.
Kubera iki ufise agahinda?
Mbwirizwa kukubona.
Nawe turagukumbuye.
Mariya atora Tom ku gituro c'igari ya moshi.
Urandondera?
Gira ico ubwiwe.
Njana i muhira.
Niho ndi!
Nturi musazanje.
Nagira ngo woba watashe.
Ndabitwara.
Ifagitiri ringana gute?
Uragiye nawe?
Ntimuzi namba ivyashitse, canke?
Ndazi igituma ubishaka.
Sindavyipfuza ubu nyene.
Tubiteze amaso.
Ndavyumva
Ni intore.
Ndababonye.
Vyabaye akavunamutima.
Dushobora guhurira hehe?
Babarire ivyashitse.
Uragenda canke ntugenda?
Yakoze yivuye inyuma.
Bireke.
Sinshaka kugira uwo nkomeretsa.
Yacishije igisu ciwe ishami ry'igiti.
Ntanumwe yavuze ijambo.
Zanana!
Uri iwacu?
Tubwirizwa kubitunganya ningoga.
Ni umunyeshuri mwiza.
Umunsi mwiza.
Turi hehe?
Sinzi.
Nandika kuri twebwe.
Fata ico wipfuza.
Ntusubire kumbaza.
Kaze iwacu!
Abantu benshi bagiye.
Ugurura idirisha.
Iminsi yose aja ku kazi ku maguru, kiretse iyo imvura igwa.
Uzi izina ryanje hehe?
Birakwiye?
Ivyo turabizi.
Urafise musazawe?
Uza imuhira ryari?
Jayo ubu nyene.
Arazi ko umukunda?
Bitware hirya.
Reka gutegeka ngaha!
Indahiro ni ideni.
Asa na Se wiwe.
Narinzi ko wojayo.
Sindaheba.
Nico nshaka kumenya.
So wawe amerewe gute?
Sawa, nzogikura.
Turafise ibintu vyinshi tuvugana.
Nuko vyamwe?
Icumba cawe gifise amadirisha abiri?
Nta mvo yo kugira ubwoba.
Nshaka gutaha.
Yataye urupfunguzo rw'umuduga wiwe.
Naguhevye.
Antera kwiyumvira.
Oh, mpore.
Ntiyasomaye iki gitabo.
Twaje kukubona.
Birakwiye vyose ivyerekeye vy'urugendo?
Ndahatswe kumena amasahani.
Nryama ubusa.
Nzikosora.
Ihinguriro rizotangura gukora mu mwaka uza.
Nakwiyumyiye.
Urafise aya mahera?
Kunda umwansi wawe.
Mudutwaye hehe?
Ndakwiyumvira.
Kubera iki bataza?
Sindi umutunzi.
Kubera iki unkunda?
Sinkunda aba bantu.
Soma!
Ndabubaha.
Twugurure idirisha!
Nahisemwo kurwana urwo rugamba.
Mubaze izina ryiwe.
Kera waranywa itabi, sivyo?
Witwa nde?
Ndabakeje!
Ndashobora kubaza ikindi kibazo?
Tugende ku gituro c'igari ya moshi tugure amatike.
Wamenyesheje ivyabaye?
Umuduga wapfuye.
Usa n'umupolisi!
Mvuga ico mfise ku mutima.
Urarikunda?
Hagupfa wozanzama.
Nkora ivyo umuntu ambwira.
Uwo tukorana yaciye ansubirira mugihe nari ngwaye.
Uyu ni mama wawe?
Nagiro ngo niwe ncuti itarutwa.
Bashaka ko tubigira.
Haguta isoni wotuma upfa.
Sinzi iryo jambo.
Murakoze kuza.
Si ikintu co kwirata.
Iki ni igifaransa?
Tuzobabwira iki?
Iki giti kirashaje.
Uruhanga rwawe rurashushe cane. Ndakeeka ko ufise inyonko.
Uremera ko ataco bintwaye?
Niko abantu bavuga.
Ndashobora kubaza iyo bishira?
Yahemutse kw'ijambo!
Uri inda nsa.
Ndi mu karuhuko.
Nzokora ico unsaba.
Akira amahera.
Iki gitabo ni ciza cane.
Umuduga wawe urihe?
Naje kukurondera.
Twama dukina ku munsi w'Imana.
Niga icongereza muri kaminuza.
Utaha ryari?
Murashobora kunyuganga?
Ntubaze.
Ibishasha ni ibihe?
Kenshi twagarutse zirayoye.
Nokora gutyo.
Ibiti vyinshi vyararandutse.
Ugenda ryari?
Kubera iki harashushe?
Ishure riraheze.
Tuzobonana mu kwezi kw'icumi.
Urarurumba.
Akinirahe?
Ntibimpa agateka.
Ndashaka kubihindura.
Ntiyasomaye iki gitabo.
Muraturondera?
Nahabonye mwenewacu.
Umudandaza yaduhaye inshumbushanyo nini.
Ijipo irandenze.
Reka ndabirabe.
Mbabarira!
Hagarika uyo muduga.
Ni bitoya birenze?
Nzomuhamagaza aha.
Durashobora guhurira.
Ndagukeje!
Nururukira ngaha.
Umuhungu arabaza ikibazo.
Afise inda.
Ndazi ko unkunda.
Muri iri kostim ryirabura n'amarori y'izuba usa na umusahuzi.
Umwansi aguye, muvyure.
Ndazi ko ubanga ugutwi.
Murazi aba bantu?
Ndiko nsaza.
Nije nzotangura kwinjira.
Yakarihije igisu.
Munywa iki?
Ukuboko kwanje kw'ibubamfu kwagize ibinyanya.
Uri umunyeshuri mushasha?
Ndamanutse.
Ndanezerewe.
Ndakunda akazi kanje vy'ukuri.
Nababonye.
Sinshaka kugira uwo mbabaza.
Ibi vyicaro bigenewe abantu bashaje n'abarwaye.
Ndagukunda.
Bitebe bitebuke vyose birahera.
Ndarorerera hanze.
Ntibishoboka ko vyose biba bibi.
Turashaka kujana hamwe ku gituro c'igari ya moshi?
Ja hirya.
Nzobitora.
Ikiyaga gifise ibenga rinini?
Mbwirizwa gutunganya imishatsi yanje.
Nshaka ko uja imuhira.
Ubwirizwa kuvyuka.
Iryo jambo ntaryonzi.
Babwire ivyashitse.
Uriga igifaransa?
Dufise umwanya ungana iki?
Sinzi gufata amazina.
Uramfitiye amahera?
Kubera iki bari aha?
Ngico igitabo cawe.
Ntushavure!
Amasobe yanje ntarongorotse.
Ukora kwa nde?
Ntimwugurure idirisha.
Aramukunda.
Kubera iki ndi ngaha?
Umuhungu arasimba.
Ndatembera gato.
Nyoko arihe?
Data ari imuhira.
Ndazi iyo baja.
Ni igiki ntategera?
Bireke.
Wibaza ko ndi nde?
Narinzi ko bikunezereza.
Mpembwa neza.
Sinshaka guheba.
Uri umuhinga.
Ur'uwiwacu.
Ndabikunda vyose.
Mbwira umugambi wawe.
Nashoboye kugira.
Urashaka kumenya igituma?
Tuja hehe?
Ndakeneye abakozi b'abitanzi batatu.
Kubera iki uburiramwo?
Turakira ibikurikira.
Nururukira ngaha.
Ndarwaye gahoro.
Ngurisha impuzu ku murongo.
Dushaka akarusho.
Ni ibintu bishoboka.
Witwa ngwiki?
Bazomenya uko bagira.
Ndakunda ibiharuro.
Uranyitwararika.
Kubera iki wiga muri kaminuza?
Uragenda canke?
Ndakunda umuduga wawe.
Ndagenda kuryama.
Amaze igihe kingana iki arwaye?
Nta mvo yo kugira impungenge.
Ikimuga gisumba imva.
Ndi mu kiruhuko.
Ni ingorane?
Nje gusezera.
Nari mbizi.
Inyuma yacu hari urugendo runini.
Capfuye?
Twiga mw'isomero rimwe.
Turabasororeye.
Muragaba k'umutwe wanyu.
Noshimishwa no kumenya izina ryawe.
Kubera iki utazanana na twe?
Ukora iki ngaha?
Uza imuhira gute?
Ibitoke bisa n'umuhondo.
Yavyutse nabi.
Nari mbizi.
Ijoro ryiza!
Nta wundi muntu yarahari kiretse jewe.
Ndamusavye umpe urupapuro rwo kwandika.
Kubera iki utaciga igifaransa?
Ukora iki ngaha?
Hitamwo inomero.
Basinye?
Nimuduhitemwo!
Ndazi ingene bikoreshwa.
Uyu ni nyoko?
Mbwirizwa kuzirikana.
Muri ico gihe nararavye ya cenema wamye urata.
Ndagukunze.
Ndazi ingene bigenda.
Turi kumwe.
Ndamaramaye.
Kigurwa angahe?
Murakoze cane kandi.
Narabikubwiye mu ndwi iheze.
Uri mu ruhande uruhe?
Ntubwirizwa kuza.
Uba ngaha?
Sinzi ico ushaka.
Muri ino gant hari intoboro ku rukumu.
Mvyuka isaha imwe zo mugitondo.
Urateganya kugenda mu nama?
Ndakunda gutemberera ku ruzi.
Bite uyu munsi?
Ndonka ico nshaka.
Nturi mwenewacu.
Mu buseruko bw'ikigwati hari ikiyaga.
Ndabibonye.
Kubera iki abantu batankunda?
Woba ufise akanya?
Turazi igituma.
Urashaka kuraba iki?
Twoshobora kujana.
Imbwa zihamba kenshi amagufa.
Iyo menya sinari kuza.
Sindi intore.
Turumvikana.
Nico cakuzanye ngaha?
Ntimushakisha igituma!
Iki gikorwa kiramuvuna.
Ijipo ntiyari inkwiye nico gituma nabwirijwe guyihindura.
Raba hariya!
Nabiketse.
Nimwambure ibirato vyanyu.
Ni vyiza, sivyo?
Reka kuvuga uko.
Kubera iki utari kumwe na jewe?
Urabona iyi mitumba?
Aranezerewe.
Ashaka kuvuga iki?
Ndagukunda nanje.
Iyi nomero ya terefone ni iyande?
Ndafise bashikanje.
Urampimbaza.
Ntuzi musazanje.
Urondera ibi aha?
Turaja ku burengero.
Mfise benewacu.
Muri bande kandi?
Kuri ino ncuro sinshobora gushika.
Ni vyaba atarivyo, ni umubeshi.
Usa n'uwunezerewe.
Igisu kirakarishe cane.
Harashushe cane, canke?
Kubera iki ubaza?
Ntiwari ubizi?
Shishikara!
Durashobora kubonana.
Ntibigoye cane.
Ugara amadirisha yose.
Sinshaka.
Ndibaza ko azoza.
Inzu yanje iri hafi y'inyubakwa yo gusengeramwo.
Ngirango ntubikunda.
Ngibi ibisu, amakanya n'ibiyiko.
Urafise ico gusoma?
Simbesha na rimwe.
Tom ni umubaji.
Sinzi aba bantu.
Urabibonye?
Dushaka ko ubitwara.
Ndi umwotsi w'imikate.
Iyi nzu iri ku gasozi ni ishure ryacu.
Nahomvye.
Ntushavure!
Tom arazi igituma?
Ndabirora.
Urukundo rurahuma.
Ntumpate kubikora.
Turagarutse.
Urabishaka canke?
Ndakunda umuduga wanyu.
Sindashonje.
Tom nihari nawe?
Ni igice c'umugambi.
Singushimye.
Azoza nawe?
Ibara ry'ikirava rihuje n'uruhome.
Murashobora kwinyuganza?
Ni umunyamerika?
Mba ngaha.
Nashaka kubaza, mbe muhakura inyungu nki?
Ndashaka bimwe nanje.
Nzobiraba.
Ndazi ingene umuntu ashikayo.
Ingo wirorere.
Ngirango araza.
Mwama kubivuga.
Data ari imuhira.
Usa na so.
Uzobikunda.
Iyi kanzu nijewe nayigiriye.
Capfuye.
Ntibabana.
Ntiyibungenze.
Ashaka kuvuga iki?
Si isango y'ikiyago. Tuja gusa muri cenema.
Niga igifaransa mw'ishure.
Uva hehe?
Kubera iki muri imuhira?
Twatandukanye.
Nimuzanire abandi.
Ndazi neza ko hari aho maze kumubona.
Ni munsi.
Mariya ahitana Tom ku gituro c'igari ya moshi.
Urazi ko ndagukunda.
Yakuriye kwa nyirakuru.
Nta mahera tugifise.
Amahera arihe?
Ntimutore inomero.
Kubera iki ijuru risa n'ubururu?
Urabona iyi nzu? Ni rwanje.
Urazi aho arihe?
Ibintu vyawe birihe?
Ndabakunda bose.
Mvuga ico niyumvira.
Turakuzi.
Ndakwemera.
Yamugomwe.
Ndibaza ko babizi.
Mbabarira, sinshobora kugenda.
Navuze ko bimbabaje.
Ndakunda ibiharuro.
Reka gusoma.
Ndabitegera.
Nzobiraba.
Urafise ikintu mu gutima, ushaka kwikura? Urashobora binganirira.
Mugenda hehe?
Si ikintu co kwishima.
Afise imyaka ingahe?
Bose bameze kumwe?
Ntibinshimishije.
Uyu muduga usa na mushasha.
Ntegerezwa kuja imuhira.
Muzi iki ku vyashitse?
Simbakorera.
Nyoko ari imuhira?
Ndiko nduhuka.
Sinzi izina ryiwe.
Nabigiriye wewe.
Naguze amagi n'amata make.
Bishire nyoko.
Dushaka agahembo karusha.
Ndakeneye umwanya wo kwiyumvira.
Urafise isaha imwe.
Muzi iki ku vyabaye?
Kuki utaja imuhira?
Bose bateye kumwe?
Ikiganza gifise intoki zitanu: urukumu, inkombarukoko, msumba zose, igihugunibenga, agahererezi.
Ntiwosubira kumpa ikindi gikombe c'icayi?
Injira.
Urazi nyene uyu muduga?
Uri iwawe?
Mva muri Bresil.
Twabirahiye.
Amahera yanje ari hehe?
Kubera iki nobesha?
Ndi mu muduga.
Twese dufise imiryango.
Ndazi ingene bameze.
Utagavye uzovuna amagufa.
Nje kugutwara i muhira.
Ndashobora kwinjira?
Simbikora neza.
Si vyiza.
Ijuru riracika ryiza mu kanya.
Ntimubitegera?
Bimuhe.
Sinzi ingene.
Kubera iki ubivuga?
Udushakako iki?
Wabonye amaso yabo?
Siniyumva neza ngaha.
Wigahe?
Yatwawe ku bitaro.
Heba!
Sinzi izina ryiwe.
Bizoja imbere.
Baba hehe?
Murashobora kuntegera?
Ndabizi.
Niwe umugabo ndiko mvuga.
Vyose birashoboka.
Ntanumwe yumviriza.
Duteka umuceri uku.
Urazi aho aba?
Ndi uwo ku murizo.
Ntidushobora kubiganirira ngaha?
Wari kungirira cokimwe.
Sinzi izina ryiwe.
Harakanye cane.
Novuga gutyo.
Nabarira vyose abavyeyi banje.
Nashaka kubaza, mbe mugenzwa n'amaki?
Ndamuzi.
Uraba iki?
Ndazi ico nzokora.
Subira kandi.
Turajana?
Natekeye neza ibirahuri kugira ntibimeneke.
Sindakunda kwiga.
Kera yari umwigisha.
Nganirira umugambi wawe.
Uraza canke?
Ndi mu karuhuko.
Ni abanyamerika?
Igitwazi kirasimba.
Ntadukunda.
Mbe nambare iki - ipantalo canke ijipo?
Ndashika isaha zine.
Uza imuhira ryari?
Uri umugenzi wanje.
Kubera iki harashushe?
Nta bishasha.
Turavukana.
Abavyeyi banje bampamagara kira munsi.
Murashaka kubitwara?
Ndi uwanyuma.
Yazunguje umutwe.
Ntavuga icongereza.
Ninde asoma?
Urazi ico bavuze?
Ndazi ikiriko kiba.
Kubera iki utabikora?
Ntanumwe ari i muhira.
Usa n'uwuhiriwe.
Ntaco ntibindaba.
"Aya marori ni ayande?" – "Nyeneyo ni Data."
Ndi umunyeshuri muri kaminuza.
Sinshaka kurira.
Korera iciza ababanka.
Birera?
Ntuhebe!
Sindabitegera.
Turi magara make.
Uyu munsi ni ku wa kangahe?
Mubwirizwa kugenda i muhira.
Mize ndababara mu muhogo.
Nturekuriwe kwinjira.
Ubibona gute?
Bwakeye!
Mushiki wanje yoga ningoga.
Kubera iki tutaja imuhira?
Turagukunda.
Urazi izina ryiwe?
Ndondera inzu mu gisagara, ata cizero.
Uheruka gutamba ubwanyuma ryari?
Kazibe!
Ntashobora kuza kubera ko ararwaye.
Biranteye isoni.
Heba!
Nturoreyo.
Ntwumviriza.
Uba ngaha?
Mbwirizwa kwiga.
Bikuvako.
Nyogokuru avuga buhoro buhoro.
Kubera iki udashobora kuronka na kimwe?
Iki gikorwa kimugora birenze.
Turazi imvo.
Sinzi ingene witwa.
Yagarutse ngaha.
Ni ibiki bifatanye n'akazi kawe?
Twaje kukuraba.
Abo nabo mu bujapani?
Urazi ico ubwirizwa kugira?
Ni binini cane.
Sindakizi.
Ndaribwa mu nda.
Iki gitabo ntigifise akamo.
Watinye?
Ushaka kuba hehe?
Mvuga ico mfise ku muzirikanyi.
Araguzi?
Urupapuru rumwe rurabuze.
Uramukiwe.
Yitwa ngwiki kandi?
Uzogaruka ku wa kabiri?
Ugara idirisha.
Abo bandi ni bande?
Ndashobora kuronka iki gitabo?
Ntimushobora gufatira kuri ivyo.
Tujane?
Ntasa n'uwunezerewe.
Haraza gushuha.
Ubironderera ngaha?
Nturabe hasi.
Umuduga wa data ni mushasha.
Raba ingene biteye igomwe.
Kubera iki mbwirizwa kubikora?
Ntimubitegera?
Siho ari.
Umubaji arapima ikibanza.
Tubarire ivyo mukora muri kino gihe.
Iyi hinguriro rikora ivyuma vy'imiduga.
Nta mahera yari agifise.
Vyose ni bimwe?
Sintegera igifaransa.
Ndashobora kubibona kandi?
Biranshimishije.
Amadirisha aranduye.
Ja hiyo!
Kubera iki ufise ivyo?
Ni abavukanyi.
Reka kundaba.
Muribuka ihimbaza ry'amavuko ya data?
Sinshaka kubabaza umuntu.
Urazi ingene bisa?
Ngirango araza uyu munsi.
Ndashobora kwinjira?
Birashobora gupfa.
Kubera iki ataco uronka?
Urakoze kwicisha iwacu.
Nta ngorane.
Sinshaka kubimenya.
Umuduga wanyu wabaye iki?
Ego, ndazi.
Nzofata ivyo nshobora kwakira.
Bitebe bitebuke bizoba.
Nasuzumye vyose.
Yamoye umutwe wiwe.
Sindagutegera.
Nije nzobanza kwinjira.
Ugara idirisha!
Ndazi ibitari bike kuri wewe.
Iki kibazo ni ciza.
Kubera iki ufise ico?
Ndazi ingene bigirwa.
Nsubire kugaruka?
Ikintu cose gifise amaherezo.
Kubera iki bari aha?
Muri beza cane gwose.
Nta gorane.
Sinkugomwe.
Data wanje ntari imuhira.
Hari amategeko.
Uribaza ko nezerewe?
Sinzi kugumya amazina.
Nibajije ko ndakuzi.
Ni bitoya birenze?
Genda kwoga!
Urafise amahera yanje?
Ndagukumbuye cane.
Ntaco ntibindora.
Ishure ryawe ririhe?
Ndaje kuguhitana.
Murazi aho mba?
Iyo aguma imuhira uyo munsi, ntiyogize isanganya.
Ubona iki?
Ikosa ni iryande?
Nsubiza iki gitabo hehe?
Twasezeye.
Iki gitabo ni gishasha.
Ntibamuriha ku kwezi ahubwo ku munsi.
Wibuke ubuntu bwawe wiyobagize ibindi.
Ndatinya inyoni.
Yatezuye!
Urazi ko tugukunda.
Sinshaka kugumya rwaye.
Biranyuze.
Ukorera nde?
Simfise musazanje.
Duga hejuru!
Nimuzanire ibindi.
Antera kuzirikana.
Ubikuye hehe?
Iki gitabo kiri ku meza ni icande?
Ntundungike.
Iki gihugu gikesha itunga ibitoro.
Mpa akanya.
Mba ngaha.
Nzobishobora.
Simbikeneye.
Arafasha nyina wiwe rimwe rimwe.
Aramukunda.
Mfise umukoshi uyu munsi.
Ndashaka ko usoma iki gitabo.
Ntanumwe arazi aho turi.
Mpora mesura isutiye yanje n'amaboko.
Uwu muduga ni mushasha?
Ubugeni buzoba ku wagatandatu.
Bisa naho muri mu kuri.
Ndazi aho muri.
Ruhuka!
Ejo naryamye umunsi wose, kuko wari umunsi w'Imana.
Kazae!
Iki kinyamakuru ni icande?
Kubera iki abantu bavuga ivyo?
Noshimishwa no kumubona.
Kubera iki wibaza ivyo?
Uri umuhinga.
Abo ni abajapani?
Nari nzi ko wogaruka.
Na jewe ngenda kw'ishure ngaha.
Ushaka kugenda ryari?
Tubiravye neza, ni bimwe!
Reka kubaza!
Ntibiri nkuko uvyiyumvira.
Tubwirizwa kureka guhura uko.
Aribungenze.
Wibaza ko ico ariki?
Egeka imeza ku ruhome.
Sinshobora guhinduka uwo ndi.
Uri umuntu mwiza.
Ni bitoya birenze.
Ndazi ingene bateye.
Urira mu muduga.
Nta bitabo mfise vyo gusoma.
Ndanezerewe ko ariho uri.
Urafise mwenewawe?
Nariyumviye kuguma iminsi mike iwawe.
Ndazi kubikora.
Nimusohoke mu muduga.
Tega amatwi!
Uri umubanyi wanje.
Twagenze inzira ndende.
Woba ufise umunota?
Vyibagire ivyo.
Sinarinzi ko muri buhabe uyu munsi.
Nasubiye kumubona.
Igifurwe ntigifise amenyo.
Ni ku wambere.
Uwutwenga inkovu ntazi uruguma.
Uranezereza.
Sindamuzi.
Nguyo!
Ni ku wagatandatu.
Iri darapo ni nziza cane.
Niyumviye ko vyogutwenza.
Sekuru wabo aba hehe?
Mbabarira kugukankamira.
Mpamagara hagati y'isaha imwe n'isaha zibiri.
Uba he?
Ntiwoshobora kubisubira ico wavuze?
Murabona iyi mitumba?
Ngirango araza.
Natekeye neza ibiyo kugira ntibimeneke.
Mukunda gusoma ubwoko bw'ibitabo ibihe?
Ijipo iranduta.
Ndazi aho biri.
Sindi umuntu mwiza.
Amahera yampereyeko.
Nta mvo ihari yo gutinya.
Ntaco tugiheraniye.
Ntitujana.
Utumvise, baza.
Iki gitabo ntigifise akamo.
Nokwongera.
Urakenuye cane!
Namerewe nabi.
Ipantalo yawe iranduye.
Asa na data.
Uribuka?
Yatetse umutaga wose.
Ntugende zirayoye.
Amahera yarampereyeko.
Urakoze cane.
Urashaka kubibona?
Uyu muvinyu ni uwande?
Tuzobanza kubikorako.
Ndabikorera wewe.
Mugenda hehe?
Ni beza cane gwose.
Ndakira ibi.
Kubera iki ubimbwira ubu?
Ibi biro ni ivyande?
Iki gitanda kiranonotse cane.
Muri hehe uyu munsi?
Wiga ryari?
Baravukana.
Bamwe muri abo bakozi ntibamenyeye gukora ako kazi.
Bite, ico kunywa?
Ikanzu rikozwe mw'iharire.
Sindi umutunzi.
Nyumviriza.
Agafuni kabagara ubucuti ni akarenge.
Ndipfuza bimwe nanje.
Nturoraniwe?
Nryama uko zandemye.
Bashizeko umukono?
Tebuka!
Ni igiki gituma abantu bagira uko ivyo?
Ndi uw'impera.
Kubera iki mwabeshe mu vyerekeye imyaka yanyu?
Uzobitegera vuba.
Egeka ingazi ku ruhome.
Turageramiwe.
Barabizi.
Aragenda ku maguru.
Ku wambere musée yama yugaye.
Va mu buriri bwanje!
Bashaka ko tubikora.
Ntibishobora kuba ivyo mwipfuza.
Uramuzi.
Simfise umuduga.
Nitwa Jack.
Urazi nyene uyu muduga?
Kubera iki tuticara?
Niga igifaransa mw'ishure.
Nije nzotangura kwinjira.
Rindira hariya.
Birakwiye vyose ivyerekeye vy'urugendo?
Waciye ku kimenyetso c'itara ritukura.
Ndi umwe mu banyeshuri bawe.
Ndazi izina ryiwe gusa.
Ni mwenewacu.
Ndi iwanje.
Nanje.
Ntibindaba mugihe ahimbawe.
Data wanje ntari imuhira.
Iyo azakugira umwanya yari kugenda.
Ndazi uyo mwigeme.
Ntanumwe amuzi neza kiretse abavyeyi biwe.
Idirisha riraba mu rugo.
Iki gitabo ntaco kimaze.
Tujane twese hamwe gufungura ku mutaga.
Nagira ngo urabizi.
Murazi aba bantu?
Mpore ko ndabivuze.
Nije nzobanza kwinjira.
Sindabikeneye.
Sinzi ico novuga...
Ndashaka kubana na wewe.
Urondera ibi aha?
Uzobikunda.
Ushoboye iki?
Iyi nzoga ni iyande?
Nyene ibi bitabo ni mushikanje.
Ntanumwe yakubajije.
Ni isaha icenda ibuze iminuta icumi n'itanu.
Turumva.
Uvyuka ryari?
Nasivye kw'ishuri.
Turiga igifaransa.
Nta numwe ahari!
Ndi ngaha ijoro rimwe.
Nshaka kwicara hafi y'idirisha.
Sinshobora kwoza amasahani. Harabuze amazi.
Uyu mwaka ntegekanya gusoma ibitabo vyinshi bishoboka.
Rindira musazawe.
Urazi izina ryiwe?
Ndakurondera.
Ndashaka gusubira kukubona.
Urakoze kuza iwanje.
Tom arihe?
Nshaka kugutekera.
Rindira mushikawe.
Ni twebwe murondera?
Ni rwanje. Nsubiza.
Nzokugarukako.
Namwe muravyiyumvira gutyo?
Izi ntebe bigenewe abantu bashaje n'abarwaye.
Ndashonje.
Sibiraba amahera.
Ngaha nta numwe afise umuduga.
Turi abanyeshuri ba kaminuza.
Wiga kw ishure irihe?
Nta ngorane.
Nzota nomoke.
Nta wundi nipfuza atari wewe.
Ni ibiki bijanye n'akazi kawe?
Mpora mesura isutiye yanje n'amaboko.
Ntutwibagira!
Ndakunda iki gitabo.
Ni igitabo ciza cane.
Urazi aho aba?
Narakunze uyu muduga.
Uri umutetsi mwiza.
Iki ciyumviro cari icande?
Bisa neza.
Nivyo urondera?
Ndazi uyo mukobwa.
Aba ngaha?
Ndaguhwatira umucungwa.
Ni vyose bisigaye.
Kubera iki uretse?
Ndashobora kumenya ibintu nokuzanira.
Ndabizi neza.
Urakoze kuza iwanje.
Nzovyishoboza.
Ndabikorera wewe.
Nagize igitondo c'imirimo myinshi.
Ndazi igituma uri ngaha.
Si neza.
Urira hejuru!
Ndakujana.
Mfashe ibi aha.
Kuwagatatu haza ni vyiza.
Data afise imirimo myinshi.
Ntibishobora ko ari ivyo mushaka.
Sinarinzi ko muri buhabe uyu munsi.
Urameneka umutwe?
Igitabo kirihe?
Kubera iki mbwirizwa kubikora?
Kubika ahakanye kandi humutse.
Ntibintera iteka.
Ngizo impapuro zanje.
Mpa amahera make.
Mubwirizwa kugenda i muhira.
Mwashikiwe niki ejo ku mugoroba?
Iki gitabo ni gitoya.
Kubera iki tudataha imuhira?
Umudandaza yaratugabanirije cane igiciro.
Agiye buhoro buhoro kugira umwana ashobore gukurikira.
Urakoze kuza.
Uherereye hehe?
Twavanye.
Biramuraba.
Neza, nawe?
Ntimushaka kumenya igituma?
Ibarabara riri urwamo rwinshi.
Birakunyuze?
Nzogira amagara meza vuba?
Nagasaga, Sayoko.
Ubwirizwa kujayo kubizana.
Tujana twese hamwe.
Ntibabana.
Mbwirizwa kwiyumvira.
Nshaka ko ubisoma.
Wahagaritse umuduga hehe?
Je hanze!
Ni rwacu.
Ndera.
Ntibashaka ko tubimenya.
Ntimugaruke.
Bishoboka ko bipfa.
Nikomerekeje n'igisu ku rutoki.
Ndazi aho turi.
Ndameneka umutwe.
Namubonye yiruka.
Turumvikana.
Abavyeyi banyu baracariho?
Sinzi ico nshaka.
Nosubira kubikora.
Umuntu kanaka azugara idirisha.
Twarukiye hamwe.
Ndarenga umugenzi.
Urashaka kureka?
Kuri ino ncuro sinshobora kubikora.
Ntaco ndabiziko.
Ntwara i muhira.
Ingo tujane.
Yamukunze.
Bizoba neza cane.
Inzu yanje iri hafi y'urusengero.
Mpa isaha yawe.
Ndi umushinwakazi.
Bafungura ifi.
Nzokurora.
Ntiyashatse gusaba imfashanyo naho yari ashonje cane.
Akira ico ushaka.
Bashize amazi y'icayi ku ziko.
Mubwirizwa gutaha.
Namugomwe.
Urazi ico ubwirizwa gukora?
Ni isaha icenda ibuze iminuta icumi n'itanu.
Ndakunda akazi kanje pe.
Urira aha canke uratekera?
Ur'uwiwacu.
Ni murabe neza iri foto.
Izuba riserukira mu buseruko.
Ndahatswe gutura amasahani hasi.
Nagira ngo urashobora kubitegera.
Ndagutwara kw'ishure.
Turabizi.
Sinzi ico novuga...
Kubera iki udataha?
Ikibazo ciza.
Mumuzi hehe?
Iki kintu kimaze iki?
Yigira nk'uwurwaye.
Narasomye iki gitabo.
Ndasemagurika.
Ni birebire cane.
Imbere yo gukatira iburyo mu masanganzira, gensura ko ata munyekinga aje.
Ninde yabirekuye?
Afise imyaka ingana iki?
Turabizi.
Ntashobora kubika ibanga.
Ni ryari uheruka gutamba ubwanyuma?
Sintegera ibintu nk'ivyo.
Manuka!
Nshaka ko umubona.
Umwana ari ku ruhande rw'ibubamfu rw'inzu.
Sinkunda kwiruka.
Ugenda kw'ishure gute?
Ndarindirira hanze.
Sinshobora kugira vyinshi gusumba ivyo.
Urugendo rwiza!
