Ndanezerewe.
Sinarinzi ko muri buhabe uyu munsi.
Aramukunda.
Harashushe cane, sivyo?
Sinzi ico nokora.
Yazunguje umutwe.
Ni neza cane.
Sinshaka kubimenya.
Reka ndabe.
Murakoze cane kandi.
Kira gitondo mva imuhira imbere y'isaha zibiri.
Ndazi ico nokora.
Ntiwitinye.
Ja hiyo!
Ntitubizi.
Nanje.
Ibi biro ni ivyande?
Ndagukunda.
Simfise amahera.
Ntanumwe abizi.
Mushikanje asa na Mama.
Urakoze cane.
Iri jambo ryamuka mu kigereki.
Uri umugenzi wanje.
Yamukunze.
Ndi umwigisha.
Mfise benewacu.
Abavyeyi banje bampamagara kira munsi.
Ndazi ico nzokora.
Uri umuntu mwiza.
Kubera iki wiga igifaransa?
Uri umunyeshuri mwiza.
Ikosa ni iryande?
Ndibuka aho ubwambere.
Bimuha.
Ni binini birenze?
Kubera iki ijuru risa n'ubururu?
Ntanumwe antegura.
Simbikeneye.
Turabitegera.
Ntuza, sivyo?
Ushaka kuja hehe?
Iyo azakugira umwanya yari kugenda.
Nagasaga!
Igituro ca bisi kiri iminota itanu uvuye ngaha.
Iri terefone ni iryande?
Nta mahera yari agifise.
Kubera iki bataza?
Turi imuhira.
Nyoko arihe?
Ubu buriri ni ubwande?
Sintegera iri jambo.
Ni umunyeshuri mwiza.
Uteganya iki ku mpera z'indwi?
Ndi umwigisha.
Ndazi ibikenewe gukorwa.
Sinshaka kubisoma.
Ndamukunda.
Urugendo rwiza!
Mbirizwa kwiga gifaransa.
Ntibintera iteka.
Siniyumva neza ngaha.
Sohoka mu cumba canje!
Iyo menya nari kugenda.
Urazi ko ndagukunda.
Sinzi iyo ngana.
Muri abana.
Uko ni vyiza gusumba?
Sindamuzi.
Ngurisha impuzu ku murongo.
Ipantalo yawe iranduye.
Nagira ngo urashobora kubitegera.
Ntituri twenyene.
Ndakunda ibiharuro.
Sindi umunyeshuri.
Ndakunda ibiharuro.
Ntubange ugutwi.
Niga igifaransa mw'ishure.
Urarurumba.
Nturabe munsi.
Nagira ngo woba watashe.
Ndazi Tom?
Ndi umunyeshuri muri kaminuza.
Injira.
Narinzi ko vyogushimisha.
Iciyumviro nyabaki!
Hari ijana y'abantu mu ngoro.
Ndarurumba.
Ushaka kubimenya iki?
Usa n'umupolisi!
Nirukiye kwa mama.
Nta kamaro.
Ndashaka ko usoma iki gitabo.
Ndakunda imishatsi migufi.
Aribungenze.
Kubera iki unkunda?
Kubera iki utari kumwe na jewe?
Sinzi ico novuga...
Uyu muduga ni mwiza cane.
Mfise abakobwa batatu.
So arihe?
Nahabonye mwenewacu.
Urazi nyene uyu muduga?
Sinumva igifaransa.
Kubera iki ndi ngaha?
Nta kibazo.
Baratuzi.
Aranezerewe.
Nzokora igikenewe vyose.
Kubera iki wiga muri kaminuza?
Nzogenda n'umuduga.
Mbwirizwa gutunganya imishatsi yanje.
Ndashonje.
Uramuzi?
Murakoze cane.
Ndashobore kubikoresha?
Nshaka ko utaha.
Ngurisha impuzu ku murongo.
Ndakunda kwiga igifaransa.
Naganiriye vyose abavyeyi banje.
Uri umutetsi mwiza.
Ni bitoya birenze urugero.
Niibagiye kugura umukate.
Ngiyo ifagitiri.
Nje kugutwara i muhira.
Ngirango ntaza.
Ndakunda umuryango wanje.
Ndiko ndasoma igitabo.
Bigurwa angahe?
Ndazi aba bagore.
Ndafise ubwato.
Ipantalo yanje yajovye.
Ntitubwirizwe kubivugana ubu nyene.
Bavuga ko atunze cane.
Navyiyumviye.
Turanezerewe cane.
Sinibagira na rimwe amaso.
Muzinaniye hehe?
Nta wundi muntu yarahari kiretse jewe.
Urazi gutandukanya intama n'impene?
Sinzi neza igifaransa.
Nzanira ingwa zibiri.
Harashushe cane ngaha.
Ni umuntu mwiza.
Ndazi igituma uri ngaha.
Sinshaka gutunga.
Ndi umuhererezi.
Nturi mwenewacu.
Nshaka kuganira nawe.
Nje gusezera.
Korera iciza ababanka.
Birera?
Ntiwibagire gutwara ibaruwa.
Ndibaza ko ntegeye.
Bite! Urakomeye?
Ntituri twenyene.
Iyi nyabu ni yanje.
Ni ku wagatandatu.
Ndakujana.
Kubera iki tutabiraba?
Umuduga urihe?
Niga igifaransa mw'ishure.
Urashaka kuba umutunzi?
Inzovu zirya ivyatsi.
We si umwana.
Ntanumwe yakubajije.
Vyibagire!
Uri mushasha?
Uragenda canke?
Ni bitoya birenze?
Ja mu buriri!
Yataye urupfunguzo rw'umuduga wiwe.
Ndabitegera.
Afise ibitabo amajana n'amajana.
Nzokunyara.
Ni umufaransa.
Bikuvako.
Amahera yanje ari hehe?
Sinzi guteka.
Umwigisha wanyu ni nde?
Ni rwacu.
Reka kuvuga ivyo!
Muri Abadagi, sivyo?
Urafise umuduga?
Ntariye nopfa.
Urashobora kujayo.
Ndazi uyo mwigeme.
Vyibagire ivyo.
Umuvyeyi wanje arankunda.
Uyu muhungu ni mwenebabo.
Afise imyaka ingana iki?
Aya madirisha araba mu bumanuko.
Abo ni abajapani?
Sinibaza ko aza.
Bobo ni abana.
Ndibaza ko azoza.
Kubera iki mutagerageza iyi goti? Ijanye neza n'ipantalo yanyu.
Nganirira umugambi wawe.
Kubera iki tudataha imuhira?
Yatetse umutaga wose.
Urashaka kuraba iki?
Turavukana.
Ntuzi icarico?
Sindi ikijuju.
Ndakunda kuba ngaha.
Ntuhebe!
Ntanumwe yumviriza.
Ntiyasomaye iki gitabo.
Nagira ngo urashobora kubitegera.
Ndazi neza ko hari aho maze kumubona.
Umuryango wanje ni muto.
Sinzi ico nshaka.
Ntibimpa agateka.
Nimusohoke mu muduga.
Kubera iki udashaka kugenda?
Ni umunyamerika?
Mvuga indimi zitatu.
Uzoza iwawe ryari?
Kubera iki ubaza?
Ntabana nawe.
Ntanumwe azi izina ryiwe.
Tuja hehe?
Naje kubera wewe.
Ndafise bashikanje.
Urashobora gutora irangi iryariryo ryose ushimye.
Nta gishasha.
Uyu munsi ni umunsi w'Imana.
Ndategera ico ushaka kuvuga.
Inzu yanje iri hafi y'inyubakwa yo gusengeramwo.
Umuryango umerewe gute?
Asa na nyina wiwe.
Sindi intore.
Nzoguha igitabo.
Twamanutse twiruka agasozi.
Kubera iki tubikora?
Bavuga ko atunze cane.
Imbwa zihamba kenshi amagufa.
Nshaka kukubona.
Iminsi yose aja ku kazi ku maguru, kiretse iyo imvura igwa.
Urafise ico gusoma?
Yafashe ikinyugunyugu n'urukumu hamwe n'inkombarukoko.
Ndazi uyo mwigeme.
Uyu muduga ni mwiza cane.
Arumva igifaransa.
Abantu bose bagiye hehe?
Ndafise ikibazo.
Umutetsi arihe?
Inzu yanje iri hafi y'isengero.
Iki gitabo ni ciza cane.
Yamukunze.
Sinibagira na rimwe amaso.
Uba he?
Narumvise ko warongoye.
Urabona itandukaniro hagati y'ivyo bicapu bibiri?
Ntavuga icongereza gusa, avuga kandi n'ikidagi.
Duteka umuceri uku.
Ufise imyaka ingahe?
Nyoko ari imuhira?
Akira igitabo usome.
Murazi aho mba?
Icawe ni ciza gusumba.
Akira ico ushaka.
Mubwirizwa gutaha.
Ndavyakira.
Bitware hirya.
Raba iyi foto.
Uri iwawe?
Icawe ni ciza gusumba.
Ni bitoya birenze?
Reka kuvuga ivyo!
Fata itagisi ikujana mw ihoteri.
Yarabimpaye.
Hagarara!
Ukuboko kwanje kw'ibubamfu kwagize ibinyanya.
Asa na nyina.
Ejo naryamye umunsi wose, kuko wari umunsi w'Imana.
Noshimishwa no kumenya izina ryawe.
Ushaka kuzobiraba.
Ntidufise amahera.
Ni naco gituma ndagukunda.
Urabishaka canke?
Indahiro ni ideni.
Mbirizwa kwiga gifaransa.
Nta bitabo mfise vyo gusoma.
Bimuhe.
Twama dukina ku munsi w'Imana.
Reka ndabirabe.
We si umwana.
Sinzi aho bari.
Mfise mukuruwanje.
Ntaco nywa.
Nje gusezera.
Aya masanganzira afise impanuka y'urupfu.
Mpamagara hagati y'isaha imwe n'isaha zibiri.
Ndi imuhira.
Nta ngorane.
Kubera iki utari aha?
Nikomerekeje n'imbugita ku rutoki.
Ruhuka!
Kubera iki mbwirizwa kubikora?
Kubera iki ataho tutajana?
Ndazi ikiriko kiba.
Yavyaye umwana wa mbere afise imyaka mirongo ibiri.
Iri darapo ni nziza cane.
Amapome vyose aguye hasi azoribwa n'ingurube.
Hariko haba iki hariya epfo?
Urashaka ikintu co kunywa?
Uyu mwaka ntegekanya gusoma ibitabo vyinshi bishoboka.
Nyene ibi bitabo ni mushikanje.
Ndashaka gusubira kukubona.
Nari mbizi.
Nabo baraza?
Sinzi aho aba.
Muritwararikire umutwe wanyu.
Nkura ngaha.
Ibi ni birebire birenze urugero.
Si umuduga wanje.
Urabona iyi nzu? Ni inzu yanje.
Ndiga igifaransa imuhira.
Umukobwa wanje azorongorwa mu kwezi kwa gatandatu.
Turagarutse.
Urihe?
Urashobora gukoresha uwu muduga.
Ni mushiki wawe?
Umuduga wa data ni mushasha.
Nta ngorane.
Bingwa neza.
Rabira mw'idirisha.
Sinshaka amahera yawe.
Nta mahera tugifise.
Mva muri Bresil.
Kera waranywa itabi, sivyo?
Nahabonye mwenewacu.
Kubera iki udatomora ico ufise ku muzirikanyi?
Mbwirizwa kwiga.
Ndi hehe?
Turanezerewe.
Inzu yanje iri hafi y'urusengero.
Ntanumwe azi amazina yabo.
Iyi hinguriro rikora ivyuma vy'imiduga.
Ugara amadirisha yose.
Ntaco bibaye.
Mpa igitabo.
Nasubiye kumubona.
Sinshaka gutunga.
Ntanumwe antega ugutwi.
Nyene uyu muduga ni data wanje.
Raba hariya!
Ntitugifise amahera.
Ntavuga icongereza.
Ni angahe?
Iki gitabo ni gishasha.
Uru ni urukundo?
Nzokora ivyangombwa vyose.
Ubwirizwa guheba inzoga.
Igitabo kirihe?
Sindi umubaji mwiza cane.
Urazi bano bantu.
Iki giti kirashaje.
So wawe amerewe gute?
Ubwirizwa kureka kunywa.
Izi ntambwe zirashobora kubuza ko ingwara isasagazwa.
Ntubange ugutwi.
Urakunda kwiga?
Nta kamaro.
Nturabe hasi.
Ndafise amahera.
Namugomwe.
Wasomye iki gitabo?
Nta ngorane.
Ndi umushinwakazi.
Nico ndiko ndondera.
Ndashaka kuguherekeza.
Iminsi yose aja ku kazi ku maguru, kiretse iyo hari imvura.
Uranzi.
Ndarahiye.
Ibintu vyawe birihe?
Hari umuntu ahagaze inyuma y'uruhome.
Aramwumva.
Umukobwa wanje azorongorwa muri ruheshi.
Kubika ahapfutse kandi humutse.
Nta mazi akiri mw'icupa.
Abo ni abajapani?
Ndagukumbuye cane.
Ndakubonye.
Tuzojana.
Ndashaka kukubona pe.
Turabitegera.
Biruguruye.
Uzomara umwanya ungana iki?
Ndashobora kubibona kandi?
Uribaza ko nezerewe?
Nico nshaka kumenya.
Yamugomwe.
Urazi ico ubaza?
Ndategera ico uvuga.
Ndafise ibikorwa vy'ishure.
Ni neza cane.
Ndiko nduhuka.
Iryo jambo ntaryonzi.
Reka ndaguhobere.
Izuba rirasira mu buseruko.
Nshaka kwiga igifaransa.
Ntanzi.
Ndakurondera.
Ndi umunyeshuri mushaha muri kaminuza.
Tom arihe?
Uyu muvinyu ni uwande?
Data ari imuhira.
Iyi nyabu ni yanje.
Mbwira umugambi wawe.
Nshobore gusubira kubibona?
Ufise imyaka ingana iki?
Kuva ejo dushobora kujana ku kazi.
Ndakwiyumvira.
Ntugende n'iminwe misa.
Ndazi igituma ubishaka.
Ndaribwa mu nda.
Nabonye hariya mushikanje.
Ntumuhagarike.
Ndazi aho uba.
Sindavyumva.
Uyu ni data wanje.
Ibisi irahagaze ariko nta muntu yururutse.
Nico nshaka kumenya.
Ntubaze.
Yatoye ikanzu izimvye gusumba zose.
Ntusabe amahera.
Twashitse.
Simfise mushikanje.
Reka kundaba!
Nyogokuru avuga buhoro buhoro.
Yagirije uyo mugabo ubusuma.
Ni umunyeshuri mwiza.
Reka gusoma.
Abo nabo mu bujapani?
Ntiwibagire gutwara ikete.
Nshaka kugutekera.
Amahera yarampereyeko.
Ndi mu gikoni.
Nryama ubusa.
Ndazi uyo mukobwa.
Ryama neza, Timmy.
Turiga igifaransa.
Asa na mwenewanyu.
Nzobigerageza.
Ukuboko kwanje kw'ibubamfu kwagize ibinyanya.
Uragenda canke ntugenda?
Umuryango wiwe urihe?
Ni twebwe murondera?
Ivyo turabizi.
Izuba riserukira mu buseruko.
Muraturondera?
Murategera igifaransa?
Ryama neza, Timmy.
Ndi umwotsi w'imikate.
Uva hehe?
Sinywa.
Yama ata mobile yiwe.
Bite, ico kunywa?
Twatandukanye.
Ukora iki?
Oya, urakoze.
Turiko dutakaza umwanya uzimvye.
Ndashobora kwinjira?
Uba ngaha?
Ndazi aba bantu.
Ntibiri nkuko uvyiyumvira.
Utaha ryari?
Namerewe nabi.
Ndibaza ku mfise umwanya w'ikindi gikombe c'ikawa.
We si umwana.
Kubera iki umbaza?
Ushobora gukoresha umuduga wanje.
Nzogushimisha.
Nazanwe no kwiga.
Isaha yawe irihe?
Umuryango umerewe gute?
Uri umuhinga.
Akora mw'ihinguriro.
Turihe?
Urupapuru rumwe rurabuze.
Sindabitegera.
Mariya arihe?
Bandanya!
Ni bitoya birenze.
Ijwi ryanje rirasaraye kubera inkorora.
Sindi umuntu mwiza.
Ndazi neza ko namubonye ahantu ikindi gihe.
Urabitegera, sivyo?
Ni isaha icenda ibuze iminuta icumi n'itanu.
Ntitumuzi.
Sinzi izina ryiwe.
Ugenda kw'ishure gute?
Sinshonje.
Idirisha riraba mu rugo.
Umuduga wanje urihe?
Harashushe.
Uraza canke?
Nataye impfunguzo zanje.
Ntuzoza, sivyo?
Ntwumviriza.
Urukundo ni iki?
Tuzongera ku wambere.
Ikiganza gifise intoki zitanu: urukumu, inkombarukoko, msumba zose, igihugunibenga, agahererezi.
Ahari ugushaka haba inzira.
Uri umugenzi wanje.
Ndazi kubikora.
Bamwe muri abo bakozi ntibamenyeye gukora ako kazi.
Ibirato birihe?
Waciye ku kimenyetso c'itara ritukura.
Banze imbere, ndakurikira.
Sinashoboye kutarira.
Ndazi ingene bikoreshwa.
Kubera iki utajana na jewe?
Mugenda hehe?
Murakoze cane kandi.
Sinzi.
Sinzi neza igifaransa.
Uramuzi.
Sinshobora kwoza amasahani. Harabuze amazi.
Abo ni abavukanyi banje.
Simbizi.
Ndasemagurika.
Simfise mwenewacu.
Birakunezereje?
Ivyirabura ni vyanje.
Intumbero y'urugendo rwanyu ni iyihe?
Ndumva ico uvuga.
Harashushe birenze.
Urazi ico yavuze?
Mvuga ico niyumvira.
Urafise umuduga?
Ntimushakisha igituma!
Urafise aya mahera?
Sindakunda kwiga.
Sindabikeneye.
Ayo madirisha yerekeye mu bumanuko.
Ndazi so wawe.
Nzobiraba.
Ntegerezwa kuja imuhira.
Ugara idirisha.
Ndashobora kubibona kandi?
Biragenda?
Ndazi ico wiyumvira.
Sinzi aba bantu.
Wiyumvira iki?
Utaha ryari?
Sinshaka aya mahera.
Izina ryanje ni John.
Ndakunda gusoma.
Nta mahera tugifise.
Ntuzi musazanje.
Ni ku wambere.
Urashaka kubibona?
Ni abanyamerika?
Sintunze.
Ikiganza gifise intoki zitanu: urukumu, inkombarukoko, msumba zose, igihugunibenga, agahererezi.
Urakoze kuza.
Urandondera?
Mu ruguma hari amashira.
Urazi izina ryiwe?
Ndibaza ko ari vyiza.
Baranezerewe.
Umuhungu arasimba.
Ntegerezwa kugenda ubu.
Ubugeni buzoba ku wagatandatu.
Narabiravye muri yu tubi.
Yazunguje umutwe.
Uriko usoma iki?
Ndakwemera.
Uza imuhira ryari?
Uramuzi.
Mvyuka isaha imwe zo mugitondo.
Ntibimeze uko uvyiyumvira.
Kubera iki wijiriwe?
Ndanezerewe ko uhari.
Turakuzi.
Ntiwibagire gutwara ikete.
Kubera iki utabikora?
Ndafise umuduga.
Urambabarira ko ndabivuze.
Urategera ivyanditse ngaha?
Iyi hinguriro rikora ivyuma vy'imiduga.
Kubera iki unkunda?
Ntunzi.
Ndabizi.
Iyi nzoga ni iyande?
Ndi mushasha aha.
Uzomara igihe kingana iki?
Idirisha rirugaye.
Naguze amagi n'amata make.
Ndagenda kuryama.
Sico kimwe.
Ndazi umuryango wiwe.
Uranezereza.
Twakuriye hamwe.
Sindamubona.
Araza nawe?
Ni vyiza gusumba uko biri.
Nzogerageza.
Iki ni igifaransa?
Uwushaka kumurongora abwiriza kubiganira neza na se wiwe.
Raba neza ingene ndabikora!
Nsabe uruhusha nde?
Ndazi ingene bigenda.
Ndanezerewe ku uhimbawe.
Sinteka.
Ndazi aho mbwirizwa kugaba.
Nta muduga mfise.
Umfata ko ndi nde?
Si igifaransi.
Niki?
Ayo mashurwe ubona ni amarosi.
Ntashobora kuza kubera ko ararwaye.
Nabonye hariya mushikanje.
Ugurura idirisha.
Urafise ikintu co gusoma?
Sinkomeye muri vyo.
Kubera iki bari aha?
Ushaka kuzobibona.
Sinshaka kukubona.
Mpore ko ndabivuze.
Ntibinyuze.
Kubera iki ubibaza?
Nshobore gusubira kubibona?
Uhaguruka ryari?
Ariko yiga.
Ntiwibagire gutwara ibaruwa.
Bite uyu munsi?
Ndazi uvyirumvira.
Rimwe rimwe tujana muri cenema.
Umviriza nyoko!
Ntanumwe ari i muhira.
Siko biri nkuko uvyiyumvira.
Urazi aho nzoba ndi.
Ndazi ingene bigirwa.
Kera yari umwigisha.
Sinshaka kubimenya.
Umuduga wacu urihe?
Ndakunda iyo ndi jenyene.
Wipfuza iki?
Aya masanganzira afise impanuka y'urupfu.
Urashaka ikintu co kunywa?
Uyu mwigeme asa neza.
Turi hehe?
Kubera iki tugira ivyo?
"Aya marori ni ayande?" – "Ni aya Data."
Asa na Se wiwe.
Si umuduga wanje.
We si umwana.
Iri jambo riva mu kigereki.
Ukora iki ngaha?
Nanje ndavyiyumvira uko.
Nta mahera dufise.
Ubwirizwa kuvyuka.
Hari imashini yo kumesura mu nzu?
Iri saho ni irya nde?
Uribuka?
Ntugende zirayoye.
Muragaba k'umutwe wanyu.
Ntegerezwa kugenda ubu.
Ndakwumviriza.
Ipantalo yawe iranduye.
Ndakunda uyu muduga.
Uragikunda?
Uyu muduga usa na mushasha.
Urabizi?
Iki gitabo ntigifise akamo.
Sinzi neza igifaransa.
Simfise umuduga.
Ubibona gute ku wagatanu?
Watinye?
Sinzi iryo jambo.
Mushikawe amerewe gute?
Kigurwa angahe?
Nzobiguha.
Murakoze kwumviriza.
Ntundabe gutyo.
Ndazi nyoko.
Amatapi yo mukahise arafise agaciro kanini.
Nzokora ico unsaba.
Twiga ubuhinga bw'umuziki.
Tuzobonana ejo!
Ntuzi musazanje.
Uyu ni nyoko?
Umukobwa wanje azorongorwa muri ruheshi.
Utaha ryari?
Umuduga wanje wapfuye.
Bishire nyoko.
Uri imuhira?
Urashaka ikintu co kunywa?
Ngirango araza.
Urashaka gutunga?
Ntibimeze uko uvyiyumvira.
Nzero, Ruruhuma, Ntwarante, Ndamukiza, Rusama, Ruheshi, Mukakaro, Myandagaro, Nyakanga, Gitugutu, Munyonyo na Kigarama ni amezi icumi n'abiri y'umwaka.
Haraho uzogenda muri iri ci?
Nta mahera yari agifise.
Ur'uwiwacu.
Urazi nyene uyu muduga?
Nguyo!
Sinkubona.
Twugurure idirisha!
Isaha yanje irihe?
Ndazi ico baravuze.
Yamugomwe.
Abonye amaraso umurwayi yaciye araba.
Capfuye.
Ndamuzi.
Simfise mushikanje.
Sinkomeye muri vyo.
Kubera iki jewe?
Uzosigara umwanya ungana iki?
Nshaka ko uja imuhira.
Arakunda gusoma ibitabo.
Maze kuduga aka gasozi niruka, ugusemagurika ni kwose.
Kubera iki utariyo?
Ndavyumva
Wiga kw ishure irihe?
Magdalena na Ania ni abagenzi pfampfe.
Indoto yanje yabaye ukuri.
Afise imyaka ingahe?
Ndi mu muduga.
Ingo!
Ni neza, siko?
Birampimbaza.
Ndabasavye, mumpe ifagitiri.
Nagize igitondo c'imirimo myinshi.
Sindakwumva.
Ndazi ico mvuga.
Ibi bitabo ni rwacu.
Abo nabo mu bujapani?
Mu buseruko bw'ikigwati hari ikiyaga.
Reka nje kugura umukate.
Urabibonye?
Ni umufaransa.
Wiga ryari?
Urafise umuduga?
Ngico igitabo cawe.
Ndamuzi.
Ni isaha icenda ibuze iminuta icumi n'itanu.
Simfise aho mba.
Nshaka gutaha.
Uranezerewe?
Nagira ngo ni ikigorwa cawe.
Urazi ico yavuze?
Nshaka kubibona.
Nyene ikintu ni musazanje.
Komeza!
Ku minsi y'Imana simba ndi imuhira.
Namugwiriye.
Ntanumwe yakubajije.
Umuryango wawe uri hehe?
Icumba cawe gifise amadirisha abiri?
Uri mushasha?
Sindi umunyeshuri muri kaminuza.
Yacishije igisu ciwe ishami ry'igiti.
Musazanje ntari i muhira.
Ndazi ko ubifise.
Urabitegera?
Urarwaye, ubwirizwa kuruhuka.
Urazi icarico urukundo?
Birakwiye vyose ivyerekeye vy'urugendo?
Birakwiye vyose ivy'urugendo?
Abana bagiye kw ishure?
Ushaka kuba hehe?
"Aya marori ni ayande?" – "Nyeneyo ni Data."
Soma ibi.
Ntibimpa agateka.
Ihinguriro rikora ibihumbi n'ibihumbi vy'amacupa kira kwezi.
Akira igitabo usome.
Subira gusoma.
Uraza? Ego canke oya?
Umuduga wanje urihe?
Ni birebire birenze urugero.
Ni vyiza, sivyo?
Ndazi kubikora.
Kaze iwacu!
Mba ngaha.
Igitwazi kirasimba.
Murabe.
Dusangire akanyobwa.
Bikozwe muki?
Sindashonje.
Ntuzi icarico?
Ntidushaka kubimenya.
Kubera iki utaciga igifaransa?
Ntunezerewe?
Ntubange ugutwi.
Ndi mu karuhuko.
Reka ndakugurire gishasha.
Uri umuhinga.
Ejo hari kuwagatanu.
Urazi icarico?
Uyu muduga ni rwacu.
Ndaguhwatira umucungwa.
Kubera iki mbikora?
Ndi umutetsi.
Wagize ubwoba?
Nariye amagi ejo.
Kubera iki harashushe?
Ntushaka kumenya ivyo!
Namukunze.
Kubera iki abantu batankunda?
Nzogaruka.
Indimi zifise amajambo agoye.
Iryo jambo ntaryonzi.
Ndazi uyo mukobwa.
Kuki utinjira?
Sibiraba amahera.
Ntibaza uyu munsi.
Mbwirizwa kwugurura idirisha?
Nyumviriza.
Twavanye.
Twakuriye hamwe.
Kubera iki babikora?
Ndakunda iyo ndi jenyene.
Araguzi?
Nakwiyumyiye.
Uriga igifaransa?
Ndashaka gusoma iki gitabo.
Nariyumviye kuguma iminsi mike iwawe.
Nitwa Jack.
Ntusubire!
Mbe nambare iki - ipantalo canke ijipo?
Ikibazo ciza.
Sinshaka guteka.
Ni isaha icenda ibuze iminuta icumi n'itanu.
Ntiwoshobora kubisubira ico wavuze?
Simbesha na rimwe.
Urazi aho aba?
Nturyame idirisha ryuguruye.
Nta muduga dufise.
Mama wanje arihe?
Ntibiri nkuko uvyiyumvira.
Afise umuduga.
Iyo udategereye, baza.
Uraba iki?
Si ikintu co kwirata.
Wari umugambi wande?
Ntiwibagire gutwara ibaruwa.
Ntiwibagire gutwara ikete.
Ndameneka umutwe.
So wawe arihe?
Ndafise umuduga.
Ni birebire birenze?
Mudutwaye hehe?
Noshimishwa no kumubona.
Ndamubonye.
Ndazi ico nogira.
Ntumpate kubikora.
Kubika ahakanye kandi humutse.
Kubera iki wibaza ivyo?
Sindagutegera.
Ndazi icarico urukundo.
Nzero ni ukwezi kwambere mu mwaka.
Ntibintera iteka.
Sinzi ico novyiyumvirako.
Kora ibikorwa vyawe vy'ishure.
Urashobora gutandukanya intama n'impene.
Nuko rero nabigize.
Reka gutungira ijisho amabere yiwe!
Urashobora gutera ururirimbo.
Umunyeshuri arashaka kukubona.
Va mu buriri bwanje!
Ntiwitinye.
Kera hari isengero ngaha.
Ni umunsi!
Ndanezerewe ko ariho uri.
Data ntari i muhira.
Kera hari urusengero ngaha.
Muri Abadagi, sivyo?
Capfuye?
Sinzi iryo jambo.
Ni akazi kiwe.
Ndazi aho ari.
Turavyumva.
Ingo kunsura.
Muzinaniye hehe?
Umukobwa wanje azorongorwa mu kwezi kwa gatandatu.
Nshaka kwiga igifaransa.
Za kunsura.
Ibitoke bisa n'umuhondo.
Uri umuvyeyi mwiza.
Narataye amarori yanje.
Igihe ntikigize gukanya gusa, kiranajovye.
Turabizi.
Ni umugambi mwiza.
Urukundo rurahuma.
Urashobora gutora irangi iryariryo ryose rigushimisha.
Asa na musazawe.
Uramundamukiriza ni mwahurira mu giteramo.
Uruhanga rwawe rurashushe cane. Ndakeeka ko ufise inyonko.
Uzi iki?
Nanje ndavyiyumvira uko.
Ndizeye ko ukomeye neza.
Narinzi ko uri ngaha.
Urazi ko mbwirizwa kugenda.
Si ikintu co kwishima.
Sinshaka kuba umutunzi.
Uranhunga ko ndabivuze.
Nturi musazanje.
Sinshaka kuba umutunzi.
Urazi ico yavuze?
Hagarika uyo muduga.
Mu mwaka uheze navyaye imfura yanje.
Ntitugifise amahera.
Ibiti vyinshi vyaraguye.
Urazi ko tugukunda.
Nanje ndavyiyumvira uko.
Ntanumwe amuzi neza kiretse abavyeyi biwe.
Sinzi ico nshaka.
Mbabarire cane!
Nshaka ko umubona.
Ururuka mu muduga.
Abana na we.
Iyo ukeneye imfashanyo urampamagara.
Ni mwenewacu.
Nabarira vyose abavyeyi banje.
Waciye ku kimenyetso c'itara ritukura.
Mfise umukoshi.
Uyu munsi ni kuwagatatu.
Ntegerezwa gutaha.
Ntusubire kubikora.
Urantegera.
Ntaco ndabiziko.
Kubera iki tutaja imuhira?
Urya mugambi wari uwande?
Ntimushaka kumenya ivyabaye?
We si umwana.
Data wanje ntari imuhira.
Arazi ko umukunda?
Urashobora kugendayo.
Abashakashatsi bubutse ku magufa y'umuntu mw'isenga.
Uramuzi?
Turavukana.
Turajana?
Simbizi.
Aramutegera.
Amadirisha araguruye.
Ndazi izina ryiwe gusa.
Akinirahe?
Ntushaka kubimenya!
Nzokunezereza.
Mubaze izina ryiwe.
Kubera iki urwanko rwinshi?
Aba ngaha?
Imana iguhezagire!
Sintegera igifaransa.
Ikiganza gifise intoki zitanu: urukumu, inkombarukoko, msumba zose, igihugunibenga, agahererezi.
Ndamukunda.
Si umunsi wanje.
Sinzi izina ryiwe.
Urafise umuduga?
Urazi aho arihe?
Bitwarire nyoko.
Ndabitegera.
Ntanumwe abizi.
Sinshaka kukubona.
Ntibinshimishije.
Musazawe arihe?
Iyo aguma imuhira uyo munsi, ntiyogize isanganya.
Ndazi ingene bikorwa.
