Urakunda kwiga?
Njana i muhira.
Mpamagara hagati y'isaha imwe n'isaha zibiri.
Bishire nyoko.
Bitwarire nyoko.
Nzanira ingwa zibiri.
Uriga igifaransa?
Maze kuduga aka gasozi niruka, ugusemagurika ni kwose.
Banze imbere, ndakurikira.
Utaha ryari?
Uhaguruka ryari?
Uvyuka ryari?
Ibi biro ni ivyande?
Ikosa ni iryande?
Ubu buriri ni ubwande?
Iyi koti ni iyande?
Iyi nomero ya terefone ni iyande?
Iri saho ni irya nde?
Iri terefone ni iryande?
Iki cayi ni icande?
Iyi nzoga ni iyande?
Iyi nzu ni iyande?
Ikosa ni iryande?
Iri kosa ni iryande?
Izi mpapuro ni izande?
Usa gute?
Usa gute?
Reka gusoma.
Reka gutungira ijisho amabere yiwe!
Hagarika uyo muduga.
Uracababara ku kuguru kwawe kw'ibubamfu?
Urafise ico gusoma?
Urafise ikintu co gusoma?
Urafise umuduga?
Urafise musazawe?
Urafise mwenewawe?
Urafise uwo muvukana?
Muragaba k'umutwe wanyu.
Muritwararikire umutwe wanyu.
Uyu munsi ni umunsi w'Imana.
Uyu munsi ni kuwagatatu.
Woba ufise akanya ko kumfasha ikintu?
Woba ufise akanya?
Nagasaga!
Murafise umuceri?
Haraho mwabonye uyu mugabo?
Mwarabonye uyu mugabo?
Neza, nawe?
Kaze iwacu!
Ijoro ryiza!
Ikibazo ciza.
Urugendo rwiza!
Bisa neza.
Nyene ikintu ni musazanje.
Bitebe bitebuke bizoba.
Bitebe bitebuke bizoshika.
Bigurwa angahe?
Kigurwa angahe?
Bikuvako.
Birampimbaza.
Ntibindaba mugihe ahimbawe.
Sico gituma.
Siyo mvo.
Ntibimara umwanya mu nini.
Biraduhimbaye cane.
Biratunezereje cane.
Birakwiye.
Biragushimisha?
Uraberewe.
Biragenda?
Ibi nivyo bigezweko.
Iki nico gikurikira.
Iki nico kiramukiwe.
Iri darapo ni nziza cane.
Muri ino gant hari intoboro ku rukumu.
Uyu muhungu ni mwenebabo.
Vyanteye kukwiyumvira.
Ivyo bizonezereza.
Ivyo bizonezereza.
Biragushimishije?
Birakunyuze?
Iki gitabo ni ciza cane.
Iki gitabo ntigifise akamo.
Iri jambo ryamuka mu kigereki.
Iri jambo riva mu kigereki.
Uru ruhome rurakanye.
Si neza.
Si vyiza.
Ntibimeze uko uvyiyumvira.
Ntibiri nkuko uvyiyumvira.
Siko biri nkuko uvyiyumvira.
Nta kamaro.
Ntibikenewe ko mwihisha.
Ntibikenewe ko mwinyegeza.
Sico gituma.
Siyo mvo.
Si umuduga wanje.
Si umunsi wanje.
Sibiraba amahera.
Hari ikindi mwipfuza?
Ayo mashurwe ubona ni amarosi.
Ibi bitabo ni rwacu.
Izi mpapuro ni izande?
Abo ni abavukanyi banje.
Reka gutanga amategeko ngaha!
Reka gutegeka ngaha!
Ni vyiza uko biri.
Ni neza, siko?
Ni vyiza, sivyo?
Birera?
Ni neza, siko?
Ni vyiza, sivyo?
Uru ni urukundo?
Capfuye?
Nico ndiko ndondera.
Nico nshaka kumenya.
Mwama kubivuga.
Mwama kubivuga.
Ni angahe?
Birababaje, umugenzi wanje mukuru arimutse, yimukiye mu kindi gisagara.
Ni rwacu.
Ni rwacu.
Iyi nyabu ni yanje.
Ni umuduga wanje mushasha.
Ni vyiza gusumba uko biri.
Iyi nyabu ni yanje.
Uyu ni data wanje.
Ni naco gituma ndagukunda.
Ni ku wagatandatu.
Ni umuduga wiwe.
Ni akazi kiwe.
Ni neza cane.
Ku bwanje harakanye birengeye.
Ku bwanje harakanye birenze.
Ibi ni birebire birenze urugero.
Ni birebire birenze urugero.
Ni bitoya birenze.
Ni bitoya birenze urugero.
Ni umunyeshuri mwiza.
Ni umugambi mwiza.
Ni umuntu mwiza.
Ni umuhungu muremure.
Iki giti kirashaje.
Uyu mukobwa yiyambika nk'umuhungu.
Uyu mwigeme yiyambika nk'umuhungu.
Uyu mwigeme asa neza.
Aya masanganzira afise impanuka y'urupfu.
Ibarabara riri urwamo rwinshi.
Iyi hinguriro rikora ivyuma vy'imiduga.
Iyo mesa ishaje iracakenewe.
Iyo mesa ishaje iracakoreshwa.
Uyu muduga usa na mushasha.
Tanga akaryobwa.
Kigurwa angahe?
Wanyoye ibikombe vy'ikawa bingahe?
Uzomara igihe kingana iki?
Uzomara umwanya ungana iki?
Bite uyu munsi?
Umuryango umerewe gute?
Yitwa ngwiki kandi?
Umuryango umerewe gute?
Bite uyu munsi?
„Namaki?“ – „Nameza, murakoze!“
Mushikawe amerewe gute?
So wawe amerewe gute?
Imuhira bite?
Murategera igifaransa?
Urazi izina ryiwe?
Kubika ahakanye kandi humutse.
Kubika ahapfutse kandi humutse.
Bandanya!
Komeza!
Ego, nzogikomanda.
Reka ndagitumeko.
Sawa, nzogikura.
Sawa, nzogitumako.
Ibice binini vy'bahari birabangamiwe n'umwanda.
Mubaze izina ryiwe.
Iki ciyumviro cari icande?
Bikozwe muki?
Ururuka!
Imana iguhezagire!
Babarire ivyashitse.
Mbwirizwa kwugurura idirisha?
Mpa ico kunywa.
Mpa ikintu co kunywa.
Mpa isaha yawe.
Ryama neza, Timmy.
Ubikuye hehe?
Muvahe?
Uva hehe?
Muzinaniye hehe?
Mu ruguma hari amashira.
Umviriza nyoko!
Tega amatwi!
Eh, ushaka kuja hehe?
Arakeneye amazi.
Afise ibitabo amajana n'amajana.
Yarezwe na nyirakuru.
Yavyaye umwana wa mbere afise imyaka mirongo ibiri.
Arakunda gusoma ibitabo.
Yatetse umutaga wose.
Yatetse umutaga wose.
Yataye urupfunguzo rw'umuduga wiwe.
Yamugomwe.
Yamukunze.
Aribungenze.
Ni umufaransa.
Aranezerewe.
Aramukunda.
Aramwumva.
Ntiyasomaye iki gitabo.
Ntiyibungenze.
Siho ari.
Ntibamuriha ku kwezi ahubwo ku munsi.
We si umwana.
Ntabana nawe.
Asa na nyina.
Asa na nyina wiwe.
Yamoye umutwe wiwe.
Bambonye.
Bambonye.
Ntibashaka kubikoresha.
Ntibafise amahera.
Baratuzi.
Bazomenya uko bagira.
Bobo ni abana.
Bashaka ko tubigira.
Bashaka ko tubikora.
Abana na we.
Ntanumwe amuzi neza kiretse abavyeyi biwe.
Nimukure ibirato vyanyu.
Nimwambure ibirato vyanyu.
Injira.
Ico nico uriko urondera?
Nivyo urondera?
Ubironderera aha?
Ubironderera ngaha?
Urondera ibi aha?
Ni uyo wabonye?
Ndazi Tom?
Ineza ihimbara abantu gusumba ubwiza?
Araguzi?
Nyoko ari imuhira?
Tom nihari nawe?
Urafise aya mahera?
Wasomye iki gitabo?
Waravye itelevisiyo uyu mugoroba?
Urafise umuduga?
Uranywa itabi?
Urazi icarico urukundo?
Urazi aho arihe?
Urashaka ko nza?
Muranywa itabi?
Ntimubitegera?
Ntimubitegeye?
Ni binini birenze?
Ni birebire birenze?
Ni bitoya birenze?
Ni mushiki wawe?
Ni umunyamerika?
Igihe carenze?
Uri iwacu?
Uri iwawe?
Uranezerewe?
Uranezerewe?
Uri umunyeshuri mushasha?
Muri abanyeshuri?
Muri abanyeshuri?
Kubera iki tudataha imuhira?
Naraje ejo.
Mbabarira!
Kora ibikorwa vyawe vy'ishure.
Imbere yo gukatira iburyo mu masanganzira, gensura ko ata munyekinga aje.
Kore igikenewe.
Ugara idirisha!
Ugara idirisha.
Ugara amadirisha yose.
Uba ngaha?
Ejo naryamye umunsi wose, kuko wari umunsi w'Imana.
Ejo hari kuwagatanu.
Yagirije uyo mugabo ubusuma.
Yaryamye isaha imwe.
Yakarihije igisu.
Arakunda gusoma ibitabo.
Yazunguje umutwe.
Afise umuduga.
Arumva igifaransa.
Yamugomwe.
Yamukunze.
Ariko yiga.
Aranezerewe.
Yagarutse mu kwezi kw'umunani guheze.
Yagarutse muri Myandagaro iheze.
Yagarutse ino.
Yagarutse ngaha.
Ni isaha icenda ibuze iminuta icumi n'itanu.
Yaje wenyene.
Harashushe cane ngaha.
Harashushe birenze.
Mubwirizwa kunyaruka.
Mubwirizwa kwihuta.
Aramukunda.
Urupapuru rumwe rurabuze.
Ntegerezwa kuja imuhira.
Mbwirzwa guhagarika.
Mbwirizwa guheraheza.
Mbwirizwa kureka.
Ndakeneye umwanya wo kwiyumvira.
Nkeneye umwanya wo kwiyumvira.
Mbwirizwa kwiyumvira.
Mbwirizwa kukubona.
Yarabimpaye.
Ntasa n'uwunezerewe.
Ntanzi.
Ntadukunda.
Ntavuga icongereza.
Sibijanye n'amahera.
Siho ari.
Ngirango ntanezerewe.
Tubwirizwa tubijamwo ningoga.
Nta bundi buryo.
Imana ntibaho.
Nta mana ihari.
Nta ngorane.
Nta numwe ahari!
Nta mazi akiri mw'icupa.
Nta wundi muntu yarahari kiretse jewe.
Avuga icongereza neza.
Yafashe ikinyugunyugu n'urukumu hamwe n'inkombarukoko.
Asa na nyina.
Asa na nyina wiwe.
Asa na Se wiwe.
Asa na musazawe.
Asa na mwenewanyu.
Bavuga ko atunze cane.
Ngirango ntubikunda.
Iminsi yose aja ku kazi ku maguru, kiretse iyo hari imvura.
Iminsi yose aja ku kazi ku maguru, kiretse iyo imvura igwa.
Bambonye.
Bambonye.
Ntavyo bazi.
Ntibakunezereza.
Ntibashaka kubikoresha.
Ntibaza uyu munsi.
Ntibafise amahera.
Baratuzi.
Bazomenya uko bagira.
Bobo ni abana.
Baranezerewe.
Bashaka ko tubigira.
Bashaka ko tubikora.
Akora mw'ihinguriro.
Haraza gushuha.
Ngirango araza uyu munsi.
Ngirango araza.
Hari ico nshaka kuvuga.
Mu buseruko bw'ikigwati hari ikiyaga.
Hari ijana y'abantu mu ngoro.
Ndakunda ico nkora.
Ndakunda ibiharuro.
Ndakunda kukuraba uteka.
Ndakunda kuraba ingene uteka.
Naguze amagi n'amata make.
Narakunze uyu muduga.
Ndakeneye abakozi b'abitanzi batatu.
Natanguye gukora muri ino societé kuva umwaka uheze.
Natanguye gukora muri ino societé kuva umwaka uheze.
Ndarurumba.
Ndafise amahera.
Ndafise ibikorwa vy'ishure.
Mfise benewacu.
Ndafise bashikanje.
Navuze ko bimbabaje.
Mu mwaka uheze navyaye imfura yanje.
Nahaye umuhungu igitabo.
Ejo naryamye umunsi wose, kuko wari umunsi w'Imana.
Nagize igitondo c'imirimo myinshi.
Ndashonje.
Iyi kanzu nijewe nayigiriye.
Iyi kanzu nijewe nayikoreye.
Ndaribwa mu nda.
Ndakunda iyo ndi jenyene.
Ndakunda kwiga igifaransa.
Ndakunda imishatsi migufi.
Ndakunda ibiharuro.
Ndakunda ibiharuro.
Ndakunda gusoma.
Ndakunda umuryango wanje.
Ndakunda kuba ngaha.
Umuduga wanyu uranshimisha.
Ndakunda umuduga wanyu.
Niibagiye kugura umukate.
Navuganye n'umuganga wawe, yambwiye ko ngo ubwirizwa kuguma mu gitanda indwi yose iburiburi.
Nataye impfunguzo zanje.
Narataye amarori yanje.
Naratakaje ikaramu ryanje.
Ndahatswe gutura amasahani hasi.
Amahera narayakiriye.
Nasivye kw'ishuri.
Mfise imbwa zitatu.
Ndafise imbwa zitatu.
Ndafise ubwato.
Ndafise ikibazo.
Ndafise umuduga.
Mfise mukuruwanje.
Nabaye ngaha igihe kirekire.
Ndashaka kukubona pe.
Nzero ni ukwezi kwambere mu mwaka.
Nzero, Ruruhuma, Ntwarante, Ndamukiza, Rusama, Ruheshi, Mukakaro, Myandagaro, Nyakanga, Gitugutu, Munyonyo na Kigarama ni amezi icumi n'abiri y'umwaka.
Niga igifaransa mw'ishure.
Ndondera inzu mu gisagara, ata cizero.
Ndategera ico ushaka kuvuga.
Ndategera ico uvuga.
Ndategera.
Ndazi aba bagore.
Ndazi aba bantu.
Ndazi aba bantu.
Ndazi uyo mukobwa.
Ndazi uyo mwigeme.
Ndazi umuryango wiwe.
Ndazi nyoko.
Ndazi so wawe.
Ndakwemera.
Nanje ndururutse.
Mvuga ico niyumvira.
Mbirizwa kwiga gifaransa.
Mbwirizwa kwiga.
Mbirizwa kwiga gifaransa.
Ntegerezwa gutaha.
Nryama ubusa.
Nryama ubusa.
Ndi mu karuhuko.
Ndi mu kiruhuko.
Nzokora ico unsaba.
Ndamuzi.
Nabigiriye wewe.
Ndamukunda.
Namuburiye.
Narabiravye muri yu tubi.
Namubonye yiruka.
Ndamubonye.
Ndamubonye.
Noshimishwa no kumubona.
Mpora mesura isutiye yanje n'amaboko.
Ndavyumva
Ndamuzi.
Ndazi izina ryiwe gusa.
Ndabigirira kubera wewe.
Ndabikorera wewe.
Nanje ndavyiyumvira uko.
Ndavyakira.
Nosubira kubikora.
Nzobiraba.
Ndabizi.
Nari mbizi.
Nzobigerageza.
Nitwa Jack.
Ndibaza, icamushikiye.
Aho ufungura ku mugoroba sindabinzwe.
Ndakunda aho mba.
Ndiko nduhuka.
Ndibuka aho ubwambere.
Nikomerekeje n'igisu ku rutoki.
Nikomerekeje n'imbugita ku rutoki.
Nariyumviye kuguma iminsi mike iwawe.
Namerewe nabi.
Sindakunda kwiga.
Sinkunda aba bantu.
Sinkunda kwiruka.
Sinsa uko.
Simfise amahera.
Simfise aho mba.
Simfise imuhira.
Simfise musazanje.
Simfise mwenewacu.
Nta bitabo mfise vyo gusoma.
Simfise mushikanje.
Simfise mwenewacu.
Nta muduga mfise.
Sindashaka kuba ngaha.
Sindashonje.
Sinshonje.
Nta mwanya mfise wo gusinzira.
Sinashoboye kutarira.
Ndasemagurika.
Sinshobora kuvyuka.
Sinywa.
Ntaco nywa.
Sindabitegera.
Sintegera iri jambo.
Sintegera igifaransa.
Sinumva igifaransa.
Iryo jambo ntaryonzi.
Sinzi iryo jambo.
Sinzi aba bantu.
Sinzi izina ryiwe.
Sinzi izina ryawe.
Sinteka.
Sindamuzi.
Ndazi izina ryiwe gusa.
Sindavyumva.
Simbizi.
Sindamubona.
Simbesha na rimwe.
Siniyumva neza ngaha.
Simbikeneye.
Sindabikeneye.
Ntaco ndabiziko.
Ntibinshimishije.
Ntibinyuze.
Ntibinshimishije.
Ntibinyuze.
Ntibimpa agateka.
Ntibintera iteka.
Ntibimpa agateka.
Ntibintera iteka.
Sinibaza ko aza.
Sinshobora kuvyibagira.
Sinzi ico novyiyumvirako.
Sinzi gute.
Sinzi ingene.
Sinzi guteka.
Sinzi iyo ngana.
Sinzi aho bari.
Sinzi aho aba.
Sinzi aho aba.
Sinzi aho bari.
Sinzi igihe bifata.
Sinzi igihe uko kingana.
Sinzi igihe bifata.
Sinzi igihe uko kingana.
Sinzi ico nokora.
Sinzi.
Ku minsi y'Imana simba ndi imuhira.
Singushimye.
Sinkugomwe.
Sinkomeye muri vyo.
Sinzi neza igifaransa.
Sinkomeye muri vyo.
Sinzi neza igifaransa.
Sindi umutunzi.
Sintunze.
Sindi umunyeshuri.
Sindi umunyeshuri.
Sindi umunyeshuri muri kaminuza.
Sindi ikijuju.
Sindagutegera.
Sindakwumva.
Sinzobikubuza.
Simbiheba.
Sinzorabayo.
Sinshaka guheba.
Sinshaka guteka.
Sinshaka amahera yawe.
Sinshaka gutunga.
Sinshaka kuba umutunzi.
Sinshaka kubimenya.
Sinshaka kubisoma.
Sinshaka kukubona.
Sindashaka kurwara.
Ntitujana.
Ntitujana.
Biranshimishije.
Biranyuze.
Biranshimishije.
Biranyuze.
Aho biri ndanezerewe.
Biranshimishije.
Ndumva ico uvuga.
Mara umwanya munini niga igitari.
Niyumviye ko vyogutwenza.
Nagira ngo ni ikigorwa cawe.
Nagira ngo niwe ncuti idasumbwa.
Nagiro ngo niwe ncuti itarutwa.
Nagira ngo urashobora kubitegera.
Nagira ngo woba watashe.
Nagira ngo urabizi.
Nagira ngo woba watashe.
Nagira ngo woba watashe.
Ndakwiyumvira.
Ndibaza ku mfise umwanya w'ikindi gikombe c'ikawa.
Ndibaza ko ari vyiza.
Ndibaza ko ntegeye.
Ndibaza ko azoza.
Ndashobora kwinjira?
Ndashobora kugutegera.
Ndakira ibi.
Kira gitondo mva imuhira imbere y'isaha zibiri.
Nzogaruka.
Ndazi ico nkora.
Ndazi ico nogira.
Ndazi ico nokora.
Ndazi ico nzokora.
Ndazi ico bagira.
Ndazi ico baravuze.
Ndazi ico wiyumvira.
Ndazi uvyirumvira.
Ndazi ico bagira.
Ndazi ico baravuze.
Ndazi ikiriko kiba.
Ndazi ingene bigirwa.
Ndazi ingene bikorwa.
Ndazi kubikora.
Ndazi aho ari.
Ndazi aho turi.
Ndazi aho uba.
Ndazi igituma uri ngaha.
Ndazi ko wabivuze.
Ndazi ko ubifise.
Ndazi ko ubizi.
Ndazi aho mbwirizwa kugaba.
Ndazi ico mbwirizwe kwiga.
Ndazi ibikenewe gukorwa.
Nzi ico gusa.
Nzi ivyo gusa.
Narinzi ko wojayo.
Narinzi ko vyogushimisha.
Narinzi ko uri ngaha.
Nzoba ndi mu muduga wanje.
Nzohaba ejo.
Nzogerageza.
Ndi imuhira.
Namugomwe.
Namugwiriye.
Namukunze.
Ndi umwotsi w'imikate.
Ndi umwotsi w'imikate.
Ndazi neza ko hari aho maze kumubona.
Ndazi neza ko namubonye ahantu ikindi gihe.
Ndazi neza ko hari aho maze kumubona.
Ndazi neza ko namubonye ahantu ikindi gihe.
Ndi iwanje.
Ndi umushinwakazi.
Ndanezerewe ko ariho uri.
Ndanezerewe ko uhari.
Ndanezerewe ko ariho uri.
Ndanezerewe ko uhari.
Ndi umutetsi.
Numva amatsiko.
Ndi mu gikoni.
Ndi mu muduga.
Mpore ko ndabivuze.
Urambabarira ko ndabivuze.
Uranhunga ko ndabivuze.
Mpore ko ndabivuze.
Urambabarira ko ndabivuze.
Uranhunga ko ndabivuze.
Mbabarira ko nagutaye mu rudubi.
Ntunga ko nagutaye mu rudubi.
Mbabarira ko nagutaye mu rudubi.
Ntunga ko nagutaye mu rudubi.
Mpore ko ndabivuze.
Urambabarira ko ndabivuze.
Uranhunga ko ndabivuze.
Mpore ko ndabivuze.
Urambabarira ko ndabivuze.
Uranhunga ko ndabivuze.
Mbabarira ko nagutaye mu rudubi.
Ntunga ko nagutaye mu rudubi.
Ndi umwigisha.
Ndi umwigisha.
Ndiko ndasoma igitabo.
Ndi umunyeshuri muri kaminuza.
Ndanezerewe ko ariho uri.
Ndanezerewe ko uhari.
Ndanezerewe.
Ndanezerewe ku uhimbawe.
Ndanezerewe ko ariho uri.
Ndanezerewe ko uhari.
Ndi ngaha kubera wewe gusa.
Ndi umuhererezi.
Ndi umuhererezi.
Ndi umunyeshuri mushaha muri kaminuza.
Ndi umunyeshuri mushaha muri kaminuza.
Naje kubera wewe.
Naje kukurondera.
Naje kukurondera.
Nazanwe no kwiga.
Nazanwe no kwiga.
Nje kugutwara i muhira.
Naragukunda.
Naragukunda.
Ndagukunda.
Ndagukunda.
Ndakubonye.
Ndakubonye.
Ndakujana.
Nzokurindira.
Ndakurondera.
Ndakuzi.
Nzoguha igitabo.
Nzobiguha.
Ndaguhwatira umucungwa.
Nzogushimisha.
Nzokunezereza.
Nzokunyara.
Nzogushimisha.
Nzokunezereza.
Nzokunyara.
Niga igifaransa mw'ishure.
Ndiga igifaransa imuhira.
Ngiye guzana umuduga wanje.
Ndagenda kuryama.
Ndabitwara.
Nzogenda n'umuduga.
Nzogushimisha.
Nzokunezereza.
Nzokunyara.
Ngurisha impuzu ku murongo.
Nshaka gutaha.
Nshaka kwiga igifaransa.
Nshaka kugutekera.
Nshaka kwiga igifaransa.
Ndashaka gusoma iki gitabo.
Nshaka ko uja imuhira.
Nshaka ko utaha.
Nshaka ko uja imuhira.
Nshaka ko utaha.
Nshaka ko umubona.
Ndashaka ko usoma iki gitabo.
Nshaka ko ubimenya.
Nshaka ko mubibona.
Ndashaka kuguherekeza.
Nshaka kuganira nawe.
Ndashaka gusubira kukubona.
Nshaka kukubona.
Ndashaka kubana na wewe.
Nshaka kubibona.
Ndashaka kukubona pe.
Nzoza kugutora.
Natsitaye kw'ino.
Mva muri Bresil.
Nje gusezera.
Ndababonye.
Ndababonye.
Ndabubaha.
Mba ngaha.
Sinzi aho aba.
Sinzi aho muba.
Sinzi izina ryawe.
Nzoza kugutora.
Navyiyumviye.
Nabonye hariya mushikanje.
Nahabonye mwenewacu.
Idirisha riraba mu rugo.
Uramukunda?
Reka nje kugura umukate.
Reka ndakugurire gishasha.
Reka ndakugurire gishasha.
Reka ndabe.
Ikiganza gifise intoki zitanu: urukumu, inkombarukoko, msumba zose, igihugunibenga, agahererezi.
Urukundo rurahuma.
Ivyirabura ni vyanje.
Ikanzu rikozwe mw'iharire.
Nguyo!
Nguyo araje!
Umuduga wa data ni mushasha.
Umuduga wa data ni mushasha.
Umuduga wapfuye.
Umuduga wapfuye.
Umuduga wapfuye.
Ibisi irahagaze ariko nta muntu yururutse.
Igitwazi kirasimba.
Hari ibicu vyinshi vyirabura mu kirere.
Umuhungu arasimba.
Intwaro iritwararika cane iki gikorwa.
Uyo muti urabaho mu mama?
Umubaji arapima isi.
Ku wambere musée yama yugaye.
Ivyirabura ni vyanje.
Igiciro kiraduga.
Igiciro kiraduga.
Ibitoke bisa n'umuhondo.
Imbwa zihamba kenshi amagufa.
Ishure riraheze.
Inzoka yamize igikere.
Ayo madirisha yerekeye mu bumanuko.
Amadirisha araguruye.
Abahungu barabaza ibibazo.
Ku mugoroba kuva isaha cumi na zibiri gushika isaha zibiri ni igihe co kunezerwa.
Izuba rirasira mu buseruko.
Ibiciro vyaraduze.
Amatapi yo mukahise arafise agaciro kanini.
Igihe ntikigize gukanya gusa, kiranajovye.
Umudandaza yaduhaye inshumbushanyo nini.
Umudandaza yaratugabanirije cane igiciro.
Nguyo araje!
Nguyo arashitse!
Soma ibi.
Soma!
Ihinguriro rikora ibihumbi n'ibihumbi vy'amacupa kira kwezi.
Ihinguriro rizotangura gukora mu mwaka uza.
Umuryango wanje ni muto.
Umukobwa wanje azorongorwa mu kwezi kwa gatandatu.
Umukobwa wanje azorongorwa muri ruheshi.
Magdalena na Ania ni abagenzi pfampfe.
Mize ndababara mu muhogo.
Nyogokuru avuga buhoro buhoro.
Ko turi twenyene, reka twiryohere.
Ko turi twenyene, reka twiryohere.
Inzu yanje iri hafi y'inyubakwa yo gusengeramwo.
Inzu yanje iri hafi y'isengero.
Inzu yanje iri hafi y'urusengero.
Mushikanje ni mwiza.
Mushikanje asa na Mama.
Umuduga wanje wapfuye.
Umuduga wanje wapfuye.
Murakoze cane.
Urakoze cane!
Urakoze cane.
Urakoze kwicisha iwacu.
Urakoze kwicisha iwacu.
Urakoze kwicisha iwacu.
Urakoze kwicisha iwacu.
Murakoze kuza.
Urakoze kuza.
Murakoze kuza.
Urakoze kuza.
Urakoze kuza.
Murakoze!
Urakoze!
Abavyeyi banje bampamagara kira munsi.
Nanje.
Ukuboko kwanje kw'ibubamfu kwagize ibinyanya.
Musazanje ntari i muhira.
Izina ryanje ni John.
Ipantalo yanje yajovye.
Data ari imuhira.
Data wanje ntari imuhira.
Indoto yanje yabaye ukuri.
Amasobe yanje ntarongorotse.
Umubanyi wanje ni umubaji.
Ntubinywe!
Ntimubitegera?
Ntimubitegeye?
Ntusabe amahera.
Ntubaze.
Ntumuhagarike.
Ntimubitegera?
Ntimubitegeye?
Ntumwumvirize.
Ntusubire!
Ntusubire kubikora.
Ntimusubire!
Ntimusubire kubigira.
Ntuntere kubivuga!
Ntumbwirize kubikora.
Ntumpate kubikora.
Ntumpebe.
Ntundabe gutyo.
Reka kundaba!
Ntusubire kumbaza.
Ntumpate kubikora.
Ntutwibagira!
Ntugende n'iminwe misa.
Ntugende zirayoye.
Nturabe hasi.
Nturabe munsi.
Ntimusubire kugaruka.
Ntuzi icarico?
Ntiwitinye.
Ntushavure!
Ntimushaka kumenya igituma?
Umuntu wese arashobora kubisoma.
Oya, urakoze.
Ntavuga icongereza gusa, avuga kandi n'ikidagi.
Umwanya wacu uraharuye.
Ntiwibagire gutwara ibaruwa.
Ntiwibagire gutwara ikete.
Ntiwibagire kubaza ibindi bibazo.
Ntiwibagire gutwara ibaruwa.
Ntiwibagire gutwara ikete.
Turakunda pariki yacu.
Rimwe rimwe tujana muri cenema.
Twamanutse twiruka agasozi.
Dufise amatwi abiri.
Twarukiye hamwe.
Muraturondera?
Ni twebwe murondera?
Turategera.
Turumva.
Tubwirizwa gushira uburinganire hagati y'bisohoka n'ivyinjira.
Turiga igifaransa.
Turaruhuka mu kanya.
Turamuzi.
Turabitegera.
Turamuzi.
Nta mahera dufise.
Ntidufise amahera.
Nta muduga dufise.
Ntitubwirizwe kubivugana ubu nyene.
Ntitumuzi.
Ntituri twenyene.
Ntituri twenyene.
Ntidushaka kubimenya.
Turumvikana.
Twasezeye.
Twatandukanye.
Twavanye.
Twatandukanye.
Twavanye.
Turiko dutakaza umwanya uzimvye.
Kenshi twagarutse zirayoye.
Turi imuhira.
Twashitse.
Turageramiwe.
Turagarutse.
Turavukana.
Turavukana.
Ni mwenewacu.
Turavukana.
Turanezerewe.
Turi ngaha kubera wewe.
Turi ngaha kubwawe.
Turi twenyene.
Turi twenyene.
Turanezerewe cane.
Twaje kugusura.
Turakuzi.
Dushaka ko ubitwara.
Dushaka ko ubitwara.
Turagenda kenshi yo.
Ntimwugurure idirisha.
Oh, mpore.
Bavuga ko atunze cane.
Turamuzi.
Tuzobonana ejo!
Tuzongera ku wambere.
Mugenda hehe?
Tuja hehe?
Vyibagire ivyo.
Abantu bose bagiye hehe?
Ushaka kuba hehe?
Mugenda hehe?
Umuduga urihe?
Umutetsi arihe?
Igitabo kirihe?
Mama wanje arihe?
Isaha yanje irihe?
Mariya arihe?
Umuduga wanje urihe?
Amahera yanje ari hehe?
Umuryango wiwe urihe?
Nyoko arihe?
Isaha yawe irihe?
Umuduga wawe urihe?
Tom arihe?
Musazawe arihe?
So arihe?
So wawe arihe?
Urihe?
Warihe?
Warihe?
Uba he?
Akinirahe?
Turihe?
Turi hehe?
Ibirato birihe?
Ibintu vyawe birihe?
Ndi hehe?
Bagutwaraye hehe?
Bagutwaraye hehe?
Ugenda kw ishure hehe?
Ushaka kuja hehe?
Ushaka kuba hehe?
Uba he?
Twugurure idirisha!
Data ntari i muhira.
Mbwira umugambi wawe.
Nganirira umugambi wawe.
Ngaha nta numwe afise umuduga.
Ntanumwe yabonye ikintu.
Ntanumwe azi amazina yabo.
Ntanumwe azi izina ryiwe.
Ntanumwe yumviriza.
Ntanumwe abizi.
Ntanumwe antega ugutwi.
Ntanumwe azi amazina yabo.
Ntanumwe arazi aho turi.
Ntanumwe arazi aho turi.
Ntanumwe azi ibikenewe gukorwa.
Ntanumwe azi izina ryiwe.
Ntanumwe yarazi ibikenewe kurangurwa.
Ntanumwe ari i muhira.
Nta numwe ahari!
Ntanumwe yakubajije.
Ngirango ntaza.
Ngirango azoza ejo.
Urashobora gutandukanya intama n'impene.
Urazi gutandukanya intama n'impene?
Urashobora kurungika umuntu ngo abikiranure mu maguru masha?
Urashobora kurungika umuntu ngo akemure ingorane mu maguru masha?
Nimumutware mu cumba co kubaga.
Umfata ko ndi nde?
Kubera iki ubaza?
Kubera iki mbwirizwa kugenda.
Kubera iki mbwirizwa kubikora?
Kubera iki mbikora?
Kubera iki wiga muri kaminuza?
Kubera iki utari kumwe na jewe?
Kubera iki wijiriwe?
Kubera iki muri imuhira?
Kubera iki wiga igifaransa?
Kubera iki mbikora?
Kubera iki tubikora?
Kubera iki tugira ivyo?
Kubera iki babikora?
Kubera iki babikora?
Kubera iki mbikora?
Kubera iki ijuru risa n'ubururu?
Kubera iki jewe?
Kubera iki udaheba?
Kubera iki ataho tutajana?
Kubera iki utumviriza?
Kubera iki batankunda?
Kubera iki batankunda?
Kuki utinjira?
Kubera iki tudataha imuhira?
Kubera iki mutagerageza iyi goti? Ijanye neza n'ipantalo yanyu.
Kubera iki utari kw ishure?
Kubera iki utari mw'isomero?
Kubera iki utaciga igifaransa?
Kubera iki wibaza ivyo?
Kubera iki bari aha?
Kubera iki bari aha?
Kubera iki ndi ngaha?
Kubera iki urwanko rwinshi?
Kubera iki ubibaza?
Kubera iki unkunda?
Kubera iki utabikora?
Kubera iki utari aha?
Kubera iki udataha?
Kuki utaja imuhira?
Ntiwoshobora kubisubira ico wavuze?
Murashobora kwugurura idirisha?
Akira ico ushaka.
Akira amahera.
Akira igitabo usome.
Ndashobora kwinjira?
Ndashobore kubikoresha?
Ndashobora kuza nanje?
Ndashobora kuza nanje?
Ndashobora kubona itike ryanyu.
Uzoza iwawe ryari?
Uza imuhira ryari?
Aza ryari?
Ugenda ryari?
Ivyo ni ibiki?
Munywa iki?
Urondera iki?
Wipfuza iki?
Ukora iki ngaha?
Ukora iki, data?
Ukora iki?
Mukora iki?
Bakora iki ngaha?
Ufise imyaka ingahe?
Afise imyaka ingahe?
Ivyo birashavuza!
Ivyo bitera ishavu!
Igituma c'urugendo rwanyu ni nyabaki?
Intumbero y'urugendo rwanyu ni iyihe?
Igituma c'urugendo rwanyu ni nyabaki?
Intumbero y'urugendo rwanyu ni iyihe?
Ashaka gushika kuki?
„Ni ryari?“ — „Ni isaha zine n'igice.“
Iciyumviro nyabaki!
Ni umunsi!
Wari umunsi!
Wibaza ko ico ariki?
Uzi iki?
Nibiki bibaye ngaha?
Ni igiki ntategera?
Urukundo ni iki?
Urondera iki?
Ukora iki ngaha?
Ubu ukora iki?
Ukora iki?
Uraba iki?
Urashaka kuraba iki?
Uripfuza kuraba iki?
Mukora iki?
Nibiki bibaye ngaha?
Bakora iki ngaha?
Hariko haba iki hariya epfo?
Urukundo ni iki?
Mbe nambare iki - ipantalo canke ijipo?
Ushaka kubimenya iki?
Ubona iki?
Umwigisha wanyu ni nde?
Ninde asoma?
Wibuke ubuntu bwawe kandi wibagire ibisigaye.
Wibuke ubuntu bwawe wiyobagize ibindi.
Subira kubivuga.
Raba iyi foto.
Raba neza ingene ndabikora!
Raba hariya!
Rabira mw'idirisha.
Ni murabe neza iri foto.
Ntaco bibaye.
Urazi icarico?
Urazi ico yavuze?
Urazi ico bashaka?
Urazi icarico urukundo?
Urazi icarico urukundo?
Urazi ico yavuze?
Urazi ico bashaka?
Urazi aho arihe?
Urazi aho aba?
Urazi aho bari?
Urazi aho biri?
Urazi aho arihe?
Urazi aho aba?
Urazi izina ryiwe?
Murazi aho mba?
Iyo menya sinari kuza.
Ntariye nopfa.
Ku muntu agerageza gutegera, iryo kete ni akamo k'amahera mu maguru masha.
Umuntu asomye neza agategera, iryo kete ritaka imfashanyo y'amahera mu maguru masha.
Hatari ubu, ryari?
Iyo udategereye, baza.
Abo nabo mu bujapani?
Abo ni abajapani?
Ni abanyamerika?
Abo nabo mu bujapani?
Abo ni abajapani?
Ururuka mu muduga.
Sohoka mu cumba canje!
Va mu buriri bwanje!
Ja hanze.
Bitware hirya.
Jana hiyo.
Nkura ngaha.
Nimusohoke mu muduga.
Muri kino gisomwa ca umurongo munsi y'amavuga yose ya kazoza muri.
Wibuke ubuntu bwawe kandi wibagire ibisigaye.
Wibuke ubuntu bwawe wiyobagize ibindi.
Ceceka!
Numa!
Nyoko ari imuhira?
Nyoko ari imuhira?
Nyoko niho ari?
O yawe isa na A yawe.
Tom ni umubaji.
Uruhanga rwawe rurashushe cane. Ndakeeka ko ufise inyonko.
Ipantalo yawe iranduye.
Ipantalo yawe iranduye.
Amapome vyose aguye hasi azoribwa n'ingurube.
Birasanzwe.
Urarurumba.
Usa naho unezerewe cane.
Ufise imyaka ingahe?
Wagize ubwoba?
Watinye?
Ubwirizwa kuvyuka.
Uri umutetsi mwiza.
Uri iwawe?
Uri umugore nkunda.
Urarwaye, ubwirizwa kuruhuka.
Uri umugenzi wanje.
Uri umugenzi wanje.
Uri mushasha?
Waciye ku kimenyetso c'itara ritukura.
Waciye ku kimenyetso gitukura.
Waciye ku kimenyetso c'itara ritukura.
Waciye ku kimenyetso gitukura.
Urazi kubigira neza cane.
Urazi kubigira neza cane.
Uri umuvyeyi mwiza.
Ukora iki?
Kera waranywa itabi, sivyo?
Uranywa itabi?
Uba he?
Uramuzi?
Uramuzi?
Urandondera?
Urantegera.
Ndagukumbuye cane.
Umfata ko ndi nde?
Umfata ko ndi nde?
Uranezereza.
Ntubwirizwa kwandika ikete rirerire.
Ntiwakomye kw'isahani yawe na gato. Hari akakubakiye?
Ntuzi musazanje.
Ntubange ugutwi.
Nturekuriwe kwinjira.
Ntunzi.
Ntubwirizwa kuza.
Ntubwirizwa kuza.
Nturi musazanje.
Nturi mwenewacu.
Ntubwirizwa kuza.
Ntubwirizwa kuza.
Ntushaka kubimenya!
Ntushaka kumenya ivyo!
Ntukomeye muri vyo.
Ntukomeye muri vyo.
Urashobora gutera ururirimbo.
Urashobora gutora irangi iryariryo ryose rigushimisha.
Urashobora gutora irangi iryariryo ryose ushimye.
Urashobora kurara iwacu.
Ushobora gukoresha umuduga wanje mu gihe cose.
Urashobora kugendayo.
Urashobora kujayo.
Uzomara igihe kingana iki?
Urazi icarico urukundo?
Urazi aho nzoba ndi.
Urazi ko mbwirizwa kugenda.
Urazi ko ndagukunda.
Urazi ko tugukunda.
Urashaka umuduga?
Uva hehe?
Uraza? Ego canke oya?
Uba ngaha?
Ushaka kuzobibona.
Ushaka kuzobiraba.
Umunyeshuri arashaka kukubona.
Hagati y'igisigara hadutse umuriro.
Kera hari isengero ngaha.
Kera hari urusengero ngaha.
Rimwe, gatatu no gatanu ni ibiharuro bitagaburwa na kabiri.
Ja mu buriri!
Urataha?
Haraho uzogenda muri iri ci?
Uzofata urugendo wenyene?
Ndamusavye umpe urupapuro rwo kwandika.
Urashaka kuba umutunzi?
Urashaka kwinjira?
Urashaka gutunga?
Urashaka kuba umutunzi?
Urashaka kubibona?
Ushaka ko ndagusigira irangi ku nzara zawe?
Urashaka ikintu co kunywa?
Urashaka kumenya igituma?
Urashaka kureka?
Urashaka umuduga?
Nabo baraza?
Nabo baraza?
Ingo!
Ingo kunsura.
Za kunsura.
Uraza? Ego canke oya?
Uraza canke?
Uraza? Ego canke oya?
Ingo wirabiye.
Araza nawe?
Uba ngaha?
Baba iwawe?
Nuko rero nabigize.
Ngiyo ifagitiri.
Ngico igitabo cawe.
Aya ni amadolari atanu.
Nuko rero nabigize.
Umuceri utekwa uku.
Urabona iyi nzu? Ni rwanje.
Urabona iyi nzu? Ni inzu yanje.
Murashaka kubitora?
Murashaka kubitwara?
Mubwirizwa gutaha.
Mubwirizwa kugenda i muhira.
Mubwizwa gumperekeza.
Banze imbere, ndakurikira.
Muri Abadagi, sivyo?
Muri abana.
Mwebwe muri abana.
Murabona iyi nzu? Ni inzu yanje.
Turajana?
Icumba cawe gifise amadirisha abiri?
Urafise ikintu mu gutima, ushaka kwikura? Urashobora binganirira.
Hari imashini yo kumesura mu nzu?
Hari imashini yo kumesura mu nzu?
Uragenda canke?
Uragenda canke ntugenda?
