Abana bagiye kw ishure?
Abana na we.
Aba ngaha?
Abantu bose bagiye hehe?
Abashakashatsi bubutse ku magufa y'umuntu mw'isenga.
Abavyeyi banje bampamagara kira munsi.
Abo nabo mu bujapani?
Abo nabo mu bujapani?
Abo ni abajapani?
Abo ni abajapani?
Abo ni abavukanyi banje.
Abonye amaraso umurwayi yaciye araba.
Afise ibitabo amajana n'amajana.
Afise imyaka ingahe?
Afise imyaka ingana iki?
Afise umuduga.
Ahari ugushaka haba inzira.
Akinirahe?
Akira ico ushaka.
Akira igitabo usome.
Akira igitabo usome.
Akora mw'ihinguriro.
Amadirisha araguruye.
Amahera yanje ari hehe?
Amahera yarampereyeko.
Amapome vyose aguye hasi azoribwa n'ingurube.
Amatapi yo mukahise arafise agaciro kanini.
Araguzi?
Arakunda gusoma ibitabo.
Aramukunda.
Aramutegera.
Aramwumva.
Aranezerewe.
Araza nawe?
Arazi ko umukunda?
Aribungenze.
Ariko yiga.
Arumva igifaransa.
Asa na musazawe.
Asa na mwenewanyu.
Asa na nyina.
Asa na nyina wiwe.
Asa na Se wiwe.
Aya madirisha araba mu bumanuko.
"Aya marori ni ayande?" – "Ni aya Data."
"Aya marori ni ayande?" – "Nyeneyo ni Data."
Aya masanganzira afise impanuka y'urupfu.
Aya masanganzira afise impanuka y'urupfu.
Ayo madirisha yerekeye mu bumanuko.
Ayo mashurwe ubona ni amarosi.
Bamwe muri abo bakozi ntibamenyeye gukora ako kazi.
Bandanya!
Banze imbere, ndakurikira.
Baranezerewe.
Baratuzi.
Bavuga ko atunze cane.
Bavuga ko atunze cane.
Bigurwa angahe?
Bikozwe muki?
Bikuvako.
Bimuha.
Bimuhe.
Bingwa neza.
Biragenda?
Birakunezereje?
Birakwiye vyose ivyerekeye vy'urugendo?
Birakwiye vyose ivy'urugendo?
Birampimbaza.
Birera?
Biruguruye.
Bishire nyoko.
Bite, ico kunywa?
Bite! Urakomeye?
Bite uyu munsi?
Bitware hirya.
Bitwarire nyoko.
Bobo ni abana.
Capfuye?
Capfuye.
Data ari imuhira.
Data ntari i muhira.
Data wanje ntari imuhira.
Dusangire akanyobwa.
Duteka umuceri uku.
Ejo hari kuwagatanu.
Ejo naryamye umunsi wose, kuko wari umunsi w'Imana.
Fata itagisi ikujana mw ihoteri.
Hagarara!
Hagarika uyo muduga.
Haraho uzogenda muri iri ci?
Harashushe birenze.
Harashushe cane ngaha.
Harashushe cane, sivyo?
Harashushe.
Hari ijana y'abantu mu ngoro.
Hari imashini yo kumesura mu nzu?
Hariko haba iki hariya epfo?
Hari umuntu ahagaze inyuma y'uruhome.
Ibi biro ni ivyande?
Ibi bitabo ni rwacu.
Ibi ni birebire birenze urugero.
Ibintu vyawe birihe?
Ibirato birihe?
Ibisi irahagaze ariko nta muntu yururutse.
Ibiti vyinshi vyaraguye.
Ibitoke bisa n'umuhondo.
Icawe ni ciza gusumba.
Icawe ni ciza gusumba.
Iciyumviro nyabaki!
Icumba cawe gifise amadirisha abiri?
Idirisha riraba mu rugo.
Idirisha rirugaye.
Igihe ntikigize gukanya gusa, kiranajovye.
Igitabo kirihe?
Igituro ca bisi kiri iminota itanu uvuye ngaha.
Igitwazi kirasimba.
Ihinguriro rikora ibihumbi n'ibihumbi vy'amacupa kira kwezi.
Ijwi ryanje rirasaraye kubera inkorora.
Ikibazo ciza.
Ikiganza gifise intoki zitanu: urukumu, inkombarukoko, msumba zose, igihugunibenga, agahererezi.
Ikiganza gifise intoki zitanu: urukumu, inkombarukoko, msumba zose, igihugunibenga, agahererezi.
Ikiganza gifise intoki zitanu: urukumu, inkombarukoko, msumba zose, igihugunibenga, agahererezi.
Iki gitabo ni ciza cane.
Iki gitabo ni gishasha.
Iki gitabo ntigifise akamo.
Iki giti kirashaje.
Iki ni igifaransa?
Ikosa ni iryande?
Imana iguhezagire!
Imbwa zihamba kenshi amagufa.
Iminsi yose aja ku kazi ku maguru, kiretse iyo hari imvura.
Iminsi yose aja ku kazi ku maguru, kiretse iyo imvura igwa.
Indahiro ni ideni.
Indimi zifise amajambo agoye.
Indoto yanje yabaye ukuri.
Ingo kunsura.
Ingo!
Injira.
Intumbero y'urugendo rwanyu ni iyihe?
Inzovu zirya ivyatsi.
Inzu yanje iri hafi y'inyubakwa yo gusengeramwo.
Inzu yanje iri hafi y'isengero.
Inzu yanje iri hafi y'urusengero.
Ipantalo yanje yajovye.
Ipantalo yawe iranduye.
Ipantalo yawe iranduye.
Iri darapo ni nziza cane.
Iri jambo riva mu kigereki.
Iri jambo ryamuka mu kigereki.
Iri saho ni irya nde?
Iri terefone ni iryande?
Iryo jambo ntaryonzi.
Iryo jambo ntaryonzi.
Isaha yanje irihe?
Isaha yawe irihe?
Ivyirabura ni vyanje.
Ivyo turabizi.
Iyi hinguriro rikora ivyuma vy'imiduga.
Iyi hinguriro rikora ivyuma vy'imiduga.
Iyi nyabu ni yanje.
Iyi nyabu ni yanje.
Iyi nzoga ni iyande?
Iyo aguma imuhira uyo munsi, ntiyogize isanganya.
Iyo azakugira umwanya yari kugenda.
Iyo menya nari kugenda.
Iyo udategereye, baza.
Iyo ukeneye imfashanyo urampamagara.
Izina ryanje ni John.
Izi ntambwe zirashobora kubuza ko ingwara isasagazwa.
Izuba rirasira mu buseruko.
Izuba riserukira mu buseruko.
Ja hiyo!
Ja mu buriri!
Kaze iwacu!
Kera hari isengero ngaha.
Kera hari urusengero ngaha.
Kera waranywa itabi, sivyo?
Kera yari umwigisha.
Kigurwa angahe?
Kira gitondo mva imuhira imbere y'isaha zibiri.
Komeza!
Kora ibikorwa vyawe vy'ishure.
Korera iciza ababanka.
Kubera iki abantu batankunda?
Kubera iki ataho tutajana?
Kubera iki babikora?
Kubera iki bari aha?
Kubera iki bataza?
Kubera iki harashushe?
Kubera iki ijuru risa n'ubururu?
Kubera iki jewe?
Kubera iki mbikora?
Kubera iki mbwirizwa kubikora?
Kubera iki mutagerageza iyi goti? Ijanye neza n'ipantalo yanyu.
Kubera iki ndi ngaha?
Kubera iki tubikora?
Kubera iki tudataha imuhira?
Kubera iki tugira ivyo?
Kubera iki tutabiraba?
Kubera iki tutaja imuhira?
Kubera iki ubaza?
Kubera iki ubibaza?
Kubera iki udashaka kugenda?
Kubera iki udatomora ico ufise ku muzirikanyi?
Kubera iki umbaza?
Kubera iki unkunda?
Kubera iki unkunda?
Kubera iki urwanko rwinshi?
Kubera iki utabikora?
Kubera iki utaciga igifaransa?
Kubera iki utajana na jewe?
Kubera iki utari aha?
Kubera iki utari kumwe na jewe?
Kubera iki utariyo?
Kubera iki wibaza ivyo?
Kubera iki wiga igifaransa?
Kubera iki wiga muri kaminuza?
Kubera iki wijiriwe?
Kubika ahakanye kandi humutse.
Kubika ahapfutse kandi humutse.
Kuki utinjira?
Ku minsi y'Imana simba ndi imuhira.
Kuva ejo dushobora kujana ku kazi.
Magdalena na Ania ni abagenzi pfampfe.
Mama wanje arihe?
Mariya arihe?
Maze kuduga aka gasozi niruka, ugusemagurika ni kwose.
Mbabarire cane!
Mba ngaha.
Mbe nambare iki - ipantalo canke ijipo?
Mbirizwa kwiga gifaransa.
Mbirizwa kwiga gifaransa.
Mbwira umugambi wawe.
Mbwirizwa gutunganya imishatsi yanje.
Mbwirizwa kwiga.
Mbwirizwa kwugurura idirisha?
Mfise abakobwa batatu.
Mfise benewacu.
Mfise mukuruwanje.
Mfise umukoshi.
Mpa igitabo.
Mpamagara hagati y'isaha imwe n'isaha zibiri.
Mpore ko ndabivuze.
Mubaze izina ryiwe.
Mu buseruko bw'ikigwati hari ikiyaga.
Mubwirizwa gutaha.
Mudutwaye hehe?
Mugenda hehe?
Mu mwaka uheze navyaye imfura yanje.
Murabe.
Muragaba k'umutwe wanyu.
Murakoze cane kandi.
Murakoze cane kandi.
Murakoze cane.
Murakoze kwumviriza.
Murategera igifaransa?
Muraturondera?
Murazi aho mba?
Muri Abadagi, sivyo?
Muri Abadagi, sivyo?
Muri abana.
Muritwararikire umutwe wanyu.
Mu ruguma hari amashira.
Musazanje ntari i muhira.
Musazawe arihe?
Mushikanje asa na Mama.
Mushikawe amerewe gute?
Muzinaniye hehe?
Muzinaniye hehe?
Mva muri Bresil.
Mvuga ico niyumvira.
Mvuga indimi zitatu.
Mvyuka isaha imwe zo mugitondo.
Nabarira vyose abavyeyi banje.
Nabo baraza?
Nabonye hariya mushikanje.
Nabonye hariya mushikanje.
Naganiriye vyose abavyeyi banje.
Nagasaga!
Nagira ngo ni ikigorwa cawe.
Nagira ngo urashobora kubitegera.
Nagira ngo urashobora kubitegera.
Nagira ngo woba watashe.
Nagize igitondo c'imirimo myinshi.
Naguze amagi n'amata make.
Nahabonye mwenewacu.
Nahabonye mwenewacu.
Naje kubera wewe.
Nakwiyumyiye.
Namerewe nabi.
Namugomwe.
Namugwiriye.
Namukunze.
Nanje ndavyiyumvira uko.
Nanje ndavyiyumvira uko.
Nanje ndavyiyumvira uko.
Nanje.
Narabiravye muri yu tubi.
Narataye amarori yanje.
Nari mbizi.
Narinzi ko uri ngaha.
Narinzi ko vyogushimisha.
Nariye amagi ejo.
Nariyumviye kuguma iminsi mike iwawe.
Narumvise ko warongoye.
Nasubiye kumubona.
Nataye impfunguzo zanje.
Navyiyumviye.
Nazanwe no kwiga.
Ndabasavye, mumpe ifagitiri.
Ndabitegera.
Ndabitegera.
Ndabizi.
Ndafise amahera.
Ndafise bashikanje.
Ndafise ibikorwa vy'ishure.
Ndafise ikibazo.
Ndafise ubwato.
Ndafise umuduga.
Ndafise umuduga.
Ndagenda kuryama.
Ndaguhwatira umucungwa.
Ndagukumbuye cane.
Ndagukunda.
Ndakubonye.
Ndakujana.
Ndakunda gusoma.
Ndakunda ibiharuro.
Ndakunda ibiharuro.
Ndakunda imishatsi migufi.
Ndakunda iyo ndi jenyene.
Ndakunda iyo ndi jenyene.
Ndakunda kuba ngaha.
Ndakunda kwiga igifaransa.
Ndakunda umuryango wanje.
Ndakunda uyu muduga.
Ndakurondera.
Ndakwemera.
Ndakwiyumvira.
Ndakwumviriza.
Ndameneka umutwe.
Ndamubonye.
Ndamukunda.
Ndamukunda.
Ndamuzi.
Ndamuzi.
Ndanezerewe.
Ndanezerewe ko ariho uri.
Ndanezerewe ko uhari.
Ndanezerewe ku uhimbawe.
Ndarahiye.
Ndaribwa mu nda.
Ndarurumba.
Ndasemagurika.
Ndashaka gusoma iki gitabo.
Ndashaka gusubira kukubona.
Ndashaka ko usoma iki gitabo.
Ndashaka kuguherekeza.
Ndashaka kukubona pe.
Ndashobora kubibona kandi?
Ndashobora kubibona kandi?
Ndashobora kwinjira?
Ndashobore kubikoresha?
Ndashonje.
Ndategera ico ushaka kuvuga.
Ndategera ico uvuga.
Ndavyakira.
Ndavyumva
Ndazi aba bagore.
Ndazi aba bantu.
Ndazi aho ari.
Ndazi aho mbwirizwa kugaba.
Ndazi aho uba.
Ndazi ibikenewe gukorwa.
Ndazi icarico urukundo.
Ndazi ico baravuze.
Ndazi ico mvuga.
Ndazi ico nogira.
Ndazi ico nokora.
Ndazi ico nzokora.
Ndazi ico wiyumvira.
Ndazi igituma ubishaka.
Ndazi igituma uri ngaha.
Ndazi ikiriko kiba.
Ndazi ingene bigenda.
Ndazi ingene bigirwa.
Ndazi ingene bikoreshwa.
Ndazi ingene bikorwa.
Ndazi izina ryiwe gusa.
Ndazi ko ubifise.
Ndazi kubikora.
Ndazi kubikora.
Ndazi neza ko hari aho maze kumubona.
Ndazi neza ko namubonye ahantu ikindi gihe.
Ndazi nyoko.
Ndazi so wawe.
Ndazi Tom?
Ndazi umuryango wiwe.
Ndazi uvyirumvira.
Ndazi uyo mukobwa.
Ndazi uyo mukobwa.
Ndazi uyo mwigeme.
Ndazi uyo mwigeme.
Ndibaza ko ari vyiza.
Ndibaza ko azoza.
Ndibaza ko ntegeye.
Ndibaza ku mfise umwanya w'ikindi gikombe c'ikawa.
Ndibuka aho ubwambere.
Ndiga igifaransa imuhira.
Ndi hehe?
Ndi imuhira.
Ndiko ndasoma igitabo.
Ndiko nduhuka.
Ndi mu gikoni.
Ndi mu karuhuko.
Ndi mu muduga.
Ndi mushasha aha.
Ndi umuhererezi.
Ndi umunyeshuri muri kaminuza.
Ndi umunyeshuri mushaha muri kaminuza.
Ndi umushinwakazi.
Ndi umutetsi.
Ndi umwigisha.
Ndi umwigisha.
Ndi umwotsi w'imikate.
Ndizeye ko ukomeye neza.
Ndumva ico uvuga.
Nganirira umugambi wawe.
Ngico igitabo cawe.
Ngirango araza.
Ngirango ntaza.
Ngiyo ifagitiri.
Ngurisha impuzu ku murongo.
Ngurisha impuzu ku murongo.
Nguyo!
Ni abanyamerika?
Ni akazi kiwe.
Ni angahe?
Ni binini birenze?
Ni birebire birenze?
Ni birebire birenze urugero.
Ni bitoya birenze?
Ni bitoya birenze?
Ni bitoya birenze.
Ni bitoya birenze urugero.
Nico ndiko ndondera.
Nico nshaka kumenya.
Nico nshaka kumenya.
Niga igifaransa mw'ishure.
Niga igifaransa mw'ishure.
Niibagiye kugura umukate.
Ni isaha icenda ibuze iminuta icumi n'itanu.
Ni isaha icenda ibuze iminuta icumi n'itanu.
Ni isaha icenda ibuze iminuta icumi n'itanu.
Niki?
Nikomerekeje n'imbugita ku rutoki.
Ni ku wagatandatu.
Ni ku wambere.
Ni mushiki wawe?
Nimusohoke mu muduga.
Ni mwenewacu.
Ni naco gituma ndagukunda.
Ni neza cane.
Ni neza cane.
Ni neza, siko?
Nirukiye kwa mama.
Ni rwacu.
Nitwa Jack.
Ni twebwe murondera?
Ni umufaransa.
Ni umufaransa.
Ni umugambi mwiza.
Ni umunsi!
Ni umuntu mwiza.
Ni umunyamerika?
Ni umunyeshuri mwiza.
Ni umunyeshuri mwiza.
Ni vyiza gusumba uko biri.
Ni vyiza, sivyo?
Nje gusezera.
Nje gusezera.
Nje kugutwara i muhira.
Nkura ngaha.
Noshimishwa no kumenya izina ryawe.
Noshimishwa no kumubona.
Nryama ubusa.
Nsabe uruhusha nde?
Nshaka gutaha.
Nshaka ko uja imuhira.
Nshaka ko umubona.
Nshaka ko utaha.
Nshaka kubibona.
Nshaka kuganira nawe.
Nshaka kugutekera.
Nshaka kukubona.
Nshaka kwiga igifaransa.
Nshaka kwiga igifaransa.
Nshobore gusubira kubibona?
Nshobore gusubira kubibona?
Ntabana nawe.
Nta bitabo mfise vyo gusoma.
Ntaco bibaye.
Ntaco ndabiziko.
Ntaco nywa.
Nta gishasha.
Nta kamaro.
Nta kamaro.
Nta kibazo.
Nta mahera dufise.
Nta mahera tugifise.
Nta mahera tugifise.
Nta mahera yari agifise.
Nta mahera yari agifise.
Nta mazi akiri mw'icupa.
Nta muduga dufise.
Nta muduga mfise.
Nta ngorane.
Nta ngorane.
Nta ngorane.
Ntanumwe abizi.
Ntanumwe abizi.
Ntanumwe amuzi neza kiretse abavyeyi biwe.
Ntanumwe antega ugutwi.
Ntanumwe antegura.
Ntanumwe ari i muhira.
Ntanumwe azi amazina yabo.
Ntanumwe azi izina ryiwe.
Ntanumwe yakubajije.
Ntanumwe yakubajije.
Ntanumwe yumviriza.
Ntanzi.
Ntariye nopfa.
Ntashobora kuza kubera ko ararwaye.
Ntavuga icongereza.
Ntavuga icongereza gusa, avuga kandi n'ikidagi.
Nta wundi muntu yarahari kiretse jewe.
Ntegerezwa gutaha.
Ntegerezwa kugenda ubu.
Ntegerezwa kugenda ubu.
Ntegerezwa kuja imuhira.
Ntibaza uyu munsi.
Ntibimeze uko uvyiyumvira.
Ntibimeze uko uvyiyumvira.
Ntibimpa agateka.
Ntibimpa agateka.
Ntibinshimishije.
Ntibintera iteka.
Ntibintera iteka.
Ntibinyuze.
Ntibiri nkuko uvyiyumvira.
Ntibiri nkuko uvyiyumvira.
Ntidufise amahera.
Ntidushaka kubimenya.
Ntimushaka kumenya ivyabaye?
Ntimushakisha igituma!
Ntitubizi.
Ntitubwirizwe kubivugana ubu nyene.
Ntitugifise amahera.
Ntitugifise amahera.
Ntitumuzi.
Ntituri twenyene.
Ntituri twenyene.
Ntiwibagire gutwara ibaruwa.
Ntiwibagire gutwara ibaruwa.
Ntiwibagire gutwara ibaruwa.
Ntiwibagire gutwara ikete.
Ntiwibagire gutwara ikete.
Ntiwibagire gutwara ikete.
Ntiwitinye.
Ntiwitinye.
Ntiwoshobora kubisubira ico wavuze?
Ntiyasomaye iki gitabo.
Ntubange ugutwi.
Ntubange ugutwi.
Ntubange ugutwi.
Ntubaze.
Ntugende n'iminwe misa.
Ntugende zirayoye.
Ntuhebe!
Ntumpate kubikora.
Ntumuhagarike.
Ntundabe gutyo.
Ntunezerewe?
Ntunzi.
Nturabe hasi.
Nturabe munsi.
Nturi musazanje.
Nturi mwenewacu.
Nturyame idirisha ryuguruye.
Ntusabe amahera.
Ntushaka kubimenya!
Ntushaka kumenya ivyo!
Ntusubire kubikora.
Ntusubire!
Ntuza, sivyo?
Ntuzi icarico?
Ntuzi icarico?
Ntuzi musazanje.
Ntuzi musazanje.
Ntuzoza, sivyo?
Ntwumviriza.
Nuko rero nabigize.
Nyene ibi bitabo ni mushikanje.
Nyene ikintu ni musazanje.
Nyene uyu muduga ni data wanje.
Nyogokuru avuga buhoro buhoro.
Nyoko arihe?
Nyoko ari imuhira?
Nyumviriza.
Nzanira ingwa zibiri.
Nzero ni ukwezi kwambere mu mwaka.
Nzero, Ruruhuma, Ntwarante, Ndamukiza, Rusama, Ruheshi, Mukakaro, Myandagaro, Nyakanga, Gitugutu, Munyonyo na Kigarama ni amezi icumi n'abiri y'umwaka.
Nzobigerageza.
Nzobiguha.
Nzobiraba.
Nzogaruka.
Nzogenda n'umuduga.
Nzogerageza.
Nzoguha igitabo.
Nzogushimisha.
Nzokora ico unsaba.
Nzokora igikenewe vyose.
Nzokora ivyangombwa vyose.
Nzokunezereza.
Nzokunyara.
Oya, urakoze.
Raba hariya!
Raba iyi foto.
Raba neza ingene ndabikora!
Rabira mw'idirisha.
Reka gusoma.
Reka gutungira ijisho amabere yiwe!
Reka kundaba!
Reka kuvuga ivyo!
Reka kuvuga ivyo!
Reka ndabe.
Reka ndabirabe.
Reka ndaguhobere.
Reka ndakugurire gishasha.
Reka nje kugura umukate.
Rimwe rimwe tujana muri cenema.
Ruhuka!
Ryama neza, Timmy.
Ryama neza, Timmy.
Sibiraba amahera.
Sico kimwe.
Si igifaransi.
Si ikintu co kwirata.
Si ikintu co kwishima.
Siko biri nkuko uvyiyumvira.
Simbesha na rimwe.
Simbikeneye.
Simbizi.
Simbizi.
Simfise aho mba.
Simfise amahera.
Simfise mushikanje.
Simfise mushikanje.
Simfise mwenewacu.
Simfise umuduga.
Sinarinzi ko muri buhabe uyu munsi.
Sinashoboye kutarira.
Sindabikeneye.
Sindabitegera.
Sindagutegera.
Sindakunda kwiga.
Sindakwumva.
Sindamubona.
Sindamuzi.
Sindashonje.
Sindavyumva.
Sindi ikijuju.
Sindi intore.
Sindi umubaji mwiza cane.
Sindi umuntu mwiza.
Sindi umunyeshuri muri kaminuza.
Sindi umunyeshuri.
Sinibagira na rimwe amaso.
Sinibagira na rimwe amaso.
Sinibaza ko aza.
Siniyumva neza ngaha.
Sinkomeye muri vyo.
Sinkomeye muri vyo.
Sinkubona.
Sinshaka amahera yawe.
Sinshaka aya mahera.
Sinshaka guteka.
Sinshaka gutunga.
Sinshaka gutunga.
Sinshaka kuba umutunzi.
Sinshaka kuba umutunzi.
Sinshaka kubimenya.
Sinshaka kubimenya.
Sinshaka kubisoma.
Sinshaka kukubona.
Sinshaka kukubona.
Sinshobora kwoza amasahani. Harabuze amazi.
Sinshonje.
Sintegera igifaransa.
Sintegera iri jambo.
Sinteka.
Sintunze.
Sinumva igifaransa.
Sinywa.
Sinzi aba bantu.
Sinzi aho aba.
Sinzi aho bari.
Sinzi guteka.
Sinzi ico nokora.
Sinzi ico novuga...
Sinzi ico novyiyumvirako.
Sinzi ico nshaka.
Sinzi ico nshaka.
Sinzi iryo jambo.
Sinzi iryo jambo.
Sinzi iyo ngana.
Sinzi izina ryiwe.
Sinzi izina ryiwe.
Sinzi neza igifaransa.
Sinzi neza igifaransa.
Sinzi neza igifaransa.
Sinzi.
Si umuduga wanje.
Si umuduga wanje.
Si umunsi wanje.
So arihe?
Sohoka mu cumba canje!
Soma ibi.
So wawe amerewe gute?
So wawe arihe?
Subira gusoma.
Tom arihe?
Tuja hehe?
Turabitegera.
Turabitegera.
Turabizi.
Turagarutse.
Turajana?
Turakuzi.
Turanezerewe cane.
Turanezerewe.
Turavukana.
Turavukana.
Turavyumva.
Turiga igifaransa.
Turihe?
Turi hehe?
Turi imuhira.
Turiko dutakaza umwanya uzimvye.
Tuzobonana ejo!
Tuzojana.
Tuzongera ku wambere.
Twakuriye hamwe.
Twakuriye hamwe.
Twama dukina ku munsi w'Imana.
Twamanutse twiruka agasozi.
Twashitse.
Twatandukanye.
Twavanye.
Twiga ubuhinga bw'umuziki.
Twugurure idirisha!
Uba he?
Uba ngaha?
Ubibona gute ku wagatanu?
Ubu buriri ni ubwande?
Ubugeni buzoba ku wagatandatu.
Ubwirizwa guheba inzoga.
Ubwirizwa kureka kunywa.
Ubwirizwa kuvyuka.
Ufise imyaka ingahe?
Ufise imyaka ingana iki?
Ugara amadirisha yose.
Ugara idirisha.
Ugenda kw'ishure gute?
Ugurura idirisha.
Uhaguruka ryari?
Uko ni vyiza gusumba?
Ukora iki ngaha?
Ukora iki?
Ukuboko kwanje kw'ibubamfu kwagize ibinyanya.
Ukuboko kwanje kw'ibubamfu kwagize ibinyanya.
Umfata ko ndi nde?
Umuduga urihe?
Umuduga wacu urihe?
Umuduga wa data ni mushasha.
Umuduga wanje urihe?
Umuduga wanje urihe?
Umuduga wanje wapfuye.
Umuhungu arasimba.
Umukobwa wanje azorongorwa mu kwezi kwa gatandatu.
Umukobwa wanje azorongorwa mu kwezi kwa gatandatu.
Umukobwa wanje azorongorwa muri ruheshi.
Umukobwa wanje azorongorwa muri ruheshi.
Umunyeshuri arashaka kukubona.
Umuryango umerewe gute?
Umuryango umerewe gute?
Umuryango wanje ni muto.
Umuryango wawe uri hehe?
Umuryango wiwe urihe?
Umutetsi arihe?
Umuvyeyi wanje arankunda.
Umviriza nyoko!
Umwigisha wanyu ni nde?
Uraba iki?
Urabibonye?
Urabishaka canke?
Urabitegera?
Urabitegera, sivyo?
Urabizi?
Urabona itandukaniro hagati y'ivyo bicapu bibiri?
Urabona iyi nzu? Ni inzu yanje.
Urafise aya mahera?
Urafise ico gusoma?
Urafise ikintu co gusoma?
Urafise umuduga?
Urafise umuduga?
Urafise umuduga?
Urafise umuduga?
Uragenda canke ntugenda?
Uragenda canke?
Uragikunda?
Urakoze cane.
Urakoze kuza.
Urakunda kwiga?
Urambabarira ko ndabivuze.
Uramundamukiriza ni mwahurira mu giteramo.
Uramuzi?
Uramuzi?
Uramuzi.
Uramuzi.
Urandondera?
Uranezerewe?
Uranezereza.
Uranhunga ko ndabivuze.
Urantegera.
Uranzi.
Urarurumba.
Urarwaye, ubwirizwa kuruhuka.
Urashaka gutunga?
Urashaka ikintu co kunywa?
Urashaka ikintu co kunywa?
Urashaka ikintu co kunywa?
Urashaka kuba umutunzi?
Urashaka kubibona?
Urashaka kuraba iki?
Urashobora gukoresha uwu muduga.
Urashobora gutandukanya intama n'impene.
Urashobora gutera ururirimbo.
Urashobora gutora irangi iryariryo ryose rigushimisha.
Urashobora gutora irangi iryariryo ryose ushimye.
Urashobora kugendayo.
Urashobora kujayo.
Urategera ivyanditse ngaha?
Uraza canke?
Uraza? Ego canke oya?
Urazi aho aba?
Urazi aho arihe?
Urazi aho nzoba ndi.
Urazi bano bantu.
Urazi gutandukanya intama n'impene?
Urazi icarico?
Urazi icarico urukundo?
Urazi ico ubaza?
Urazi ico yavuze?
Urazi ico yavuze?
Urazi ico yavuze?
Urazi izina ryiwe?
Urazi ko mbwirizwa kugenda.
Urazi ko ndagukunda.
Urazi ko tugukunda.
Urazi nyene uyu muduga?
Urazi nyene uyu muduga?
Uribaza ko nezerewe?
Uribuka?
Uriga igifaransa?
Urihe?
Uri imuhira?
Uri iwawe?
Uriko usoma iki?
Uri mushasha?
Uri mushasha?
Uri umugenzi wanje.
Uri umugenzi wanje.
Uri umuhinga.
Uri umuhinga.
Uri umuntu mwiza.
Uri umunyeshuri mwiza.
Uri umutetsi mwiza.
Uri umuvyeyi mwiza.
Urugendo rwiza!
Uruhanga rwawe rurashushe cane. Ndakeeka ko ufise inyonko.
Urukundo ni iki?
Urukundo rurahuma.
Uru ni urukundo?
Urupapuru rumwe rurabuze.
Ururuka mu muduga.
Ur'uwiwacu.
Urya mugambi wari uwande?
Usa n'umupolisi!
Ushaka kuba hehe?
Ushaka kubimenya iki?
Ushaka kuja hehe?
Ushaka kuzobibona.
Ushaka kuzobiraba.
Ushobora gukoresha umuduga wanje.
Utaha ryari?
Utaha ryari?
Utaha ryari?
Uteganya iki ku mpera z'indwi?
Uva hehe?
Uwushaka kumurongora abwiriza kubiganira neza na se wiwe.
Uyu muduga ni mwiza cane.
Uyu muduga ni mwiza cane.
Uyu muduga ni rwacu.
Uyu muduga usa na mushasha.
Uyu muhungu ni mwenebabo.
Uyu munsi ni kuwagatatu.
Uyu munsi ni umunsi w'Imana.
Uyu muvinyu ni uwande?
Uyu mwaka ntegekanya gusoma ibitabo vyinshi bishoboka.
Uyu mwigeme asa neza.
Uyu ni data wanje.
Uyu ni nyoko?
Uza imuhira ryari?
Uzi iki?
Uzomara igihe kingana iki?
Uzomara umwanya ungana iki?
Uzosigara umwanya ungana iki?
Uzoza iwawe ryari?
Va mu buriri bwanje!
Vyibagire ivyo.
Vyibagire!
Waciye ku kimenyetso c'itara ritukura.
Waciye ku kimenyetso c'itara ritukura.
Wagize ubwoba?
Wari umugambi wande?
Wasomye iki gitabo?
Watinye?
We si umwana.
We si umwana.
We si umwana.
We si umwana.
We si umwana.
Wiga kw ishure irihe?
Wiga ryari?
Wipfuza iki?
Wiyumvira iki?
Yacishije igisu ciwe ishami ry'igiti.
Yafashe ikinyugunyugu n'urukumu hamwe n'inkombarukoko.
Yagirije uyo mugabo ubusuma.
Yama ata mobile yiwe.
Yamugomwe.
Yamugomwe.
Yamukunze.
Yamukunze.
Yarabimpaye.
Yataye urupfunguzo rw'umuduga wiwe.
Yatetse umutaga wose.
Yatoye ikanzu izimvye gusumba zose.
Yavyaye umwana wa mbere afise imyaka mirongo ibiri.
Yazunguje umutwe.
Yazunguje umutwe.
Za kunsura.
