Ubwirizwa kujayo kubizana.
Kubera iki muri imuhira?
Asa na data.
Ntumuhagarike.
Ndi mushasha aha.
Sinzotenyenya.
Turazi ico ukora.
So wawe amerewe gute?
Ndazi ico baravuze.
Kubera iki ataho tutajana?
Tuzosubira kubonana!
Ruhuka!
Simfise aho mba.
Urabishobora.
Mu mwaka uheze navyaye imfura yanje.
Ndazi neza ko hari aho maze kumubona.
Uri umuntu mwiza.
Umuryango wawe uri hehe?
Vyiza kuruta vyobaye iyo utajaho.
Sindashonje.
Ndi umunyeshuri mushaha muri kaminuza.
Nataye impfunguzo zanje.
Ntituri twenyene.
Nshaka ko ubimenya.
Nashaka kubaza, mbe muhakura inyungu nki?
Ntanumwe yarazi ibikenewe kurangurwa.
Vyanteye kukwiyumvira.
Ndi umwe mu banyeshuri bawe.
Kubera iki utaciga igifaransa?
Siko biri nkuko uvyiyumvira.
Ndashaka kukubona pe.
Ndanezerewe ko uhari.
Uvyuka ryari?
Tom arazi igituma?
Isaha yanje irihe?
Nta mahera dufise.
Mbabarira!
Sindabikeneye.
Nabarira vyose abavyeyi banje.
Nta bundi buryo.
Ndazi ico nogira.
Ndazi aho ari.
Ni neza cane.
Igihe ntikigize gukanya gusa, kiranajovye.
Naratakaje ikaramu ryanje.
Uhaguruka ryari?
Urashobora gutora irangi iryariryo ryose ushimye.
Yatetse umutaga wose.
Ntibafise amahera.
Uri umuvyeyi mwiza.
Uraza canke?
Nshaka kugutekera.
Urashaka gutunga?
Ndameneka umutwe.
Utumvise, baza.
Uyu ni data wanje.
Nico nshaka kumenya.
Ni igiki ntategera?
Sinibaza ko aza.
Sindavyumva.
Bavuga ko atunze cane.
Ijambo ryiwe ryari igitangaza.
Sinshaka guteka.
Ntimusubire kubigira.
Ntanumwe amuzi neza kiretse abavyeyi biwe.
Nashoboye kugira.
Sinibaza ko aza.
Yamugomwe.
Izuba rirasira mu buseruko.
Kubera iki utabikora?
Bizoba neza cane.
Nta ngorane.
Ndibuka aho ubwambere.
Murashaka kubitwara?
Yitwa ngwiki kandi?
Uranhunga ko ndabivuze.
Musazanje ntari i muhira.
Abavyeyi banje bampamagara kira munsi.
Bakora iki ngaha?
Urafise musazawe?
Raba iyi foto.
Ndi mu muduga.
Ushoboye iki?
Uyu ni mama wawe?
Kubera iki ijuru risa n'ubururu?
Iyo udategereye, baza.
Uyu muduga ni rwacu.
Ngaha nta numwe afise umuduga.
Nimuduhitemwo!
Sinzi iryo jambo.
Uranzi.
Ndanezerewe ko ariho uri.
Ni twebwe murondera?
Vyibagire!
Iki kintu kimaze iki?
Ntibimpa agateka.
Umukobwa wanje azorongorwa mu kwezi kwa gatandatu.
Ndazi aba bagore.
Ndategera ico uvuga.
Birampimbaza.
Uzi izina ryanje hehe?
Urabishaka canke?
Uru ni urukundo?
Murazi aho mba?
Nzero, Ruruhuma, Ntwarante, Ndamukiza, Rusama, Ruheshi, Mukakaro, Myandagaro, Nyakanga, Gitugutu, Munyonyo na Kigarama ni amezi icumi n'abiri y'umwaka.
Ndafise ikibazo.
Narumvise ko warongoye.
Uragenda canke?
Kera yari umwigisha.
Namugomwe.
Nagasaga!
Umfata ko ndi nde?
Ndabibonye nanje.
Ushaka kuzobiraba.
Indahiro ni ideni.
Ntabana nawe.
Sinkunda aba bantu.
Urashaka ikintu co kunywa?
Uranezerewe?
Nta makenga!
Ntanumwe yumviriza.
Nagira ngo ni ikigorwa cawe.
Fata itagisi ikujana mw ihoteri.
Ntuza, sivyo?
Nguyo araje!
Bimuha.
Sinzi igihe uko kingana.
Iri saho ni irya nde?
Ngaruke?
Kazibe!
Ntanumwe azi ibikenewe gukorwa.
Nturabe hasi.
Nzomubaza.
Turagarutse.
Nzokuraba.
Ndazi ibitari bike kuri wewe.
Nta ngorane.
Nshaka kwiga igifaransa.
Umuduga wanje wapfuye.
Urazi ko ndagukunda.
Ndamuzi.
Tega amatwi!
Ndazi ico nokora.
Ndazi ikiriko kiba.
Yataye urupfunguzo rw'umuduga wiwe.
Kubera iki utari iwanje?
Ndashobora kubibona kandi?
Urazi gutandukanya intama n'impene?
Ntuzi musazanje.
Ndagutwara kw'ishure.
Ndazi Tom?
Birakunyuze?
Nsubire kugaruka?
Ni naco gituma ndagukunda.
Uri iwawe?
Haraza gushuha.
Ndabasavye, mumpe ifagitiri.
Ni ku wambere.
Harashushe birenze.
Urazi ko ndagukunda.
Iki gitanda kirasusurutse cane.
Urugendo rwacu ruva ku gihe.
Amahera narayakiriye.
Uripfuza kuraba iki?
Ugenda kw'ishure gute?
Uri mushasha?
Ndazi ibikenewe gukorwa.
Urakunda kwiga?
Uramfitiye amahera?
Sinzi gute.
Ndazi ingene bikorwa.
Ibirato birihe?
Ndanezerewe ko uhari.
Iki gitabo ni ciza cane.
Urakoze kwicisha iwacu.
Ndabubaha.
Mpore cane!
Arakomeye.
Aya ni amadolari atanu.
Nirukiye kwa mama.
Biratunganye.
Ipantalo yawe iranduye.
Ndakurora.
Urakoze guhita.
Urakunda kwiga?
Nzobiguha.
Dusangire akanyobwa.
Ndashaka bimwe nanje.
Uri umugenzi wanje.
Umuduga wacu urihe?
Ntanumwe azi ibikenewe gukorwa.
Wiga kw ishure irihe?
Ntushaka kubimenya!
Ni umunyeshuri mwiza.
Antera kuzirikana.
Akira igitabo usome.
Simfise imuhira.
Urakoze cane.
Ndazi ko wabivuze.
Ndakwiyumvira.
Aranezerewe.
Ndashonje.
Ntunzi.
Ntundabe gutyo.
Nagira ngo woba watashe.
Umukobwa wanje azorongorwa muri ruheshi.
Yarerewe kwa nyirakuru.
Nagutaye.
Nshaka gutaha.
Ntavyo bazi.
Mfise mukuruwanje.
Iyi kanzu nijewe nayigiriye.
Ushaka kukigumya igihe kingana iki?
Kira gitondo mva imuhira imbere y'isaha zibiri.
Narataye amarori yanje.
Kubera iki bari aha?
Urukundo ni iki?
Turategera.
Ndakunda iki gitabo.
Ndagusavye usome ivyanditse munsi.
Uri umugore nkunda.
Nzogushimisha.
Ni rwacu.
Umuryango wawe uri hehe?
Ntusubire kuvuga iri jambo.
Sawa, nzogitumako.
Tuja hehe?
Sintegera ingene.
Urazi aho nzoba ndi.
Intumbero y'urugendo rwanyu ni iyihe?
Turanezerewe kubabona.
Ndazi uyo mwigeme.
Hagarika uyo muduga.
Sintegera gute.
Urazi ico ubwirizwa kugira?
Turakuzi.
Oya, urakoze.
Ushaka kuba hehe?
Ndakunda aho mba.
Ntubaze.
Mbwirizwa kwugurura idirisha?
Haguye amama make y'imvura.
Mugenda hehe?
Usa naho unezerewe cane.
Ubwirizwa kuja imuhira.
Aba ngaha?
Uriga igifaransa?
Muzovyigaya cane.
Za kunsura.
Umuduga wanje urihe?
Sinzi ingene.
Nahabonye mwenewacu.
Ndazi ico nkora.
Nahaye umuhungu igitabo.
Umwigisha wanyu ni nde?
Ndabikorera wewe.
Uyu mukobwa yiyambika nk'umuhungu.
Simfise musazanje.
Birababaje, umugenzi wanje mukuru arimutse, yimukiye mu kindi gisagara.
Baba iwawe?
Urazi ko mbwirizwa kugenda.
Ngico igitabo cawe.
Si umunsi wanje.
Amaze igihe kingana iki arwaye?
Iyo aguma imuhira uyo munsi, ntiyogize isanganya.
Ntavuga icongereza gusa, avuga kandi n'ikidagi.
Singushimye.
Ndazi ikiriko kiba.
Ndazi ko ubizi.
Ni vyiza, sivyo?
Ndazi ico wiyumvira.
Urarurumba.
Ijipo ntiyari inkwiye nico gituma nabwirijwe guyihindura.
Vyiza kuruta vyobaye iyo utajaho.
Uyu mukobwa yiyambika nk'umuhungu.
Ndakunda kukuraba uteka.
Mbwirizwa gutunganya imishatsi yanje.
Ni bitoya birenze?
Nyene ikintu ni musazanje.
Ndanezerewe ku uhimbawe.
Woba ufise akanya ko kumfasha ikintu?
Bimuhe.
Sinzi gufata amazina.
Urazi icarico urukundo?
Ubugeni buzoba ku wagatandatu.
Ntariye nopfa.
Mbwira umugambi wawe.
Iki gitabo kiri ku meza ni icande?
Naratakaje ikaramu ryanje.
Urakoze kuza.
Ndi umutetsi.
Hari umuntu ahagaze inyuma y'uruhome.
Nasivye kw'ishuri.
Birabe neza.
Urabibonye?
Bariko baturaba?
Uri umutamvyi mwiza?
Maze kuduga aka gasozi niruka, ugusemagurika ni kwose.
Nyoko niho ari?
Twaje kukubona.
Bobo ni abana.
Komera ko muheto, Tom. Ntiwitinye!
Ntiwibagire gutwara ibaruwa.
Ndazi ko unkunda.
Ahari ugushaka haba inzira.
Na jewe ngenda kw'ishure ngaha.
Simfise mwenewacu.
Nikomerekeje n'igisu ku rutoki.
Uraba iki?
Nzokunyara.
Urazi aho arihe?
So wawe arihe?
Ntusubire kumbaza.
Data ari imuhira.
Ijipo iranduta.
Abo ni abajapani?
Mpa igitabo.
Uri umuntu mwiza.
Ayo madirisha yerekeye mu bumanuko.
Niibagiye kugura umukate.
Nzogenda ku munsi w'Imana.
Sinkubona.
Uva hehe?
Turi ngaha kubwawe.
Sinzi aho aba.
Hari ijana y'abantu mu ngoro.
Ndabitegera.
Igifurwe ntigifise amenyo.
Ntibinyuze.
Indoto yanje yabaye ukuri.
Murashobora kuntegera.
Sinzi ico novuga...
Urazi aho arihe?
Sindi umunyeshuri muri kaminuza.
Reka ndabe.
Uri iwacu?
Korera iciza ababanka.
Utahari sico kimwe.
Ni bitoya birenze urugero.
Asanseri ntikora uyu munsi.
Turanezerewe cane.
Uyu mwigeme asa neza.
Ingo kunsura.
Sindi umubaji mwiza cane.
Ntunzi.
Babwire ivyashitse.
Nagira ngo woba watashe.
Nabigiriye wewe.
Ndakunda umuduga wanyu.
Umwigisha wanyu ni nde?
Urataha?
Biragushimishije?
Birakwiye.
Nta gushidikanya.
Mbe nakunze?
Sindamuzi.
Ndanezerewe ko uhari.
Nkeneye guhoberwa.
Naguhevye.
Ntimuhindure amungane ata makosa afise. Murashobora kuyahinyanyura mu bundi buryo.
Sinzi ico novyiyumvirako.
Sinzi ico nokora.
Ni igiki gituma abantu bagira uko ivyo?
Ndi hehe?
Urazi izina ryiwe?
Amahera yaheze.
Ndashaka kugurana umuduga.
Ndashaka nanje kugenda.
Ntibisa neza.
Isaha yawe irihe?
Twasezeye.
Kanyemwo!
Nataye impfunguzo zanje.
Sintegera iri jambo.
Sinarinzi ko muri buhabe uyu munsi.
Ndakurondera.
Murabona iyi nzu? Ni inzu yanje.
Umuduga wanyu uranshimisha.
Bavuga ko atunze cane.
Ntanumwe abizi.
Uragenda canke ntugenda?
Ntitujana.
Kera hari urusengero ngaha.
Ndazi ko wabivuze.
Oh, mpore.
Kuki utaja imuhira?
Namwe muravyiyumvira gutyo?
Ntibimpa agateka.
Uripfuza kuraba iki?
Kubera iki ubaza?
Nguyo araje!
Ntibindaba mugihe ahimbawe.
Ndizeye ko ukomeye neza.
Akira ico ushaka.
Ndazi uyo mukobwa.
Ntivyapfuye.
Uri umuvyeyi mwiza.
Urashaka umuduga?
Simfise amahera.
Kora ibikorwa vyawe vy'ishure.
Ndashaka kuguherekeza.
Ndazi izina ryiwe gusa.
Asa na nyina wiwe.
Nzokunezereza.
Turabitegera.
Umuryango umerewe gute?
Mvuga igisupanyoli gato.
Komeza!
Afise imyaka ingana iki?
Mbwirizwa kumenya imvo.
Nturi mwenewacu.
Umuryango wanje ni muto.
Tom arazi imvo?
Nyoko ari imuhira?
Ndakunda ibiharuro.
Ndazi kubikora.
Utahari sico kimwe.
Ntaco bibaye.
Turabonana.
Bite!
Tom arihe?
Ntiwitinye.
Ubikuye hehe?
Sinzi neza igifaransa.
Ugenda ryari?
Ntibafise amahera.
Babarire ivyashitse.
Iyi nomero ya terefone ni iyande?
Sinteka.
Si igifaransi.
Reka kundaba!
Bitebe bitebuke bizoba.
Bambonye.
Birakwiye vyose ivy'urugendo?
Sinarinzi ko muri buhabe uyu munsi.
Yazunguje umutwe.
Uri iwacu?
Si ikintu co kwirata.
Ingo hejuru!
Ndakunda uyu muduga.
Ndazi aho mbwirizwa kugaba.
O yawe isa na A yawe.
Bigurwa angahe?
Bitware hirya.
Nti hanze!
Ushaka kuba hehe?
Murabe.
Ntanumwe antega ugutwi.
Ntiwibagire gutwara ibaruwa.
Turi ngaha kubera wewe.
Ubona iki?
Kubera iki ndi ngaha?
Nimukure ibirato vyanyu.
Baratuzi.
Uhaguruka ryari?
Sinzoheba.
Mva mu Bwongereza.
Uranhunga ko ndabivuze.
Reka kunsomboroza kubivuga.
Amadirisha araguruye.
Ntubwirizwa kuza.
Ntanumwe yumviriza.
Sinibagira na rimwe amaso.
Sinibaza ko aza.
Nta ngorane.
Umuceri utekwa uku.
Ndazi ingene bigirwa.
Ntanumwe yakubajije.
Bashaka ko tubigira.
Ubona iki hanze?
Narinzi ko bigushimisha.
Sinzorabayo.
Tom arihe?
Iki ni igifaransa?
Nyene ibi bitabo ni mushikanje.
Kuva ejo dushobora kujana ku kazi.
Twashitse.
Ndiga igifaransa imuhira.
Murakoze kwumviriza.
Ndazi iyo baja.
Ni igitabo c'agatangaza.
Ibitwazi vyacu birarushe.
Ndazi so wawe.
Niga igifaransa mw'ishure.
Mubwirizwa kugenda i muhira.
Abantu bose bagiye hehe?
Murashobora kwugurura idirisha?
Haraho uzogenda muri iri ci?
Mama wanje arihe?
Bitabaye ubu, ryari?
Nivyo urondera?
Umuduga wawe urihe?
Data wanje ntari imuhira.
Nta kibazo.
Hari ico ubizi ko?
Sinkugomwe.
Ubironderera ngaha?
Nta batunzi baba ngaha.
Muri ino gant hari intoboro ku rukumu.
Uramuzi.
Noshimishwa no kumubona.
Data ntari i muhira.
Heba!
Iri terefone ni iryande?
Urashobora gutera ururirimbo.
Mbabarire cane!
Ndazi kubikora neza cane.
Sinshonje.
Nagira ngo urashobora kubitegera.
Turi hehe?
Urukundo rurahuma.
Reka ndagitumeko.
Ndazi ko ubifise.
Sindi umunyeshuri.
Nzobigerageza.
Umuyaga ukomeye urahuhuta kandi sinshobora kugenda ningoga.
Ngirango ntubikunda.
Nabonye hariya mushikanje.
Sindaheba.
Uzosigara umwanya ungana iki?
Asa na Se wiwe.
Ivyo ni ibiki?
Uraberewe.
Inzu yanje iri hafi y'inyubakwa yo gusengeramwo.
Yahemutse kw'ijambo!
Amapome vyose aguye hasi azoribwa n'ingurube.
Sinashoboye kutarira.
Sinshaka kubisoma.
Ntanumwe azi izina ryiwe.
Urazi aho bari?
Ugenda kw ishure hehe?
Urihe?
Iciyumviro nyabaki!
Yarabimpaye.
Sindamubona.
Nyoko arihe?
Ntwumviriza.
Kubera iki abantu bavuga ivyo?
Amatapi yo mukahise arafise agaciro kanini.
Ndarahiye.
Sintegera igifaransa.
Nta numwe ahari!
Kubera iki mbwirizwa kubikora?
Ni ku wagatandatu.
Nuko rero nabigize.
Ndi umutetsi.
Ni angahe?
Ntidufise amahera.
Ndazi ko utega ugutwi.
Nimwambure ibirato vyanyu.
Ndazi ingene usa.
Ndanezerewe.
Uwu muduga ni mushasha?
Kuki utinjira?
Ntiyasomaye iki gitabo.
Sinshaka kuba umutunzi.
Urambabarira ko ndabivuze.
Ikinyamasyo ntikigira amenyo.
Ivyo bizonezereza.
Urashobora kujayo.
Uza imuhira ryari?
Ntiyasomaye iki gitabo.
Ubwirizwa kuvyuka.
Turagukunda.
Iki gitabo ni gishasha.
Uramuzi.
Ni umufaransa.
Simfise umuduga.
Muritwararikire umutwe wanyu.
Kubera iki udatomora ico ufise ku muzirikanyi?
Nshaka ko umubona.
Urashobora gukoresha uwu muduga.
Ntanzi.
Ndi umwigisha.
Ndamukunda.
Sindi umunyeshuri.
Urashaka kubibona?
Reka kuvuga ivyo!
Ndagukunda.
Yaje wenyene.
Naguze amagi n'amata make.
Urupapuru rumwe rurabuze.
Nasubiye kumubona.
Uyu ni nyoko?
Twakuriye hamwe.
Wari umugambi wande?
Muraturondera?
Nzoba ndi mu muduga wanje.
Sinkunda kwiruka.
Ni umufaransa.
Ni umuhungu muremure.
Ndazi ingene bameze.
Urazi kubigira neza cane.
Ndafise umuduga.
Uzoza iwawe ryari?
Ku mugoroba kuva isaha cumi na zibiri gushika isaha zibiri ni igihe co kunezerwa.
Ntutegerejwe kuza.
Ubwirizwa guheba inzoga.
Bitwarire nyoko.
Ahari ugushaka haba inzira.
Wahagaritse umuduga hehe?
Mpamagara hagati y'isaha imwe n'isaha zibiri.
Ufise bazoka mu kanwa, yicire.
Mbe nambare iki - ipantalo canke ijipo?
Igitabo kirihe?
Ni abanyamerika?
Bisa gute?
Reka kundaba!
Ndiko ndasoma igitabo.
Soma!
Ntaco ndabiziko.
Ntibimeze uko uvyiyumvira.
Tujane?
Ibintu vyawe birihe?
Ikosa ni iryande?
Sinywa.
Nguyo araje!
Sinzobireka
Ndaguhwatira umucungwa.
Turanezerewe.
Kubika ahapfutse kandi humutse.
Ntibintera iteka.
Ndabitwara.
Sindashonje.
Ndategera.
Si neza.
Niga igifaransa mw'ishure.
Kubera iki cubitse?
Nshaka ko uja imuhira.
Asa na nyina.
Urandondera?
Bishire nyoko.
Urazi ko mbwirizwa kugenda.
Umuduga urihe?
Uramukunda?
Tubwirizwa gushira uburinganire hagati y'bisohoka n'ivyinjira.
Inzoka yamize igikere.
Ntibaza uyu munsi.
Urazi ico ubaza?
Twugurure idirisha!
Kaze iwacu!
Uyu muhungu ni mwenebabo.
Kubera iki utari kw ishure?
Kubera iki tutaja imuhira?
Ndashobora kwinjira?
Urazi ko ndagukunda.
Abashakashatsi bubutse ku magufa y'umuntu mw'isenga.
Urugendo rwacu ruvana n'igihe.
Nshobore gusubira kubibona?
Izi ntambwe zirashobora kubuza ko ingwara isasagazwa.
Ngiyo ifagitiri.
Turabwirizwe gufungura ku mutaga hamwe.
Ntushavure!
Si isango y'ikiyago. Tuja gusa muri cenema.
Namukunze.
Kubera iki tudataha imuhira?
Sohoka mu cumba canje!
Ndi mushasha aha.
Nshaka kwiga igifaransa.
Nzoza kugutora.
Simfise mushikanje.
Nryama ubusa.
Mfise umukoshi.
Amazi arajovye.
Iyo menya nari kugenda.
Mvuga ico niyumvira.
Ni igiciro giki?
Ndazi aho turi.
Kubera iki bataza?
Ngiye guzana umuduga wanje.
Kubera iki utari mw'isomero?
Turi abanyeshuri ba kaminuza.
Sinzi izina ryiwe.
Nzota nomoke.
Ugenda kw'ishure gute?
Mbabarira!
Bireke.
Ntuntere kubivuga!
Urazi icarico?
Urambabarira ko ndabivuze.
Ndazi umuryango wiwe.
Ndazi ingene bigenda.
Nataye impfunguzo zanje.
Ndakira ibi.
Ntibimpa agateka.
Igituma c'urugendo rwanyu ni nyabaki?
Kubera iki tutabiraba?
Ntavuga icongereza.
Nariye amagi ejo.
Ni neza, siko?
Turamuzi.
Ndashaka kuruhuka gato.
Ntanumwe yakubajije.
Sinshonje.
Namerewe nabi.
Naganiriye vyose abavyeyi banje.
Mvyuka isaha imwe zo mugitondo.
Ntimwugurure idirisha.
Ingo wirabiye.
Kubera iki utariyo?
Kubera iki harashushe?
Iminsi yose aja ku kazi ku maguru, kiretse iyo hari imvura.
Ni rwacu.
Nturabe munsi.
Mushikawe amerewe gute?
Turashobora kugira aho tuganirira?
Mudutwaye hehe?
Narakunze uyu muduga.
Kubera iki wiga igifaransa?
Nanje ndavyiyumvira uko.
Ndababonye.
Ndazi uvyirumvira.
Yagirije uyo mugabo ubusuma.
Iyi kanzu nijewe nayikoreye.
Sindakwumva.
Sinzi amazina yabo.
Nganirira umugambi wawe.
Ndazi ico nogira.
Bavuga ko atunze cane.
Ipantalo yawe iranduye.
Muri Abadagi, sivyo?
Urayikunda?
"Aya marori ni ayande?" – "Nyeneyo ni Data."
Ntimukeneye gunkengurukira.
Mwashikiwe niki ejo ku mugoroba?
Dushaka ko ubitwara.
Asa na nyina wiwe.
Ko turi twenyene, reka twiryohere.
Twaje kukuraba.
Urabishaka canke?
Si umuduga wanje.
Sinzi izina ryiwe.
Urashaka ikintu co kunywa?
Ntimuzi namba ivyashitse, canke?
Ndazi icarico urukundo.
Sico kimwe.
Igitwazi kirasimba.
Ukora iki ngaha?
Ngiyo ifagitiri.
Ntanumwe antegura.
Twiga mw'isomero rimwe.
Warihe?
Vyanteye kukwiyumvira.
Murafise umuceri?
Aba ngaha?
Twojana.
Turavukana.
Ndazi igituma uri ngaha.
Kubera iki wiga muri kaminuza?
Nyoko arihe?
Bitebe bitebuke bizoshika.
Utaha ryari?
Natsitaye kw'ino.
Biranyuze.
Umviriza nyoko!
Soma ibi.
Nzobiguha.
Amakuru maki?
Va mu cumba canje!
Iki cayi ni icande?
Urashaka ikintu co kunywa?
Ndi umuhererezi.
Kigurwa angahe?
Ndashaka ko usoma iki gitabo.
Mva muri Bresil.
Nje kugutwara i muhira.
Twiga mw'isomero rimwe.
Ntutwibagira!
Nandika kuri twebwe.
Ntimutange amungane ya barundi ataruhusha.
Urafise aya mahera?
Ni bitoya birenze.
Ni akazi kiwe.
Ngico ico mwasavye.
Ni mwenewacu.
Urondera iki?
Araguzi?
Yamugomwe.
Nshaka kubibona.
Reka gutanga amategeko ngaha!
Rimwe rimwe tujana muri cenema.
Uba ngaha, sivyo?
Wasomye iki gitabo?
Turihe?
Kubera iki tubikora?
Ibi ni birebire birenze urugero.
Uremera ko ataco bintwaye?
Mu ruguma hari amashira.
Ni mwenewacu.
Ni akazi kiwe.
Urazi ico bavuze?
Sindabitegera.
Ntaco babiziko.
Ni umunyamerika?
Ikawa canke icayi?
Hariko haba iki hariya epfo?
Mbabarira ko nagutaye mu rudubi.
Turi twenyene.
Ndakunda ico nkora.
Ijwi ryanje rirasaraye kubera inkorora.
Urazi ico yavuze?
Ijambo ryiwe ryari agahore.
Ushaka kugenda ryari?
Sintegera ibintu nk'ivyo.
Uko ni vyiza gusumba?
Abo nabo mu bujapani?
Nzogerageza.
Arazi ko umukunda?
Turiko dutakaza umwanya uzimvye.
Kubera iki udaheba?
Tange insiguro y'amungane ibereye mudasamajwe n'izindi ndimi.
Umuryango wiwe urihe?
Magdalena na Ania ni abagenzi pfampfe.
Ndanezerewe ku uhimbawe.
Turakwiye gufungura ku mutaga hamwe.
Fata kimwe.
Urafise mwenewawe?
Twarukiye hamwe.
Ndakwemera.
Mbwirizwa kwiyumvira.
Mariya arihe?
Ndasemagurika.
Mbwirizwa guheraheza.
Ndanezerewe ko ariho uri.
Uribaza ko nezerewe?
Kubera iki utari kumwe na jewe?
Ntanumwe ari i muhira.
Mpore ko ndabivuze.
Yamukunze.
Ntiyibungenze.
Kubera iki batankunda?
Ifagitiri ringana gute?
Wampaye iki?
Ja hanze.
Tom ni umubaji.
Sindi umutunzi.
Arihanaguye icuya mu maso.
Ntibinyuze.
Ururuka!
Nzobijamwo.
Amajoro angahe?
Tuzobishobora.
Nazanwe no kuramukanya.
Mubwirizwa gutaha.
Asa na Se wiwe.
Mubwizwa gumperekeza.
Urazi aho aba?
Ntibinshimishije.
Kubera iki utajana na jewe?
Mpa isaha yawe.
Urafise amahera yanje?
Iri darapo ni nziza cane.
Nagira ngo woba watashe.
Simfise mwenewacu.
Ntaco ndabiziko.
Sinzi kugumya amazina.
Urashobora gusubiramwo?
Ndabirora.
Murazi aba bantu?
Iyi koti ni iyande?
Kubera iki mbikora?
Sindagutegera.
Iyi hinguriro rikora ivyuma vy'imiduga.
Sindi umunyeshuri.
Turumvikana.
Ntusubire kubikora.
Rabira mw'idirisha.
Ntibinshimishije.
Urupapuru rumwe rurabuze.
Akira amahera.
Aranezerewe.
Ururuka mu muduga.
Urashaka kumenya igituma?
Murashaka kubitora?
Wibuke ubuntu bwawe wiyobagize ibindi.
Ndi umuhererezi.
Wibaza ko ivyo ari ibiki?
Twipfuza insiguro zo mu rurimi rwa misi yose.
Nico gituma cakuzanye ngaha?
Sindabitegera.
Naje kwiga.
Ntanumwe yavuze ijambo.
Turavukana.
Harashushe birenze.
Nuko rero nabigize.
Mbwirizwa kwiga.
Urakoze cane!
Biramuraba.
Birakunezereje?
Ur'uwacu.
Urya mugambi wari uwande?
Singifise umushikiwanje n'umwe.
Turi abanyeshuri ba kaminuza.
Nta gishasha.
Uraza? Ego canke oya?
Ntiwoshobora kubisubira ico wavuze?
Ntanumwe yabonye ikintu.
Nzogerageza.
Nashaka kubaza, mbe mugenzwa n'amaki?
Ndazi uyo mukobwa.
Mukunda gusoma ubwoko bw'ibitabo ibihe?
Arakeneye amazi.
Bagutwaraye hehe?
Nta ngorane.
Biranshimishije.
Wanyoye ibikombe vy'ikawa bingahe?
Ibi biro ni ivyande?
Uyu muduga ni mwiza cane.
Turumva.
Ibitwazi vyacu vyarushe.
Tuzojana.
Amakuru yawe?
Ndazi ko ubifise.
Mbabarira kugukankamira.
Abana na we.
Ndi umwigisha.
Twamanutse twiruka agasozi.
Nta zina na rimwe nshobora kwibuka.
Urashaka kuba umutunzi?
Ndashaka gusoma iki gitabo.
Simbesha na rimwe.
Ndi umunyeshuri muri kaminuza.
Ibi bitabo ni rwacu.
Ntibashaka ko tubimenya.
Si umuduga wanje.
Waciye ku kimenyetso c'itara ritukura.
Ndazi ico mbwirizwe kwiga.
Ndagukumbuye cane.
Ndumva ico uvuga.
Nshaka ko utaha.
Tujana twese hamwe.
Tanga akaryobwa.
Sinkomeye muri vyo.
Nta numwe ahari!
Si ikintu co kwishima.
Murategera igifaransa?
Antera kwiyumvira.
Ni ku wambere.
Uyu muvinyu ni uwande?
Mfise mukuruwanje.
Ntibimara umwanya mu nini.
Iyo ukeneye imfashanyo urampamagara.
Nanje.
Twavanye.
Ngaha ntibaba abatunzi.
Ashaka gushika kuki?
Umviriza nyoko!
Ndakunda ibiharuro.
Nguyo araje!
Tujanayo twese hamwe.
Tuzongera mu ndwi iza.
Ndakunda kuraba ingene uteka.
Mukora iki?
Ndiko nduhuka.
Nabo baraza?
Urazi ko tugukunda.
Urashobora gutandukanya intama n'impene.
Nzovyiyumvira.
Ntanumwe antega ugutwi.
Ndakunda kwiga igifaransa.
Ngirango dushobora kujana mu nkengera y'ikiyaga iyi mpera y'indwi.
Kubera iki babikora?
Ntuza, sivyo?
Mubwirizwa gutaha.
Afise imyaka ingahe?
Ndakuzi.
Sinzobireka
Ntasa n'uwunezerewe.
Ndazi aho mbwirizwa kugaba.
Iminsi yose aja ku kazi ku maguru, kiretse iyo imvura igwa.
Urakoze cane!
Sinshaka guheba.
Hariko haba iki hariya epfo?
Nzobona igikino.
Bisa neza.
Ndiko ndasoma igitabo.
Urazi nyene uyu muduga?
Ndiko nduhuka.
Uri umunyeshuri mwiza.
Vyibagire ivyo.
Ndazi neza ko namubonye ahantu ikindi gihe.
Woba ufise umunota?
Ndakunda imishatsi migufi.
Urateganya kugenda mu nama?
Ijipo irandenze.
Ntundungike.
Bimuha.
Ururuka!
Kubera iki wibaza ivyo?
Ndafise bashikanje.
Yacishije igisu ciwe ishami ry'igiti.
Araza nawe?
Ntadukunda.
Bite!
Si vyiza.
Mbirizwa kwiga gifaransa.
Bizoba neza cane.
Ndarahiye.
Injira.
Ikintu cose gifise impera.
Nagize igitondo c'imirimo myinshi.
Biraduhimbaye cane.
Reka tugure ivyo.
Sindi umuntu mwiza.
Ndazi ico nzokora.
Ushaka kubimenya iki?
Turazi igituma waje ngaha.
Nyogokuru avuga buhoro buhoro.
Nzobigerageza.
Ndakunda kwiga igifaransa.
Aribungenze.
Iyo menya sinari kuza.
Wibaza ko ico ariki?
Ndashobora kwugururura irido?
Wari umunsi!
Ndazi ico nokora.
Ndi umunyeshuri muri kaminuza.
Nyumviriza.
Amahera yanje ari hehe?
Ndakubonye.
Uri imuhira?
Ndazi uvyirumvira.
Nshaka kuganira nawe.
Ndashimishwa nivyo mbona.
Ndazi ico wiyumvira.
Bikuvako.
Ndiga igifaransa imuhira.
Ni mushiki wawe?
Turavukana.
Ntibaza uyu munsi.
Abana bagiye kw ishure?
Urondera iki?
Muzinaniye hehe?
Ntanumwe antegura.
Simbiheba.
Ntundabe gutyo.
Akira amahera.
Kubera iki jewe?
Nzogaruka.
Ntunga ko nagutaye mu rudubi.
Nimudutore!
Iri jambo riva mu kigereki.
Ibisi irahagaze ariko nta muntu yururutse.
Uramukunda?
Ibarabara riri urwamo rwinshi.
Nasomye itama ryiwe.
Bivuge mu gifaransa.
Imbwa zihamba kenshi amagufa.
Ikirahuri cuzuye gushika hagati canke kirigusa gushika hagati?
Ntundabe gutyo.
Nimumutware mu cumba co kubaga.
Kenshi twagarutse zirayoye.
Mumuzi hehe?
Ushaka kuja hehe?
Mbwirizwa kureka.
Haracari kare ko tubivuga.
Ni umuntu mwiza.
Nzogushimisha.
Ndashaka gusubira kukubona.
Bandanya!
Ndashaka kukubona pe.
Ntimubitegeye?
Uri umugenzi wanje.
Ntwumviriza.
Kubera iki muri imuhira?
Urondera ibi aha?
Ayo mashurwe ubona ni amarosi.
Ntukomeye muri vyo.
Twoshobora kujana.
Urazi ko ndagukunda.
Duteka umuceri uku.
Nturi mwenewacu.
Ntuzoza, sivyo?
Baza imuhira.
Ndanezerewe ko uhari.
Nzobishobora.
Kera waranywa itabi, sivyo?
Urashobora gutora irangi iryariryo ryose rigushimisha.
Nta kamaro.
Ikosa ni iryande?
Uri umutetsi mwiza.
Iri kosa ni iryande?
Urazi ico yavuze?
Namerewe nabi.
Urashaka kumenya ingene?
Igiciro kiraduga.
Ukuboko kwanje kw'ibubamfu kwagize ibinyanya.
Iyi nyabu ni yanje.
Kunywa itabi vyica amagara.
Umuduga wa data ni mushasha.
Nje gusezera.
Sindavyumva.
Ntumbaze icarico.
Urakeneye umugambi.
Urantegera.
Urashaka kureka?
Ndakunda umuryango wanje.
Sindashaka kuba ngaha.
Mwebwe muri abana.
Nkeneye umwanya wo kwiyumvira.
Uyu muduga ni rwanje.
Ugara idirisha!
Sinumva igifaransa.
Ntiwibagire gutwara ibaruwa.
Nico nshaka kumenya.
Uranezereza.
Narinzi ko biguhimbara.
Ivyo birashavuza!
Nari mbizi.
Ico nico uriko urondera?
Naragukunda.
Sinzi izina ryawe.
Nzofata umunsi w'akaruhuko.
Muragaba k'umutwe wanyu.
Afise ibitabo amajana n'amajana.
Ntumwumvirize.
Ivyirabura ni vyanje.
Ukora iki?
Twipfuza amungane akwiye.
Ndacababara ivi gatoya.
Iki gitabo ntigifise akamo.
Sinshaka kukubona.
Ni umunyeshuri mwiza.
Ntubwirizwa kwandika ikete rirerire.
Ntunga ko nagutaye mu rudubi.
Uri umunyeshuri mwiza.
Ibirato birihe?
Aya masanganzira afise impanuka y'urupfu.
Baranezerewe.
Urashaka kwinjira?
Aramukunda.
So wawe arihe?
Subira gusoma.
Ndazi ko utega ugutwi.
Ntanumwe azi izina ryiwe.
Nzogenda n'umuduga.
Nturi musazanje.
Akora mw'ihinguriro.
Mpore ko ndabivuze.
Raba hariya!
Yama ata mobile yiwe.
Mba ngaha.
Nta kamaro!
Ndamuzi.
Ugara idirisha.
Ihinguriro rizotangura gukora mu mwaka uza.
Ibiciro vyaraduze.
Uyu mwaka ntegekanya gusoma ibitabo vyinshi bishoboka.
Siniyumva neza ngaha.
Turavukana.
Ikiganza gifise intoki zitanu: urukumu, inkombarukoko, msumba zose, igihugunibenga, agahererezi.
Nabonye so wawe.
Uriko usoma iki?
Ntanumwe ari i muhira.
Umuduga wanje urihe?
Ku wambere musée yama yugaye.
Urafise umuduga?
Kubera iki bavuga ivyo?
Sinzi guteka.
Kubika ahakanye kandi humutse.
Ubibona gute ku wagatanu?
Ndanezerewe ko ariho uri.
Biramuraba.
"Aya marori ni ayande?" – "Ni aya Data."
Ndazi ico nzokora.
Siho ari.
Reka gutungira ijisho amabere yiwe!
Ubu buriri ni ubwande?
Ndamusavye umpe urupapuro rwo kwandika.
Sinshaka kubimenya.
Ntiwibagire gutwara ikete.
Iyo azakugira umwanya yari kugenda.
Uwushaka kumurongora abwiriza kubiganira neza na se wiwe.
Aramwumva.
Nagira ngo urabizi.
Ni beza cane gwose.
Umuryango umerewe gute?
Ushaka kuzobibona.
Twashitse.
Ninde asoma?
Kubera iki abantu batankunda?
Mara umwanya munini niga igitari.
Ntibiri nkuko uvyiyumvira.
Mbabarira ko nagutaye mu rudubi.
Ndashonje.
Sintunze.
Kubera iki utumviriza?
Kubera iki ufise ico?
Umuduga urihe?
Ntegerezwa kugenda ubu.
Umuduga wanje wapfuye.
Turi imuhira.
Turanezerewe kubabona.
So wawe amerewe gute?
Ndakunda ibiharuro.
Ntanzi.
Ngirango azoza ejo.
Nanje ndururutse.
Inzu yanje iri hafi y'urusengero.
Ndazi ingene bikoreshwa.
Nkura ngaha.
Reka ndabe.
Yataye urupfunguzo rw'umuduga wiwe.
Uri umunyeshuri mushasha?
Birampimbaza.
Kubera iki tugira ivyo?
Mbabarira kugutuka.
Nta muduga mfise.
Ntuza, sivyo?
Aranezerewe.
Kubera wewe ndi mu ngorane.
Uribuka?
Tebuka!
Ntanumwe yarazi ibikenewe kurangurwa.
Narabiravye muri yu tubi.
Namaki?
Kubera wewe ndi mu rudubi.
Nshaka ko mubibona.
Ndashobora kumenya ibintu nokuzanira.
Sindakunda kwiga.
Ntanumwe abizi.
Bashaka ko tubikora.
Uba ngaha?
Ugara amadirisha yose.
Nshaka gutaha.
Nagize igitondo c'imirimo myinshi.
Narataye amarori yanje.
Bamwe muri abo bakozi ntibamenyeye gukora ako kazi.
Ukora iki ngaha?
Ntibanezerewe.
Birera?
Kore igikenewe.
Ntimushaka kumenya igituma?
Asa na musazawe.
Ndakwumviriza.
Kubera iki utari kumwe na jewe?
Sinshaka amahera yawe.
Ni umunsi!
Ndazi ibikenewe kurangurwa.
Mize ndababara mu muhogo.
Ndafise ibikorwa vy'ishure.
Narinzi ko wojayo.
Ntimusubire!
Reka nje kugura umukate.
Umukobwa wanje azorongorwa muri ruheshi.
Ndazi kubikora.
Nzero ni ukwezi kwambere mu mwaka.
Ndashika isaha zine.
Mbwirizwa kubimenya.
Ishokola irasosa.
Turahurirayo.
Ntubange ugutwi.
Ndashaka kubana na wewe.
Indimi zifise amajambo agoye.
Kera hari isengero ngaha.
Nawe turagukumbuye.
Wibaza ko ndi nde?
Kubera iki udashaka kugenda?
Ntimushaka kumenya ivyabaye?
Kubera iki wibaza ivyo?
Kubera iki mutagerageza iyi goti? Ijanye neza n'ipantalo yanyu.
Mushikanje asa na Mama.
Urashobora kugendayo.
Nshaka kukubona.
Ntibintera iteka.
Kubera iki utabikora?
Urafise uwo muvukana?
We si umwana.
Nta bitabo mfise vyo gusoma.
Twama dukina ku munsi w'Imana.
Mpora mesura isutiye yanje n'amaboko.
Iyi nzu ni iyande?
Kubera iki utari mw'isomero?
Ndibaza ko ari vyiza.
Sinzi iyo ngana.
Ndarurumba.
Turiga igifaransa.
Nshaka kukubona.
Ushaka kukigumya umwanya ungana iki?
Asa na Se wiwe.
Ntanumwe azi izina ryiwe.
Idirisha rirugaye.
Ntimusubire kugaruka.
Ni igitabo ciza cane.
Iki gitabo ni ciza cane.
Ja mu buriri!
Iki gitanda kiranonotse cane.
Sindabimenya.
Ryama neza, Timmy.
Ntwumviriza.
Ubwirizwa kureka kunywa.
Vugana nanje.
Sinashoboye kutarira.
Yamoye umutwe wiwe.
Sinzi.
Yatoye ikanzu izimvye gusumba zose.
Ndazi izina ryiwe gusa.
Asa na mwenewanyu.
Reka kundaba.
Ntibisa na rwawe.
Ndakujana.
Birakwiye vyose ivyerekeye vy'urugendo?
Ndibaza ko bitunganye.
Sindi ikijuju.
Ndi ngaha kubera wewe gusa.
Umunyeshuri arashaka kukubona.
Mbe nambare iki - ipantalo canke ijipo?
Ndi umunyeshuri mushaha muri kaminuza.
Agiye buhoro buhoro kugira umwana ashobore gukurikira.
Icumba ni ciza.
Sinzoreka.
Nariyumviye kuguma iminsi mike iwawe.
Ndi umunyeshuri muri kaminuza.
Turaja ku burengero.
Niyumviye ko vyogutwenza.
Imuhira bite?
Ndakunda kuza ino.
Icumba cawe gifise amadirisha abiri?
Natanguye gukora muri ino societé kuva umwaka uheze.
Ni birebire birenze urugero.
Nzotegera.
Kubera iki ufise ivyo?
Ntiyasomaye iki gitabo.
Mba muri Noroveje ubu.
Ejo naryamye umunsi wose, kuko wari umunsi w'Imana.
Musazawe arihe?
Nazanwe no kwiga.
Sinshobora kwoza amasahani. Harabuze amazi.
Ndi mu karuhuko.
Arazi ko umukunda?
Ndi umwotsi w'imikate.
Ni umuduga wanje mushasha.
Nimusohoke mu muduga.
Raba neza ingene ndabikora!
Ndi mu gikoni.
Noshimishwa no kumenya izina ryawe.
Urarikunda?
Ndazi ikiriko kiba.
Hagati y'igisigara hadutse umuriro.
Ntubinywe!
Nta mahera tugifise.
Umuryango umerewe gute?
Wigahe?
Ndakunda ico nkora.
Nta muduga dufise.
Subira kubivuga.
Nzokunezereza.
Ndakunda kuba ngaha.
Usa gute?
Afise umuduga.
Wibuke ubuntu bwawe kandi wibagire ibisigaye.
Ntumpate kubikora.
Mbwirizwa kukubona.
Ntusabe amahera.
Ndazi ico bagira.
Urazi ingene bisa?
Ndanezerewe ko ariho uri.
Aho ufungura ku mugoroba sindabinzwe.
Muri abana.
Ntibakunezereza.
Igituro ca bisi kiri iminota itanu uvuye ngaha.
Ndibaza ko ntegeye.
Uri umutetsi mwiza.
Reka ndaguhobere.
Wipfuza iki?
Kubera iki mumbaza?
Isaha yanje irihe?
Dusangire akayoga.
Namubonye yiruka.
Ikibazo ciza.
Ndakunda gusoma.
Uyu mwigeme yiyambika nk'umuhungu.
Ndagukunda.
Yatoye ikanzu izimvye gusumba zose.
Nimukure ibirato vyanyu.
Ntitubizi.
Aramukunda.
Ni umuntu mwiza.
Biranshimishije.
Mariya arihe?
Kubera iki umbaza?
Ni umugambi mwiza.
Nzokunyara.
Ntasa n'uwunezerewe.
Mbabarire cane!
Urabitegera?
Wewe uri umugenzi wanje.
Mukunda gusoma ubwoko bw'ibitabo ibihe?
We si umwana.
Kubera iki ujaho?
Nagira ngo woba watashe.
Ihinguriro rikora ibihumbi n'ibihumbi vy'amacupa kira kwezi.
Harashushe cane ngaha.
Sinzi aba bantu.
Uzomukunda.
Ntuzoza, sivyo?
Ndoza amadirisha.
Kubera iki mbwirizwa kugenda.
Sawa, nzogikura.
Narinzi ko vyogushimisha.
Reka ndakugurire gishasha.
Ja hiyo!
Ur'uwiwacu.
Ni binini birenze?
Aramukunda.
Arakunda gusoma ibitabo.
Kuki utinjira?
Sinzi igihe bifata.
Ntuzi icarico?
Kubera iki utajana na jewe?
Kubera iki ubaza?
Fata ico wipfuza.
Uzobikunda.
Ntavuga icongereza.
Umuduga wapfuye.
Uru ruhome rurakanye.
Kubera iki wibaza uko?
Ntanumwe azi amazina yabo.
Njana.
So arihe?
Ndagenda kuryama.
Ndashobore kubikoresha?
Ni birebire birenze?
Wabonye amaso yabo?
Uramuzi?
Ntibamuriha ku kwezi ahubwo ku munsi.
Neza, nawe?
Ndi umushinwakazi.
Nyene uyu muduga ni data wanje.
Urakoze!
Asa na nyina.
Turamuzi.
Amashurwe n'ibiti birakeneye impemu nziza n'amazi mashasha.
Nanje ngenda kw'ishure ngaha.
Ndaje kuguhitana.
Ejo hari kuwagatanu.
Nguyo!
Ntitwumva igifaransa.
Ntidushaka kubimenya.
Ndagufitiye amahera.
Ndaribwa mu nda.
Ntimwongere kugaruka.
Ndategera ico uvuga.
Ndazi igituma ubishaka.
Ndibaza ko azoza.
Tom nihari nawe?
Raba ingene biteye igomwe.
Oya, urakoze.
Wiyumvira iki?
We si umwana.
Ntanumwe arazi aho turi.
Ngirango ntibigushimisha.
Ni rwacu.
Ntadukunda.
Bizoba neza cane.
Ni umufaransa.
Waciye ku kimenyetso gitukura.
Urashaka ko nza?
Narinzi ko uri ngaha.
Reka gusoma.
Bavuga ko atunze cane.
Ndazi neza ko hari aho maze kumubona.
Bite uyu munsi?
Uruhanga rwawe rurashushe cane. Ndakeeka ko ufise inyonko.
Aramutegera.
Muri abanyeshuri?
Ijoro ryiza!
Sinzi aho bari.
Kubera iki udataha?
Ndibaza ko navyicayeko.
Nagira ngo urabizi.
Inzu yanje iri hafi y'isengero.
Simfise mushikanje.
Ntitubwirizwe kubivugana ubu nyene.
Ndabizi.
Sinshaka aya mahera.
Umutetsi arihe?
Urashobora kurara iwacu.
Nzanira ingwa zibiri.
Uyu muduga usa na mushasha.
Wiga ryari?
Aya madirisha araba mu bumanuko.
Ntuhebe!
Nanje.
Kubera iki utari kw ishure?
Iri terefone ni iryande?
Iri terefone ni iryande?
Turabizi.
Data ari imuhira.
Sinzi ico ushaka.
Akira kimwe.
Umuryango wiwe urihe?
Iki ciyumviro cari icande?
Ndi mu kiruhuko.
Urarwaye, ubwirizwa kuruhuka.
Amahera yarampereyeko.
Ibitoke bisa n'umuhondo.
Nta wundi muntu yarahari kiretse jewe.
Navuze ko bimbabaje.
Ndazi ico mvuga.
Nagira ngo urashobora kubitegera.
Umugenzi wanje vyaramushikiye nawe mu ndwi iheze.
Ntwara i muhira.
Nzobitora.
Tuzongera ku wambere.
Yamukunze.
Musazawe arihe?
Ntuzoza, sivyo?
Iyo aguma imuhira, ntiyogize ingorane.
Ntusa neza.
Nico cakuzanye ngaha?
Uzomukunda.
Ndamubonye.
Nico ndiko ndondera.
Ingo!
Sindi intore.
Ndoza amadirisha.
Sinsa uko.
Data wanje ntari imuhira.
Ntusubire!
Urawukunda?
Siho ari.
Umuhungu arasimba.
Ishure riraheze.
Nosubira kubikora.
Amafaranga yaheze.
Turi abanyeshuri ba kaminuza.
Nabiketse.
Mbwirizwa kuruhuka.
Nanje ndavyiyumvira uko.
Ndakujana.
Namugwiriye.
Kubera iki urwanko rwinshi?
Narasomye iki gitabo.
Ndaje kugutora.
Ndibaza ko ntegeye.
Urazi ico ubwirizwa gukora?
Bimuhe.
Muri beza cane gwose.
Ndibaza ko ntegeye.
Nimwambure ibirato vyanyu.
Ndazi ko unkunda.
Nturi musazanje.
Nzobiraba.
Uyu munsi ni umunsi w'Imana.
Ndabizi.
Nzomoka.
Iri darapo ni nziza cane.
Kaze iwacu!
Tuzotunga.
Urabona iyi nzu? Ni inzu yanje.
Biragenda?
Nzokora ico unsaba.
Ni birebire birenze.
Reka ndabirabe.
Urakoze cane.
Ndakeneye umwanya wo kwiyumvira.
Narinzi ko bikunezereza.
Nico gitabo mfise nanje.
Uriko usoma iki?
Mvuga indimi zitatu.
Uba he?
Nikomerekeje n'imbugita ku rutoki.
Ntitumuzi.
Ntimugaruke.
Uzi iki?
Turashobora gutangura ubu?
Ntadukunda.
Arakunda gusoma ibitabo.
Raba ico neza.
Simbikeneye.
Hari imashini yo kumesura mu nzu?
Imana iguhezagire!
Ndazi aho uba.
Uzomara umwanya ungana iki?
Ni murabe neza iri foto.
Ubibona gute?
Ndakunda ibiharuro.
Umubanyi wanje ni umubaji.
Ibiti vyinshi vyaraguye.
Uragikunda?
Ja ku ruhande!
Ntimushakisha igituma!
Ndavyakira.
Niko bimeze.
Jana hiyo.
Abonye amaraso umurwayi yaciye araba.
Urazi ico bashaka?
Urashaka kuraba iki?
Nzoguha igitabo.
Akinirahe?
Ndagukunda nanje.
Hatari ubu, ryari?
Sinzi aho muba.
Kubera iki ataco uronka?
Ugurura idirisha.
Ntiwibagire kubaza ibindi bibazo.
Ni isaha icenda ibuze iminuta icumi n'itanu.
Twatandukanye.
Ndazi ko wumviriza.
Ni naco gituma ndagukunda.
Muzi iki ku vyashitse?
Bazomenya uko bagira.
Tuhavuye tuba twenyene.
Urazi aho biri?
Turabizi.
Ndazi ingene umuntu ashikayo.
Umuduga wanyu wabaye iki?
Mw ijoro inyabu zose zirasa.
Iki gitabo ni gishasha.
Nta mazi akiri mw'icupa.
Ngurisha impuzu ku murongo.
Harashushe cane, sivyo?
Ndazi ibikenewe gukorwa.
Nguyo!
Ndakwiyumvira.
Uribuka uru rukino?
Aranezerewe.
Ntitugifise amahera.
Sinzi ico nshaka.
Murakoze!
Uyu munsi ni kuwagatatu.
Urabizi?
Mubaze izina ryiwe.
Ntibashaka kubikoresha.
Indoto yanje yabaye ukuri.
Muvahe?
Ndazi ko wumviriza.
Raba neza aho ugenda.
Ntiwibagire gutwara ikete.
Arumva igifaransa.
Ndamukunda.
Ndagusavye soma ivyanditse munsi.
Sindi umunyeshuri muri kaminuza.
Iyi mbugita irapfushe.
Ndakwumviriza.
Ndibaza ku mfise umwanya w'ikindi gikombe c'ikawa.
Turakunda pariki yacu.
Kubera iki unkunda?
Nturabeyo.
Nshaka ko ubisoma.
Raba neza iyo uja.
Nagira ngo urashobora kubitegera.
Ntibintera iteka.
Iri jambo ryamuka mu kigereki.
Nyene ikintu ni musazanje.
Kubera iki mbwirizwa kubikora?
Kubera iki utari aha?
Capfuye?
Ndazi ibikenewe gukorwa.
Ntiwibagire gutwara ikete.
Ntushaka kumenya ivyo!
Ndazi nyoko.
Iryo jambo ntaryonzi.
Ndonka ico nshaka.
Ikanzu rikozwe mw'iharire.
Ndipfuza impobero.
Amahera yanje ari hehe?
Kubera iki ubibaza?
Urafise ikintu mu gutima, ushaka kwikura? Urashobora binganirira.
Murakoze cane.
Uyu mwigeme yiyambika nk'umuhungu.
Naje kukurondera.
Ku minsi y'Imana simba ndi imuhira.
Korera iciza ababanka.
Iri jambo ryamuka mu kigereki.
Iki ciyumviro cari icande?
Ntimutore inomero.
Izina ryanje ni John.
Urategera ivyanditse ngaha?
Mfise benewacu.
Urazi nyene uyu muduga?
Sinzoheba.
Ariko yiga.
Ushaka ko ndagusigira irangi ku nzara zawe?
Ni ku wagatandatu.
Ndakeneye abakozi b'abitanzi batatu.
Nta mahera yari agifise.
Sibijanye n'amahera.
Ntitumuzi.
Ntumpebe.
Ushobora kuvga icongereza.
Va mu buriri bwanje!
Ndabitegera.
Mbwirzwa guhagarika.
Umuvyeyi wanje arankunda.
Sinshaka gutunga.
Ndafise amahera.
Ipantalo yanje yajovye.
Iyi nzoga ni iyande?
Ndazi aba bantu.
Simfise aho mba.
Twatandukanye.
Ntibaza uyu munsi.
Udushakako iki?
Niki?
Mbirizwa kwiga gifaransa.
Mushikawe amerewe gute?
Sindashaka kurwara.
Arashimishwa cane n'ikinga yiwe nshasha.
Ineza ihimbara abantu gusumba ubwiza?
Ntimubitegera?
Nje gusezera.
