Hagati y'igisigara hadutse umuriro.
Maze kuduga aka gasozi niruka, ugusemagurika ni kwose.
Mw ijoro inyabu zose zirasa.
Amapome vyose aguye hasi azoribwa n'ingurube.
Mbe nakunze?
Amatapi yo mukahise arafise agaciro kanini.
Ntanumwe amuzi neza kiretse abavyeyi biwe.
Indahiro ni ideni.
Icumba cawe gifise amadirisha abiri?
Ni abanyamerika?
Nabo baraza?
Abo nabo mu bujapani?
Abo ni abajapani?
Bariko baturaba?
Uri umutamvyi mwiza?
Uri umunyeshuri mushasha?
Uri iwacu?
Uraza canke?
Uraza? Ego canke oya?
Urataha?
Uragenda canke?
Uragenda canke ntugenda?
Haraho uzogenda muri iri ci?
Uranezerewe?
Uri imuhira?
Uri iwacu?
Uri iwawe?
Uriga igifaransa?
Urandondera?
Ico nico uriko urondera?
Nivyo urondera?
Ubironderera ngaha?
Urondera ibi aha?
Muraturondera?
Ni twebwe murondera?
Uri mushasha?
Urateganya kugenda mu nama?
Muri abanyeshuri?
Mubaze izina ryiwe.
Umuyaga ukomeye urahuhuta kandi sinshobora kugenda ningoga.
Umunyeshuri arashaka kukubona.
Ibitoke bisa n'umuhondo.
Korera iciza ababanka.
Nzanira ingwa zibiri.
Kenshi twagarutse zirayoye.
Ndashobora kwinjira?
Ndashobora kwugururura irido?
Ndashobore kubikoresha?
Murashobora kwugurura idirisha?
Uribuka uru rukino?
Woba ufise umunota?
Urashobora gutandukanya intama n'impene.
Urazi gutandukanya intama n'impene?
Nimumutware mu cumba co kubaga.
Tanga akaryobwa.
Ishokola irasosa.
Ishure riraheze.
Ugara amadirisha yose.
Ugara idirisha!
Ugara idirisha.
Ikawa canke icayi?
Ingo wirabiye.
Ingo!
Injira.
Bireke.
Komera ko muheto, Tom. Ntiwitinye!
Ingo hejuru!
Ingo kunsura.
Za kunsura.
Ndabasavye, mumpe ifagitiri.
Urashobora gusubiramwo?
Ntiwoshobora kubisubira ico wavuze?
Data ntari i muhira.
Wabonye amaso yabo?
Ineza ihimbara abantu gusumba ubwiza?
Arazi ko umukunda?
Aba ngaha?
Arazi ko umukunda?
Araguzi?
Aba ngaha?
Birakunezereje?
Biragushimishije?
Birakunyuze?
Tom arazi igituma?
Tom arazi imvo?
Korera iciza ababanka.
Imbwa zihamba kenshi amagufa.
Mbwirizwa kwugurura idirisha?
Ndazi Tom?
Ntimutange amungane ya barundi ataruhusha.
Ntusabe amahera.
Ntusubire kumbaza.
Ntumbaze icarico.
Ntubaze.
Ntiwitinye.
Ntushavure!
Ntimuhindure amungane ata makosa afise. Murashobora kuyahinyanyura mu bundi buryo.
Ntimusubire kugaruka.
Ntimwongere kugaruka.
Ntimugaruke.
Ntimusubire!
Ntimusubire kubigira.
Ntusubire!
Ntusubire kubikora.
Ntubinywe!
Ntiwibagire kubaza ibindi bibazo.
Ntiwibagire gutwara ibaruwa.
Ntiwibagire gutwara ikete.
Ntiwibagire gutwara ibaruwa.
Ntiwibagire gutwara ikete.
Ntiwibagire gutwara ibaruwa.
Ntiwibagire gutwara ikete.
Ntutwibagira!
Ntundabe gutyo.
Ntuhebe!
Ntumpebe.
Ntumwumvirize.
Nturabeyo.
Ntundabe gutyo.
Reka kundaba!
Reka kundaba!
Ntundabe gutyo.
Nturabe hasi.
Nturabe munsi.
Ntumpate kubikora.
Ntuntere kubivuga!
Reka kunsomboroza kubivuga.
Ntimwugurure idirisha.
Ntusubire kuvuga iri jambo.
Ntundungike.
Ntumuhagarike.
Ntuzi icarico?
Ntimubitegera?
Ntimubitegeye?
Ntimushaka kumenya ivyabaye?
Ntimushaka kumenya igituma?
Abana bagiye kw ishure?
Baba iwawe?
Kore igikenewe.
Urafise musazawe?
Urafise mwenewawe?
Urafise uwo muvukana?
Urafise umuduga?
Urafise amahera yanje?
Uramfitiye amahera?
Murafise umuceri?
Urafise aya mahera?
Uramuzi?
Urazi izina ryiwe?
Urazi ingene bisa?
Hari ico ubizi ko?
Urabizi?
Murazi aba bantu?
Urazi ico yavuze?
Urategera ivyanditse ngaha?
Urazi icarico urukundo?
Urazi ico yavuze?
Urazi ico bavuze?
Urazi ico bashaka?
Urazi icarico?
Urazi ico ubwirizwa gukora?
Urazi ico ubwirizwa kugira?
Urazi ico ubaza?
Urazi aho arihe?
Urazi aho aba?
Murazi aho mba?
Urazi aho arihe?
Urazi aho bari?
Urazi aho biri?
Urazi nyene uyu muduga?
Urazi nyene uyu muduga?
Uragikunda?
Urarikunda?
Urawukunda?
Urayikunda?
Urakunda kwiga?
Urakunda kwiga?
Uba ngaha?
Uramukunda?
Uramukunda?
Uribuka?
Kora ibikorwa vyawe vy'ishure.
Urabibonye?
Murabona iyi nzu? Ni inzu yanje.
Urabona iyi nzu? Ni inzu yanje.
Uremera ko ataco bintwaye?
Uribaza ko nezerewe?
Murategera igifaransa?
Urabitegera?
Urashaka umuduga?
Urabishaka canke?
Urashaka ko nza?
Ushaka ko ndagusigira irangi ku nzara zawe?
Urashaka ikintu co kunywa?
Urabishaka canke?
Urashaka gutunga?
Urashaka kuba umutunzi?
Urashaka kwinjira?
Urashaka ikintu co kunywa?
Urashaka ikintu co kunywa?
Urashaka kumenya ingene?
Urashaka kumenya igituma?
Urashaka kubibona?
Urashaka kureka?
Murashaka kubitora?
Murashaka kubitwara?
Ikintu cose gifise impera.
Mbabarira!
Mbabarira!
Amashurwe n'ibiti birakeneye impemu nziza n'amazi mashasha.
Vyibagire!
Vyibagire ivyo.
Uzosigara umwanya ungana iki?
Amajoro angahe?
Ku mugoroba kuva isaha cumi na zibiri gushika isaha zibiri ni igihe co kunezerwa.
Kuva ejo dushobora kujana ku kazi.
Ururuka!
Ururuka!
Bitware hirya.
Jana hiyo.
Nkura ngaha.
Bandanya!
Ja hanze.
Va mu buriri bwanje!
Sohoka mu cumba canje!
Va mu cumba canje!
Nimusohoke mu muduga.
Ururuka mu muduga.
Bimuha.
Bimuhe.
Bimuha.
Bimuhe.
Mpa igitabo.
Mpa isaha yawe.
Heba!
Komeza!
Ja hiyo!
Imana iguhezagire!
Neza, nawe?
Nagasaga!
Ijoro ryiza!
Ikibazo ciza.
Ja mu buriri!
Dusangire akanyobwa.
Dusangire akayoga.
Ni murabe neza iri foto.
Wasomye iki gitabo?
Yagirije uyo mugabo ubusuma.
Yaje wenyene.
Yacishije igisu ciwe ishami ry'igiti.
Ntiyasomaye iki gitabo.
Yahemutse kw'ijambo!
Ntadukunda.
Ntasa n'uwunezerewe.
Ntavuga icongereza.
Ntanzi.
Ntadukunda.
Ntasa n'uwunezerewe.
Ntadukunda.
Ntavuga icongereza.
Yarabimpaye.
Iminsi yose aja ku kazi ku maguru, kiretse iyo hari imvura.
Iminsi yose aja ku kazi ku maguru, kiretse iyo imvura igwa.
Afise umuduga.
Ni umunyeshuri mwiza.
Ni umufaransa.
Aranezerewe.
Yamugomwe.
Yamukunze.
We si umwana.
Siho ari.
We si umwana.
Biramuraba.
Ni akazi kiwe.
Asa na Se wiwe.
Arakunda gusoma ibitabo.
Asa na Se wiwe.
Asa na nyina.
Asa na nyina wiwe.
Asa na data.
Asa na musazawe.
Asa na mwenewanyu.
Aramukunda.
Nta mahera yari agifise.
Nguyo araje!
Ngiyo ifagitiri.
Ngico igitabo cawe.
Aya ni amadolari atanu.
Nguyo araje!
Nguyo!
Ngiyo ifagitiri.
Ngico ico mwasavye.
Ni umuhungu muremure.
Ni umufaransa.
Ni umuntu mwiza.
Yama ata mobile yiwe.
Aranezerewe.
Yazunguje umutwe.
Ariko yiga.
Asa na Se wiwe.
Arashimishwa cane n'ikinga yiwe nshasha.
Arumva igifaransa.
Agiye buhoro buhoro kugira umwana ashobore gukurikira.
Arihanaguye icuya mu maso.
Akora mw'ihinguriro.
Bite!
Bite!
Ijambo ryiwe ryari agahore.
Ijambo ryiwe ryari igitangaza.
Ubibona gute ku wagatanu?
Ivyo birashavuza!
Imuhira bite?
Namaki?
Bite uyu munsi?
Ugenda kw'ishure gute?
Ugenda kw'ishure gute?
Uzi izina ryanje hehe?
Biragenda?
Umuryango umerewe gute?
Umuryango umerewe gute?
So wawe amerewe gute?
Mushikawe amerewe gute?
Ushaka kukigumya igihe kingana iki?
Ushaka kukigumya umwanya ungana iki?
Amaze igihe kingana iki arwaye?
Uzomara umwanya ungana iki?
Wanyoye ibikombe vy'ikawa bingahe?
Bigurwa angahe?
Kigurwa angahe?
Ni angahe?
Ni igiciro giki?
Afise imyaka ingahe?
Afise imyaka ingana iki?
Umuryango umerewe gute?
So wawe amerewe gute?
Mushikawe amerewe gute?
Mpora mesura isutiye yanje n'amaboko.
Ndi umutetsi.
Ndi umunyeshuri mushaha muri kaminuza.
Ndi umwigisha.
Ndi umunyeshuri muri kaminuza.
Ndi umushinwakazi.
Ndanezerewe ko ariho uri.
Ndanezerewe ko uhari.
Ndashonje.
Ndakwumviriza.
Ndi mushasha aha.
Sindi umunyeshuri.
Sindi umunyeshuri muri kaminuza.
Sindashonje.
Sinshonje.
Ntibimpa agateka.
Ntibintera iteka.
Ndiko ndasoma igitabo.
Mbabarire cane!
Ndoza amadirisha.
Nariye amagi ejo.
Ndakwemera.
Naguze amagi n'amata make.
Naje kwiga.
Nazanwe no kwiga.
Naje kukurondera.
Nje gusezera.
Nazanwe no kuramukanya.
Sinshobora kwoza amasahani. Harabuze amazi.
Sindavyumva.
Nta zina na rimwe nshobora kwibuka.
Mva muri Bresil.
Mva mu Bwongereza.
Sinashoboye kutarira.
Sinashoboye kutarira.
Nasivye kw'ishuri.
Nikomerekeje n'igisu ku rutoki.
Nikomerekeje n'imbugita ku rutoki.
Nabigiriye wewe.
Sinarinzi ko muri buhabe uyu munsi.
Sinarinzi ko muri buhabe uyu munsi.
Ndashaka kugurana umuduga.
Noshimishwa no kumubona.
Simfise mushikanje.
Sinibaza ko aza.
Ntibindaba mugihe ahimbawe.
Aho ufungura ku mugoroba sindabinzwe.
Sinteka.
Sinywa.
Siniyumva neza ngaha.
Sindabitegera.
Sindagutegera.
Simfise musazanje.
Simfise mwenewacu.
Simfise umuduga.
Simfise aho mba.
Simfise imuhira.
Singifise umushikiwanje n'umwe.
Simfise mushikanje.
Simfise mwenewacu.
Nta bitabo mfise vyo gusoma.
Simfise amahera.
Sintegera ibintu nk'ivyo.
Ntaco ndabiziko.
Sinzi izina ryiwe.
Sindamuzi.
Sinzi izina ryiwe.
Sinzi igihe bifata.
Sinzi igihe uko kingana.
Sinzi gute.
Sinzi ingene.
Sinzi guteka.
Sinzi.
Iryo jambo ntaryonzi.
Sinzi iryo jambo.
Sinzi amazina yabo.
Sinzi aba bantu.
Sinzi ico nshaka.
Sinzi ico nokora.
Sinzi ico novuga...
Sinzi ico novyiyumvirako.
Sinzi ico ushaka.
Sinzi aho aba.
Sinzi aho bari.
Sinzi iyo ngana.
Sinzi aho muba.
Sinzi izina ryawe.
Sindakunda kwiga.
Sinkunda aba bantu.
Sinkunda kwiruka.
Sinsa uko.
Simbikeneye.
Sindabikeneye.
Sindamubona.
Sintegera gute.
Sintegera ingene.
Sinkubona.
Sinibaza ko aza.
Sinibaza ko aza.
Sintegera igifaransa.
Sinumva igifaransa.
Sindabitegera.
Sindavyumva.
Sintegera iri jambo.
Sindakwumva.
Sinshaka aya mahera.
Sindashaka kuba ngaha.
Sinshaka gutunga.
Sinshaka kuba umutunzi.
Sinshaka guteka.
Sindashaka kurwara.
Sinshaka guheba.
Sinshaka kubimenya.
Sinshaka kubisoma.
Sinshaka kukubona.
Sinshaka amahera yawe.
Ndashaka kukubona pe.
Namerewe nabi.
Namerewe nabi.
Iyo azakugira umwanya yari kugenda.
Iyo aguma imuhira, ntiyogize ingorane.
Iyo aguma imuhira uyo munsi, ntiyogize isanganya.
Ntariye nopfa.
Iyo menya nari kugenda.
Iyo menya sinari kuza.
Niibagiye kugura umukate.
Iyo udategereye, baza.
Utumvise, baza.
Ufise bazoka mu kanwa, yicire.
Iyo ukeneye imfashanyo urampamagara.
Mu mwaka uheze navyaye imfura yanje.
Nahaye umuhungu igitabo.
Ndabitegera.
Nanje ndururutse.
Mvyuka isaha imwe zo mugitondo.
Ndonka ico nshaka.
Ndategera ico uvuga.
Na jewe ngenda kw'ishure ngaha.
Nanje ngenda kw'ishure ngaha.
Nagize igitondo c'imirimo myinshi.
Mfise mukuruwanje.
Ndafise umuduga.
Ndarurumba.
Ndameneka umutwe.
Mfise mukuruwanje.
Ndafise ikibazo.
Nashoboye kugira.
Ndafise ibikorwa vy'ishure.
Nataye impfunguzo zanje.
Naratakaje ikaramu ryanje.
Ndagufitiye amahera.
Ndafise amahera.
Nta muduga mfise.
Simfise aho mba.
Mfise benewacu.
Ndafise bashikanje.
Mbwirizwa kubimenya.
Mbwirizwa kumenya imvo.
Mbirizwa kwiga gifaransa.
Mbwirizwa kwiga.
Mbwirizwa kukubona.
Mbwirizwa guheraheza.
Mbwirizwa kureka.
Mbwirzwa guhagarika.
Mbirizwa kwiga gifaransa.
Mbwirizwa kuruhuka.
Mbwirizwa kwiyumvira.
Narumvise ko warongoye.
Ndumva ico uvuga.
Ndizeye ko ukomeye neza.
Natsitaye kw'ino.
Nasomye itama ryiwe.
Nari mbizi.
Narinzi ko biguhimbara.
Narinzi ko bigushimisha.
Narinzi ko bikunezereza.
Narinzi ko uri ngaha.
Narinzi ko wojayo.
Narinzi ko vyogushimisha.
Ndamuzi.
Ndamuzi.
Ndazi izina ryiwe gusa.
Ndazi umuryango wiwe.
Ndazi ingene bigenda.
Ndazi ingene bigirwa.
Ndazi ingene bikorwa.
Ndazi kubikora.
Ndazi kubikora.
Ndazi ingene umuntu ashikayo.
Ndazi ingene bikoreshwa.
Ndabizi.
Ntaco ndabiziko.
Ndazi uyo mukobwa.
Ndabizi.
Ndazi ko ubifise.
Ndazi ko unkunda.
Ndazi ko utega ugutwi.
Ndazi ko wumviriza.
Ndazi ko wabivuze.
Ndazi uyo mukobwa.
Ndazi uyo mwigeme.
Ndazi aba bantu.
Ndazi ibitari bike kuri wewe.
Ndazi aba bagore.
Ndazi ico nogira.
Ndazi ico nokora.
Ndazi ibikenewe gukorwa.
Ndazi ico nzokora.
Ndazi ico nkora.
Ndazi ico mvuga.
Ndazi ibikenewe gukorwa.
Ndazi ibikenewe kurangurwa.
Ndazi ico nzokora.
Ndazi ico nogira.
Ndazi ico nokora.
Ndazi icarico urukundo.
Ndazi ikiriko kiba.
Ndazi ikiriko kiba.
Ndazi ikiriko kiba.
Ndazi ico bagira.
Ndazi ingene bameze.
Ndazi ico baravuze.
Ndazi ibikenewe gukorwa.
Ndazi aho mbwirizwa kugaba.
Ndazi ico mbwirizwe kwiga.
Ndazi aho mbwirizwa kugaba.
Ndazi ico wiyumvira.
Ndazi uvyirumvira.
Ndazi ingene usa.
Ndazi ico wiyumvira.
Ndazi uvyirumvira.
Ndazi aho ari.
Ndazi iyo baja.
Ndazi aho turi.
Ndazi aho uba.
Ndazi igituma uri ngaha.
Ndazi igituma ubishaka.
Ndazi ko ubifise.
Ndazi ko ubizi.
Ndazi ko unkunda.
Ndakuzi.
Ndazi ko utega ugutwi.
Ndazi ko wumviriza.
Ndazi so wawe.
Ndazi nyoko.
Ndazi ko wabivuze.
Niga igifaransa mw'ishure.
Kira gitondo mva imuhira imbere y'isaha zibiri.
Ndakunda kuba ngaha.
Ndakunda ibiharuro.
Ndakunda ibiharuro.
Ndakunda ibiharuro.
Ndakunda imishatsi migufi.
Ndakunda kwiga igifaransa.
Ndakunda gusoma.
Ndakunda kwiga igifaransa.
Ndashimishwa nivyo mbona.
Ndakunda aho mba.
Ndagukunda.
Ndakunda umuduga wanyu.
Umuduga wanyu uranshimisha.
Ndagukunda nanje.
Mba ngaha.
Mba muri Noroveje ubu.
Nzomubaza.
Nzoba ndi mu muduga wanje.
Nzogenda n'umuduga.
Nzokuraba.
Nzoza kugutora.
Nzogaruka.
Ndashika isaha zine.
Nzokora ico unsaba.
Nzobiguha.
Nzoguha igitabo.
Nzobitora.
Ngiye guzana umuduga wanje.
Nzogenda ku munsi w'Imana.
Ndabirora.
Nzogushimisha.
Nzokunezereza.
Nzokunyara.
Ndaguhwatira umucungwa.
Nzobiraba.
Nzobijamwo.
Ndakira ibi.
Ndakujana.
Nzovyiyumvira.
Nzobigerageza.
Nzogerageza.
Nzotegera.
Narataye amarori yanje.
Nataye impfunguzo zanje.
Ndakunda kuza ino.
Narakunze uyu muduga.
Naragukunda.
Ndamukunda.
Ndamukunda.
Ndakunda ibiharuro.
Ndakunda umuryango wanje.
Ndakunda iki gitabo.
Ndakunda uyu muduga.
Ndakunda kukuraba uteka.
Ndakunda kuraba ingene uteka.
Ndakunda ico nkora.
Ndakunda ico nkora.
Ndagukunda.
Ndi umwotsi w'imikate.
Ndi umutetsi.
Iyi kanzu nijewe nayigiriye.
Iyi kanzu nijewe nayikoreye.
Ndi umunyeshuri mushaha muri kaminuza.
Ndi umunyeshuri muri kaminuza.
Ndi umwigisha.
Ndi umunyeshuri muri kaminuza.
Ndaje kuguhitana.
Ndaje kugutora.
Ndabikorera wewe.
Ndanezerewe ko ariho uri.
Ndanezerewe ko uhari.
Ndanezerewe ko ariho uri.
Ndanezerewe ko uhari.
Ndagenda kuryama.
Nzobishobora.
Nzomoka.
Nzota nomoke.
Ndabitwara.
Ndanezerewe.
Ndanezerewe ku uhimbawe.
Biranshimishije.
Biranshimishije.
Biranyuze.
Ndanezerewe ku uhimbawe.
Ndanezerewe ko ariho uri.
Ndanezerewe ko uhari.
Ndashonje.
Namugomwe.
Namugwiriye.
Namukunze.
Ndi mu muduga.
Ndi mu gikoni.
Kubera wewe ndi mu ngorane.
Kubera wewe ndi mu rudubi.
Ndagukumbuye cane.
Ndakwumviriza.
Ndakurondera.
Ndi mushasha aha.
Sinzobireka
Sinzoheba.
Sinzotenyenya.
Sindi intore.
Sindi umuntu mwiza.
Sindi ikijuju.
Sindi umunyeshuri.
Sindi umutunzi.
Sindi umunyeshuri.
Sindi umunyeshuri muri kaminuza.
Sindi umubaji mwiza cane.
Ntitujana.
Simbiheba.
Sindaheba.
Sinzorabayo.
Sinzobireka
Sinzoheba.
Sinzoreka.
Sinzi neza igifaransa.
Sinkomeye muri vyo.
Sinzi gufata amazina.
Sinzi kugumya amazina.
Ntibinshimishije.
Ntibinyuze.
Ntibinshimishije.
Ntibinyuze.
Ku minsi y'Imana simba ndi imuhira.
Sindashonje.
Sinshonje.
Singushimye.
Sinkugomwe.
Ntibimpa agateka.
Ntibintera iteka.
Ntibimpa agateka.
Ntibintera iteka.
Sintunze.
Ndi umwe mu banyeshuri bawe.
Ndi ngaha kubera wewe gusa.
Ndi mu kiruhuko.
Ndasemagurika.
Uyu mwaka ntegekanya gusoma ibitabo vyinshi bishoboka.
Ndiko ndasoma igitabo.
Ndiko nduhuka.
Mbabarira kugukankamira.
Mbabarira kugutuka.
Mbabarira ko nagutaye mu rudubi.
Ntunga ko nagutaye mu rudubi.
Mpore ko ndabivuze.
Urambabarira ko ndabivuze.
Uranhunga ko ndabivuze.
Mbabarira ko nagutaye mu rudubi.
Ntunga ko nagutaye mu rudubi.
Mpore ko ndabivuze.
Urambabarira ko ndabivuze.
Uranhunga ko ndabivuze.
Ndiga igifaransa imuhira.
Ndazi neza ko hari aho maze kumubona.
Ndazi neza ko hari aho maze kumubona.
Ndazi neza ko namubonye ahantu ikindi gihe.
Ndiko nduhuka.
Ndi mu karuhuko.
Nzofata umunsi w'akaruhuko.
Ndagutwara kw'ishure.
Ndakujana.
Ndi umuhererezi.
Ndi umuhererezi.
Ndakwiyumvira.
Ndakwiyumvira.
Mfise umukoshi.
Ntegerezwa kugenda ubu.
Ndazi kubikora neza cane.
Mbabarire cane!
Mpore cane!
Ndoza amadirisha.
Ndakurora.
Nandika kuri twebwe.
Nkeneye guhoberwa.
Ndakeneye abakozi b'abitanzi batatu.
Ndakeneye umwanya wo kwiyumvira.
Nkeneye umwanya wo kwiyumvira.
Sinibagira na rimwe amaso.
Simbesha na rimwe.
Ntimushakisha igituma!
Nashaka kubaza, mbe mugenzwa n'amaki?
Nashaka kubaza, mbe muhakura inyungu nki?
Ndazi izina ryiwe gusa.
Amahera yarampereyeko.
Nirukiye kwa mama.
Ndashaka kukubona pe.
Ndabubaha.
Nti hanze!
Nasubiye kumubona.
Ndamubonye.
Namubonye yiruka.
Nabiketse.
Nabonye hariya mushikanje.
Nahabonye mwenewacu.
Ndabibonye nanje.
Ndababonye.
Ndakubonye.
Nabonye so wawe.
Mvuga ico niyumvira.
Ngurisha impuzu ku murongo.
Birakwiye vyose ivyerekeye vy'urugendo?
Birakwiye vyose ivy'urugendo?
Ni umunyamerika?
Capfuye?
Ni binini birenze?
Ni birebire birenze?
Ni bitoya birenze?
Birera?
Nryama ubusa.
Ejo naryamye umunsi wose, kuko wari umunsi w'Imana.
Raba ingene biteye igomwe.
Mvuga igisupanyoli gato.
Mvuga indimi zitatu.
Mara umwanya munini niga igitari.
Araza nawe?
Ni mushiki wawe?
Natanguye gukora muri ino societé kuva umwaka uheze.
Uko ni vyiza gusumba?
Namwe muravyiyumvira gutyo?
Nico cakuzanye ngaha?
Nico gituma cakuzanye ngaha?
Uyu ni mama wawe?
Uyu ni nyoko?
Ikirahuri cuzuye gushika hagati canke kirigusa gushika hagati?
Hari imashini yo kumesura mu nzu?
Urafise ikintu mu gutima, ushaka kwikura? Urashobora binganirira.
Turashobora kugira aho tuganirira?
Uwu muduga ni mushasha?
Iki ni igifaransa?
Uru ni urukundo?
Sindabimenya.
Ndacababara ivi gatoya.
Ndibuka aho ubwambere.
Tom nihari nawe?
Ndiga igifaransa imuhira.
Niga igifaransa mw'ishure.
Ndarahiye.
Nyoko ari imuhira?
Nyoko niho ari?
Ndavyakira.
Nyene ikintu ni musazanje.
Bikuvako.
Ntibisa neza.
Ntibimara umwanya mu nini.
Ndibaza ko azoza.
Ndibaza ko ntegeye.
Ndibaza ko navyicayeko.
Ndibaza ku mfise umwanya w'ikindi gikombe c'ikawa.
Ndibaza ko bitunganye.
Ndibaza ko ari vyiza.
Ndibaza ko ntegeye.
Ndibaza ko ntegeye.
Nanje ndavyiyumvira uko.
Niyumviye ko vyogutwenza.
Nagira ngo ni ikigorwa cawe.
Nagira ngo woba watashe.
Nagira ngo urashobora kubitegera.
Nagira ngo urabizi.
Nagira ngo woba watashe.
Nagira ngo woba watashe.
Nagira ngo urashobora kubitegera.
Nagira ngo urabizi.
Nagira ngo woba watashe.
Nagira ngo urashobora kubitegera.
Ni ku wambere.
Si umunsi wanje.
Si neza.
Si vyiza.
Si umuduga wanje.
Utahari sico kimwe.
Ni ku wagatandatu.
Nico gitabo mfise nanje.
Harashushe birenze.
Haraza gushuha.
Bisa neza.
Uraberewe.
Antera kuzirikana.
Antera kwiyumvira.
Nabarira vyose abavyeyi banje.
Naganiriye vyose abavyeyi banje.
Amahera narayakiriye.
Ni umugambi mwiza.
Ni isaha icenda ibuze iminuta icumi n'itanu.
Birababaje, umugenzi wanje mukuru arimutse, yimukiye mu kindi gisagara.
Bizoba neza cane.
Bitebe bitebuke bizoba.
Bitebe bitebuke bizoshika.
Ni ku wambere.
Nyene ikintu ni musazanje.
Sibijanye n'amahera.
Si isango y'ikiyago. Tuja gusa muri cenema.
Si ikintu co kwirata.
Si ikintu co kwishima.
Ntivyapfuye.
Nta kamaro.
Si umuduga wanje.
Ntubwirizwa kwandika ikete rirerire.
Nta gishasha.
Sico kimwe.
Utahari sico kimwe.
Ntibimeze uko uvyiyumvira.
Ntibiri nkuko uvyiyumvira.
Siko biri nkuko uvyiyumvira.
Nta kamaro!
Ni rwacu.
Biratunganye.
Ni ku wagatandatu.
Haracari kare ko tubivuga.
Harashushe birenze.
Ni birebire birenze.
Ni bitoya birenze.
Ni bitoya birenze urugero.
Ni neza cane.
Harashushe cane ngaha.
Harashushe cane, sivyo?
Vyiza kuruta vyobaye iyo utajaho.
Vyiza kuruta vyobaye iyo utajaho.
Ndabitegera.
Ndategera.
Ndategera ico uvuga.
Nje gusezera.
Nje kugutwara i muhira.
Naguhevye.
Nagutaye.
Mbwirizwa gutunganya imishatsi yanje.
Nagize igitondo c'imirimo myinshi.
Narataye amarori yanje.
Nataye impfunguzo zanje.
Naratakaje ikaramu ryanje.
Narasomye iki gitabo.
Navuze ko bimbabaje.
Nshaka gutaha.
Nshaka kukubona.
Ndashaka bimwe nanje.
Nshaka kugutekera.
Nshaka gutaha.
Ndashaka nanje kugenda.
Ndashaka kuguherekeza.
Noshimishwa no kumenya izina ryawe.
Nshaka kwiga igifaransa.
Ndashaka kubana na wewe.
Ndashaka gusoma iki gitabo.
Nshaka kubibona.
Ndashaka gusubira kukubona.
Nshaka kukubona.
Nshaka kwiga igifaransa.
Ndashaka kuruhuka gato.
Nshaka kuganira nawe.
Nshaka ko uja imuhira.
Nshaka ko utaha.
Nshaka ko ubimenya.
Nshaka ko ubisoma.
Ndashaka ko usoma iki gitabo.
Nshaka ko umubona.
Nshaka ko mubibona.
Nariyumviye kuguma iminsi mike iwawe.
Narabiravye muri yu tubi.
Nzobiguha.
Nzogushimisha.
Nzokunezereza.
Nzokunyara.
Nzobigerageza.
Nzogerageza.
Nosubira kubikora.
Nzero, Ruruhuma, Ntwarante, Ndamukiza, Rusama, Ruheshi, Mukakaro, Myandagaro, Nyakanga, Gitugutu, Munyonyo na Kigarama ni amezi icumi n'abiri y'umwaka.
Nzero ni ukwezi kwambere mu mwaka.
Indimi zifise amajambo agoye.
Reka ndakugurire gishasha.
Reka ndaguhobere.
Reka nje kugura umukate.
Reka ndabirabe.
Reka ndabe.
Reka ndabe.
Reka tugure ivyo.
Twugurure idirisha!
Tega amatwi!
Nyumviriza.
Umviriza nyoko!
Umviriza nyoko!
Murabe.
Raba iyi foto.
Rabira mw'idirisha.
Raba hariya!
Urukundo rurahuma.
Magdalena na Ania ni abagenzi pfampfe.
Tange insiguro y'amungane ibereye mudasamajwe n'izindi ndimi.
Urakoze cane.
Ibiti vyinshi vyaraguye.
Ngirango dushobora kujana mu nkengera y'ikiyaga iyi mpera y'indwi.
Ngaruke?
Nsubire kugaruka?
Ndashobora kubibona kandi?
Nshobore gusubira kubibona?
Ndashobora kumenya ibintu nokuzanira.
Nanje.
Nanje.
Muragaba k'umutwe wanyu.
Muritwararikire umutwe wanyu.
Musazanje ntari i muhira.
Umuduga wanje wapfuye.
Umuduga wanje wapfuye.
Umukobwa wanje azorongorwa muri ruheshi.
Umukobwa wanje azorongorwa mu kwezi kwa gatandatu.
Umukobwa wanje azorongorwa muri ruheshi.
Indoto yanje yabaye ukuri.
Indoto yanje yabaye ukuri.
Umuryango wanje ni muto.
Data ari imuhira.
Data ari imuhira.
Data wanje ntari imuhira.
Data wanje ntari imuhira.
Umuduga wa data ni mushasha.
Nyogokuru avuga buhoro buhoro.
Inzu yanje iri hafi y'inyubakwa yo gusengeramwo.
Inzu yanje iri hafi y'isengero.
Inzu yanje iri hafi y'urusengero.
Ukuboko kwanje kw'ibubamfu kwagize ibinyanya.
Umuvyeyi wanje arankunda.
Izina ryanje ni John.
Umubanyi wanje ni umubaji.
Abavyeyi banje bampamagara kira munsi.
Mushikanje asa na Mama.
Ndaribwa mu nda.
Mize ndababara mu muhogo.
Ipantalo yanje yajovye.
Ijwi ryanje rirasaraye kubera inkorora.
Ntanumwe yakubajije.
Ntanumwe yarazi ibikenewe kurangurwa.
Ntanumwe azi izina ryiwe.
Ntanumwe abizi.
Ntanumwe abizi.
Ntanumwe azi ibikenewe gukorwa.
Ntanumwe yumviriza.
Ntanumwe antega ugutwi.
Ntanumwe antegura.
Ntanumwe yakubajije.
Ntanumwe yavuze ijambo.
Ngaha nta numwe afise umuduga.
Nta numwe ahari!
Ntanumwe ari i muhira.
Ntanumwe yumviriza.
Ntanumwe yarazi ibikenewe kurangurwa.
Ntanumwe azi izina ryiwe.
Ntanumwe azi izina ryiwe.
Ntanumwe azi amazina yabo.
Ntanumwe azi ibikenewe gukorwa.
Ntanumwe arazi aho turi.
Ntanumwe antega ugutwi.
Ntanumwe yabonye ikintu.
Nta numwe ahari!
Ntanumwe ari i muhira.
Ntanumwe antegura.
Nta ngorane.
Ngaha ntibaba abatunzi.
Nta batunzi baba ngaha.
Oya, urakoze.
Oya, urakoze.
Ntaco bibaye.
Bitabaye ubu, ryari?
Hatari ubu, ryari?
Ntavuga icongereza gusa, avuga kandi n'ikidagi.
Nta kibazo.
Ko turi twenyene, reka twiryohere.
Oh, mpore.
Reka ndagitumeko.
Sawa, nzogikura.
Sawa, nzogitumako.
Haguye amama make y'imvura.
Ugurura idirisha.
Ibitwazi vyacu birarushe.
Ibitwazi vyacu vyarushe.
Urugendo rwacu ruva ku gihe.
Urugendo rwacu ruvana n'igihe.
Ngirango azoza ejo.
Mpamagara hagati y'isaha imwe n'isaha zibiri.
Ndipfuza impobero.
Ndamusavye umpe urupapuro rwo kwandika.
Ndagusavye soma ivyanditse munsi.
Ndagusavye usome ivyanditse munsi.
Ibiciro vyaraduze.
Mu ruguma hari amashira.
Subira gusoma.
Soma!
Soma ibi.
Wibuke ubuntu bwawe kandi wibagire ibisigaye.
Wibuke ubuntu bwawe wiyobagize ibindi.
Tebuka!
Bivuge mu gifaransa.
Subira kubivuga.
Tuzosubira kubonana!
Turabonana.
Tuzongera ku wambere.
Turashobora gutangura ubu?
Tujane?
Ntiyasomaye iki gitabo.
Ntiyasomaye iki gitabo.
Ntanzi.
Ntabana nawe.
Afise ibitabo amajana n'amajana.
Yataye urupfunguzo rw'umuduga wiwe.
Ni umunyeshuri mwiza.
Ni umufaransa.
Aranezerewe.
Yamugomwe.
Yamukunze.
Siho ari.
Ntibamuriha ku kwezi ahubwo ku munsi.
Ntiyibungenze.
Aribungenze.
Biramuraba.
Ni akazi kiwe.
Aramukunda.
Arakunda gusoma ibitabo.
Abana na we.
Asa na nyina.
Asa na nyina wiwe.
Aramukunda.
Arakeneye amazi.
Yatoye ikanzu izimvye gusumba zose.
Yatoye ikanzu izimvye gusumba zose.
Ni umuntu mwiza.
Aranezerewe.
Yamoye umutwe wiwe.
Yataye urupfunguzo rw'umuduga wiwe.
We si umwana.
Yatetse umutaga wose.
Arakomeye.
Aramutegera.
Aramwumva.
Kera yari umwigisha.
Yarerewe kwa nyirakuru.
Kanyemwo!
Kazibe!
Ryama neza, Timmy.
Kunywa itabi vyica amagara.
Bamwe muri abo bakozi ntibamenyeye gukora ako kazi.
Hari umuntu ahagaze inyuma y'uruhome.
Vugana nanje.
Ja ku ruhande!
Reka kundaba.
Reka gusoma.
Reka kuvuga ivyo!
Reka gutungira ijisho amabere yiwe!
Hagarika uyo muduga.
Kubika ahakanye kandi humutse.
Kubika ahapfutse kandi humutse.
Akira igitabo usome.
Ruhuka!
Birabe neza.
Raba ico neza.
Ntimutore inomero.
Fata itagisi ikujana mw ihoteri.
Ntwara i muhira.
Njana.
Nimukure ibirato vyanyu.
Nimwambure ibirato vyanyu.
Akira kimwe.
Fata kimwe.
Akira amahera.
Bishire nyoko.
Bitwarire nyoko.
Fata ico wipfuza.
Akira ico ushaka.
Nimukure ibirato vyanyu.
Nimwambure ibirato vyanyu.
Mbwira umugambi wawe.
Nganirira umugambi wawe.
Babarire ivyashitse.
Babwire ivyashitse.
Urakoze cane!
Urakoze cane.
Urakoze kuza.
Murakoze kwumviriza.
Urakoze guhita.
Urakoze kwicisha iwacu.
Murakoze!
Urakoze!
Murakoze cane.
Urakoze cane!
Iki gitanda kiranonotse cane.
Iki gitanda kirasusurutse cane.
Ivyirabura ni vyanje.
Iki gitabo ntigifise akamo.
Uyu mwigeme asa neza.
Uyu mukobwa yiyambika nk'umuhungu.
Uyu mwigeme yiyambika nk'umuhungu.
Uyu mukobwa yiyambika nk'umuhungu.
Uyu mwigeme yiyambika nk'umuhungu.
Nico nshaka kumenya.
Bizoba neza cane.
Ivyo bizonezereza.
Vyanteye kukwiyumvira.
Birampimbaza.
Biraduhimbaye cane.
Uyu muduga ni mwiza cane.
Birakwiye.
Niko bimeze.
Uyu muduga ni rwanje.
Ni rwacu.
Ni birebire birenze urugero.
Ibarabara riri urwamo rwinshi.
Nico ndiko ndondera.
Nanje ndavyiyumvira uko.
Nico nshaka kumenya.
Ni naco gituma ndagukunda.
Ni naco gituma ndagukunda.
Iri jambo ryamuka mu kigereki.
Umuhungu arasimba.
Igituro ca bisi kiri iminota itanu uvuye ngaha.
Ibisi irahagaze ariko nta muntu yururutse.
Umuduga wapfuye.
Ikanzu rikozwe mw'iharire.
Asanseri ntikora uyu munsi.
Umugenzi wanje vyaramushikiye nawe mu ndwi iheze.
Abashakashatsi bubutse ku magufa y'umuntu mw'isenga.
Ihinguriro rikora ibihumbi n'ibihumbi vy'amacupa kira kwezi.
Ihinguriro rizotangura gukora mu mwaka uza.
Muri ino gant hari intoboro ku rukumu.
Ikiganza gifise intoki zitanu: urukumu, inkombarukoko, msumba zose, igihugunibenga, agahererezi.
Igitwazi kirasimba.
Amafaranga yaheze.
Amahera yaheze.
Ku wambere musée yama yugaye.
Abonye amaraso umurwayi yaciye araba.
Igiciro kiraduga.
Nta ngorane.
Nguyo araje!
Urupapuru rumwe rurabuze.
Nta bundi buryo.
Nta ngorane.
Nta mazi akiri mw'icupa.
Urupapuru rumwe rurabuze.
Nguyo araje!
Nguyo!
Nta ngorane.
Kera hari isengero ngaha.
Kera hari urusengero ngaha.
Nta wundi muntu yarahari kiretse jewe.
Hari ijana y'abantu mu ngoro.
Icumba ni ciza.
Ibi bitabo ni rwacu.
Ayo mashurwe ubona ni amarosi.
Izi ntambwe zirashobora kubuza ko ingwara isasagazwa.
Aya madirisha araba mu bumanuko.
Ayo madirisha yerekeye mu bumanuko.
Ijipo ntiyari inkwiye nico gituma nabwirijwe guyihindura.
Ijipo irandenze.
Ijipo iranduta.
Inzoka yamize igikere.
Izuba rirasira mu buseruko.
Igihe ntikigize gukanya gusa, kiranajovye.
Ubugeni buzoba ku wagatandatu.
Idirisha rirugaye.
Amadirisha araguruye.
Baranezerewe.
Ntibaza uyu munsi.
Ntibaza uyu munsi.
Ntibanezerewe.
Ntibafise amahera.
Ntaco babiziko.
Ntavyo bazi.
Ntibakunezereza.
Ntibashaka kubikoresha.
Ntibashaka ko tubimenya.
Ntibafise amahera.
Baratuzi.
Bazomenya uko bagira.
Bobo ni abana.
Baza imuhira.
Ntibaza uyu munsi.
Muri beza cane gwose.
Ni beza cane gwose.
Bambonye.
Bavuga ko atunze cane.
Bavuga ko atunze cane.
Bavuga ko atunze cane.
Bavuga ko atunze cane.
Bashaka ko tubigira.
Bashaka ko tubikora.
Ni igitabo c'agatangaza.
Iki gitabo ni gishasha.
Iki gitabo ni ciza cane.
Iki gitabo ni gishasha.
Uyu muhungu ni mwenebabo.
Uyu muduga usa na mushasha.
Nyene uyu muduga ni data wanje.
Ntibisa na rwawe.
Iyi hinguriro rikora ivyuma vy'imiduga.
Iri darapo ni nziza cane.
Iri darapo ni nziza cane.
Aya masanganzira afise impanuka y'urupfu.
Ni igitabo ciza cane.
Iki gitabo ni ciza cane.
Ni neza, siko?
Ni vyiza, sivyo?
Nuko rero nabigize.
Nuko rero nabigize.
Umuceri utekwa uku.
Duteka umuceri uku.
Iyi nyabu ni yanje.
Uyu ni data wanje.
Ni umuduga wanje mushasha.
Si igifaransi.
Uyu muduga ni rwacu.
Ni rwacu.
Ibi ni birebire birenze urugero.
Iyi mbugita irapfushe.
Bizoba neza cane.
Vyanteye kukwiyumvira.
Birampimbaza.
Uru ruhome rurakanye.
Iri jambo riva mu kigereki.
Iri jambo ryamuka mu kigereki.
Nyene ibi bitabo ni mushikanje.
Uyu munsi ni umunsi w'Imana.
Uyu munsi ni kuwagatatu.
Tom ni umubaji.
Igifurwe ntigifise amenyo.
Ikinyamasyo ntikigira amenyo.
Tuzongera mu ndwi iza.
Nimuduhitemwo!
Nimudutore!
Raba neza ingene ndabikora!
Raba neza aho ugenda.
Raba neza iyo uja.
Amazi arajovye.
Turavukana.
Ni mwenewacu.
Turavukana.
Turanezerewe kubabona.
Turanezerewe.
Turi imuhira.
Twiga mw'isomero rimwe.
Turi abanyeshuri ba kaminuza.
Twatandukanye.
Twavanye.
Twaje kukubona.
Twaje kukuraba.
Twojana.
Twoshobora kujana.
Ntitumuzi.
Nta muduga dufise.
Ntitumuzi.
Ntitubizi.
Ntitubwirizwe kubivugana ubu nyene.
Ntitwumva igifaransa.
Ntidushaka kubimenya.
Rimwe rimwe tujana muri cenema.
Twatandukanye.
Twakuriye hamwe.
Twarukiye hamwe.
Twashitse.
Nta mahera dufise.
Ntidufise amahera.
Turamuzi.
Turamuzi.
Turabizi.
Turabizi.
Turazi ico ukora.
Turazi igituma waje ngaha.
Turakuzi.
Kaze iwacu!
Kaze iwacu!
Tujanayo twese hamwe.
Tujana twese hamwe.
Tuzojana.
Turahurirayo.
Turakunda pariki yacu.
Turagukunda.
Nawe turagukumbuye.
Twama dukina ku munsi w'Imana.
Twamanutse twiruka agasozi.
Turi twenyene.
Turagarutse.
Turavukana.
Ni mwenewacu.
Turavukana.
Tuhavuye tuba twenyene.
Turabitegera.
Tuzotunga.
Tuzobishobora.
Nzobona igikino.
Turaja ku burengero.
Turanezerewe kubabona.
Turi ngaha kubera wewe.
Turi ngaha kubwawe.
Twiga mw'isomero rimwe.
Ntituri twenyene.
Nta mahera tugifise.
Ntitugifise amahera.
Turi abanyeshuri ba kaminuza.
Turi abanyeshuri ba kaminuza.
Turanezerewe cane.
Turiko dutakaza umwanya uzimvye.
Turabwirizwe gufungura ku mutaga hamwe.
Turakwiye gufungura ku mutaga hamwe.
Tubwirizwa gushira uburinganire hagati y'bisohoka n'ivyinjira.
Turiga igifaransa.
Turumvikana.
Turategera.
Turumva.
Twashitse.
Twasezeye.
Twipfuza amungane akwiye.
Twipfuza insiguro zo mu rurimi rwa misi yose.
Dushaka ko ubitwara.
Ni umunsi!
Wari umunsi!
Ukora iki ngaha?
Ushoboye iki?
Uraba iki?
Urondera iki?
Uriko usoma iki?
Wipfuza iki?
Iciyumviro nyabaki!
Bisa gute?
Ifagitiri ringana gute?
Ni igiki ntategera?
Bakora iki ngaha?
Ivyo ni ibiki?
Ukora iki ngaha?
Mukora iki?
Ukora iki?
Muzi iki ku vyashitse?
Uzi iki?
Usa gute?
Ubona iki hanze?
Ubona iki?
Umfata ko ndi nde?
Wibaza ko ico ariki?
Wibaza ko ivyo ari ibiki?
Wiyumvira iki?
Udushakako iki?
Ushaka kubimenya iki?
Uripfuza kuraba iki?
Urashaka kuraba iki?
Uripfuza kuraba iki?
Mwashikiwe niki ejo ku mugoroba?
Umuduga wanyu wabaye iki?
Wampaye iki?
Hariko haba iki hariya epfo?
Ashaka gushika kuki?
Urukundo ni iki?
Iki kintu kimaze iki?
Mukunda gusoma ubwoko bw'ibitabo ibihe?
Ni igiki gituma abantu bagira uko ivyo?
Niki?
Urondera iki?
Uriko usoma iki?
Wiga kw ishure irihe?
Hariko haba iki hariya epfo?
Mbe nambare iki - ipantalo canke ijipo?
Mbe nambare iki - ipantalo canke ijipo?
Yitwa ngwiki kandi?
Amakuru maki?
Amakuru yawe?
Igituma c'urugendo rwanyu ni nyabaki?
Intumbero y'urugendo rwanyu ni iyihe?
Mukunda gusoma ubwoko bw'ibitabo ibihe?
Ubibona gute?
Uhaguruka ryari?
Utaha ryari?
Uza imuhira ryari?
Uhaguruka ryari?
Uvyuka ryari?
Ugenda ryari?
Wiga ryari?
Ushaka kugenda ryari?
Uzoza iwawe ryari?
Ndi hehe?
Ibirato birihe?
Bagutwaraye hehe?
Turihe?
Turi hehe?
Mugenda hehe?
Ibintu vyawe birihe?
Mudutwaye hehe?
Urihe?
Abantu bose bagiye hehe?
Tuja hehe?
Muvahe?
Uva hehe?
Ugenda kw ishure hehe?
Muzinaniye hehe?
Mumuzi hehe?
Ubikuye hehe?
Uba he?
Wahagaritse umuduga hehe?
Wigahe?
Ushaka kuba hehe?
Ushaka kuja hehe?
Ushaka kuba hehe?
Warihe?
Akinirahe?
Umuryango wiwe urihe?
Umuryango wiwe urihe?
Mariya arihe?
Umuduga wanje urihe?
Amahera yanje ari hehe?
Isaha yanje irihe?
Igitabo kirihe?
Umuduga urihe?
Tom arihe?
Musazawe arihe?
Umuryango wawe uri hehe?
So wawe arihe?
Nyoko arihe?
Ibirato birihe?
Mariya arihe?
Umuduga wanje urihe?
Mama wanje arihe?
Amahera yanje ari hehe?
Isaha yanje irihe?
Umuduga wacu urihe?
Umuduga urihe?
Umutetsi arihe?
Tom arihe?
Musazawe arihe?
Umuduga wawe urihe?
Umuryango wawe uri hehe?
So arihe?
So wawe arihe?
Nyoko arihe?
Isaha yawe irihe?
Ahari ugushaka haba inzira.
Ahari ugushaka haba inzira.
Wibaza ko ndi nde?
Uwushaka kumurongora abwiriza kubiganira neza na se wiwe.
Ninde asoma?
Umwigisha wanyu ni nde?
Ubu buriri ni ubwande?
Iyi nzoga ni iyande?
Iki gitabo kiri ku meza ni icande?
Iyi koti ni iyande?
Ikosa ni iryande?
Iri kosa ni iryande?
Ikosa ni iryande?
"Aya marori ni ayande?" – "Ni aya Data."
"Aya marori ni ayande?" – "Nyeneyo ni Data."
Iri saho ni irya nde?
Iyi nzu ni iyande?
Iki ciyumviro cari icande?
Iki ciyumviro cari icande?
Iri terefone ni iryande?
Ibi biro ni ivyande?
Iri terefone ni iryande?
Iri terefone ni iryande?
Iyi nomero ya terefone ni iyande?
Urya mugambi wari uwande?
Wari umugambi wande?
Iki cayi ni icande?
Uyu muvinyu ni uwande?
Umwigisha wanyu ni nde?
Kubera iki mbikora?
Kubera iki ndi ngaha?
Kubera iki bataza?
Kubera iki utari kw ishure?
Kubera iki utari mw'isomero?
Kubera iki utari aha?
Kubera iki utari kw ishure?
Kubera iki utari mw'isomero?
Kubera iki utariyo?
Kubera iki utari iwanje?
Kubera iki utari kumwe na jewe?
Kubera iki bari aha?
Kubera iki bavuga ivyo?
Kubera iki tugira ivyo?
Kubera iki tubikora?
Kubera iki ubaza?
Kubera iki mumbaza?
Kubera iki umbaza?
Kubera iki ubibaza?
Kubera iki muri imuhira?
Kubera iki ujaho?
Kubera iki muri imuhira?
Kubera iki utabikora?
Kubera iki utari kumwe na jewe?
Kubera iki mbwirizwa kubikora?
Kubera iki mbwirizwa kubikora?
Kubera iki mbwirizwa kugenda.
Kubera iki abantu batankunda?
Kubera iki batankunda?
Kubera iki tudataha imuhira?
Kubera iki tutaja imuhira?
Kubera iki ataho tutajana?
Kubera iki tutabiraba?
Kuki utinjira?
Kubera iki utajana na jewe?
Kubera iki utabikora?
Kuki utinjira?
Kubera iki ataco uronka?
Kubera iki udaheba?
Kubera iki udataha?
Kuki utaja imuhira?
Kubera iki udatomora ico ufise ku muzirikanyi?
Kubera iki utumviriza?
Kubera iki utaciga igifaransa?
Kubera iki mutagerageza iyi goti? Ijanye neza n'ipantalo yanyu.
Kubera iki udashaka kugenda?
Kubera iki abantu bavuga ivyo?
Kubera iki babikora?
Kubera iki ubaza?
Kubera iki ufise ico?
Kubera iki ufise ivyo?
Kubera iki unkunda?
Kubera iki wiga igifaransa?
Kubera iki wiga muri kaminuza?
Kubera iki wibaza ivyo?
Kubera iki wibaza uko?
Kubera iki wibaza ivyo?
Kubera iki harashushe?
Kubera iki cubitse?
Kubera iki ijuru risa n'ubururu?
Kubera iki jewe?
Kubera iki utajana na jewe?
Kubera iki urwanko rwinshi?
Nta gushidikanya.
Nta makenga!
Woba ufise akanya ko kumfasha ikintu?
Ejo hari kuwagatanu.
Uri umutetsi mwiza.
Uri umuvyeyi mwiza.
Uri umuntu mwiza.
Uri umunyeshuri mwiza.
Muri abana.
Mwebwe muri abana.
Uri umugenzi wanje.
Wewe uri umugenzi wanje.
Ntuza, sivyo?
Ntuzoza, sivyo?
Nturi musazanje.
Nturi mwenewacu.
Ntuza, sivyo?
Ntuzoza, sivyo?
Ntwumviriza.
Ur'uwacu.
Ur'uwiwacu.
Urashobora gutora irangi iryariryo ryose rigushimisha.
Urashobora gutora irangi iryariryo ryose ushimye.
Urashobora gutera ururirimbo.
Ushobora kuvga icongereza.
Urashobora kurara iwacu.
Murashobora kuntegera.
Urashobora gukoresha uwu muduga.
Ntunzi.
Reka gutanga amategeko ngaha!
Ntubwirizwa kuza.
Ntutegerejwe kuza.
Ntimukeneye gunkengurukira.
Ntunzi.
Ntuzi musazanje.
Ntwumviriza.
Ntusa neza.
Ntushaka kubimenya!
Ntushaka kumenya ivyo!
Ndarahiye.
Ntimuzi namba ivyashitse, canke?
Mubwizwa gumperekeza.
Ubwirizwa kuvyuka.
Ubwirizwa kujayo kubizana.
Mubwirizwa gutaha.
Mubwirizwa kugenda i muhira.
Ubwirizwa kuja imuhira.
Ubwirizwa kureka kunywa.
Uramuzi.
Uramuzi.
Urazi ko mbwirizwa kugenda.
Urazi ko ndagukunda.
Urazi ko ndagukunda.
Uranzi.
Urazi ko mbwirizwa kugenda.
Urazi ko ndagukunda.
Urazi ko ndagukunda.
Urazi ko tugukunda.
Urazi aho nzoba ndi.
Uba ngaha, sivyo?
Muzovyigaya cane.
Uzomukunda.
Uzomukunda.
Uzobikunda.
Urabishobora.
Ushaka kuzobibona.
Ushaka kuzobiraba.
Usa naho unezerewe cane.
Uranezereza.
Urashobora kugendayo.
Urashobora kujayo.
Ngirango ntibigushimisha.
Ngirango ntubikunda.
Mubwirizwa gutaha.
Ubwirizwa guheba inzoga.
Urakeneye umugambi.
Waciye ku kimenyetso c'itara ritukura.
Waciye ku kimenyetso gitukura.
Uri umutetsi mwiza.
Uri umuvyeyi mwiza.
Uri umuntu mwiza.
Uri umunyeshuri mwiza.
Muri Abadagi, sivyo?
Uri umugenzi wanje.
Ntuza, sivyo?
Ntuzoza, sivyo?
Ntukomeye muri vyo.
Ntwumviriza.
Nturi musazanje.
Nturi mwenewacu.
Urarwaye, ubwirizwa kuruhuka.
Uri umugore nkunda.
Urazi kubigira neza cane.
Uruhanga rwawe rurashushe cane. Ndakeeka ko ufise inyonko.
O yawe isa na A yawe.
Ipantalo yawe iranduye.
Ipantalo yawe iranduye.
Ntubange ugutwi.
Akira amahera.
Urantegera.
Kera waranywa itabi, sivyo?
Urarurumba.
