Mir send em Tom saine Seene.
Ria isch em Tom sai Oma.
Bisch du aigschlôfå?
Was hend Siå dô gfondå?
En dera Nacht gang i durch s ganz Land Ägypten ond breng älle Erstgeburta om, von de Menscha ond vom Vieh. Ond i, dr Herrgott, halt s Sträfgericht ab über de Ägypter ihre Götter.
Ond lent nex üvrig bis an da Morga; aber wenn ebbas übrigbleibt, nä dent r s em Feuer vrbrennä.
Mir Eiropäer missad lärnå, ons ohne des Englisch z'ondrhaldå.
So dent r s essa: Da Gürtel ä, d Schah an de Füaß ond da Wanderstab en dr Hâd, so dent r s anandernôch essa, des ischd a Passa für da Herrgott.
Mai Vaddr hôd se ned kennd.
Deidschland isch å grooß Land.
Send ihr aigschlôfå?
Dor frie Vogl fengd då Wurå, abr erschd zwoide Maus grigt då Käs.
Des Bluat an dene Häuser, mô ihr dren wohnat, des isch a Schutzzoeche. Môn e des Bluat sieh, gang e an euch vrbei, dass euch koi Schlag trifft, solang e en Ägypten draeschlag.
Mai Schweschdr isch zwoi Jôhr jengr wiå i.
